### ISSUE TITLE
How to count API calls?

### ISSUE THREAD

**Issue by copumpkin** [boto/botocore#1001]
I'm using boto3 and while the resources it provides are great, it can be difficult to track what's going on behind the scenes. I want to make sure that my boto3 code isn't doing anything stupid and is making bulk API calls where possible, and I figured that the botocore hooks mechanism would let me count calls. Unfortunately I can't find much documentation on how hooks work, so I figured I'd ask both how to do it, and ask whether some documentation could be added.

**Comment by srri** [comment]
You can enable the debug logging with `boto3.set_stream_logger('')` which might help provide the data you're looking for (you may need to take the output and do some processing of it to count requests)

**Comment by copumpkin** [comment]
Hmm, would that let me get programmatic access to the API calls being made behind the scenes. I was hoping to put some stuff using this into automated tests.

**Comment by srri** [comment]
It would output verbose logs of what is going on behind the scenes, ex:
```
2016-07-09 21:46:40,990 botocore.endpoint [DEBUG] Sending http request: <PreparedRequest [PUT]>
2016-07-09 21:46:40,991 botocore.vendored.requests.packages.urllib3.connectionpool [INFO] Starting new HTTP connection (3): 127.0.0.1
2016-07-09 21:46:40,992 botocore.awsrequest [DEBUG] Waiting for 100 Continue response.
2016-07-09 21:46:41,993 botocore.awsrequest [DEBUG] No response seen from server, continuing to send the response body.
2016-07-09 21:46:42,204 botocore.endpoint [DEBUG] ConnectionError received when sending HTTP request.
```

**Comment by kyleknap** [comment]
@copumpkin Would using the event system help? Here is documentation on the ``provide-client-params`` event you could hook into to grab information related to the params passed in and the operation to be invoked by the underlying client.

**Comment by jamesls** [comment]
@kyleknap Looks like the docs aren't linked?  Actually looks like we don't document this event.  Let me see if I can get a code snippet together.

**Comment by kyleknap** [comment]
It is in the boto3 docs: https://boto3.readthedocs.io/en/latest/guide/events.html. The botocore guide on events is really out of date.

**Comment by kyleknap** [comment]
Specifically here:
https://boto3.readthedocs.io/en/latest/guide/events.html#provide-client-params

**Comment by jamesls** [comment]
Ah, I see.  Looks like our search needs some work :( https://boto3.readthedocs.io/en/latest/search.html?q=provide-client-params&check_keywords=yes&area=default

Ok, I'm going to go ahead and close out the issue.  @copumpkin let me know if this event doesn't work for you and I'll reopen and take another look.

**Comment by copumpkin** [comment]
That looks pretty promising, thanks. I'll try it out and let you know if it doesn't work.
