### ISSUE TITLE
Where to solve problem with calculate_md5?

### ISSUE THREAD

**Issue by pacahon** [boto/botocore#1022]
In boto3 1.4.0 I can see next [if statement](https://github.com/boto/botocore/blob/11ec1411be8a78f8739efea287a86244c99b61b5/botocore/handlers.py#L131):
```
if request_dict['body'] and 'Content-MD5' not in params['headers']:
```

In my file-like object `__bool__` method depends on file name. If file name is empty, this check is fail and my POST-request to s3 is failed with `ClientError` later.

Can this check be improved or should I manage file name by myself?

**Comment by kyleknap** [comment]
Interesting, is this a custom file-like object class you are using or is it coming from a library? I think ideally we would like to keep it as is, but if there are existing classes in other libraries that have this behavior I could see a case being made to change it.

**Comment by pacahon** [comment]
@kyleknap Thanks for response! This is not python file-like object, I talked about Django's [File object](https://docs.djangoproject.com/en/1.10/_modules/django/core/files/base/#File)
As it works bad with `requests` library too, I guess no need to change something in `botocore`.
