### ISSUE TITLE
CreateSnapshotRequest: DryRun parameter definition incorrect

### ISSUE THREAD

**Issue by davideagen** [boto/botocore#1035]
The services-2.json for ec2's CreateSnapshotRequest has locationName set to `dryRun` which results in AWS rejecting the request:

`<?xml version="1.0" encoding="UTF-8"?> <Response><Errors><Error><Code>UnknownParameter</Code><Message>The parameter dryRun is not recognized</Message></Error></Errors><RequestID>...</RequestID></Response>`

The correct case is `DryRun` which AWS accepts:

`<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>DryRunOperation</Code><Message>Request would have succeeded, but DryRun flag is set.</Message></Error></Errors><RequestID>...</RequestID></Response>`

**Comment by JordonPhillips** [comment]
The model is correct, but there are some differences in the `ec2` protocol over the very similar `query` protocol. One of those differences is that for *input* the first letter in `locationName` is capitalized. 

You can see how we handle those differences in our serializer ([here](https://github.com/boto/botocore/blob/develop/botocore/serialize.py#L259)).
