### ISSUE TITLE
URLs with underscores are considered invalid

### ISSUE THREAD

**Issue by Qo-Ops** [boto/botocore#1042]
My url "vm_test_1.hsg.test" is considered invalid by botocore. After replacing underscores with hyphens like this "vm-test-1.hsg.test" it works fine. I have read that google advises to use hyphens over underscores, however, I don't think that urls with underscores should be considered invalid.

**Comment by joguSD** [comment]
This has been previously discussed in issues #960 and #1013. Underscores are deemed invalid as they are not part of the RFC. Check out the above issues for a more detailed discussion.

**Comment by JordonPhillips** [comment]
As @joguSD mentioned, underscores are invalid according to the [RFC](https://tools.ietf.org/html/rfc952).

> The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.
