### ISSUE TITLE
mapping of API name to action keys used in IAM policies?

### ISSUE THREAD

**Issue by hakanson** [boto/botocore#1043]
I'm looking for a programmatic/data driven way to map from an AWS API to the `Action` key I need to `ALLOW` in my IAM Policy.

For example, if I use the `S3.GetBucketNotificationConfiguration` API, I need to grant the `s3:GetBucketNotification` permission.  Because `GetBucketNotificationConfiguration` was an update to the deprecated `GetBucketNotification` API, a dumb string substitution wouldn't work here (nor for matching something like the `S3.ListObjectsV2` API to the  `s3:ListBucket` key).  I'm using [Actions and Condition Context Keys for Amazon S3](http://docs.aws.amazon.com/IAM/latest/UserGuide/list_s3.html) as my source of truth for these keys.

The [botocore data for GetBucketNotificationConfiguration](https://github.com/boto/botocore/blob/558e1e3253f2e41d7e46a55515466f0fd8ae47b2/botocore/data/s3/2006-03-01/service-2.json#L263) looks like:

```
    "GetBucketNotificationConfiguration":{
      "name":"GetBucketNotificationConfiguration",
      "http":{
        "method":"GET",
        "requestUri":"/{Bucket}?notification"
      },
      "input":{"shape":"GetBucketNotificationConfigurationRequest"},
      "output":{"shape":"NotificationConfiguration"},
      "documentation":"Returns the notification configuration of a bucket."
   },
```

Would it be a good idea to add the IAM policy action keys to this data structure?  Is there another or better source of this mapping?

**Comment by jamesls** [comment]
I agree this would be useful, but I'm not sure botocore is the right place for this.  It'd be great if there was some way to get this data directly from the service somehow.  For now you'll have to maintain a mapping.  I've started a mapping over in chalice that you should be able to use: https://github.com/awslabs/chalice/blob/master/chalice/policies.json but it's not complete and is missing the case you mention above.

**Comment by hakanson** [comment]
Where do you think the "right place" is? I saw in [CONTRIBUTING.rst](https://github.com/boto/botocore/blob/develop/CONTRIBUTING.rst) this note:

> We may choose not to accept pull requests that change the JSON service descriptions, such as botocore/data/aws/s3/2006-03-01/service-2.json. We generate these files upstream based on our internal knowledge of the AWS services

Where is the upstream location for service-2.json and would that have the policy action keys?

**Comment by JordonPhillips** [comment]
@hakanson The upstream source does not have that information unfortunately. Closing out here since there's nothing actionable for us.
