### ISSUE TITLE
Repeated docs for DynamoDB.Client.create_table StreamSpecification

### ISSUE THREAD

**Issue by FrancescoRizzi** [boto/botocore#1047]
Just a documentation issue, and a marginal one at that.

From [botocore readthedocs for DynamoDB Client create_table](https://botocore.readthedocs.io/en/latest/reference/services/dynamodb.html#DynamoDB.Client.create_table), if you scroll down to the description about the request's StreamSpecification argument, you'll see that its children arguments are described 3 times, with slightly different formatting:

> The settings for DynamoDB Streams on the table. These settings consist of:
> - _StreamEnabled_ - Indicates whether Streams is to be enabled (true) or disabled (false).
> - _StreamViewType_ - When an item in the table is modified, StreamViewType determines what information is written to the table's stream. Valid values for StreamViewType are: _[...]_
> - **StreamEnabled** (boolean) -- Indicates whether DynamoDB Streams is enabled (true) or disabled (false) on the table.
> - **StreamViewType** (string) -- The DynamoDB Streams settings for the table. These settings consist of:
>   - _StreamEnabled_ - Indicates whether DynamoDB Streams is enabled (true) or disabled (false) on the table.
>   - _StreamViewType_ - When an item in the table is modified, StreamViewType determines what information is written to the stream for this table. Valid values for StreamViewType are: _[...]_

HTH

**Comment by kyleknap** [comment]
So it looks like there is an issue with the documentation content in our model. Our documentation is more or less the same content as the API Reference. So if you look at the API reference for [CreateTable](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html) and [StreamSpecification](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_StreamSpecification.html) type you can see the duplication as well. I will look to get this updated in both places.

**Comment by FrancescoRizzi** [comment]
ah.. indeed.. thanks for pointing to the source for the docs.
If I find more doc issues, I can check the AWS API docs.. is there by chance a better place for me to report issues I might find with those docs? I feel bad reporting it to this project, as it is really an issue with the upstream sources...

**Comment by kyleknap** [comment]
Yeah so the best way to get the documentation updated is by posting in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131) about their API References having the duplicate documentation. If they get that updated, we should be able to pick that up pretty easily.

If you want to drive this, go for it. Otherwise, we will get around to getting the documentation updated.

**Comment by JordonPhillips** [comment]
Closing out since the action items are on the service side. Though it looks like they have removed one layer of duplication and made things more consistent since.
