### ISSUE TITLE
get_template returns string or dict?

### ISSUE THREAD

**Issue by amosshapira** [boto/botocore#1058]
The documentation at http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.get_template says this about the response syntax of `get_template`:
```
TemplateBody (string) --
Structure containing the template body. (For more information, go to Template Anatomy in the AWS CloudFormation User Guide.)

AWS CloudFormation returns the same template that was used when the stack was created.
```
From the `(string)` part, I was expecting to get a single string representation of the template, but when I try to use it, I get a `dict` object:
```
>>> import boto3
>>> region='region'
>>> stack_name='stack-name'
>>> session = boto3.session.Session(region_name=region)
>>> client = session.client('cloudformation')
>>> template = client.get_template(StackName = stack_name)
>>> type(template['TemplateBody'])
<type 'dict'>
```
Am I missing something or is the documentation due to be updated?

**Comment by JordonPhillips** [comment]
Sorry about that! We have a customization that decodes it, but missed on getting the documentation updated.

**Comment by amosshapira** [comment]
No worries. Thanks for taking care of this.
