### ISSUE TITLE
Blank params in base URL not preserved in SigV4 Presigned URL 

### ISSUE THREAD

**Issue by eukaryote** [boto/botocore#1059]
Generating a sigv4 presigned URL when the base URL contains a query parameter without a value results in a presigned URL that doesn't contain the parameter at all, because parse_qs strips blank parameters by default. 

For example, 'https://s3.amazonaws.com/mybucket/mykey?uploads' is a base URL for creating a multipart upload URL, and the resulting presigned URL that is generated by the following code no longer has an 'uploads' param when SigV4 is used:

```
s3.generate_presigned_url(
    'create_multipart_upload',
    Params={
        'Bucket': 'mybucket',
        'Key': 'mykey',
    }
)
```

**Comment by JordonPhillips** [comment]
Lets' go ahead and move all discussion to the PR
