### ISSUE TITLE
Log message in credentials module appears to contradict code

### ISSUE THREAD

**Issue by gatoruso** [boto/botocore#1078]
If an [explicit profile is found](https://github.com/boto/botocore/blob/master/botocore/credentials.py#L86), no log message is generated. If the explicit profile is _not_ found, a [log message is generated](https://github.com/boto/botocore/blob/master/botocore/credentials.py#L104) that says "Skipping environment variable credential check because profile name was explicitly set."

**Comment by JordonPhillips** [comment]
That's true, looks like this was a miss during some refactoring.
