### ISSUE TITLE
Six is imported directly instead of from botocore.compat

### ISSUE THREAD

**Issue by jagill** [boto/botocore#1106]
`six` is directly imported, instead of using `botocore.compat` or `botocore.vendored`, in both
`botocore/configloader.py` and `tests/unit/test_utils.py`.

This manifests if you install botocore into a fresh virtualenv, then try to `import botocore.session` or `botocore.configloader`.  It will die with an `ImportError: No module named six.moves`.

I'm happy to make a PR to fix this if it would help.

**Comment by jamesls** [comment]
Thanks for catching that.  A PR for this would be great.

**Comment by andyfuse** [comment]
Hi folks,
Is it fixed or not? https://github.com/boto/botocore/issues/1179

**Comment by jamesls** [comment]
Working on a PR now.

**Comment by andyfuse** [comment]
I see that PR #1180 is merged. 
When do you plan to release this on pypi? 
Thanks
