### ISSUE TITLE
Support Python 3.6

### ISSUE THREAD

**Issue by Fale** [boto/botocore#1115]
Python 3.6 got released, and some distro (like Fedora) are swithcing to it.

**Comment by jamesls** [comment]
Is there something specific you're running into that's not working?

We run python3.6 against travis, and we fixed the only test failure we're aware of (https://travis-ci.org/boto/botocore/jobs/184373187, https://github.com/boto/botocore/pull/1107)

**Comment by JordonPhillips** [comment]
I assume this is asking for official support. I've sent up a pr to update the various places.
