### ISSUE TITLE
DMS CreateReplicationTask operation: Invalid Table Mapping document

### ISSUE THREAD

**Issue by rakeshkotha** [boto/botocore#1121]
Hi Team,
   I am trying to use boto3 for the dms operations where I tried to create a replication task  for it. While doing so I am getting the below error from the code 

`botocore.exceptions.ClientError:
 An error occurred (InvalidParameterValueException) when calling the CreateReplicationTask operation: Invalid Table Mappings document`

I am using below Table Mapping Json 
`{
  "TableMappings": 
  [
   {
    "Type": "Include", 
    "SourceSchema": "cloudthat_blog", 
    "SourceTable": "%" 
    }
   ]
}`

Please help me on this

Thanks,
Rakesh

**Comment by dstufft** [comment]
I believe that this error is going to be coming directly from the API and botocore does not have any control over it. I suggest asking over on the [database migration service forum](https://forums.aws.amazon.com/forum.jspa?forumID=216&start=0).

**Comment by rakeshkotha** [comment]
Thanks Donald, The issue is resolved and the problem is we are giving the file directly to the replication task creation method but instead we need to pass the json which resolved the issue.

**Comment by dstufft** [comment]
Glad to hear you got it figured out!
