### ISSUE TITLE
UpdateItem response documentation is incorrect

### ISSUE THREAD

**Issue by garrettheel** [boto/botocore#1123]
The documentation from the following page is incorrect:

http://boto3.readthedocs.io/en/stable/reference/services/dynamodb.html#DynamoDB.Client.update_item

> Attributes (dict) --
> A map of attribute values as they appeared before the UpdateItem operation. This map only appears if ReturnValues was specified as something other than NONE in the request. Each element represents one attribute.

This conflicts with the definition of `ReturnValues`:

> ReturnValues (string) --
> Use ReturnValues if you want to get the item attributes as they appeared either before or after they were updated.

It implies that you'll always get attribute values _before_ the update operation, which is not the case if you specify  `"ReturnValues": "ALL_NEW"|"UPDATED_NEW"`

The offending docs are here:
https://github.com/boto/botocore/blob/0387055fc157846d300c116f5da9d63e869814a6/botocore/data/dynamodb/2012-08-10/service-2.json#L1821

I think this should be reworded to something like:

> A map of attribute values as they appeared before or after the <i>UpdateItem</i> operation, determined by <i>ReturnValues</i>.

**Comment by dstufft** [comment]
I agree that this is worded poorly and should be fixed.

**Comment by JordonPhillips** [comment]
We've let the service team know, closing out the issue here
