### ISSUE TITLE
attempt AWS auth with task role before attempting auth with instance role

### ISSUE THREAD

**Issue by brianwhigham** [boto/botocore#1124]
Amazon ECS has provided roles at the task level for several months.  Boto3 has even been able to register task definitions with a role for several months.  But, it doesn't seem to reference the metadata service to actually authenticate itself with the task roles if boto is executing from within an ECS task.

Please attempt to use the ECS task role credentials before using the instance profile credentials.

The task role credentials can be found at http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

The output looks like this:

  ```
{
  "RoleArn": "arn:aws:iam::079393838737363:role/some-role-name",
  "AccessKeyId": "ASDFSKJLWENDKILDSKFJ",
  "SecretAccessKey": "LKJEKJDSLFKDSJFELWKJFWELDFKJSDLFK",
  "Token": "dlkasjdhfe3iudjfKJ22342mnsDKJFSKDHUWEKSJDFHSKHDSFKJSHDFKSJDHFKSDJHFKSJDHFLKSDJHFSDKJFHSDLKJFGSDFJHSDFHGIDWUWHFSDIHJFWKLJHFDSFKJh32342342345235235235/sdslkfjsdlfkjsdf234234234SDFSDFSDFSDFSDoP5kkcV91heXNix8c0CwtI8Hv2TpVkwhw8zU4FUSqQMsAp1pV5bh2iUjcDjbbrM4197ATydI/e+xSl7Gn0QA21Q4yf3ma7XSxXD2QBjSYW3dtSQxhpHJ0iEnWBUaDydolcGtAYa03oj/TOZ7ec1Gi2cCUjgFdrSfs/14oz4rVwwU=",
  "Expiration": "2017-01-11T02:34:23Z"
}
```
Thanks

```
>>> botocore.__version__
'1.4.93'
```
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```
```
python -V
Python 2.7.6
```

**Comment by dstufft** [comment]
Marking as feature request, thanks!

**Comment by freefood89** [comment]
Am I mistaken or does botocore already do this?

https://github.com/boto/botocore/blob/1.4.37/botocore/credentials.py#L76-L77

It looks like the ContainerProvider (169.254.170.2) is earlier in the provider chain than the MetadataProvider (169.254.169.254) all the way back from botocore version 1.4.37

I was able to confirm this on botocore (1.4.93) in a task.

**Comment by GreggBzz** [comment]
Hi @brianwhigham do you have any verification that this feature works as of these versions?

boto3: 1.4.3
botocore: 1.5.79

I can't get it working.. I do see `ContainerProvider()` in the authentication chain..

My IAM task role is configured with the right trust relationship following the AWS guide. Yet, with this code, I get an exception.

```
import boto3
import botocore.session

session = botocore.session.get_session()
sts_client = session.create_client('sts')

assumedRoleObject = sts_client.assume_role(
    RoleArn="arn:aws:iam::<accountid>:role/task-role",
    RoleSessionName="Test1"
)
```

Generates an exception:
`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::<accountid>:assumed-role/task-role/fd43042a-cc1f-4a4a-7b5d-3662a32b3b43 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<accountid>:role/task-role`

Either I'm just doing it wrong or, as this is still an open issue, it never really made it to the versions above.

**Comment by aschokking** [comment]
Did you ever get to the bottom of this?
