### ISSUE TITLE
AssumeRoleProvider shadows SharedCredentialProvider

### ISSUE THREAD

**Issue by martijnvermaat** [boto/botocore#1126]
In the default provider chain, `AssumeRoleProvider` has precedence over `SharedCredentialProvider`. The result is that valid session credentials in `~/.aws/credentials` are ignored when the profile has a `role_arn` value.

We write temporary session credentials for several profiles to `~/.aws/credentials` (not via botocore). These profiles are using assume-role, so to adhere to the standard setup and play nice with other tools, we like to also set `role_arn` for them in `~/.aws/config`. Unfortunately, botocore doesn't use the written credentials in that case.

**Comment by kyleknap** [comment]
Are you sure it does not read it from the ``~/.aws/config`` as well? Implementation-wise the shared credential is merged on top of the config file. So the ``role_arn`` should be picked up. Furthermore in the [documentation](http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles) of the AWS CLI, which is powered by botocore, states that it respects ``role_arn`` in the config file.

Also I have a side question... With what other tools are using with ``botocore``?

**Comment by martijnvermaat** [comment]
@kyleknap Yes, it does read `role_arn` from `~/.aws/config`, but that is the issue. There is no need to start a new assume-role role session (possible asking for an MFA code when MFA is configured) when one is already available in `~/.aws/credentials`.

See the [source code](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L59-L82). With `aws-cli` this behaviour is obscured because `AssumeRoleProvider` is caching (in `~/.aws/cli/cache`, not `~/.aws/cache` as incorrectly stated in the docs you linked), but you'll experience it with any other program using botocore with this default provider chain in `get_credentials()`.

Moving `SharedCredentialsProvider` above `AssumeRoleProvider` fixes this and still passes all the botocore tests.

**Comment by sczizzo** [comment]
I found the same. The behavior as currently implemented is actually [counter to the documentation](https://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials) in terms of search order. I opened PR #1138 some time ago; it's got a bit more context for those interested

**Comment by martijnvermaat** [comment]
@sczizzo Yes, the patch you propose is exactly what I also tried. It passes all tests and fixes the issue. The use case you describe is also very similar to mine.
