### ISSUE TITLE
Lower dateutil dependency

### ISSUE THREAD

**Issue by Fale** [boto/botocore#1128]
On some systems, such as EL7, dateutil 2.1 is not present, but dateutil 1.4 is present.
We have botocore running on such systems by [patching the requirement](http://pkgs.fedoraproject.org/cgit/rpms/python-botocore.git/tree/botocore-1.5.3-fix_dateutil_version.patch).
This has no side effects, as far as we saw, so I think it should be done in the upstream version as well.

**Comment by kyleknap** [comment]
Marking as feature request. We would have to do some research to see if it is possible to loosen the requirement. One initial concern that I have off the bat is that it would span across major versions, which do not guarantee backwards compatibility. So we would have to do some research to see what changed.

**Comment by Fale** [comment]
Some information about this can be found at: https://github.com/dateutil/dateutil/blob/master/NEWS. It seems like the big change that brought them to switch from 1.x to 2.x has been the introduction of py3

**Comment by jurgenhaas** [comment]
I do have a similar request but wanted to ask if the upper limitation could be removed though. My PIP is playing pingpong for a couple of weeks now because some packages would like to install python-dateutil 2.7.2 where cotocore has an upper limit of 2.7 for that package. Could that be removed probably?

**Comment by tjrileywisc** [comment]
@jurgenhaas 
Running into something similar- the develop branch has set an upper limit for python-dateutil set to 3.0.0 for python 2.7 and above, though I'm not sure how stable that branch is. You could try installing that branch through pip.

**Comment by jurgenhaas** [comment]
@tjrileywisc well I'm running botocore on production servers and won't go for a dev release. I think, the current stable release should simply allow dateutil version 2.x and not `<2.7` unless something got introduced in 2.7 that breaks it - which is very unlikely I guess.
