### ISSUE TITLE
Duplicate errors in RDS service definition

### ISSUE THREAD

**Issue by adimarco** [boto/botocore#1137]
The RDS service definition contains a couple `errors` lists with duplicate entries.  Specifically:

* `RestoreDBClusterFromSnapshot` has `StorageQuotaExceededFault` and `DBSubnetGroupNotFoundFault` twice
* `RestoreDBClusterToPointInTime` has `StorageQuotaExceededFault` and `DBSubnetGroupNotFoundFault` twice

Not a big deal to work around, but figured I'd log the issue.

**Comment by JordonPhillips** [comment]
Thanks for reporting! I've informed the service team about the issue. I'm closing out the issue here, but feel free to report if you find any other such cases.
