### ISSUE TITLE
 Instance type 'r4.2xlarge' is not supported

### ISSUE THREAD

**Issue by dailinge** [boto/botocore#1147]
I'm getting an error with 1.5.7:
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the RunJobFlow operation: Instance type 'r4.2xlarge' is not supported 

I checked the latest listed instance type and r4.2xlarge is there. Could you guys help triage?

**Comment by stealthycoin** [comment]
Hi @dailinge 

Which region was this in? What is the exact call you are making that returns this error?

**Comment by pabloqc** [comment]
I had the same issue with Elasticbeanstalk, it is not yet supported in eu-west-1

**Comment by JordonPhillips** [comment]
As mentioned, the support for this is based on your region.
