### ISSUE TITLE
Can't generate documentation

### ISSUE THREAD

**Issue by ouroboroscoding** [boto/botocore#1155]
I installed sphinx and ran `make html` in the doc folder and...

> sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.6
making output directory...

> Exception occurred:
  File "conf.py", line 15, in <module>
ImportError: No module named botocore.session
The full traceback has been saved in /tmp/sphinx-err-sVqWfT.log, if you want to report the issue to the developers.

Log file renamed to .txt so github would accept it
[sphinx-err-sVqWfT.txt](https://github.com/boto/botocore/files/784259/sphinx-err-sVqWfT.txt)

**Comment by ouroboroscoding** [comment]
The same thing happens no matter what documentation output type I select. It seems strange to me that a file from the repo in question is necessary to generate the docs. That would mean I need to install botocore first before I can even find out how to use it?

**Comment by dstufft** [comment]
Currently the botocore docs do require botocore to be installed (or at least importable) before you can generate the documentation. That is by design as the doc building using some parts of botocore itself.

**Comment by ouroboroscoding** [comment]
And you don't see how this is a problem? Would it not be wiser to provide the documentation instead of a broken make process?
