### ISSUE TITLE
Fix for date parsing in AssumeRoleProvider _is_expired check

### ISSUE THREAD

**Issue by richarpw** [boto/botocore#1163]
The current AssumeRoleProvider._is_expired check will pull the expiration date time from cache when checking the expiration. The expiration is stored as a datetime however the method attempts to parse it as a string. The resolution is to use the credentials._parse_if_needed method instead of the dateutil.parser parse method.

**Comment by dstufft** [comment]
The cached object is a response from ``client.assume_role()``, and as per the documentation, that type looks like:

```python
{
    'Credentials': {
        'AccessKeyId': 'string',
        'SecretAccessKey': 'string',
        'SessionToken': 'string',
        'Expiration': datetime(2015, 1, 1)
    },
    'AssumedRoleUser': {
        'AssumedRoleId': 'string',
        'Arn': 'string'
    },
    'PackedPolicySize': 123
}
```

This appears to be a valid bug.

**Comment by dstufft** [comment]
Are you able to tell me what error you got or steps to reproduce this? I'm looking at this and trying to figure out how this ever worked and that would be useful.
