### ISSUE TITLE
ParamValidator object has no attribute 'validate_msg' error

### ISSUE THREAD

**Issue by jegesh** [boto/botocore#1165]
I just started getting this error when calling `list_queues()` on a sqs client object.  The error emanates from the file `botocore/validate.py`, on line 267.  I'm using python 2.7.13, botocore version 1.5.26.  This may be a regression in the latest update to the library, since this is the first time getting it in code that hasn't changed in a number of months, and I recently bumped the boto version.  

Then again, I tried downgrading to v1.4 and then to v1.3, and I'm still getting the error.

**Comment by stealthycoin** [comment]
To be clear you are doing something like this?

```python
import botocore.session

session = botocore.session.get_session()
sqs = session.create_client('sqs', region_name='us-west-2')
response = sqs.list_queues()
print(response)
```

**Comment by jegesh** [comment]
For the record, this is my code:
```
    self._client = boto3.client('sqs')
    self._queue_name = queue
    queues = self._client.list_queues()
```

In the meantime, I nuked the virtual env, reinstalled all packages, and it's working fine again.
