### ISSUE TITLE
SignatureDoesNotMatch when s3 metadata contains two consecutive spaces

### ISSUE THREAD

**Issue by kilburn** [boto/botocore#1169]
# Description

Including two consecutive spaces in a metadata entry triggers an invalid signature error when uploading a file to s3.

# How to reproduce
The following code shows the issue. Notice that the `'Double  Space'` string contains two spaces between the words:
```
import boto3

session = boto3.session.Session(region_name='eu-central-1',
  aws_access_key_id='***redacted***',
  aws_secret_access_key='***redacted***')

s3 = session.resource('s3')
item = s3.Object('**redacted**', 'test.pdf')
item.upload_file('test.pdf', ExtraArgs={
        'Metadata': {'key': 'Double  Space'}
})
```
Running this throws:
```
boto3.exceptions.S3UploadFailedError: Failed to upload test.pdf to **redacted**/test.pdf: An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
However, removing one of the spaces and re-running succeeds without errors.

# Test system
- OS X 10.11.6
- Python 2.7.12 (macports compiled)
- botocore 1.5.26

**Comment by dstufft** [comment]
I'm guessing that this is going to be the same thing as https://github.com/aws/aws-cli/issues/2474.

**Comment by dstufft** [comment]
This is certainly a bug, although I'm not entirely sure if it is a bug in botocore or a bug in the services, but I believe that either botocore should do this normalization when generating the signature, or the services should not.

**Comment by jamesls** [comment]
Fixed via https://github.com/boto/botocore/pull/1182
