### ISSUE TITLE
S3 client for Asia Pacific (Mumbai) cannot connect to buckets in  Asia Pacific (Mumbai)

### ISSUE THREAD

**Issue by deepakAWS** [boto/botocore#1178]
I checked with US-East(Viginia) region bucket, the code works fine, but same code does not work with Mumbai region bucket

```
s3 = boto3.client('s3')
filename = 'C:\\IMG_5350.jpg'
bucket_name = 'deletebucket007'
# Uploads the given file using a managed uploader, which will split up large
# files automatically and upload parts in parallel.
s3.upload_file(filename, bucket_name, filename)

error is
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

**Comment by JordonPhillips** [comment]
You will need to use signature version 4 (`s3v4`) in that region, as signature version 2 is not supported.

**Comment by deepakAWS** [comment]
ok and is this the only way to do it
client = boto3.client('s3', config=Config(signature_version='s3v4'))

**Comment by JordonPhillips** [comment]
You can also set the configuration in your config file (`aws configure set s3.signature_version s3v4`)
