### ISSUE TITLE
Minor issue in retryhandler - random.random() can return 0

### ISSUE THREAD

**Issue by jseakle** [boto/botocore#1194]
in the function delay_exponential, at [line 53](https://github.com/boto/botocore/blob/c632931a6cc5eab4113c976d430bcb9c059f829f/botocore/retryhandler.py#L53), base is set to random.random(). However, the documentation (and the other branch of that if) declare that "Base must be greater than 0.", and the [spec for random.random()](https://docs.python.org/3/library/random.html#random.random) is that it will return a float in the range [0.0, 1.0), which includes 0.0. 

Thus, in extremely rare cases, time_to_sleep could repeatedly be 0, defeating the purpose of exponential backoff.

**Comment by JordonPhillips** [comment]
That random base is generated every time and serves to introduce jitter.

**Comment by jseakle** [comment]
Ah, I guess it's true that it's not going to be 0 every time for a given retry (unless you're absurdly unlucky), it's just going to be 0 once. Retrying immediately instead of after five seconds is probably not usually a big deal, but it's still incorrect.

**Comment by joguSD** [comment]
Seeing as this is an internal implementation detail and we do not currently have plans to change it I'm going to go ahead and close this issue out.
