### ISSUE TITLE
No exponential backoff for EMR

### ISSUE THREAD

**Issue by aiell0** [boto/botocore#1199]
For EMR, calling `DescribeCluster` for each EMR in an account gets throttled after 4 max retries. I created a PR for a fix, but it has not yet been approved.

https://github.com/boto/botocore/pull/1192

**Comment by aiell0** [comment]
From test results, I call DescribeClusters on a total of 27 clusters, and I am getting rate limited on those with the default configuration. This is **after** I filtered out terminated or terminating clusters, so this is just a list of active and running clusters. This is not acceptable.

**Comment by dstufft** [comment]
Going to close this to keep the discussion on the PR (#1192) as mentioned in the original issue (https://github.com/boto/botocore/issues/1193). Thanks!
