### ISSUE TITLE
How can I log request IDs (S3)

### ISSUE THREAD

**Issue by btoueg** [boto/botocore#1200]
I'm having a lot of those lately https://github.com/boto/boto3/issues/1090

I've opened a ticket in the Amazon Web Services Support Center and they ask me to provide `request IDs of the failed requests of the error time outs`

Is there an easy way to log those, or do I have to fork and dive into the code?

**Comment by stealthycoin** [comment]
It in the response as the`x-amz-request-id` header.
You can enable maximum logging with `boto3.set_stream_logger('')`  which will log the response headers you get back from all requests.

**Comment by btoueg** [comment]
Thx
