### ISSUE TITLE
Question: how is botocore redacting my plaintext when I call Encrypt?

### ISSUE THREAD

**Issue by 2rs2ts** [boto/botocore#1210]
Example log line:

```
2017-05-31 23:30:30,323:DEBUG:botocore.endpoint:endpoint.py:140:Making request for OperationModel(name=Encrypt) (verify_ssl=True) with params: {'body': '{"Plaintext": "Ym9vcA==", ....
```

My actual plaintext was just the string `"boop"`. So how'd this value get put there instead? I am curious to see whether it is safe for me to be writing these logs to disk, or if that would expose my secret.

**Comment by ctso** [comment]
`Ym9vcA==` is simply the base64 encoded value of `boop`:

```
$ echo "Ym9vcA==" | base64 -d
boop
```

**Comment by 2rs2ts** [comment]
Ah, well, that answers that. Thanks.
