### ISSUE TITLE
Can we get the spot instance price with the granularity of minute with describe-spot-price-history?

### ISSUE THREAD

**Issue by syang** [boto/botocore#1215]
http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-price-history.html does not provide a granularity parameter, and a naive query gives me the granularity of one data point per day.

Can I somehow get the price granularity for one data point per minute (or at least per 5 minutes)? I only need the data for the last two hours.

**Comment by JordonPhillips** [comment]
This question would be best suited for the service team or one of our [community resources](https://github.com/boto/botocore#getting-help), unfortunately I haven't got the expertise to help out.
