### ISSUE TITLE
SignatureDoesNotMatch generate_presigned_url with put_object and KMS

### ISSUE THREAD

**Issue by badisa** [boto/botocore#1226]
I have a bucket that only supports put_object when used with KMS, so I am attempting to generate a presigned_url so that users can upload arbitrary files without having credentials. Now the following code works fine without the ServerSideEncryption and SSEKMSKeyId fields on buckets that don't have this restriction.

And I have numerous calls in the codebase to s3 using put_object with the kms encryption, it just seems to be a problem with the presigned_url.

```
import requests
from botocore.session import Session
from botocore.config import Config
session = Session()
s3 = session.create_client('s3', config=Config(signature_version='s3v4'))

url = s3.generate_presigned_url(
    'put_object',
    Params={
        'Bucket': 'mybucket',
        'Key': 'object_key',
        'ServerSideEncryption': 'aws:kms',
        'SSEKMSKeyId': 'kms_key',
    },
    ExpiresIn=1000,
    HttpMethod='PUT'
)

files = {
    'file': "path/to/file.txt"
}
resp = requests.put(url, files=files)

```

Am I missing something obvious?

**Comment by badisa** [comment]
Figured out the issue, I needed to exclude the SSEKMSKeyId and add the header `'x-amz-server-side-encryption': 'aws:kms'` to the requests.put call.

**Comment by dai-fuji** [comment]
@badisa 
Hello,
Cloud you explain code finaly?
I am also having the same problem.
