### ISSUE TITLE
Support for Mediaflux S3 

### ISSUE THREAD

**Issue by sachsbl** [boto/botocore#1232]
I'm working on a project backed by a non-AWS S3 installation. It uses Mediaflux S3 (http://www.arcitecta.com/Products/Mediaflux). That was not my decision, and I know this means AWS isnt getting paid ;-), but I'd like to still use boto3 as my client for this. Mediaflux is an Australian product and it likes to use commas in float values i.e "2345,67" instead of "2345.67" in its ContentLength headers. This causes a fatal error in boto3 and makes it impossible to use boto3 against Mediaflux. To resolve this, I successfully monkey-patched botocore.

Gist:
https://gist.github.com/sachsbl/f6619b1d735641233e6e6b68fbb5aa58

Wrapped-client implementation:
https://github.com/sachsbl/Mediaflux_S3

I would like to apply this patch to botocore itself so we can abandon my monkey-patch approach. I plan on opening a Pull Request with the small change required. Thanks!

**Comment by dstufft** [comment]
Hey there!

While I understand this can be frustrating, I'm going to close this issue as it's not something that we're going to want to support. I would suggest raising a bug report with Mediaflux instead.
