### ISSUE TITLE
A urllib3 connection is not put back in the pool after HEAD

### ISSUE THREAD

**Issue by timuralp** [boto/botocore#1248]
Issuing a HEAD request results in the connection not being put back into the urllib3 pool. ~~This is tied to this issue in urllib3: https://github.com/shazow/urllib3/issues/673. The problem is resolved in urllib3 >= 1.11. However, botocore vendors requests 2.7.0, which vendors urllib3 1.10.4. Updating the vendored requests library to >= 2.8.0 would resolve this issue.~~

Relevant issue in urllib3: https://github.com/shazow/urllib3/issues/1234

**Comment by timuralp** [comment]
Here's an example to reproduce the issue:
```
import boto3

s = boto3.session.Session(aws_access_key_id=<AWS_ACCESS_KEY_ID>,
                          aws_secret_access_key=<AWS_SECRET_ACCESS_KEY>)
client = s.client('s3')
bucket = <Bucket>
try:
    client.put_object(Bucket=bucket, Key='foo')
    urllib3_pool = client._endpoint.http_session.adapters['https://'].poolmanager.pools._container.values()[0].pool
    print 'Size after PUT:', urllib3_pool.qsize()
    client.head_object(Bucket=bucket, Key='foo')
    print 'Size after HEAD 200:', urllib3_pool.qsize()
    client.head_object(Bucket=bucket, Key='bar')
except:
    pass
print 'Size after HEAD 404:', urllib3_pool.qsize()
```

I can reproduce it after HEAD returns 404, but not after 200.

**Comment by timuralp** [comment]
Spent more time debugging this. It's not actually fixed in urllib3 and requests as I original thought. I will open an issue with urllib3 and then with requests about this.

**Comment by timuralp** [comment]
Filed bugs in urllib3 (https://github.com/shazow/urllib3/issues/1234) and requests (https://github.com/requests/requests/issues/4199), along with a PR to fix this in urllib3 (https://github.com/shazow/urllib3/pull/1235).

There is a packaging issue for botocore. New versions of requests do not vendor urllib3 anymore. Does botocore want to continue vendoring urllib3 (previously indirectly through requests)? That would require adding a hack to register it so that requests can find it. Or if boto does not vendor urllib3, the dependency can be set in requirements.

**Comment by joguSD** [comment]
Upgrading `requests`/`urllib3` may fix: https://github.com/boto/boto3/issues/1053

**Comment by joguSD** [comment]
Seems that this was fixed upstream in: https://github.com/shazow/urllib3/pull/1235
Still need to update botocore to use newer versions.

**Comment by timuralp** [comment]
@joguSD do you know what the plan for botocore regarding urllib3 is? Currently, botocore vendors an old `requests` release, which vendors `urllib3`. However, a newer version of `requests` would not do that. Do you expect the right solution would be to patch the vendored `urllib3`? Or to update vendored `requests` to a version that does not vendor `urllib3` and then either vendor `urllib3` or specify a version dependency to address this issue?

Happy to submit a PR if there is some clarity on what the right path forward is.

**Comment by joguSD** [comment]
We currently vendor requests as we make some modifications to it, so upgrading it isn't straight forward. I'll bring this up and see what path we want to take moving forward. At least personally I think moving away from vendoring requests would be ideal so we can get upstream bug fixes and avoid issues when some some distributions (ubuntu for example) re-package our library. I can't make any promises though, and I wasn't around when the decision to vendor requests was made so once I hear the reasons behind that my opinion may change.

**Comment by genben** [comment]
I understand that update of the vendored urllib3 is not a priority. Can you just apply a hotfix?
I have submitted PR #1300. 
All credits to @timuralp

**Comment by timuralp** [comment]
@joguSD do you think maybe the `investigating` tag is no longer warranted? Is there anything else to further understand about this problem? I would think a `bug` label would be appropriate.

**Comment by joguSD** [comment]
Another reason to update urllib3: https://github.com/boto/boto3/issues/1053

**Comment by joguSD** [comment]
Another reason: ipv6 proxy supprt.
https://github.com/boto/botocore/issues/1325

**Comment by dww84** [comment]
Any update on this fix?

**Comment by Hernrup** [comment]
We are also experiencing this issue now. We desperately need a new urllib to fix multiple bugs. Boto3 is currently not usable for our company.

**Comment by dariusjs** [comment]
Would this also be affecting the upload_fileob() I’ve just spent a few days running into an issue where I see these S3 connection resets. Have switched on the debug logging but still need to figure out what to look for. I see it tries to multipart one of my objects and then it goes wrong. This is after it has dealt with 75 objects successfully.

**Comment by joguSD** [comment]
We have un-vendored requests/urllib3 and are now using urllib3 directly as of `botocore` v1.11.0.
