### ISSUE TITLE
Regarding kinesis list_streams `next token` invention

### ISSUE THREAD

**Issue by joykabir** [boto/botocore#1251]
Hi,

So far I found various botocore clients return `NextToken, nextToken, NextMarker, Marker, NextContinuationToken, position,  whatNot` etc. marker as key-value in the root level of response if there are more items to fetch. However, [Kinesis list_steams](http://botocore.readthedocs.io/en/latest/reference/services/kinesis.html#Kinesis.Client.list_streams) breaks this pattern. It wants next token to be the last item from the list of steams. Seriously! You guys are breaking your own invention. Why don't you follow similar pattern as other clients?

I have a utility function that automatically loops through tokens and fetches items based on various markers. Now Kinesis list_streams() breaks this totally. I would greatly appreciate if this behavior is modified as other clients.

Thanks //Zia

**Comment by joguSD** [comment]
Botocore has a pagination feature that handles the pagination of many operations for you. Specifically, the `list_streams` operation you mention has pagination support: [Paginator.ListStreams](http://botocore.readthedocs.io/en/latest/reference/services/kinesis.html#Kinesis.Paginator.ListStreams).

**Comment by joykabir** [comment]
Well, that is not the answer to the request. Anyways, thanks for replying. //Zia
