### ISSUE TITLE
API Gateway Documentation Duplicate AWS CLI targets

### ISSUE THREAD

**Issue by cwgem** [boto/botocore#1268]
This is coming from aws/aws-cli#2786. Looking over the botocore service files for API gateway, there are multiple links with the "AWS CLI" target including the `get-method` method. Needs to be something more specific to avoid sphinx target errors on the `aws-cli` side. Since I'm anticipating that these service files are auto generated I'm holding off on any sort of pull request.

**Comment by JordonPhillips** [comment]
Looks like the change is related to a recent change we made to make all links explicit so that we could have duplicates. Turns out that rst wants you to put two underscores after explicit hyperlinks to make them "anonymous". Sphinx will render what you would expect, but throw a warning.
