### ISSUE TITLE
GetBucketLifecycle

### ISSUE THREAD

**Issue by sven-schubert** [boto/botocore#1278]
in botocore/botocore/data/s3/2006-03-01/service-2.json

currently there is:
```
 "GetBucketLifecycleOutput":{
      "type":"structure",
      "members":{
        "Rules":{
          "shape":"Rules",
          "locationName":"Rule"
        }
      }
},
```

I think this is wrong. shape/member should be of type:
```
    "LifecycleRules":{
      "type":"list",
      "member":{"shape":"LifecycleRule"},
      "flattened":true
},
```

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlifecycle.html

**Comment by dstufft** [comment]
It is correct, the ``GetBucketLifecycleOutput`` as a member named ``Rule`` which is of type ``Rules`` which looks similar to what you posted.

**Comment by sven-schubert** [comment]
But Rule does not have, e.g. the "Filter" member as described in AWS docs:
