### ISSUE TITLE
S3 PostObject operation

### ISSUE THREAD

**Issue by Evgenus** [boto/botocore#130]
I need it to be described in JSON to be able to presign request for upload from browser (and clients without PUT method support). 

PS: Also it would be great to have presigning API method.

**Comment by kyleknap** [comment]
The feature is currently available in botocore: http://botocore.readthedocs.org/en/latest/reference/services/s3.html#S3.Client.generate_presigned_post

Here is an example of how to use the method: https://github.com/boto/botocore/blob/develop/tests/integration/test_s3.py#L468

Closing issue. Please let me know if you have any more questions or comments.
