### ISSUE TITLE
Error when trying to read 0 byte from StreamingBody

### ISSUE THREAD

**Issue by youhyunkim** [boto/botocore#1309]
Referring to the read method of `StreamingBody`:
https://github.com/boto/botocore/blob/c632931a6cc5eab4113c976d430bcb9c059f829f/botocore/response.py#L69-L81

If anyone asks for 0 bytes from a StreamingBody, the conditional on line 76 will pass because chunk is empty (since 0 bytes were asked for) and amount was set to 0 (not None). This leads to the content length verification, which will fail because you've read 0 bytes so far out of the entire content.

Might be an odd use case, but I feel like is a valid use case.
In fact, I ran into this issue when trying to use the `ijson` package [link](https://pypi.python.org/pypi/ijson).
That library uses `.read(0)` in order to figure out what type of encoding the stream reader should use. Whether that's the best way to do it or not, I'm not entirely sure. But I feel like `.read(0)` should still be supported.

If you guys agree that it should be supported, maybe considering a condition like this:
```
if (not chunk and amt > 0) or amt is None:
```

**Comment by joguSD** [comment]
Thanks for the PR @youhyunkim. I've cleaned up the PR to pass all unit tests and added a test to validate this change in #1312.
