### ISSUE TITLE
[docs] Correct Firehose docs that tell users to implement retry logic

### ISSUE THREAD

**Issue by aldraco** [boto/botocore#1311]
According to [this issue comment](https://github.com/boto/boto3/issues/505#issuecomment-191439062) and the retry .json, there is already retry logic for 503 errors built into the botocore Firehose client.

From https://boto3.readthedocs.io/en/latest/reference/services/firehose.html#Firehose.Client.put_record_batch
> If PutRecordBatch throws ServiceUnavailableException , back off and retry. If the exception persists, it is possible that the throughput limits have been exceeded for the delivery stream.

However, the docs claim that the **user** needs to implement retry logic, which is unnecessary.

Also relevant:
https://github.com/boto/boto3/issues/597
https://github.com/boto/boto3/issues/505

Somewhat relevant:
https://github.com/boto/botocore/issues/885

**Comment by joguSD** [comment]
That specific piece of documentation is generated from the service documentation (which is unaware of what botocore is doing). I can definitely see how this is confusing.

**Comment by wolfson109** [comment]
It would also be useful to include in the updated documentation how to configure the retry behaviour (e.g. number of attempts etc.).

**Comment by aldraco** [comment]
@joguSD yes, the other issues I linked mention that, but it is not stated in the docs themselves for boto3, so there is no simple way to figure that out. The docs are read as docs for `boto3`'s library, which is two layers above the underlying service. 

Perhaps there is a way to layer some kind of documentation on top of the generated docs to clarify what `boto(3)/botocore` implement and abstract away for the programmer, and what they don't.

I would be happy to help out with such an effort, I think it would be worthwhile for many users.

**Comment by YunchengLiao** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html?highlight=serviceunavailableexception

I came across the doc, it still indicate to retry.

**Comment by yotamss** [comment]
Also got confused by the docs, any plans to add that to the docs?

**Comment by tim-finnigan** [comment]
As noted early, the service documentation is generated upstream. So we don’t have control over the Firehose docs but we can pass feedback on to them. I created this issue in our shared SDK repository to update the wording around retries in those docs: https://github.com/aws/aws-sdk/issues/208

In the general reference guide on [API retries](https://docs.aws.amazon.com/general/latest/gr/api-retries.html) it does note that "Each AWS SDK implements automatic retry logic." For boto3 retry documentation you can refer to this page: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html
