### ISSUE TITLE
Latest changes to credentials.py broke patch from #1157

### ISSUE THREAD

**Issue by et304383** [boto/botocore#1320]
I don't know what was done here, but now applying a patch from #1157 to try to use cached credentials from ~/.aws/cli/cache no longer works.

As a result, we're not wasting time putting our MFA in every single time we run python shell scripts.

It's ridiculous that 1157 sat open for so long.

If you somehow added caching of credentials in the latest changes to credentials.py can you please document how we can use file cache for credentials?

**Comment by joguSD** [comment]
Looks like the PR got fixed up. Closing this out.
