### ISSUE TITLE
urllib3 / botocore 

### ISSUE THREAD

**Issue by limbo127** [boto/botocore#1325]
Hello,
it seems that urllib version using by botocore does not manage ipv6 proxy correctly,
as https://github.com/shazow/urllib3/commits/master/urllib3/connectionpool.py 

can you correct this ?
Regards, 
Nicolas Prochazka

**Comment by joguSD** [comment]
Unfortunately upgrading urllib3 is not so straightforward as we vendor it. 

Let's track requests to update urllib3 here: https://github.com/boto/botocore/issues/1248
This is yet another reason to update urllib3.
