### ISSUE TITLE
Allow process provider to work with assume role provider

### ISSUE THREAD

**Issue by stell-aelsabbahy** [boto/botocore#1329]
It would be nice if this configuration combination is allowed:
```
[profile1]
credential_process = creds_tool

[profile2]
source_profile = profile1
role_arn       = arn:aws:iam::account:role/blahblah_role
```

Currently the AssumeRole provider does not support the ProcessProvider added in #1316:
https://github.com/boto/botocore/blob/b4f017e865ab83db5dcd84dce2628742e11a2d03/botocore/credentials.py#L1315-L1322

First it checks if the source profile is static creds, then it falls back to load_creds_via_assume_role. What I would expect it to do is check for `process_provider` and use the ProcessProvider to resolve the source.

**Comment by JordonPhillips** [comment]
Right now we don't support any credential source that requires configuration except for AssumeRole. This was done to make the change simpler, as it was already a major change.

I would definitely like to see us add support for arbitrary providers in the future, but it'll be another hefty change. One problem is that the `AssumeRoleProvider` doesn't have the context to know what providers source configuration from the config file vs some other place. Even if it did, it would further need to know which providers are actually present in the chain.

It would be great to do some major refactoring here, but it's hard to do too much without making breaking changes.

**Comment by stilvoid** [comment]
Hard or impossible? It would be great to support this so that we can keep credentials somewhere safe (I use [pass](passwordstore.org)) and still be able to use assume role :)

**Comment by ChristianWilkie** [comment]
+1

**Comment by kwokster10** [comment]
Linked to https://github.com/aws/aws-cli/issues/3624.

**Comment by ngrilly** [comment]
Is this issue still relevant?

It looks it works now:

```
$ cat ~/.aws/config
[default]
credential_process = /usr/local/bin/aws-credentials.sh
[admin]
source_profile = default
role_arn       = arn:aws:iam::account:role/admin_role
$ aws --version
aws-cli/1.16.303 Python/3.7.6 Darwin/18.6.0 botocore/1.13.39
$ AWS_PROFILE=profile2 aws sts get-caller-identity
{
    "UserId": "REDACTED:botocore-session-REDACTED",
    "Account": "REDACTED",
    "Arn": "arn:aws:sts::REDACTED:assumed-role/admin_role/botocore-session-REDACTED"
}
```

**Comment by ngrilly** [comment]
@iliana If it doesn't work in your environment, I'd be happy to try to understand the difference between your environment and mine.

**Comment by iliana** [comment]
Just tested in an environment very similar to my current setup and it works fine (`aws-cli/1.16.314 botocore/1.13.50`). :tada:

**Comment by ngrilly** [comment]
@JordonPhillips wrote this in December 2017:

> Right now we don't support any credential source that requires configuration except for AssumeRole. This was done to make the change simpler, as it was already a major change.

But it seems that a series of commit from him have fixed this in July 2019:

https://github.com/boto/botocore/commits/develop/botocore/credentials.py

**Comment by ngrilly** [comment]
@iliana Very happy to have confirmation from someone else :)

**Comment by joguSD** [comment]
@ngrilly Is correct, this was implemented a while back in the file you linked. We just missed closing the issue.
