### ISSUE TITLE
Use a centrally configured ca-bundle where one is available.

### ISSUE THREAD

**Issue by apmclean** [boto/botocore#1332]
Using an example of a RHEL 7.4 Server and AWS CLI:

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
# uname -a
Linux ip-10-30-1-172.ec2.internal 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
# aws --version
aws-cli/1.14.3 Python/2.7.5 Linux/3.10.0-693.el7.x86_64 botocore/1.8.7
```

Botocore includes it's own cacert.pem file:
`/usr/lib/python2.7/site-packages/botocore/vendored/requests/cacert.pem`

However RHEL 7 has a centrally managed ca-bundle located at:
`/etc/pki/tls/certs/ca-bundle.crt`

The Python 'requests' library included with RHEL (`python-requests-2.6.0-1.el7_1.noarch`) has over-ridden the default certificate location in `certs.py` and refers to the central certificate bundle.

Contents of `/usr/lib/python2.7/site-packages/requests/certs.py`:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
certs.py
~~~~~~~~

This module returns the preferred default CA certificate bundle.

If you are packaging Requests, e.g., for a Linux distribution or a managed
environment, you can change the definition of where() to return a separately
packaged CA bundle.

We return "/etc/pki/tls/certs/ca-bundle.crt" provided by the ca-certificates
package.
"""

try:
    from certifi import where
except ImportError:
    def where():
        """ Don't use the certs bundled with requests, use ca-certificates. """
        return "/etc/pki/tls/certs/ca-bundle.crt"

if __name__ == '__main__':
    print(where())
```

Users expect that updates made to their central ca-bundle using the 'ca-certificates' tooling would be respected by botocore.  Can botocore use the requests library that comes with the O/S?  Or can some logic be added if there is an existing requests library to use its `certs.py` routine to locate the ca-bundle?

A simple workaround at present would be a symlink:
`ln -sf /etc/pki/tls/certs/ca-bundle.crt /usr/lib/python2.7/site-packages/botocore/vendored/requests/cacert.pem`

Thanks!

**Comment by stealthycoin** [comment]
Botocore already supports custom CA_BUNDLE either at the environment variable layer or the client construction layer. You can provide a path to the `verify` kwarg on the botocore client described [here](http://boto3.readthedocs.io/en/latest/reference/core/session.html#boto3.session.Session.client).

Or you can use the `AWS_CA_BUNDLE` environment variable described [here](http://boto3.readthedocs.io/en/latest/guide/configuration.html#environment-variable-configuration).

Is that what you were looking for?

**Comment by apmclean** [comment]
I was aware of the environment variables thanks!

For distributions that are . . .

* Unifying their CA bundles into a single location with tooling to manage.
* Modifying the Python requests library to point to that single location.

. . . that it would make sense to use / respect those configurations versus having to manage environment variables.  TLS intercepting proxies are becoming more and more common in enterprise environments, and it would make sense to play along as the various distributions start to address the central bundle use-case.

**Comment by jamesls** [comment]
The bundled cert is only used by botocore when connecting to AWS services, and it doesn't affect other python scripts.  We also allow you to override this var if needed (via the `AWS_CA_BUNDLE` as @stealthycoin mentions).

If this starts to cause issues for customers this is something we can take another look at.  For the time being though, changing the default behavior is challenging without affecting existing customers.
