### ISSUE TITLE
How to create presigned url for CloudFront by specified the Content-Type?

### ISSUE THREAD

**Issue by jiamo** [boto/botocore#1341]
With  `generate_presigned_post(Bucket, Key, Fields=None, Conditions=None, ExpiresIn=3600)` 
in class `S3PostPresigner`,  The `Fields` can pass ` Content-Type` as a key.

While for CloudFront I also need to set the content-type of file while I don't want to set a again after upload  by the  presigned url which generated by `CloudFrontSigner` 's `generate_presigned_url`.

Is there a easy way to do it? This may be feature request?

**Comment by joguSD** [comment]
What operation are you trying to create a presigned URL for?

**Comment by jiamo** [comment]
```python
cf_signer = CloudFrontSigner(key_id, rsa_signer)
cf_signer.generate_presigned_url(url, date_less_than=date_less_than)
```
I creathe the presigned url for user to upload file to s3 and I need the right Content-Type in s3.

**Comment by patrickf55places** [comment]
I would like to extend this to pass any custom header. I use it to authenticate using IAM. I use a custom header to protect against some replay attacks (basically, I do what [Vault does](https://www.vaultproject.io/docs/auth/aws.html#iam-auth-method)) on the `sts:GetCallerIdentity` API.

**Comment by JordonPhillips** [comment]
Unfortunately the [CloudFront presigned url spec](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html) does not allow for presigning headers, so this is not something we will be able to support.

**Comment by xchux** [comment]
@JordonPhillips According to  [custom-policy](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html) whether could I setting parameters of `response-content-type` to get response with header Content-Type?
Or needed to setting in  AWS?
