### ISSUE TITLE
Please add eu-west-3 to the list of available regions

### ISSUE THREAD

**Issue by dumrauf** [boto/botocore#1342]
When calling `get_available_regions('ec2')` in `session.py`, _eu-west-3_ is not contained in the list of available regions that gets returned. However, the region is contained in line 607 of `endpoints.json`.

I believe the region not being returned is due to the fact that the _eu-west-3_ region is missing in the `regions` section (lines 12 to 55) of `endpoints.json`. This causes the check in line 114 of `regions.py` to evaluate to `False` and exclude the region from the list of regions that eventually gets returned.

Adding
```
"eu-west-3" : {
  "description" : "EU (Paris)"
}
```
to the aforementioned `regions` section (lines 12 to 55) of `endpoints.json` should fix the bug.

**Comment by joguSD** [comment]
This is fixed in the release today (v1.8.17).

Just for reference you also could have used the EC2 API directly: `ec2.describe_regions()`.

**Comment by dumrauf** [comment]
Thanks for the quick turnaround, much appreciated. Keep up the great work!
