### ISSUE TITLE
ResourceOwner parameter doesn't validate as documented

### ISSUE THREAD

**Issue by Bashton-MattBuckland** [boto/botocore#1346]
Hi,

Not sure if this is the correct place for this, but I'm having some trouble with `iam.simulate_principal_policy` when setting `ResourceOwner`:

```
#!/usr/bin/env python

import boto3

iam = boto3.client('iam')

response = iam.simulate_principal_policy(
        PolicySourceArn='arn:aws:iam::<actualaccountid>:role/moo',
        ActionNames=['s3:GetObject'],
        ResourceOwner='123456789012')
```
When I run this I get:

```
Traceback (most recent call last):
  File "./moo.py", line 10, in <module>
    ResourceOwner='123456789012')
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 615, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInput) when calling the SimulatePrincipalPolicy operation: '123456789012' is not a valid as a Resource Owner.
```

I've tried with a valid account id and it's the same problem. I also tried specifying the account id with hyphens, like so `1234-5678-9012`, and as an arn like so `arn:aws:iam::123456789012:root` but still get the same error.

Documentation says:

```
       --resource-owner (string)
          An AWS account ID that specifies the owner of any simulated resource
          that  does not identify its owner in the resource ARN, such as an S3
          bucket or object. If ResourceOwner is specified, it is also used  as
          the  account owner of any ResourcePolicy included in the simulation.
          If the ResourceOwner parameter is not specified, then the  owner  of
          the resources and the resource policy defaults to the account of the
          identity provided in CallerArn . This parameter is required only  if
          you  specify  a  resource-based  policy  and  account  that owns the
          resource is different from the account that owns the simulated call-
          ing user CallerArn .
```

Pretty sure that's what I'm providing.

I see the same issue with the aws cli:

```
aws iam simulate-principal-policy --policy-source-arn arn:aws:iam::<actualaccountid>:role/moo --action-names s3:GetObject --resource-owner 123456789012

An error occurred (InvalidInput) when calling the SimulatePrincipalPolicy operation: '123456789012' is not a valid as a Resource Owner.
```

boto3==1.5.4
botocore==1.8.18
awscli==1.14.14

Thanks in advance for any help.

**Comment by joguSD** [comment]
This error is actually coming back from the service. So unfortunately there's not a lot we can do on the cli/boto side of things. It might be worth asking on [stackoverflow](
https://stackoverflow.com/) or opening a support ticket [here](https://console.aws.amazon.com/support/home#/).

I'm not an expert in the policy simulation API but, I think is actually related to the fact that there's no resource based policies being tested in the simulation. Since you're providing a role this is actually an identity based policy. More info [here](http://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_identity-vs-resource.html).

**Comment by Bashton-MattBuckland** [comment]
OK, thanks joguSD. Will try support. I get the same problem with a resource-based policy simulation too. Maybe I'm doing it wrong.
