### ISSUE TITLE
Implement Amazon Transcribe

### ISSUE THREAD

**Issue by vedant** [boto/botocore#1355]
@awstools Amazon Transcribe is available and the API is specified in [this developer's guide](https://docs.aws.amazon.com/transcribe/latest/dg/transcribe-dg.pdf). Would it be possible to implement a transcribe service [here](https://github.com/boto/botocore/tree/develop/botocore/data/)?

**Comment by vedant** [comment]
This is addressed in [PR 1356](https://github.com/boto/botocore/pull/1356)

**Comment by ripundeep** [comment]
Is there any way through which we can transcribe a live audio stream using boto3/botocore?
