### ISSUE TITLE
boto3.client.upload_fileobj throws http read timeout exception and also upload successfully

### ISSUE THREAD

**Issue by casper666** [boto/botocore#1357]
for side in ["NJ", "NY"]:
        # initialize a client object
        client = BCSClient(local_path, side)
        # check if bucket is ready and then try uploading
        try:
            client.checkBucket()
        except NoSuchBucketException as e:
            logger.info(e.message + ", trying to create a new one")
            client.createBucket()
        except:
            logger.error("Unexpected Error when raising NoSuchBucketException: {}".format(sys.exc_info()[0]))
        finally:
            # upload the file
            client.uploadFile()

I got the below logging info for file xxxxx: (progress is printed in callback of upload_fileobj):

Uploading file xxxx .Total sent size: 262144 / 2784334
Uploading file xxxx .Total sent size: 524288 / 2784334
Uploading file xxxx .Total sent size: 786432 / 2784334
Uploading file xxxx .Total sent size: 1048576 / 2784334
Uploading file xxxx .Total sent size: 1310720 / 2784334
Uploading file xxxx .Total sent size: 1572864 / 2784334
Uploading file xxxx .Total sent size: 1835008 / 2784334
Uploading file xxxx .Total sent size: 2097152 / 2784334
Uploading file xxxx .Total sent size: 2359296 / 2784334
Uploading file xxxx .Total sent size: 2621440 / 2784334
Uploading file xxxx .Total sent size: 2784334 / 2784334
HTTP Read Timeout Exception for xxxx: HTTPConnectionPool(host='s3.dmz.rrdc.bcs.bloomberg.com', port=80): Read timed out. (read timeout=60)

**Comment by kyleknap** [comment]
Could you potentially provide debug logs when running this? That should give us a little more detail on what may be going on. You can do so be adding the line `boto3.set_stream_logger('')` right before you make the call to `upload_fileobj`.

**Comment by casper666** [comment]
Hi, I realized that the issue might be some network issue internally.

**Comment by avi-mastov** [comment]
@casper666 do you remember what was the cause and how you solved it? I'm having the same issue now (upload successful but raising read timeout exception.
