### ISSUE TITLE
Kinesis / GetShardIterator: input declaration has invalid shape for Timestamp field

### ISSUE THREAD

**Issue by melo** [boto/botocore#1362]
Hi,

According to [GetShardIterator API documentation](https://docs.aws.amazon.com/kinesis/latest/APIReference//API_GetShardIterator.html#API_GetShardIterator_RequestSyntax), the Timestamp member of the request is a `number`.

Yet, in the file [botocore/data/kinesis/2013-12-02/service-2.json](https://github.com/boto/botocore/blob/master/botocore/data/kinesis/2013-12-02/service-2.json#L664), the `Timestamp` member of the `GetShardIteratorInput` type is declared as a `Timestamp`, and according to [parse_datetime()](botocore/utils.py#L336), this would accept multiple formats, some of them as strings.

Based on actual calls to the API, I believe the documentation is correct, and this is not a timestamp but an Epoch, an Integer. I updated [Paws](https://metacpan.org/release/Paws) (an AWS SDK for Perl generated from botocore) to use an Integer for this field ([analysis](https://github.com/pplu/aws-sdk-perl/issues/217)) and the API works after the update to a number. I tried all formats of date as strings (including the ones mentioned on `parse_datetime` above) without success.

The API currently only accepts an Integer, with an Epoch.

Thank you,

**Comment by kyleknap** [comment]
Interesting. I tried it with boto3 and it works fine:
```python
In [7]: kinesis.get_shard_iterator(
   ...:     StreamName='name',
   ...:     ShardId='id',
   ...:     ShardIteratorType='AT_TIMESTAMP',
   ...:     Timestamp=datetime.datetime(2015, 1, 1)
   ...: )
```
It works though because we serialize it to an integer. However, I do not think we can that we can change the type of the member as it will break the SDK interface. I think the best we could potentially do is add a `"timestampFormat"` metadata value to the member to label it as epoch. Would that help you with your generator?

**Comment by melo** [comment]
Paws is not my generator, I was just the user of Paws that traced this down.

Having said that, assuming that Timestamp can be serialized into multiple ways and in this case it the API requires it to be serialized as an epoch, I would say that the specification should have some metadata stating that detail, and your suggestion looks very good to me.

With that in the spec file, I can then go back to the Paws project and help them make the changes to the generator to fix this.

I believe adding the metadata is of great benefit for all concern, downstream users of this project, as it declares something that was only implicit in the boto3 implementation, that timestamps would be converted to epochs.

Thank you,

**Comment by pplu** [comment]
Hi,

  Paws author here. The proposed metadata to know how to handle timestamps would be great.

**Comment by JordonPhillips** [comment]
We're working on getting that updated, in the mean time you can safely assume that rest-json protocol defaults to unix timestamps. Since this doesn't impact botocore, I'm closing out this issue.
