### ISSUE TITLE
Need a specific exception for when images are not compatible with the Rekognition API

### ISSUE THREAD

**Issue by BTruer** [boto/botocore#1366]
Let's say we have an image sitting on a bucket in S3. The image is very small (6.9 KB) which not a min of 80 pixels (https://docs.aws.amazon.com/rekognition/latest/dg/limits.html). I ran the example as shown here (https://docs.aws.amazon.com/rekognition/latest/dg/images-s3.html) 

```python
import boto3

if __name__ == "__main__":
    fileName='smallimg.jpg'
    bucket='company-bucket'

    client=boto3.client('rekognition','us-west-2')
    response = client.detect_labels(Image={'S3Object':{'Bucket':bucket,'Name':fileName}},MaxLabels=10)
    print('Detected labels for ' + fileName)
    for label in response['Labels']:
        print (label['Name'] + ' : ' + str(label['Confidence']))
```

The error that was returned was `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the DetectLabels operation: Request has Invalid Parameters`

I spent a lot of time playing around with how I was writing the parameters not realizing that it was a problem with the image size. Because the error response said it was a problem with the parameters when infact the image could not be processed. Please give a more specific response identifying it is actually a matter of the image.

**Comment by dstufft** [comment]
Unfortunately we do not have any control over the errors given to us by the services. Your best bet is to ask for this change over on the [Rekognition forums](https://forums.aws.amazon.com/forum.jspa?forumID=234) so that the service team can see it and respond.

**Comment by iampotential** [comment]
Yup nothing has happened with this. Still getting `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RecognizeCelebrities operation: Request has invalid parameters`
couldnt be anymore vague especially when you have an entire package called errorfactory you'd this there would be a bit more information in there
