### ISSUE TITLE
Ability to set ResponseMetadata in stubber's add_client_error method

### ISSUE THREAD

**Issue by StephenWithPH** [boto/botocore#1375]
It would be nice to be able to set ResponseMetadata (specifically, `RequestId`) when stubbing.

In my case, I wanted to log the `RequestId` in the case of failure. Code to do so is fairly easy, but it is **not** easily testable.

The current stubber allows users to pass service_error_meta (dict) (Additional keys to be added to the service Error). When passing `error_info = {'RequestId': '8675309'}`, this allows a response like:
```
{
     "ResponseMetadata":
          {
               "HTTPStatusCode": 400
          },
     "Error":
          {
               "Message": "Sadness",
               "Code": "Sadness",
               "RequestId": "8675309"
          }
}
```

The actual response from the real service would be something like
```
{
     "ResponseMetadata":
          {
               "HTTPStatusCode": 400,
               "RequestId": "8675309",
               ...
          },
          ...
}
```

Extending add_client_error to also take a dictionary of items to add to `ResponseMetadata` would enable this. The pattern for `Error` (https://github.com/boto/botocore/blob/develop/botocore/stub.py#L296-L297) could be followed.

Note... this is loosely similar to https://github.com/boto/boto3/issues/1143

Please let me know if this looks reasonable; I should be able to get a PR in fairly soon.

**Comment by joguSD** [comment]
I think this sounds reasonable, marking as a feature request.

**Comment by StephenWithPH** [comment]
@joguSD  do you need me to do anything else to get https://github.com/boto/botocore/pull/1376 in line for review?

**Comment by StephenWithPH** [comment]
Closed in https://github.com/boto/botocore/pull/1376
