### ISSUE TITLE
Support encryption-at-rest for credentials

### ISSUE THREAD

**Issue by withnale** [boto/botocore#1382]
I'd like to propose adding functionality to support GPG encryption of credentials.

My initial thoughts are to implement this one of two ways:

1. If a `credentials.gpg` file exists use this in preference to the normal unencrypted `credentials` file.
2. Use a similar approach to that used in https://github.com/voxpupuli/hiera-eyaml which allows for the encrypted keys to be left in the credentials file - which improves readability whilst allowing keys to be kept securely.

In both approaches I would expect that most people would choose to use this in conjunction with `gpg-agent` which provides GPG credentials caching in a secure manner.

I would be happy to have a stab at the PR if the maintainers see this functionality as valuable.

**Comment by kyleknap** [comment]
I can see this as valuable. The only hesitation that I have is pulling it into the core of the SDK. Specifically, I am concerned with the dependencies that we may have to pull in to support this. It looks like most python libraries require GnuPG to be installed on the machine, which would break users that do not have it installed. It is probably safer if this functionality existed in a package separate to `botocore`. And in this package, I could see the package either:

1) Hook into the credential resolver of the session and add a new credential resolver to check for the GPG files.
2) Have the package include an executable that can be called out using the `credential_process` config variable. Here is [documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes) for it, but note that even though this is from the CLI, it applies to `boto3` as well.

Let us know what you think. Going to keep the issue open for now as a feature request.

**Comment by withnale** [comment]
Hi. Please close this ticket down. I've had a look at boto-core in the past and nothing was there, and had a quick scan before writing this ticket. 

I'm not sure when `credential_process` appeared but I missed it. Easy enough to achieve what is necessary with that, rather than dragging in other dependencies.
