### ISSUE TITLE
ability to override METADATA_SECURITY_CREDENTIALS_URL

### ISSUE THREAD

**Issue by sar009** [boto/botocore#1384]
we have a small use case wherein we need to call aws service from another instance. In our java project we use java system properties as `-Dcom.amazonaws.sdk.ec2MetadataServiceEndpointOverride=http://custom.endpoint` [(here)](https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/SDKGlobalConfiguration.java#L68) but we are not able to do such override in boto3 as `botocore.credentials` do not facilitate it.
```
instance_metadata_provider = InstanceMetadataProvider(
        iam_role_fetcher=InstanceMetadataFetcher(
            timeout=metadata_timeout,
            num_attempts=num_attempts)
    )
```

while `InstanceMetadataFetcher` has the ability to take in custom url, `botocore.credentials` is not facilitating it.

**Comment by jamesls** [comment]
Marking as a feature request.  Can you tell us more about your use case?  What are you overriding the instance metadata url to?

**Comment by sar009** [comment]
this was to run some unit test on the local server. we didn't want to share a key across the whole team so we created a server on a private network from where the user can get instance role of a dummy test server.

**Comment by sar009** [comment]
@jamesls any chance this be picked
