### ISSUE TITLE
Credential Provider order of precedence

### ISSUE THREAD

**Issue by ryansmith940** [boto/botocore#1388]
I assumed a role and placed the temporary credentials into my `~/.aws/credentials` file.  I was expecting my boto call to work without prompt for an mfa code, but found I was prompted.  Looking at `credentials.py` I found the AssumeRoleProvider is called before the SharedCredentialProvider, explaining why I was prompted.  If I move the AssumeRoleProvider below SharedCredentialProvider, it works as expected.  Why does AssumeRoleProvider have such a high precedence?  Shouldn't a prompt for an mfa code be the last thing that is attempted?

**Comment by jamesls** [comment]
Having both assume role configuration as well as `aws_access_key/secret_key` credentials in a single profile is undefined behavior.  The intent is for you to only have one or the other.

Unfortunately, changing the precedence order now would be a backwards incompatible change so we aren't able to change it.

**Comment by ryansmith940** [comment]
Yes, that makes sense.  I think I will just put my temporary credentials into a different section in the credentials file.  Something like `<profile-name>-temp`. Thanks.
