### ISSUE TITLE
Allow tagging in lambda update_function_configuration?

### ISSUE THREAD

**Issue by scotwk** [boto/botocore#1397]
In boto3's lambda client, [create_function](http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.create_function) accepts `Tags` but [update_function_configuration](http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.update_function_configuration) does not accept that keyword.  Any reason for that?

**Comment by stealthycoin** [comment]
This is an API question so that should be directed to the service team. You can contact them on either [AWS Support](https://console.aws.amazon.com/support/home#/) or [Lambda Forums](https://forums.aws.amazon.com/forum.jspa?forumID=186).
