### ISSUE TITLE
Misleading FIFO documentation

### ISSUE THREAD

**Issue by anderson-dan-w** [boto/botocore#1412]
For `MessageDeduplicationId`, `MessageGroupId` and `ReceiveRequestAttemptId`, the documentation says "The length of `*` is 128 characters" while it would be more accurate (and more clear to new users) to say "The maximum length of `*` is 128 characters".

I was about to submit a pull-request, but saw that this was in a `service-2.json` file (specifically `botocore/data/sqs/2012-11-05/service-2.json`), which you prefer to have opened issues for. But, if you wanted, the branch is [here](https://github.com/anderson-dan-w/botocore/commit/9b5051b59e70a415f37b9a4a10dbe9b6bba0b4b6).

**Comment by swetashre** [comment]
@anderson-dan-w - This issue has been fixed. You can verify in this documentation https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html . Now it is updated to he maximum length of ReceiveRequestAttemptId is 128 characters.

**Comment by anderson-dan-w** [comment]
Great, thanks! Consider this resolved

**Comment by swetashre** [comment]
I am closing this issue as this has been fixed.
