### ISSUE TITLE
organizations list_children and list_organizations_for_parent return empty lists when trying to get OUs

### ISSUE THREAD

**Issue by robertsj-vmware** [boto/botocore#1426]
When trying to list ORGANIZATIONAL_UNIT children under our AWS account we get an empty list returned. Boto3 throws an exception, and the awscli is returning the organizations without any issues. Attached is my test code and the output from running it. I have opened https://github.com/boto/boto3/issues/1515 for the boto3 exception.

[csposs_4242_boto.err.txt](https://github.com/boto/botocore/files/1885030/csposs_4242_boto.err.txt)
[csposs_4242_boto.out.txt](https://github.com/boto/botocore/files/1885031/csposs_4242_boto.out.txt)
[csposs_4242_boto.py.txt](https://github.com/boto/botocore/files/1885032/csposs_4242_boto.py.txt)

**Comment by stealthycoin** [comment]
Is this happening consistently? I can't replicate this using the code you gave and setting up my own organization hierarchy. My first suggestion would be to update everything to the newest `boto3` and `botocore` and see if that fixes it. There shouldn't be any differences along that code path for boto3 and awscli. Are there any other details you can provide that might help reproducing?

**Comment by robertsj-vmware** [comment]
This happens for several people on our team. We have >600 accounts, in 4 ous, under our root level account. I am currently using botocore 10.0.3, and the behavior persists.

14:01:10-robertsj~/git/csp-oss/tools (master)$ python3
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import botocore
>>> botocore.__version__
'1.10.3'

**Comment by robertsj-vmware** [comment]
Latest attempt: botocore 1.10.7

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import botocore
>>> botocore.__version__
'1.10.7'
>>> s = botocore.session.Session(profile='vmw_payer')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'botocore' has no attribute 'session'
>>> exit()
09:16:09-robertsj~$ python3
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import botocore
>>> import botocore.session
>>> s = botocore.session.Session(profile='vmw_payer')
>>> orgs = s.create_client('organizations')
>>> orgs.list_children(ParentId='r-kw69', ChildType='ORGANIZATIONAL_UNIT')
{'Children': [], 'NextToken': 'CAIStAIIARKNAggDEogCAAFbqkW9sNkEdu0QMjI1Db6UP1cqJaa3EUYzzM6xk1f1eyJAbiI6IlBhZ2luYXRpb25Db250aW51YXRpb25EVE8iLCJuZXh0S2V5IjoiQUFBQUFBQUFCNGQxQVFFQjVGR2lud0NUUWtHT2JHMDF3cGdnRDJYL3ZMMkF6VVo4cXlTK1Jacm5RZlZsY0dZN1FYd3dNamt4TlRVeU1ERXdOelo4UVZGSWExVmhTMlpCU2s1RFVWazFjMkpVV0VOdFEwRlFXbVl0T0haWlJFNVNibmx5U2t3MVJtMTFaRUk1VVRzPSIsInByZXZpb3VzUmVxdWVzdFRpbWUiOjE1MjQ1ODMwODkyNDB9GiAunj7pHb/Kl6zFAYNX9v3r7dpE/LfxZh/PrPHgJp6Bjg==', 'ResponseMetadata': {'RequestId': 'b20a1765-47d2-11e8-9131-af339c5144a6', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'b20a1765-47d2-11e8-9131-af339c5144a6', 'content-type': 'application/x-amz-json-1.1', 'content-length': '450', 'date': 'Tue, 24 Apr 2018 15:18:08 GMT'}, 'RetryAttempts': 0}}
>>> orgs.list_organizational_units_for_parent(ParentId='r-kw69')
{'OrganizationalUnits': [], 'NextToken': 'CAIStAIIARKNAggDEogCAAFbqkW9sNkEdu0QMjI1Db6UP1cqJaa3EUYzzM6xk1f1eyJAbiI6IlBhZ2luYXRpb25Db250aW51YXRpb25EVE8iLCJuZXh0S2V5IjoiQUFBQUFBQUFCNGQxQVFFQjVGR2lud0NUUWtHT2JHMDF3cGdnRDJYL3ZMMkF6VVo4cXlTK1Jacm5RZlZsY0dZN1FYd3dNamt4TlRVeU1ERXdOelo4UVZGSWExVmhTMlpCU2s1RFVWazFjMkpVV0VOdFEwRlFXbVl0T0haWlJFNVNibmx5U2t3MVJtMTFaRUk1VVRzPSIsInByZXZpb3VzUmVxdWVzdFRpbWUiOjE1MjQ1ODMxMTY0NTN9GiBpJ/gwYG6suzr5UnAUeeFRRzpUIGDUDk1WaYdndjPW9A==', 'ResponseMetadata': {'RequestId': 'c245f9b7-47d2-11e8-9131-af339c5144a6', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'c245f9b7-47d2-11e8-9131-af339c5144a6', 'content-type': 'application/x-amz-json-1.1', 'content-length': '461', 'date': 'Tue, 24 Apr 2018 15:18:36 GMT'}, 'RetryAttempts': 0}}
>>> exit()

As you can see 'Children' and 'OrganizationalUnits' are still empty.

**Comment by stealthycoin** [comment]
I would suggest contacting 
[AWS Support](https://console.aws.amazon.com/support/home#/) since this appears to be service related. If botocore is getting back an empty list then there isn't anything we can do as a client tool.
