### ISSUE TITLE
Malformed anchor in docstring: concurrent-executions

### ISSUE THREAD

**Issue by kislyuk** [boto/botocore#1428]
The import in https://github.com/boto/botocore/commit/01fc2668ee9eba2971bcee1592d98701f3e45af6 introduced a malformed link (e.g. https://github.com/boto/botocore/commit/01fc2668ee9eba2971bcee1592d98701f3e45af6#diff-bb2c907d38c5fe5f9c4aaa0677a21b60L149 - search for `concurrent-executions`). The link should point to https://docs.aws.amazon.com/lambda/latest/dg/concurrent-executions.html.

**Comment by kislyuk** [comment]
(Another anchor in that commit needs fixing: `lambda-traffic-shifting-using-aliases`.)

**Comment by JordonPhillips** [comment]
Thanks for reporting! These come from upstream, I'll let the service team know so they can fix the issue.

**Comment by JordonPhillips** [comment]
I've forwarded this on, closing out the issue
