### ISSUE TITLE
Clarification on RefreshableCredentials parameter: method

### ISSUE THREAD

**Issue by jorwoods** [boto/botocore#1439]
The class RefreshableCredentials accepts an argument "method" which tells it how to refresh. Knowing what to put into this argument is entirely unclear.

**Comment by JordonPhillips** [comment]
`method` is actually a string identifier, primarily used for logging. In general that's considered internal. We'd like to open those up (as we're not likely to break them anyway), and when we do we'll make sure to give detailed documentation.
