### ISSUE TITLE
Upstream documentation issue: AutoScalingGroupNamesType as used in DescribeAutoScalingGroups API call

### ISSUE THREAD

**Issue by ps-jay** [boto/botocore#1444]
I understand that `service-2.json` files are auto-generated, so I haven't opened a PR here.

The issue is that a `DescribeAutoScalingGroups` call with more than 50 group names provided in the `AutoScalingGroupNames` list results in an exception:

```botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeAutoScalingGroups operation: The number of group names that may be passed in is limited to 50```

Ideally, this should be documented as a restriction.

**Comment by JordonPhillips** [comment]
Thanks for the feedback! Looks like it isn't in the service api docs either. I've forwarded this on to the service team.
