### ISSUE TITLE
botocore leak when using get + head object

### ISSUE THREAD

**Issue by thehesiod** [boto/botocore#1464]
with the following modules installed:
```
bash-4.2# /valgrind/bin/python3 -m pip freeze
APScheduler==3.3.1
asynctest==0.12.0
aws-xray-sdk==1.0
botocore==1.10.21
cachetools==2.1.0
certifi==2018.4.16
chardet==3.0.4
cycler==0.10.0
datadog==0.20.0
decorator==4.3.0
dill==0.2.7.1
docutils==0.14
editdistance==0.3.1
future==0.16.0
gapic-google-cloud-pubsub-v1==0.15.4
google-api-python-client==1.6.7
google-auth==1.4.1
google-auth-httplib2==0.0.3
google-cloud-core==0.25.0
google-cloud-pubsub==0.26.0
google-gax==0.15.16
googleapis-common-protos==1.5.3
graphviz==0.8.3
grpc-google-iam-v1==0.11.4
grpcio==1.12.0
httplib2==0.11.3
idna==2.6
iso8601==0.1.12
jmespath==0.9.3
jsonpickle==0.9.6
kiwisolver==1.0.1
matplotlib==2.2.2
memory-profiler==0.52.0
nameparser==0.5.6
numpy==1.14.3
oauth2client==4.1.2
objgraph==3.4.0
ply==3.8
proto-google-cloud-pubsub-v1==0.15.4
protobuf==3.5.2.post1
psutil==5.4.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyGithub==1.39
PyJWT==1.6.1
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.4
requests==2.18.4
rsa==3.4.2
setproctitle==1.1.10
simplejson==3.15.0
six==1.11.0
tzlocal==1.5.1
uritemplate==3.0.0
urllib3==1.22
wrapt==1.10.11
```

and the following test case: https://gist.github.com/thehesiod/dc04230a5cdac70f25905d3a1cad71ce

and run with memory_profiler like so in python 3.6.5:
`PYTHONMALLOC=malloc python3 /valgrind/bin/mprof run --interval=1 /tmp/test.py -test botocore_test`

yields the following graph:
![boto_head_object](https://user-images.githubusercontent.com/4001789/40210894-5fda02e2-59fc-11e8-8f2a-2482c88e19c9.png)

when run with:
`PYTHONMALLOC=mallocpython3 /valgrind/bin/mprof run --interval=1 /tmp/test.py -test aiohttp_test -method get_object `

you get a graph like so:
![boto_get_object](https://user-images.githubusercontent.com/4001789/40210900-66797b00-59fc-11e8-8e80-7beff3caae80.png)

NOTE: it seems critical do do the `get_object` before the `head_object` to trigger the leak

**Comment by thehesiod** [comment]
hmm, so in our application the `get_object` cause is still leaking, albeit much slower.  Not sure the difference between our app and this this case that's causing it to leak.

**Comment by methane** [comment]
When you enabled Python warning, you may see this RecourceWarning:

```
botoleak.py:19: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.11.39.78', 41054), raddr=('52.219.40.141', 443)>
  raise
Object allocated at (most recent call last):
  File "botoleak.py", lineno 55
    main()
  File "botoleak.py", lineno 46
    test(s3_client)
  File "botoleak.py", lineno 16
    method(Bucket='archpi.dabase.com', Key='doesnotexist')
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/client.py", lineno 314
    return self._make_api_call(operation_name, kwargs)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/client.py", lineno 599
    operation_model, request_dict)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/endpoint.py", lineno 148
    return self._send_request(request_dict, operation_model)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/endpoint.py", lineno 175
    request, operation_model, attempts)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/endpoint.py", lineno 222
    proxies=self.proxies, timeout=self.timeout)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/sessions.py", lineno 573
    r = adapter.send(request, **kwargs)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/adapters.py", lineno 370
    timeout=timeout
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", lineno 544
    body=body, headers=headers)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", lineno 341
    self._validate_conn(conn)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", lineno 761
    conn.connect()
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", lineno 238
    ssl_version=resolved_ssl_version)
  File "/home/inada-n/v/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/util/ssl_.py", lineno 279
    return context.wrap_socket(sock, server_hostname=server_hostname)
```

I don't know much about botocore internal, but I think `get_object` read HTTP body but `head_object` doesn't.

https://urllib3.readthedocs.io/en/1.4/pools.html#urllib3.connectionpool.HTTPConnectionPool.urlopen

You may be able to use `preload_content=True`, or:

> You will need to call r.release_conn() on the response r to return the connection back into the pool.

**Comment by thehesiod** [comment]
ya apparently this is due to the terrible decision made in https://bugs.python.org/issue27535 for 3.6.x.  I'm trying out the fix now to see if it fixes it.  However given there's now way to officially close the socket in botocore I think the resource warning should be fixed in botocore.

**Comment by thehesiod** [comment]
I've verified that the leak is caused by that bug and the terrible decision not to roll it into 3.6.  I'm trying really hard for them to roll the fix into ALL python versions affected. Closing this, hopefully this proves useful to other.

**Comment by thehesiod** [comment]
actually going to re-open, as the warning should be fixed in botocore.

**Comment by methane** [comment]
FYI, Python's `-Wd` option will be helpful  to find such warnings.
These warnings are hidden by default for end users, not developers.

**Comment by phntom** [comment]
this is a bug in all types of requests that go though botocore, here's a quick workaround for you:
i'll make a pull request shortly

```
def _release_botocore_http_connection(http_response=None, **kwargs):
    if http_response is not None and http_response.raw and http_response.status_code < 300:
        # this corresponds to code in botocore/client.py _make_api_call where status_code >= 300 is error handled
        http_response.raw.release_conn()

def fix_botocore_http_release(client):
    if hasattr(client.meta, 'client'):
        target = client.meta.client
    else:
        target = client
    target.meta.events.register('after-call', _release_botocore_http_connection)
    return client
```

**Comment by joguSD** [comment]
We have un-vendored requests/urllib3 and are now using urllib3 directly as of `botocore` v1.11.0.
See #1248 for more details on the leak and #1495 for the PR to use upstream urllib3.
