### ISSUE TITLE
By default delay_exponential should not be random

### ISSUE THREAD

**Issue by outcoldman** [boto/botocore#1471]
The default behavior for retries includes a [random base](https://github.com/boto/botocore/blob/c632931a6cc5eab4113c976d430bcb9c059f829f/botocore/retryhandler.py#L39), default retry behavior for all services is to use `rand` base.

### Issue 1

growth_factor makes no sense in the case when `rand` is used. Say at first you get value `base=0.7` and wait for `0.7` seconds, if next time you get `0.01` - you will wait for `0.02`. 

### Issue 2

The base in the range of `[0, 1)` can be very high. In case of lambda functions, when you pay for milliseconds, sleeping for example for 700 ms does not make any sense, and it is a lot of machine time, so I just don't see any reason for a service to wait so long before the first retry. 

### Issue 3

There is should be a good reason to have a `random` value in the production code. Choosing the retry intervals does not look like one of them. That can lead to unpredicted behaviors and not reproducible issues. 

## Proposal

1.  Change the default base in [_retry.json](https://github.com/boto/botocore/blob/develop/botocore/data/_retry.json#L88) to the integer value of `0.01`, almost instant first retry should not be an issue.
2. Allow overriding default base using `botocore.Config`, similar to max_attempts in [_merge_client_retry_config](https://github.com/boto/botocore/blob/b54ceeaca5d4c1316fae0a0496422572d1f6aba5/botocore/translate.py#L41)

If contributors agree with that, I will be happy to make a change.

## Workaround

Currently, the only workaround I have found is to patch a client in a way like

```
firehose_client = boto3.client("firehose")
retry_handler = firehose_client.meta.events._unique_id_handlers["retry-config-firehose"]["handler"]
retry_handler._action.keywords["base"] = 0.05
```

**Comment by av239** [comment]
Might be worth reading [https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/](url)

**Comment by outcoldman** [comment]
@av239 this is a good read, but I am not sure if this article applies here.
The blog post has a specific use case, trying to solve OCC and with many writers updating the same record, and most important making an assumption, that these writers started at the same time. I see the reason for randomness in that case.

In the case of this bug, we are talking about the service unavailability. We don't know anything about other writers or clients, in this case, we need to retry the call.
Just for reference, in my case, when Lambda is working as a backend for API Gateway - I already have randomness from the callers, they aren't going to use my API at the same time. My writes go to the Firehose, where I do not need to solve any issues with OCC. 

But if we want to keep randomness in retry logic, let's at least implement it right. Taking at least the first example from the article and choosing the time to sleep as

```
time_to_sleep = random(0,  base * (growth_factor ** (attempts - 1)))
```

And keeping the base **always** const, that will be a good start.

**Comment by JordonPhillips** [comment]
The way we've implemented backoff certainly does have a decent amount of variance, but it's about as good as we can do in most cases with the information we have. I do agree that we can do better in some cases, and we should better expose configuration. There's an existing feature request for that at #1205

**Comment by outcoldman** [comment]
@JordonPhillips allowing to configure retry logic will be indeed a good solution. 

I still suggest to revisit default implementation of retry logic and especially defaults.

I have subscribed to the other ticket, feel free to close this one if you wish.

**Comment by tometzky** [comment]
Sorry - I think I was wrong. The base is randomly selected with every delay, so the probability of selecting 0.1 four times is only 1/10000. And after changing max_attempts to like 9 the probability of giving up in less than a minute is about 1/10000 too, and less than 30s is about 1/100,000,000. I can accept this. Sorry for the noise.

**Comment by swetashre** [comment]
Closing as this related to feature request https://github.com/boto/botocore/issues/1205
