### ISSUE TITLE
route53 client list_resource_record_sets with StartRecordType does not filter out the appropriate records

### ISSUE THREAD

**Issue by samuel-72** [boto/botocore#1480]
If the command is run such as given below:

`r53_client.list_resource_record_sets(HostedZoneId = '<ZONE ID>', StartRecordName='<NAME>', StartRecordType ='A')`
Then, instead of filtering out only the record sets of TYPE "A", the API returns all the record sets.

Python 2.7.12 running on EC2 Linux with Botocore 1.10.6

A workaround for this would be to do this:

`for i in rs['ResourceRecordSets']:
   if i['Type'] not in ['NS', 'SOA']:
     <Do Stuff>
`

However, it would be great if the API supports this filtering logic.

**Comment by kyleknap** [comment]
I would recommend reaching out to AWS Support or opening an issue in the [AWS Developer forums](https://forums.aws.amazon.com/forum.jspa?forumID=87) to request this feature in Route 53. Boto3/Botocore follows a strict 1:1 mapping of parameters to API so Route 53 needs to expose this parameter in their API for Boto3/Botocore to pick this feature up. Furthermore, all of the CLI and SDK's will pick this up automatically if Route 53 exposes this parameter.
