### ISSUE TITLE
[Proposal] Use urllib3 directly instead of requests

### ISSUE THREAD

**Issue by joguSD** [boto/botocore#1486]
Botocore currently vendors a fairly dated version of `requests`. This particular version of `requests` also vendors the `urllib3` library. We originally vendored `requests` to give us more control over the specific version that was being used as we need to make changes to some of the behavior provided by both `requests` (redirect behavior, etc.) and `urllib3` (HTTP 100-continue support). By dropping `requests` and using `urllib3` directly we gain more control over our HTTP client behavior and simplify our dependencies.

Let's use this issue as an aggregate issue to contain discussion around unvendoring `requests` and switching to using `urllib3` directly.

Implementation: https://github.com/boto/botocore/pull/1495

Related Issues:
https://github.com/aws/aws-cli/issues/2994
https://github.com/boto/botocore/issues/1258
https://github.com/boto/botocore/issues/1248
https://github.com/boto/botocore/issues/756
https://github.com/boto/botocore/issues/1370
https://github.com/boto/botocore/pull/1466
https://github.com/boto/botocore/pull/1300
https://github.com/boto/botocore/pull/1385
https://github.com/boto/botocore/issues/1464

**Comment by jamesls** [comment]
:+1:  yeah I've wanted to do this for a while.

**Comment by joguSD** [comment]
Implemented in #1495
