### ISSUE TITLE
Openssl library reports wrong version string

### ISSUE THREAD

**Issue by c7h** [boto/botocore#1488]
The python openssl library reports a wrong version information - therefore the `check_openssl_supports_tls_version_1_2` function ( https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L687-L697)  fails and generates a number of issues (https://github.com/lambci/docker-lambda/issues/99, https://github.com/boto/boto3/issues/1559)

I've tested it inside the docker container from image lambci/lambda

```
$ docker run --name lamba-testcontainer -it --entrypoint /bin/bash lambci/lambda:python3.6 

bash-4.2$ uname -a
Linux 91d3436e08f9 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2$ openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015

bash-4.2$ python
Python 3.6.1 (default, Apr 10 2018, 03:59:41) 
[GCC 4.9.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.0-fips 29 Mar 2010'
>>> ssl.OPENSSL_VERSION_INFO
(1, 0, 0, 0, 3)
```

**Comment by c7h** [comment]
I was able to 'hotfix' my problem by patching botocore in my lambda deployment package, but it's still a bug.

**Comment by joguSD** [comment]
We can't do anything to remedy this issue here. For what it's worth the Lambda team is aware of the issue and is looking into why python is reporting the incorrect version.
