### ISSUE TITLE
error factory exceptions for generic errors

### ISSUE THREAD

**Issue by kapilt** [boto/botocore#1489]
It would be nice to include generic exceptions, else users can only conditionally use exceptions classes on the basis of their existence without any clear guidance outside of trying each manually, and will accumulate as multiple error handling styles in a codebase.

```python
>>> import boto3
>>> client = boto3.client('s3')
>>> client.exceptions.AccessDenied
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kapilt/projects/cloud-custodian/lib/python3.6/site-packages/botocore/errorfactory.py", line 53, in __getattr__
    self, name, ', '.join(exception_cls_names)))
AttributeError: <botocore.errorfactory.S3Exceptions object at 0x108f2efd0> object has no attribute 'AccessDenied'. Valid exceptions are: BucketAlreadyExists, BucketAlreadyOwnedByYou, NoSuchBucket, NoSuchKey, NoSuchUpload, ObjectAlreadyInActiveTierError, ObjectNotInActiveTierError
```

**Comment by kapilt** [comment]
as an easy alternative, exposing error factory off the client and allowing users to create/retrieve exceptions by code would be nice.

**Comment by kapilt** [comment]
something like

```python
except client.exceptions.for_code('AccessDenied'):
    pass
```

which would do a from_code for class cache lookup before constructing & caching.

**Comment by JordonPhillips** [comment]
Yeah I think something like that would be great! The downfall of what we have now is it is based off of the service models, which don't always define every exception. A solution like `for_code` would be cool.

**Comment by rollokb** [comment]
Question, if AccessDenied is returned by S3, why isn't it part of the service definition?
