### ISSUE TITLE
Issue with S3 select 

### ISSUE THREAD

**Issue by lp060** [boto/botocore#1504]
Hi,

I get this error sometimes when s3 select API is called "An error occurred (TruncatedInput) when calling the SelectObjectContent operation: The GZIP deflator finished before all input data was read."

From my observation, when the load is more on ALB and the log is huge, we are facing this issue

**Comment by joguSD** [comment]
This error is coming back from the service when it's decompressing the gzip file you provided. This could either be an issue with the file being used or the service, either way this is not something we can help you with on the SDK side. I'd try reaching out on the [S3 service forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) or opening a [support ticket](https://console.aws.amazon.com/support/home#/) to get in contact with the service team.
