### ISSUE TITLE
Is profile prefix deprecated or required?

### ISSUE THREAD

**Issue by AlainODea** [boto/botocore#1511]
You folks say that the profile prefix is required:
https://github.com/boto/botocore/blob/d00ee27528efad227ad46d3db9fd2f80f802803f/botocore/configloader.py#L208-L222

AWS Java SDK says that profile prefix is deprecated:
https://github.com/aws/aws-sdk-java/blame/46c00efdd9240d2d20d734f806dcc71506af6e0f/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/BasicProfileConfigLoader.java#L96-L99

Between you, it is seemingly impossible to write ~/.aws/config in a compliant way.

**Comment by JordonPhillips** [comment]
No, that's just a bug in the Java SDK. Unfortunately not the kind of bug they can get rid of without breaking people who started depending on the new behavior. I believe they have a feature request to add a config loader that will behave like the CLI. In any case the V2 java SDK fixed the issue.

**Comment by AlainODea** [comment]
Thank you, @JordonPhilips.

The Java SDK folks said they’ll consider new wording to clear up the confusion:
https://github.com/aws/aws-sdk-java/issues/1707#issuecomment-409342847
