### ISSUE TITLE
UnseekableStreamError constructor triggers UnicodeDecodeError

### ISSUE THREAD

**Issue by goodhart** [boto/botocore#1513]
Hi boto team,

 I have experienced the following event while attempting to send a request using a 'bytearray' payload representing an image:
* A network event triggers request.reset_stream() - https://github.com/boto/botocore/blob/develop/botocore/endpoint.py#L183
* My input type is 'bytearray', and thus triggers an UnseekableStreamError
* The constructor of the UnseekableStreamError attempts to call string.format(), however since my payload is not a valid 'ascii' encoded string, this triggers a UnicodeDecodeException.

This issue is related to https://github.com/boto/botocore/issues/1359, in that the problem would be avoided if bytearray types are omitted from the seek(). 

I'm not a python expert, but I think the solution is simply to convert the following line https://github.com/boto/botocore/blob/develop/botocore/exceptions.py#L302:

from

fmt = ('Need to rewind the stream {stream_object}, but stream '
           'is not seekable.')

to

fmt = ('Need to rewind the stream {stream_object!a}, but stream '
           'is not seekable.')

**Comment by jamesls** [comment]
If I'm understanding correctly, this is a duplicate of #1359.  Was there something else that's separate from that issue, or can we track this work over in #1359?

**Comment by goodhart** [comment]
These issues are related in that #1359 exposes the issue more easily, but my actual bug report is for the exception that is thrown if {stream_object} has no valid ASCII representation.

**Comment by joguSD** [comment]
@goodhart This is indeed a separate issue to #1359, however the intention of the `UnseekableStreamError` was never to print the stream contents, so I'm not too concerned with fixing this issue. I think more important is skipping `bytearray` resets as they're not needed in the first place.
