### ISSUE TITLE
Empty strings are being created sometimes by iter_lines()

### ISSUE THREAD

**Issue by nlw0** [boto/botocore#1525]
Using `iter_lines` to retrieve the contents of a file, sometimes empty strings are produced in the middle of the generated strings. I suspect it could be related to something like a chunk being cut exactly before a newline character in this code:
https://github.com/boto/botocore/blob/c632931a6cc5eab4113c976d430bcb9c059f829f/botocore/vendored/requests/models.py#L705

I can try to check this function this later, perhaps, but maybe someone else can do it...

**Comment by nlw0** [comment]
Made a PR https://github.com/boto/botocore/pull/1527

**Comment by jamesls** [comment]
Looks like this got missed.  Thanks for looking into this, looking over the PR now.

**Comment by swetashre** [comment]
The linked PR https://github.com/boto/botocore/pull/1533 has already been merged. So closing this issue as it has been fixed with the merging of linked PR.
