### ISSUE TITLE
specify ENDPOINT_URL

### ISSUE THREAD

**Issue by hamroune** [boto/botocore#1526]
hi everyone I need to specify the endpoint url from configuration. is there any way to do that without change the source code of tier. my need is to use Ceph/Minio endpoint directly in /etc/boto.cfg rather than modify the source code (I have not right access)

**Comment by joguSD** [comment]
We have an issue against the AWS CLI for the same request. Let's track this over there:
https://github.com/aws/aws-cli/issues/1270
