### ISSUE TITLE
ImportError: cannot import name 'BotocoreHTTPSession'

### ISSUE THREAD

**Issue by elpaisa** [boto/botocore#1544]
I upgraded to 1.11.5 from 1.10.5, then i've got that error, it seems that Module was removed and i see nothing in the docs

**Comment by elpaisa** [comment]
Solved it by replacing it with: 
from botocore.httpsession import URLLib3Session

**Comment by joguSD** [comment]
@elpaisa Yep, for what it's worth the `URLLib3Session` is not an exact replacement for the old `BotocreHTTPSession` as their interfaces are quite different. The upgrade notes do mention that we're no longer using requests (which the old BotocoreHTTPSession inherited from). In general, if the class is not a part of our [public documentation](https://botocore.amazonaws.com/v1/documentation/api/latest/index.html), it's considered internal and shouldn't be used as we make no guarantees about their interfaces (or even presence).

**Comment by singhmaheshk** [comment]
> Solved it by replacing it with:
> from botocore.httpsession import URLLib3Session

Hi John,
Can you please help to understand what do you mean by replacing it. I am new to python and your help would highly appreciated 

I have added your line in import part. but dont get where to change to get the httpsession working. I have attached the screenshot. you can tell me what to replace with what that would be great.

![image](https://user-images.githubusercontent.com/25312933/65633662-39448a80-dfa2-11e9-82eb-6b6f4ecb11a9.png)

![image](https://user-images.githubusercontent.com/25312933/65633688-4c575a80-dfa2-11e9-987b-0fe30a51b95e.png)

**Comment by TomPengxiangWang** [comment]
Hi @singhmaheshk,
I have the same issues about that. Please follow my source codes. 
![image](https://user-images.githubusercontent.com/53742812/65655606-60a56100-e04f-11e9-8522-297d04bd89a5.png)
![image](https://user-images.githubusercontent.com/53742812/65655626-72870400-e04f-11e9-8e74-6b2c8149a9e8.png)
Both places need to be updated. Hopefully, it will help you to understand.

Thanks,
Tom

**Comment by singhmaheshk** [comment]
@TomPengxiangWang , Thank you so much I will try with your code as well. However I just fixed the issue by adding a layer in Lambda function as per below thread
https://github.com/aws-amplify/amplify-cli/issues/2353

![image](https://user-images.githubusercontent.com/25312933/65656364-374feb00-dfe5-11e9-9f82-fef0fc8cfaa1.png)

**Comment by TomPengxiangWang** [comment]
@singhmaheshk, that is awesome. Let me have a look.

**Comment by singhmaheshk** [comment]
@TomPengxiangWang , I tried to your suggestion as well but it did not worked. May be I need to use all of your import and other variables for crends and session. Would you mind sharing your code specially import part, post_data_to_es and post_to_es first few lines where we define the variables. 

import base64
import datetime
import json
import os
import time
import traceback
import urlparse

import botocore.auth
import botocore.awsrequest
import botocore.credentials
import botocore.endpoint
import botocore.session
import boto3.dynamodb.types

def post_data_to_es(payload, region, creds, host, path, method='POST', proto='https://'):
    '''Post data to ES endpoint with SigV4 signed http headers'''
    sigv4 = botocore.auth.SigV4Auth(creds, 'es', region)
    params = {'context': {}, 'method': method, 'url': proto + host + path, 'region': region, 'headers': {'Host': host}, 'body': payload}
    req = botocore.awsrequest.create_request_object(params)
    sigv4.add_auth(req)
    prep_req = req.prepare()
    http_session = botocore.endpoint.BotocoreHTTPSession()
    res = http_session.send(prep_req)
    if res.status_code >= 200 and res.status_code <= 299:
        return res._content
    else:
        raise ES_Exception(res.status_code, res._content)


def post_to_es(payload):
    '''Post data to ES cluster with exponential backoff'''

    # Get aws_region and credentials to post signed URL to ES
    es_region = ES_REGION or os.environ['AWS_REGION']
    session = botocore.session.Session({'region': es_region})
    creds = botocore.credentials.get_credentials(session)
    es_url = urlparse.urlparse(ES_ENDPOINT)
    es_endpoint = es_url.netloc or es_url.path  # Extract the domain name in ES_ENDPOINT

**Comment by TomPengxiangWang** [comment]
@singhmaheshk, Please follow https://github.com/TomPengxiangWang/Python/blob/master/dynamo-to-elastic.py.

**Comment by singhmaheshk** [comment]
@TomPengxiangWang , Thank you, after taking reference from your code, mine is also working now. Thank you very much. Now question is which solution is more robust yours one or adding a layer one?

**Comment by TomPengxiangWang** [comment]
@singhmaheshk, I am not sure about that. But I prefer to update the function.

**Comment by singhmaheshk** [comment]
@TomPengxiangWang , thanks. I will update my function.

**Comment by kyangy** [comment]
@TomPengxiangWang Using your code, have you experienced this?
<img width="1189" alt="Screen Shot 2019-12-04 at 4 50 01 PM" src="https://user-images.githubusercontent.com/9537888/70194082-280cae00-16b6-11ea-8fa7-6ddfe16c7112.png">

it seems like it doesnt like `event['Records]`

**Comment by kma3** [comment]
> @TomPengxiangWang @singhmaheshk Using the code, have you experienced this?
> <img alt="Screen Shot 2019-12-04 at 4 50 01 PM" width="1189" src="https://user-images.githubusercontent.com/9537888/70194082-280cae00-16b6-11ea-8fa7-6ddfe16c7112.png">
> 
> it seems like it doesnt like `event['Records']`

Running into the same issue. Any solution?

**Comment by singhmaheshk** [comment]
@kyangy , no I did not get that error and I was able to successfully run the code shared by @TomPengxiangWang  here. https://github.com/TomPengxiangWang/Python/blob/master/dynamo-to-elastic.py.

However at the end I used my old code and apply the AWS layer to solved the session issue  as per details mentioned below thread
aws-amplify/amplify-cli#2353

**Comment by mikeRChambers610** [comment]
I am confused why this issue is closed. This is clearly an open issue with only work arounds working for a few people with the issue. If I have the option to connect my appsync api to an Elastic Search domain, it should work out of the box. I am currently getting the below error. Any help would be greatly appreciated! Thanks in advance!

{
  "data": {
    "listPublicEventNews": null
  },
  "errors": [
    {
      "path": [
        "listEvents"
      ],
      "data": null,
      "errorType": "Elasticsearch:UserIllegalArgumentException",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 1,
          "sourceName": null
        }
      ],
      "message": "Elasticsearch responded with an error: Forbidden"
    }
  ]
}
