### ISSUE TITLE
AWSPreparedRequest.prepare_body broken for unicode parameters

### ISSUE THREAD

**Issue by kacholia** [boto/botocore#1557]
818d23505620f5091e5a4114020b66b5e6d7aa7b broke AWSPreparedRequest.prepare_body() when body is a dict with unicode values. This is common for calls to SES or other AWS services.

Previously the items in body would be utf-8 encoded in vendored/requests/models.py; with this change it directly calls urllib.urlencode before encoding unicode values.

Offending line: https://github.com/boto/botocore/commit/818d23505620f5091e5a4114020b66b5e6d7aa7b?diff=split#diff-cb00fc815f8f80ae15e7d0cecc74b395R438

**Comment by joguSD** [comment]
@kacholia This definitely seems like a possible regression.

1) What exact error are you getting? 
2) Could you provide a minimal sample to reproduce the issue?

**Comment by kacholia** [comment]
This is a major regression for anyone sending emails via SES and passing in
unicode strings as body/subject. Run prepare_body on a dict with unicode
values vs a str that's utf8 encoded.

>>> urllib.urlencode({'foo': u'Abbé'}, doseq=True)
'foo=Abb%3F'


>>> urllib.urlencode({'foo': u'Abbé'.encode('utf-8')}, doseq=True)

'foo=Abb%C3%A9'

**Comment by joguSD** [comment]
I wasn't able to reproduce this on Python 3.
On Python 2 I get the following:
```python
Python 2.7.13 (default, Jul 18 2017, 13:54:29) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from botocore.compat import urlencode
>>> urlencode({'foo': u'Abbé'}, doseq=True)
'foo=Abb%3F'
>>> urlencode({'foo': u'Abbé'.encode('utf8')}, doseq=True)
'foo=Abb%C3%A9'
>>> type(u'Abbé')
<type 'unicode'>
>>> isinstance(u'Abbé', str)
False
```

Looking into a fix.

**Comment by kacholia** [comment]
Yes python3 behavior is different. Keep in mind requests/compat.py defines
str as unicode for python2.

**Comment by joguSD** [comment]
@kacholia This should be fixed and going out in the release today.
