### ISSUE TITLE
Very slow (>60s) API calls with large params

### ISSUE THREAD

**Issue by medmunds** [boto/botocore#1561]
Problem: `boto3.client("ses").send_raw_email(..., RawMessage=b"message w/ 7MB attachment")` takes over a minute in AWS Lambda—and only the last few seconds are actually posting to the API endpoint. Most of the time is spent in `urlencode` while _repeatedly_ re-running `AWSPreparedRequest.prepare_body()`.

This likely affects any botocore client API using sigv4 auth, though it'll only be noticeable with larger params like SendRawEmail's RawMessage.

### Issue

I'm implementing an email forwarder using AWS SES and Lambda, and couldn't figure out why my Lambda function was timing out on messages with attachments. X-Ray showed the problem was in SendRawEmail:

<img width="1095" alt="aws x-ray ses sendrawemail" src="https://user-images.githubusercontent.com/639984/45712410-21d9f280-bb41-11e8-85fb-2dc7cc5d869c.png">

A little local profiling identified two problems:

1. Python's `urlencode` is not particularly fast. Addressing that seems out of scope for boto.

2. botocore's `AWSPreparedRequest.prepare_body()` is called *9 times* on the same params dict, re-urlencoding those large params every time. This seems excessive.

[Python 3.6; botocore 1.12.3 local dev <strike>or 1.10.74</strike> and Lambda; 256MB Lambda memory allocation]

### Fix

Eight of the nine `prepare_body()` calls are due to accessing `request.body` four times in `SigV4Auth`—and the `AWSRequest.body` property implementation unintentionally calls `prepare_body()` twice each time. The ninth is the one you'd expect via `AWSRequest.prepare()` as the request is sent.

I'm not sure the best way to proceed:

* No matter what, the [extraneous `prepare_body()` call](https://github.com/boto/botocore/blob/1.12.5/botocore/awsrequest.py#L391) should be removed from `AWSRequest.body`. (The body is already prepared by `AWSPreparedRequest()`'s init, on the preceding line.)

* A simple improvement for this particular case is to cache `request.body` in auth (e.g., #1478). But `AWSRequest.body` is still an expensive property to compute, which could easily trip up other code the same way. (We could add caching into the body prop implementation itself, but it's not clear to me how to reliably invalidate it.)

* The more robust fix might be to eliminate `AWSRequest.body` entirely. Code that wants the computed body (like sigv4) would need to explicitly call `AWSRequest.prepare()` and get the body prop from the resulting `AWSPreparedRequest`. That makes it clear there's more going on than a simple property access. (FWIW, the Requests models on which AWSRequest is based do it this way: `requests.Request` does not have a `body` prop; you have to get that from `requests.PreparedRequest`.)

* Even all that still leaves `urlencode` called twice on the same params: first while [adding auth](https://github.com/boto/botocore/blob/1.12.5/botocore/auth.py#L271-L284) and then again [for the actual send](https://github.com/boto/botocore/blob/1.12.5/botocore/endpoint.py#L117). It would be nice if there were some way to use a single `AWSPreparedRequest` for both, but I gather that doesn't play well with the auth implementation?

[Corrections: I'd been testing with botocore 1.12.3 in both Lambda and locally, because that was pulled in by aws-xray-sdk. The duplicate `prepare_body` was added sometime after 1.10.74, so it's only run *five* times in the current Lambda environment, but will be run nine times with the latest botocore.]

**Comment by joguSD** [comment]
Thanks for the detailed write up. Looks like this warrants some digging into. It's funny we were actually just discussing this over here: https://github.com/boto/botocore/pull/1556

As you mentioned this has been on the radar for a while now over in: https://github.com/boto/botocore/pull/1478

Let me take a look at this

**Comment by joguSD** [comment]
Digging into this a little bit more, while there is definitely room to improve on serialization it's definitely not the dominating factor here. The vast majority of time for these requests is in networking. It seems thar for larger payloads it's possible to get read timeouts and have to retry the request. I also tested this in the ruby sdk and saw similar performance. I think there might be something going on the service side here.

**Comment by medmunds** [comment]
I implemented a [simple Lambda function](https://gist.github.com/medmunds/1b32fb8873ff87dac8d29c9f0a7f4819#file-lambda_function-py) to test this, with some manual instrumentation on parts of botocore (to avoid potential interactions with aws-xray-sdk). With an 8MB raw message, `ses.send_raw_email` takes from 25–50 *seconds* to complete in Lambda; the longer time is on the latest botocore.

It appears that the vast majority of the (billable, timeout-contributing) Lambda execution time is spent repeatedly preparing `AWSRequest.body` to compute the signature. Signature calculation was 75% (botocore 1.10.74) to 85% (botocore 1.12.8) of the total `ses.send_raw_email` API call time; network appears to account for under 1.5s (3-5% of the API time).

Check the full source to see how I'm measuring (or run it yourself). Here's the test part—I'm using a roughly 8 MB RAW_MESSAGE built in memory before the timing starts:

```python
def run_test(event, context):
    logger.info("boto3==%s botocore==%s", boto3.__version__, botocore.__version__)
    logger.info("ses.send_raw_email sending %s byte message",
                "{:,d}".format(len(RAW_MESSAGE)))
    response = ses.send_raw_email(RawMessage={"Data": RAW_MESSAGE})
    logger.info("ses.send_raw_email response: %r", response)
```

With the current Lambda environment's botocore 1.10.74 ([full log](https://gist.github.com/medmunds/1b32fb8873ff87dac8d29c9f0a7f4819#file-log-botocore-1-10-74-txt)), total Lambda execution time was 28.327s, and RetryAttempts was 0. Here's how that time is spent:

* `BaseClient._make_api_call`: 28.326s (a.k.a. `ses.send_raw_email`)
  * `Endpoint.create_request`: 26.840s ("serialization," if I'm understanding the code correctly)
    * `SigV4Auth.add_auth`: 21.482s
      * `AWSRequest.body`: 5.340s
      * `AWSRequest.body`: 5.262s
      * `AWSRequest.body`: 5.263s
      * `AWSRequest.body`: 5.240s (yes, called four times)
    * `AWSPreparedRequest.prepare_body`: 5.315s
  * `Endpoint._get_response`: 1.301s (the "networking" portion, I think)

With botocore 1.12.8 ([full log](https://gist.github.com/medmunds/1b32fb8873ff87dac8d29c9f0a7f4819#file-log-botocore-1-12-8-txt)), total Lambda execution time is 49.931s, again with RetryAttempts 0:

* `BaseClient._make_api_call`: 49.919s (`ses.send_raw_email`)
  * `Endpoint.create_request`: 48.460s ("serialization")
    * `SigV4Auth.add_auth`: 43.162s
      * `AWSRequest.body`: 10.702s
        * `AWSPreparedRequest.prepare_body`: 5.342s
        * `AWSPreparedRequest.prepare_body`: 5.323s (this double-`prepare_body` seems unintentionally [introduced](https://github.com/boto/botocore/commit/818d23505620f5091e5a4114020b66b5e6d7aa7b#diff-cb00fc815f8f80ae15e7d0cecc74b395R379) while migrating off python-Requests)
      * `AWSRequest.body`: 10.683s
        * `AWSPreparedRequest.prepare_body`: 5.300s
        * `AWSPreparedRequest.prepare_body`: 5.341s
      * `AWSRequest.body`: 10.700s
        * `AWSPreparedRequest.prepare_body`: 5.281s
        * `AWSPreparedRequest.prepare_body`: 5.381s
      * `AWSRequest.body`: 10.704s
        * `AWSPreparedRequest.prepare_body`: 5.300s
        * `AWSPreparedRequest.prepare_body`: 5.381s
    * `AWSPreparedRequest.prepare_body`: 5.280s (yes, this is the *ninth* call to this function)
  * `Endpoint._get_response`: 1.267s ("networking")

(I haven't averaged across multiple test runs, but these results are pretty consistent with what I was seeing while debugging the test and in my original code.)

It's quite possible I'm misunderstanding something, but it certainly looks like there's opportunity for a big performance improvement on API requests with large params. (FWIW, by [monkey patching `AWSRequest.body`](https://gist.github.com/medmunds/ad47a5001729040d7743ae20d32786e1) to add caching, I was able to get my original email-forwarded Lambda function back down to a tolerable execution time.)

[BTW, if you check out the raw logs linked above, you'll see that a lot of the prepare_body time seems to be actually spent in process sleep (included in [`perf_counter()`](https://docs.python.org/3/library/time.html#time.perf_counter) but not [`process_time()`](https://docs.python.org/3/library/time.html#time.process_time)). I don't know if that's typical of Lambda execution, some quirk of the cPython runtime, or maybe what you were referring to by "something going on on the service side." But botocore seems like an easier performance win short-term.]
