### ISSUE TITLE
Error parsing parameter '--instances': Expected: '=', received: 'EOF' for input

### ISSUE THREAD

**Issue by treacher** [boto/botocore#1562]
Hi there.

We've recently updated to botocore==1.12.6 and we're receiving the following error on the same version of the awscli==1.15.36:
```
aws --region ap-southeast-2 elb describe-instance-health --load-balancer-name <elb-name> --instances <instance-id> --query InstanceStates[0].State

Error parsing parameter '--instances': Expected: '=', received: 'EOF' for input:
<instance-id>
```

This command was working on botocore==1.10.36

This started causing issues just yesterday.

**Comment by treacher** [comment]
Haven't finished editing yet ^^^ mis clicked.

**Comment by JordonPhillips** [comment]
The CLI has strict dependencies on botocore, so upgrading one without upgrading the other will likely cause issues. Version `1.15.36` requires botocore version `1.10.36`.
