### ISSUE TITLE
Default to input() instead of getpass() to fetch MFA credentials

### ISSUE THREAD

**Issue by 0cjs** [boto/botocore#1573]
Currently in `botocore/credentials.py` class `AssumeRoleCredentialFetcher` the default `mfa_prompter` is [`getpass.getpass()`]:

    self._mfa_prompter = mfa_prompter
    if self._mfa_prompter is None:
        self._mfa_prompter = getpass.getpass

This is unusual in that MFA authentication user input normally displays the numeric MFA code as it's typed (see, for example, the AWS web console login process, and TOTP input for most web sites). This improves user convenience at little security risk since the codes, if reusable at all, are usable only for a very short time.

Further, using `getpass()` is not completely reliable. In some environments, such as a Python script running from the MinGW Bash shell provided with Git for Windows, `getpass()` doesn't work and instead silently wedges both the script and the window within which it's running.

I suggest the default `mfa_prompter` be changed to [`input()`], which works in more situations (such as the one described above) and provides a more user-friendly experience.

As an aside, I'd also like to know how a different `mfa_prompter` could be set within a program that's calling `boto3.session.get_session().client('sts').assume_role()`; it's not obvious to me from reading the code how this would be done.

[`getpass.getpass()`]: https://docs.python.org/3/library/getpass.html#getpass.getpass
[`input()`]: https://docs.python.org/3/library/functions.html#input

**Comment by joguSD** [comment]
I understand your reasoning, but I don't think we would ever change this default. 

As for your second question, the `mfa_prompter` isn't something that can be externally configured. I could see this being useful as it would allow arbitrary MFA sources. Marking as a feature request to allow a custom MFA prompter.

**Comment by 0cjs** [comment]
Adding the ability to change the `mfa_prompter`  when using the `boto3` library will do the trick for me.

But I'm curious as to why the default is set this way (there's no explanation in commit 6e13977f1 which is I think it originated) and why it wouldn't be changed to match the way AWS console (and in fact every other MFA code system I've ever seen) does it.

**Comment by 0cjs** [comment]
The issue is still here; there's been no explanation of why, unlike AWS console (and pretty much every other program in the world that uses MFA tokens) this program must _not_ make visible to the user what he is typing.

**Comment by 0cjs** [comment]
As far as I can tell, the issue is still there, with no explanation of why this must work differently from every other MFA system including other AWS MFA systems.

To remind you again, this is not just about being different, but that in this particular circumstance the instance on being different makes the prompt break sometimes and not accept input.
