### ISSUE TITLE
Issues when using iter_lines to download files from s3

### ISSUE THREAD

**Issue by SerialDev** [boto/botocore#1574]
Reproduction code using the boto3 library:

When downloading a file from S3 using the .iter_lines() generator
```
        import io 

    obj = (
    s3.client
    .get_object(Bucket=bucket_name, Key=key_name)["Body"]
    .iter_lines())
    out_buffer = io.BytesIO()
    out_buffer.seek(0)
    [out_buffer.write(lines) for lines in obj]
    out_buffer.seek(0)
    t = out_buffer.read()
```

The file seems to be corrupted in some way 

```
s3.resource.Bucket(bucket_name).download_file(key_name, "test.jpg")
test_data = file_utils.load_file("test.jpg")
```
Bytes seem to be missing
```
    len(t) - len(test_data)
    >> -778
````

Investigating further: 
Files are the same at both tail ends
```
    t[:20]
    >> b'\xff\xd8\xff\xe1\x00\x18Exif\x00\x00II*\x00\x08\x00\x00\x00'

    test_data[:20]
    >> b'\xff\xd8\xff\xe1\x00\x18Exif\x00\x00II*\x00\x08\x00\x00\x00'

    t[-20:]
    >> b'\x1cH\xacJ\xe1T\x08\x04\x01\x15@\x98\xfe\xe2\x02\xa8\x04\x1f\xff\xd9'

    test_data[-20:]
    >> b'\x1cH\xacJ\xe1T\x08\x04\x01\x15@\x98\xfe\xe2\x02\xa8\x04\x1f\xff\xd9'

```
Find out where there was a difference: 

```
    diff_index = [i for i in range(len(t)) if t[i] != test_data[i]]
    diff_index[:2]    # Diff will propagate after this one
    >> [885, 886]
```

This yields: 
```
    t[880:890]
    >> b'\x06\x06\x08\x0b\x0c\x0b\x0c\x10\x0c\x0c'

    test_data[880:890]
    >> b'\x06\x06\x08\x0b\x0c\n\n\x0b\n\n'

```

for some reason, the \n is dropped.

**Comment by joguSD** [comment]
I believe this is the correct behavior.

The `iter_lines` method is implemented using the [`splitlines`](https://docs.python.org/2/library/stdtypes.html#str.splitlines) method, which return the contents of each line, discarding the newlines in the process.

**Comment by SerialDev** [comment]
Yes I have noticed that,, Thanks.  
I feel it might be worthwhile adding some test that replaces \n with %0A when verifying integrity, so this can be signalled to the user since some encodings might use C-Encoding as opposed to URI encoding and you might not know whether to use the delimiter, or more likely what is likely to be a delimiter that is good enough for your current binary stream.

**Comment by vijayraghavareddy** [comment]
> I believe this is the correct behavior.
> 
> The `iter_lines` method is implemented using the [`splitlines`](https://docs.python.org/2/library/stdtypes.html#str.splitlines) method, which return the contents of each line, discarding the newlines in the process.

Thanks for this!! saved my time! :) I was banging my head about the missing new line character in the response!
