### ISSUE TITLE
please publish 1.12.26

### ISSUE THREAD

**Issue by ThisGuyCodes** [boto/botocore#1581]
recently released (today) awscli depends on 1.12.26, please publish it? Also maybe try to publish leafs before the root? :)

**Comment by davebwag** [comment]
Temporary fix: 

> pip install awscli==1.16.35

**Comment by yermulnik** [comment]
https://pypi.org/project/botocore/1.12.26/

**Comment by kyleknap** [comment]
Yep. This should now be fixed. We were experiencing issues in our release system where the upload of `botocore` to PyPI failed but the upload of the CLI succeeded. We will be looking to make sure this does not happen again.

**Comment by jamesls** [comment]
Resolving, we've updated our release process to prevent this from happening again.

**Comment by oezer-sahin-ext** [comment]
Bad news, still happening :) 

```
ERROR: No matching distribution found for botocore>=1.12.183
```
