### ISSUE TITLE
Add kvm,baremental when retrive  ec2 instance hypervisor type

### ISSUE THREAD

**Issue by liangxiao1** [boto/botocore#1589]
There are many instances running on kvm or baremetal in ec2, add such support to show them corretly.

**Comment by markusboehme** [comment]
Note that this is the [documented behavior of the `DescribeInstances` API call](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Instance.html) (refer to the `hypervisor` field, whose valid values are either `ovm` or `xen`). [This FAQ](https://aws.amazon.com/ec2/faqs/) actually mentions it as being considered for removal:

> Q. Will the Nitro Hypervisor change the APIs used to interact with EC2 instances?
> 
> No, all the public facing APIs for interacting with EC2 instances that run using the Nitro Hypervisor will remain the same. For example, the “hypervisor” field of the DescribeInstances response, which will continue to report “xen” for all EC2 instances, even those running under the Nitro Hypervisor. This field may be removed in a future revision of the EC2 API.

**Comment by jamesls** [comment]
Resolving old issue, as documented, looks like this is the expected behavior from the API.
