### ISSUE TITLE
ValueError when using session with session name and role (`config_name, env_vars, default, typecast = config_options`)

### ISSUE THREAD

**Issue by stephen-mw** [boto/botocore#1602]
It looks like commit b0f97d05bbd454cd40dea98d437f39b884ea60bd, submitted on October 16th, introduced some new and breaking behavior. When creating a session with a session name and role arn, you get a TypeError because its attempting to iterate on a string:

```
  File "/usr/local/src/botocore/botocore/session.py", line 118, in __init__
    self.session_var_map = SessionVarDict(self, session_vars)
  File "/usr/local/src/botocore/botocore/session.py", line 896, in __init__
    self.__setitem__(key, value)
  File "/usr/local/src/botocore/botocore/session.py", line 903, in __setitem__
    self._update_config_store_from_session_vars(key, value)
  File "/usr/local/src/botocore/botocore/session.py", line 924, in _update_config_store_from_session_vars
    config_name, env_vars, default, typecast = config_options
TypeError: 'NoneType' object is not iterable
```

It looks like the culprit is here in [SessionVarDic](https://github.com/boto/botocore/blob/develop/botocore/session.py#L890) in `session.py`, which will take the dict and break into k/v, so any session property (such as the name) will break the function:
```
891  	    def __init__(self, session, session_vars):
892  	        self._session = session
893  	        self._store = dict()
894  	        if session_vars is not None:
895  	            for key, value in session_vars.items():
896  ->	                self.__setitem__(key, value)
```

Simple to reproduce. Create a session with session properties as a dict:

```
from botocore import session

foo = session.Session(session_vars={'role_arn': 'foo', 'assumed_role_session_name': 'foo'})
```

Which raises the exception:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-35bf5960cebf> in <module>()
----> 1 foo = session.SessionVarDict(None, {'assumed_role_session_name': 'bdp_metacat_rds', 'role_arn': 'arn:aws:iam::987128315680:role/BdpRDSBackup'})

/data/tmp/botocore/botocore/session.pyc in __init__(self, session, session_vars)
    894         if session_vars is not None:
    895             for key, value in session_vars.items():
--> 896                 self.__setitem__(key, value)
    897
    898     def __getitem__(self, key):

/data/tmp/botocore/botocore/session.pyc in __setitem__(self, key, value)
    901     def __setitem__(self, key, value):
    902         self._store[key] = value
--> 903         self._update_config_store_from_session_vars(key, value)
    904
    905     def __delitem__(self, key):

/data/tmp/botocore/botocore/session.pyc in _update_config_store_from_session_vars(self, logical_name, config_options)
    922         # the config_store component.
    923         config_chain_builder = ConfigChainFactory(session=self._session)
--> 924         config_name, env_vars, default, typecast = config_options
    925         config_store = self._session.get_component('config_store')
    926         config_store.set_config_provider(

ValueError: too many values to unpack
```

**Comment by stealthycoin** [comment]
@stephen-mw Hi can you tell me more about how you are using that code snippet? That's not at all how that parameter is supposed to work and I think its working by happenstance not by design, there is no logic in botocore that consumes those values as strings, they all assume tuples in this format: https://github.com/boto/botocore/blob/c6648a99628aec9e8ee4244a0eb63aa9790ff5d1/botocore/session.py#L83

What exactly is the context you are using that session in?

**Comment by oliverzm** [comment]
Hi, good day I am getting the same issue I am calling the session class: 

`session = Session({'region': r})`

```
File "botocore/session.py", line 927, in _update_config_store_from_session_vars
    config_name, env_vars, default, typecast = config_options
```

I printed config_options and I am only receiving:

```
print ('debbugging boto', config_options)
debugging boto us-east-1
```

**Comment by iShiBin** [comment]
I encounter the same issue 

> It looks like commit [b0f97d0](https://github.com/boto/botocore/commit/b0f97d05bbd454cd40dea98d437f39b884ea60bd), submitted on October 16th, introduced some new and breaking behavior. When creating a session with a session name and role arn, you get a TypeError because its attempting to iterate on a string:
> 
> ```
>   File "/usr/local/src/botocore/botocore/session.py", line 118, in __init__
>     self.session_var_map = SessionVarDict(self, session_vars)
>   File "/usr/local/src/botocore/botocore/session.py", line 896, in __init__
>     self.__setitem__(key, value)
>   File "/usr/local/src/botocore/botocore/session.py", line 903, in __setitem__
>     self._update_config_store_from_session_vars(key, value)
>   File "/usr/local/src/botocore/botocore/session.py", line 924, in _update_config_store_from_session_vars
>     config_name, env_vars, default, typecast = config_options
> TypeError: 'NoneType' object is not iterable
> ```
> 
> It looks like the culprit is here in [SessionVarDic](https://github.com/boto/botocore/blob/develop/botocore/session.py#L890) in `session.py`, which will take the dict and break into k/v, so any session property (such as the name) will break the function:
> 
> ```
> 891  	    def __init__(self, session, session_vars):
> 892  	        self._session = session
> 893  	        self._store = dict()
> 894  	        if session_vars is not None:
> 895  	            for key, value in session_vars.items():
> 896  ->	                self.__setitem__(key, value)
> ```
> 
> Simple to reproduce. Create a session with session properties as a dict:
> 
> ```
> from botocore import session
> 
> foo = session.Session(session_vars={'role_arn': 'foo', 'assumed_role_session_name': 'foo'})
> ```
> 
> Which raises the exception:
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-3-35bf5960cebf> in <module>()
> ----> 1 foo = session.SessionVarDict(None, {'assumed_role_session_name': 'bdp_metacat_rds', 'role_arn': 'arn:aws:iam::987128315680:role/BdpRDSBackup'})
> 
> /data/tmp/botocore/botocore/session.pyc in __init__(self, session, session_vars)
>     894         if session_vars is not None:
>     895             for key, value in session_vars.items():
> --> 896                 self.__setitem__(key, value)
>     897
>     898     def __getitem__(self, key):
> 
> /data/tmp/botocore/botocore/session.pyc in __setitem__(self, key, value)
>     901     def __setitem__(self, key, value):
>     902         self._store[key] = value
> --> 903         self._update_config_store_from_session_vars(key, value)
>     904
>     905     def __delitem__(self, key):
> 
> /data/tmp/botocore/botocore/session.pyc in _update_config_store_from_session_vars(self, logical_name, config_options)
>     922         # the config_store component.
>     923         config_chain_builder = ConfigChainFactory(session=self._session)
> --> 924         config_name, env_vars, default, typecast = config_options
>     925         config_store = self._session.get_component('config_store')
>     926         config_store.set_config_provider(
> 
> ValueError: too many values to unpack
> ```

I encounter the same issue on `Ubuntu 14.04.5 LTS` + Python 3.4. How to solve this problem?

**Comment by tedweb** [comment]
Me too.  This same issue on Ubuntu 14.04.5 LTS + Python 3.4 is happening while running the following command: 

`>aws s3 ls`

Also, not sure if this is related but the following command is saving my credentials to the config file, not credentials.

`>aws configure`

Any help would be greatly appreciated.

**Comment by hamedazhar-giz** [comment]
I have also got the same issue. Anyone who fixed this, please post the solution! :)

**Comment by Ta-m** [comment]
Hi!!!
Just replace 
`session = Session({'region': r})`
with
`session = Session()`
!

**Comment by DmitriyKartashov** [comment]
that code works with the latest python in AWS lambda:
https://github.com/TomPengxiangWang/Python/blob/master/dynamo-to-elastic.py

You can copy session setup from there

**Comment by elinxie** [comment]
Hello, can anyone link me to the fix for this issue in the code base? Thank you?
