### ISSUE TITLE
AWS Transfer SFTP

### ISSUE THREAD

**Issue by thebenwaters** [boto/botocore#1612]
Is this missing an s3 path?

https://github.com/boto/botocore/blob/0929369fd4836466625a18141ce614db304cbe73/botocore/data/transfer/2018-11-05/service-2.json#L336

So should be?

```json
      "members":{
        "HomeDirectory":{
          "shape":"HomeDirectory",
          "documentation":"<p>The landing directory (folder) for a user when they log in to the server using their SFTP client. An example is <code>/s3bucket/home/<i>username</i> </code>.</p>"
        },
```

**Comment by thebenwaters** [comment]
@joguSD Not an input, but wording. My comment is I think there is wording missing. If you read this documentation some how AWS magically connects a user to an S3 bucket. Is this true? Is it reading permissions of the user??? If you read the describe user it includes s3 bucket in it's output. CreateUser does not mention an s3 bucket anywhere

**Comment by thebenwaters** [comment]
Response of `describe_user(**kwargs)`

```
HomeDirectory (string) --

This property specifies the landing directory (or folder) which is the location that files are written to or read from in an Amazon S3 bucket for the described user. An example would be: ``/bucket_name /home/username `` .
```

**Comment by swetashre** [comment]
@thebenwaters - The documentation is wrong for ```create_user``` . The ```HomeDirectory``` should be a s3 bucket because when a user is created through aws console a s3 bucket is required as home directory not any local file. 

As this piece of documentation comes from upstream. I will let the service team know about the issue so that they can fix this.

**Comment by swetashre** [comment]
@thebenwaters - The service-2.json file is now updated with the correct description. You can see here https://github.com/boto/botocore/blob/develop/botocore/data/transfer/2018-11-05/service-2.json#L367

I am closing this issue as the issue has been fixed.
