### ISSUE TITLE
Athena Paginator response missing NextToken in certain scenarios

### ISSUE THREAD

**Issue by dropofwill** [boto/botocore#1614]
Based on the docs:
> MaxItems (integer) --
> The total number of items to return. If the total number of items available is more than the value specified in max-items then a NextToken will be provided in the output that you can use to resume pagination.

I would expect asking for 2003 rows from a 2500 result set to return at most 2003 rows and a NextToken to retrieve the rest.

However, given an Athena result set of 2500 rows:

```
athena_paginator.paginate(
  QueryExecutionId=<some_uuid>,
  PaginationConfig={'MaxItems': 2003, 'PageSize': 1000})
```
It returns the 2003 results, but no NextToken. This behavior occurs from [2001, 2499]. It seems like this is only a problem on the last page, (e.g. MaxItems 1003 behaves correctly).

I've confirmed that manually calling athena#get_query_results with MaxResults of [1000, 1000, 3] does the right thing, so I'm pretty sure it's a boto pagination issue.

**Comment by JordonPhillips** [comment]
That doc string isn't quite right. `NextToken` is only inserted if you call `build_full_result` on the page iterator. If you want to manually paginate you should just use the base api.
