### ISSUE TITLE
Save video stream to a file

### ISSUE THREAD

**Issue by Gil401** [boto/botocore#1618]
Hi Guys,

So I am trying to grab the data from the stream using the GetMedia API and save it as a webm file.
Here is my code:
```
client = boto3.client('kinesis-video-media', endpoint_url=url)
        response = client.get_media(
            StreamARN=MyARN,
            StartSelector={
            'StartSelectorType': 'EARLIEST',
            })
with open(fileName, 'a+') as f:
            chunks = response['Payload'].iter_chunks()
            for chunk in chunks:
                f.write(chunk)
```

I've encountered 2 issues:
1. it takes really long time to read the stream (around 6 mins for 1 payload object)
2. the size of the file is around 180 MB for 1 sec video!
3. what do you believe is the correct way to divide save a stream into 1 minute files?

What am I doing wrong?
Thank you for your help!

**Comment by JordonPhillips** [comment]
I would recommend asking about this on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=282) or on stackoverflow to get specific advice.

As far as download time is concerned, that will depend pretty heavily on your network. From the api docs:

> Kinesis Video Streams sends media data at a rate of up to 25 megabytes per second (or 200 megabits per second) during a GetMedia session.

So you will probably never get more than that.

Regarding size, that probably depends on your source. MKV format can contain uncompressed video of arbitrary resolution. I don't have any specific advice for chunking it up.
