### ISSUE TITLE
'region' value never checked for empty string, nor any sane default applied

### ISSUE THREAD

**Issue by tb3088** [boto/botocore#1627]
The api makes various calls to resolve service endpoints but at no stage does it actually check for empty strings nor does it provide the sensible default which per AWS docs is supposed to be 'us-east-1'. As a result of never checking for inputs programs throw ValueError on malformed endpoints like 'https://s3..amazonaws.com' - notice the double dot.

**Comment by JordonPhillips** [comment]
As discussed in the linked pr, there is no reasonable default for regions and validating empty regions would be a breaking change.
