### ISSUE TITLE
Make expect_header configurable

### ISSUE THREAD

**Issue by vmksuw** [boto/botocore#1659]
Expect header is automatically enabled as handler on 'before-call.s3' event in handlers.BUILTIN_HANDLERS. Make it configurable so that it can be disabled/enabled as needed.

**Comment by JordonPhillips** [comment]
`client.meta.events.unregister('before-call.s3', add_expect_header)`

But again, if you do this then S3 probably won't work, especially once you get into uploading / downloading.
