### ISSUE TITLE
DynamoDB: Add support for TransactWriteItems

### ISSUE THREAD

**Issue by mjonescase** [boto/botocore#1665]
AWS rolled out support for [transactions](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html) across partitions and tables at Re:Invent in November 2018.

This feature would be a game-changer for those of us who store relational data in Dynamo using patterns like [adjacency list](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-adjacency-graphs.html).

**Comment by mjonescase** [comment]
Do the maintainers of this repo also maintain the docs hosted [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/dynamodb.html)? If so, could you please add TransactWriteItems? I was misled into thinking TransactWriteItems wasn't supported yet and spent some unnecessary time to learn that it was supported (I looked at source code/commit history).

**Comment by akashg90** [comment]
I am still confused whether TransactionWriteItems is supported or not. If supported could you please provide reference to it.

**Comment by cyberfox1** [comment]
Is this supported or not? It doesn't work for me. Why no updates on this issue???
