### ISSUE TITLE
SNS Topic creation with Attributes

### ISSUE THREAD

**Issue by samuel-72** [boto/botocore#1669]
```
>>> cn_topic = snsr.meta.client.create_topic(Name='CertificateNotifier', Attributes={'DisplayName':'CNT'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Attributes", must be one of: Name
```

While trying to create a topic using SNS resource or client if one tries to specify Attributes like DisplayName then the following error comes up.

**Comment by JordonPhillips** [comment]
What version of botocore are you using? You probably just need to update.

**Comment by samuel-72** [comment]
I am running  1.11.4

pip show botocore

Name: botocore
Version: 1.11.4
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: docutils, jmespath, python-dateutil, urllib3
Required-by: s3transfer, boto3

**Comment by JordonPhillips** [comment]
You will need to update, the parameter [isn't available in that version](https://botocore.amazonaws.com/v1/documentation/api/1.11.4/reference/services/sns.html#SNS.Client.create_topic).
