### ISSUE TITLE
botocore.exceptions.SSLError: SSL validation failed for https://secretsmanager.us-west-2.amazonaws.com/ EOF occurred in violation of protocol (_ssl.c:661)

### ISSUE THREAD

**Issue by sreedev2** [boto/botocore#1673]
I'm running the following command: 

aws secretsmanager get-secret-value --secret-id Test --debug

and I get the following exception:

`Traceback (most recent call last):`
  `File "/usr/local/aws/lib/python2.7/site-packages/botocore/endpoint.py", line 179, in _get_response
    http_response = self._send(request)`
  `File "/usr/local/aws/lib/python2.7/site-packages/botocore/endpoint.py", line 223, in _send
    return self.http_session.send(request)`
  `File "/usr/local/aws/lib/python2.7/site-packages/botocore/httpsession.py", line 266, in send
    raise SSLError(endpoint_url=request.url, error=e)`
`SSLError: SSL validation failed for https://secretsmanager.us-west-2.amazonaws.com/ EOF occurred in violation of protocol (_ssl.c:661)`

boto3=1.9.85
botocore=1.12.85
Python 2.7
macOS High Sierra 10.13.6

**Comment by sreedev2** [comment]
Python 2.7.14
Also, aws-cli = 1.16.95

**Comment by caijim** [comment]
I tried explicitly installing openssl and it worked after that

**Comment by swetashre** [comment]
@sreedev2 - Do you have proxies configured? Is this only happening to you for ```secretsmanager```? Can you make any other AWS API calls with the CLI ? Which version of SSL are you using ? It would be very helpful if you could give us the full debug log. 

These are some of the related issue which might help:
https://github.com/aws/aws-cli/issues/3254
https://github.com/aws/aws-cli/issues/3268
