### ISSUE TITLE
No API for the `x-amz-server-side-encryption-context` s3:PutObject option

### ISSUE THREAD

**Issue by copumpkin** [boto/botocore#1682]
I noticed the `x-amz-server-side-encryption-context`  key in [this page](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests) but haven't been able to find any AWS SDKs that implement support for it.

I'm guessing some of the shared underlying model files don't describe the field? Or did I miss something?

Since I don't have an easy way to file a bug report against those shared underlying model files, I figured I'd ask for the functionality here and hope it bubbles up to the right people 😄

**Comment by copumpkin** [comment]
TBC, I can make a PR against the model files in this repo if that's the right thing to do, but my impression was that the basic service-2.json files were brought in from elsewhere so PRs against them weren't accepted.

**Comment by jamesls** [comment]
Thanks for letting us know, looks like we need to get these files updated.  I'll follow up internally about getting these files updated.

**Comment by copumpkin** [comment]
Thanks!

**Comment by joelthompson** [comment]
Hey @jamesls -- any update on this? Thanks!

**Comment by copumpkin** [comment]
This appears to be live now, not sure when it went in. I see lots of talk of encryption context in `https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.put_object` and elsewhere on that page, and I assume if boto3 has it, so does botocore. @jamesls safe to close or is there something else I've missed?

**Comment by swetashre** [comment]
Currently this parameter is supported. 
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#RESTObjectPUT-requests
I am closing this issue as it has been resolved. Please let us know if you have any more questions.
