### ISSUE TITLE
mediaconvert is missing "Rotate" option on VideoSelector

### ISSUE THREAD

**Issue by ant32bit-carsales** [boto/botocore#1683]
I've been trying to create a job in mediaconvert using the auto rotate option as follows

```
session = botocore.session.get_session()
client = session.create_client(
        'mediaconvert', 
        region_name=AWS_REGION,
        endpoint_url=MEDIACONVERT_ENDPOINT)

result = client.create_job(
            Role=AWS_ROLE,
            Settings={
              ...
              'Inputs': [{
                ...
                'VideoSelector': {
                  ...
                  'Rotate': 'AUTO'
                }
              }]
            })
```

However this option is missing from the service-2.json file. 
`/data/mediaconvert/2017-08-29/service-2.json`

Please update this.

**Comment by jamesls** [comment]
That change went out in today's release v1.12.103 (https://github.com/boto/botocore/blob/develop/botocore/data/mediaconvert/2017-08-29/service-2.json#L8039).
