### ISSUE TITLE
Why are certain unsigned operations marked as unsigned in handlers.py?

### ISSUE THREAD

**Issue by copumpkin** [boto/botocore#1684]
A few operations in cognito and STS are marked as unsigned here:

https://github.com/boto/botocore/blob/5028b2106e078c4257be23db0905ac9a1593acf6/botocore/handlers.py#L923-L929

But other operations in cognito like `ChangePassword` are marked as `"authtype": "none"` in the JSON models:

https://github.com/boto/botocore/blob/4c1679ca45c23966ac0a0c1aa39450ebb81567b3/botocore/data/cognito-idp/2016-04-18/service-2.json#L569-L573

Given that quite a few other projects use the botocore JSON model files to generate their own code (and various other sorts of analysis) I'm wondering why `"authtype": "none"` isn't used for all these APIs.

**Comment by jamesls** [comment]
The `disable_signing` handler predates having this modeled via `"authtype": "none"`.  It looks like when the authtype was added, pre-existing service models weren't backfilled to use this new feature.  I'll follow up about getting these services updated.

**Comment by copumpkin** [comment]
That makes sense, thanks!
