### ISSUE TITLE
Document exception raised by Waiter.wait()

### ISSUE THREAD

**Issue by charlax** [boto/botocore#1685]
The exception raised by `Waiter.wait()` is not documented in https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=object_exists#S3.Object.wait_until_exists

I had to run the code to find it.

I'd be happy to write a PR to fix this - would you mind giving me some pointers about where to start? Wasn't sure if this should be reported in `boto` or `botocore`.

**Comment by jamesls** [comment]
Those API docs are generated based on our the waiters-2.json files in botocore.  The code that generates this is in https://github.com/boto/botocore/blob/develop/botocore/docs/waiter.py.  Perhaps we can just add to the [wait_description](https://github.com/boto/botocore/blob/develop/botocore/docs/waiter.py#L110)?

**Comment by charlax** [comment]
Is the exception documented too? It would be nice to link to it...
