### ISSUE TITLE
Missing validation when retrieving file from S3 with SSECustomerKey

### ISSUE THREAD

**Issue by jerr0328** [boto/botocore#1686]
This is using boto3, but the errors happen within botocore. If I use an invalid key to upload a file to an S3 endpoint, I get:
```
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutObject operation: The secret key was invalid for the specified algorithm.
```

However, using the invalid key to fetch a file from S3 does not. With the specific cloud provider's S3 I was using, this caused botocore to try to redirect to an invalid AWS region.

I would expect to see a similar exception as above, but instead I get a connection error as botocore redirects to an invalid S3 endpoint. One workaround we will do is validate the encryption key ahead of time to make sure it's 32 bytes (256 bit for AES256) but I think this should be handled by botocore, seeing as the upload part does have validation in place. 

## Sample code
(Note: here I'm using boto3, but problem happens in botocore):
```python
import os
import boto3

S3_ENDPOINT = os.getenv("S3_ENDPOINT")
S3_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY")
S3_ENCRYPTION_KEY = os.getenv("S3_ENCRYPTION_KEY")
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")

client = boto3.client(
    "s3",
    endpoint_url=S3_ENDPOINT,
    aws_access_key_id=S3_ACCESS_KEY_ID,
    aws_secret_access_key=S3_SECRET_ACCESS_KEY,
)

def get_file(bucket_name, file_path, download_path, encryption_key):
    print(f"Fetching file s3://{bucket_name}/{file_path} to {download_path}")
    extra_args = None
    if encryption_key:
        print("Using encryption")
        extra_args = {
            "SSECustomerAlgorithm": "AES256",
            "SSECustomerKey": encryption_key,
        }
    client.download_file(
        Bucket=bucket_name, Key=file_path, Filename=download_path, ExtraArgs=extra_args
    )

    return download_path

def main():
    encryption_key = S3_ENCRYPTION_KEY
    print(f"Encryption key: {encryption_key}")

    downloaded_path = get_file(
        S3_BUCKET_NAME,
        "test.txt",
        "download.txt",
        encryption_key,
    )


if __name__ == "__main__":
    main()
```

## Versions
Python 3.6.7
Botocore 1.12.104
Boto3 1.9.104
Seen on macOS 10.14.3 and on Ubuntu

**Comment by jamesls** [comment]
> However, using the invalid key to fetch a file from S3 does not. With the specific cloud provider's S3 I was using, this caused botocore to try to redirect to an invalid AWS region

Can you share the specific error you're getting? 

Also, just want to clarify, this error message:

```
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the PutObject operation: The secret key was invalid for the specified algorithm.
```

doesn't actually come from botocore (the part about the secret key being invalid).  That's an error that's returned directly from S3 that we're surfacing back to the user.

What happens if you try to fetch an object from the real S3 with an invalid key?  I suspect S3 should return an error message back to you.  It would be helpful to compare the two responses.

**Comment by jerr0328** [comment]
The actual error we got from boto was:
```
EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.de.amazonaws.com/<bucket>/<key>"
```

from `botocore/httpsession.py` in `send` at line 278. There was also the exception from the socket.py and urllib3 indicating a connection. We received these exceptions in Sentry, so we have a bit of context to work with.

That URL was strange because we use a different endpoint, not Amazon's AWS. Since that's not a valid AWS region, the request failed to resolve, but really it also hides the underlying cause. I can't tell what we got from the server with boto (would have to check using the HTTP(S) API). 

About halfway through the call stack, I can see in botocore/client.py in _make_api_call (line 648) there's a `request_context` that is:
```
{
auth_type: [Filtered], 
client_config: <botocore.config.Config object at 0x7fee376d0ac8>, 
client_region: 's3-de-central', 
has_streaming_input: False, 
s3_redirected: True, 
signing: {
bucket: '<bucket>', 
endpoint: 'https://s3.de.amazonaws.com', 
region: 'de'
}, 
timestamp: '20190228T141818Z'
}
```

Note that the `client_region` is set to a value recommended by the provider (although it seems like maybe their actual region ends up being `de`). I also found it a bit odd that there's no configuration exposed when creating the client to set the URL format to use when `s3_redirected` ends up being True.

**Comment by jerr0328** [comment]
Having queried the S3 endpoint with the same parameters, I got back a 400 Bad Request with:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidArgument</Code>
    <Message>The secret key was invalid for the specified algorithm.</Message>
    <RequestId>4d0912e0-10df-1996-a9e7-0cc47af2c4a0</RequestId>
    <HostId>H54TdLEE4c6zTao[...]</HostId>
</Error>
```

The code that sets the `s3_redirected` I mentioned in my previous comment seems to be in botocore/utils.py, in the `redirect_from_error` function at line 1087, where it does seem to do special handling for the 400 errors. In that function, it tries to redirect regardless of the actual error message, which is likely what's hiding the validation from us and instead causes a misleading redirect and error.

Potentially also worth noting is the Server in the response header is `CloudianS3`.

**Comment by swetashre** [comment]
@jerr0328 - Following up on old issue. Are you still facing the issue ? If yes, can you please provide full debug logs ? I would be happy to help. You can enable log by adding ```boto3.set_stream_logger('')``` to your code.

**Comment by jerr0328** [comment]
@swetashre Thanks for the response! I'm not working on the codebase that had the issue, and we pretty much worked around the issue by adding our own validation to make sure the `SSECustomerKey` was the correct length before passing to `boto3`, so we don't get this behavior anymore.

**Comment by swetashre** [comment]
I am closing this issue for now. Please reopen if you have any concerns.
