### ISSUE TITLE
Update S3 BucketCannedACL list to support all available options

### ISSUE THREAD

**Issue by ryno75** [boto/botocore#1690]
Currently the S3 BucketCannedACL list only supports:
 * private
 * public-read
 * public-read-write
 * authenticated-read
per: https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json#L1200

This can be observed in boto3 s3 client docstring:
```
**Request Syntax**
::

  response = client.put_bucket_acl(
      ACL='private'|'public-read'|'public-read-write'|'authenticated-read',
      AccessControlPolicy={
...
```

However... the AWS docs indicate that there are another four canned ACLs:
https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

I propose a simple update to the service json to add the new canned ACLs.

**Comment by ryno75** [comment]
Hmm... shoot. This actually appears to be a limitation of the API.
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTacl.html

**Comment by ryno75** [comment]
I just got word back from our AWS TAM that the API documentation is incorrect and it does indeed support the `aws-exec-read` and `log-delivery-write` ACLs.  I built a patched version of botocore, installed it in a venv and tested it and it worked perfectly.

**Comment by JordonPhillips** [comment]
You don't need to patch botocore - you can provide any value you want. Enum constraints are not enforced, they're only used for docs.

**Comment by JordonPhillips** [comment]
I've let upstream know that some values are missing. Once they've updated the change will go out in all the SDKs.

**Comment by ryno75** [comment]
Ah... I see. ok. thanks.
