### ISSUE TITLE
waiters return none ? while ruby'sdk return response

### ISSUE THREAD

**Issue by mv740** [boto/botocore#1692]
Hi,

I am trying to use  EC2.Waiter.SpotInstanceRequestFulfilled method using boto3 after requesting a spotted instance and then reacting to the (status code)[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-bid-status.html#spot-instance-bid-status-understand] 

-  [boto3'sdk version](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Waiter.SpotInstanceRequestFulfilled)
   -  
      ``` 
       Returns
            None
      ```
- [ruby'sdk version](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Waiters/SpotInstanceRequestFulfilled.html)
   -  
      ``` 
      Returns:
         (Types::DescribeSpotInstanceRequestsResult) — Returns a response object which responds to the 
         following methods:
         #spot_instance_requests => Array<Types::SpotInstanceRequest>
         #next_token => String
      ```

Is there a reason why the python's sdk isn't returning the describe_spot_instance_requests response's object ? or do I need to set something to get the information. 

thanks

**Comment by JordonPhillips** [comment]
The purpose of the wait operation is to wait for a condition to be true, not to return information about the resource. If you want that information then you will need to query for it explicitly.

**Comment by mv740** [comment]
ah ok ,  I thought it was an implementation's mismatch.  I will do a describe_spot_instance_requests  call to fetch the information. 

thanks
