### ISSUE TITLE
FIPS mode causes segfault when copying to s3

### ISSUE THREAD

**Issue by zachsmorgan** [boto/botocore#1693]
S3 copy and sync operations segfault when running on a machine with FIPS enabled. This appears to be a byproduct of using md5 to generate the key hash in https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L246

Steps to reproduce:
  `[[ $(cat /proc/sys/crypto/fips_enabled) == 1 ]] && aws --debug --region <region> s3 sync --sse AES256 --delete <dir> <s3 bucket>`

Relevant debug output:
```
2019-03-05 14:40:06,606 - ThreadPoolExecutor-0_1 - s3transfer.tasks - DEBUG - Executing task PutObjectTask(transfer_id=0, {'extra_args': {'ServerSideEncryption': u'AES256'}, 'bucket': u'<BUCKET>', 'key': u'sse/<HOSTNAME>/var/opt/<DIRECTORY>'}) with kwargs {'extra_args': {'ServerSideEncryption': u'AES256'}, 'client': <botocore.client.S3 object at 0x7fd5aa0df410>, 'bucket': u'<BUCKET>', 'key': u'sse/<HOSTNAME>/var/opt/<DIRECTORY>', 'fileobj': <s3transfer.utils.ReadFileChunk object at 0x7fd5a8d653d0>}
2019-03-05 14:40:06,610 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x7fd5ab695848>
2019-03-05 14:40:06,610 - ThreadPoolExecutor-0_1 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7fd5ab692c80>
Segmentation fault (core dumped)
```

**Comment by zachsmorgan** [comment]
More details!

Downgrading to awscli 1.15.45 (and s3transfer==0.1.13, botocore==1.10.45) appears to fix the problem. 

Could this somehow be related to #1619 ?

**Comment by JordonPhillips** [comment]
Those handlers haven't changed in a very long time, so I'm not sure why a downgrade to that version would have any impact. What OS / version / python are you running?

In any case you will not be able to use any features that require MD5 since it is unavailable in FIPS mode. I'm curious why our snippet to detect that it's missing isn't working.

**Comment by zachsmorgan** [comment]
A colleague pointed out that the methods from #1619 are using the "calculate_md5" method, as opposed to "conditionally_calculate_md5" - I'm assuming that's the snippet you're referring to?

**Comment by JordonPhillips** [comment]
That method, and (hopefully) anything that touches MD5 ends up calling [`get_md5`](https://github.com/boto/botocore/blob/develop/botocore/compat.py#L251-L275) which should raise an exception. The function that seems to be the particular issue here is `sse_md5` which also ends up calling get_md5 [here](https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L256).

I'm going to try to reproduce this, but it would help if you could tell me what os, ptyhon version, and cli version you're using.

**Comment by JordonPhillips** [comment]
I'm not able to reproduce on RHEL 7.2 with python 2.7.5 and the latest version of the CLI. SSE works fine and SSE-C throws the error I would expect.

**Comment by zachsmorgan** [comment]
We're using Ubuntu 16.04, Python 2.7.12 with awscli==1.16.110. The FIPS kernel from Canonical is also installed (4.4.0-1006-fips).

**Comment by JordonPhillips** [comment]
I'm sorry for the delay here, I've been having difficulty getting an ubuntu environment set up as they don't make it easy to do self-service. I think for our purposes I could just compile openssl myself on ubuntu to replicate the behavior. What version of openssl are you using @zachsmorgan ? You can find this with `openssl version`

**Comment by mausch** [comment]
I just got this with awscli 1.23.6.
Had to downgrade to 1.15.45 as mentioned above.
