### ISSUE TITLE
No way to switch off MD5 for using boto on FIPS 

### ISSUE THREAD

**Issue by jweinst1** [boto/botocore#1700]
So, I originally had an issue with botocore and boto3 where the s3 head bucket operation would not work via the `boto3.client('s3', region='us-gov-west-1')`, dude to `fips_md.c` complaining about the algorithm being ignored. This is the original error message:

```
 fips_md.c(149): OpenSSL internal error, assertion failed: Digest Final previous FIPS forbidden algorithm error ignored
```

And the line causing the problem:

```py
self.client.head_bucket(Bucket=bucket_name)['ResponseMetadata']['HTTPHeaders']['x-amz-bucket-region']
```

This was fixed by a patch I tried on the botocore's `compat.py` file, as seen below

```py
-try:
-    hashlib.md5()
-    MD5_AVAILABLE = True
-except ValueError:
+if user_fips_mode():
     MD5_AVAILABLE = False
+else:
+    try:
+        hashlib.md5()
+        MD5_AVAILABLE = True
+    except ValueError:
+        MD5_AVAILABLE = False
```
where `user_fips_mode` is a function checking some environment variables. This patch did fix the error arising from `fips_md.c`, but now causes another error when the copy object [operation is called from `boto3`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.copy_object):

```py
  File xxx.py", line 93, in yy
    SSECustomerKey = plaintext,
  File "/opt/splunk/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/opt/splunk/lib/python2.7/site-packages/botocore/client.py", line 619, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/opt/splunk/lib/python2.7/site-packages/botocore/client.py", line 648, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/opt/splunk/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/botocore/hooks.py", line 360, in _emit
    aliased_event_name, kwargs, stop_on_response
  File "/opt/splunk/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/opt/splunk/lib/python2.7/site-packages/botocore/handlers.py", line 231, in sse_md5
    _sse_md5(params, 'SSECustomer')
  File "/opt/splunk/lib/python2.7/site-packages/botocore/handlers.py", line 254, in _sse_md5
    get_md5(key_as_bytes).digest()).decode('utf-8')
  File "/opt/splunk/lib/python2.7/site-packages/botocore/compat.py", line 276, in get_md5
    raise MD5UnavailableError()
MD5UnavailableError: This system does not support MD5 generation.
```

*Note:* The above stack trace is obtained with a copy_object call that uses SSE keys. from kms.

### Version

The versions of AWS being used are below:

```
$ aws --version
aws-cli/1.16.108 Python/2.7.12 Linux/4.4.0-1002-fips botocore/1.12.98
```

### Summary

It seems botocore nor boto3, in any interface have a universal method or object that can alter FIPS or non-FIPS code for using boto3 and botocore on a FIPS-based system. It would be good to check if this is a bug, or an enhancement is needed if this behavior, the second error message shown above, is intended.

**Comment by JordonPhillips** [comment]
The problem is that the S3 control plane apis require the content-md5 header. Python's MD5 implementation just uses OpenSSL's, which is disabled in FIPS mode. So in FIPS mode you can't use MD5 in Python. iirc there were some proposals to add a flag to indicate that you're not using it for security so you can work around this issue, but it never got merged upstream.

To make these apis work we would need S3 to remove the requirement for the content-md5 header for all operations.

**Comment by JordonPhillips** [comment]
Your best bet is to ask for this on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).

**Comment by jweinst1** [comment]
Great, thanks for clarification on the scope.

**Comment by audiem13** [comment]
@jweinst1 If you are using the Splunk Add-on for AWS, you will need to modify the hashlib.md5 lines to hashlib.sha256 in many of the python files.
