### ISSUE TITLE
setting read_timeout is not working

### ISSUE THREAD

**Issue by waynehuang13** [boto/botocore#1711]
'''File "/usr/local/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='ec2.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

Here's the code:
config_boto = Config(connect_timeout=3600, read_timeout=3600, retries={'max_attempts' : 0})
client = boto3.client('ec2', config=config_boto, region_name="us-east-1")

**Comment by jamesls** [comment]
What version of boto3/botocore are you using?  I'd double check your'e using the latest version.  Botocore will catch the `ReadTimeoutError` and raise it's own version so if you're seeing a `ReadTimeoutError` from urllib3 it could mean you're using an old version of botocore that doesn't support read timeouts.  I double checked that we are plumbing this value through to urllib3.  This is what you should see on the latest version of botocore:

```
Traceback (most recent call last):
  File "/tmp/a.py", line 5, in <module>
    client.describe_images()
  File "botocore/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "botocore/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "botocore/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "botocore/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "botocore/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "botocore/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "botocore/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "botocore/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "botocore/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "botocore/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "botocore/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "botocore/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "botocore/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "botocore/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "botocore/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
```

**Comment by sean-zou** [comment]
I tried to put read_timeout in ~/.aws/config under default profile, and it didn't take the value.

Could it be read_timeout cannot be in ~/.aws/config? 

> 21:27:54 Traceback (most recent call last):
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
21:27:54     six.raise_from(e, None)
21:27:54   File "<string>", line 3, in raise_from
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
21:27:54     httplib_response = conn.getresponse()
21:27:54   File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
21:27:54     response.begin()
21:27:54   File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
21:27:54     version, status, reason = self._read_status()
21:27:54   File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
21:27:54     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
21:27:54   File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
21:27:54     return self._sock.recv_into(b)
21:27:54   File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
21:27:54     return self.read(nbytes, buffer)
21:27:54   File "/usr/local/lib/python3.7/ssl.py", line 929, in read
21:27:54     return self._sslobj.read(len, buffer)
21:27:54 socket.timeout: The read operation timed out
21:27:54 
21:27:54 During handling of the above exception, another exception occurred:
21:27:54 
21:27:54 Traceback (most recent call last):
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 263, in send
21:27:54     chunked=self._chunked(request.headers),
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
21:27:54     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
21:27:54     raise six.reraise(type(error), error, _stacktrace)
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
21:27:54     raise value
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
21:27:54     chunked=chunked,
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
21:27:54     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
21:27:54   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
21:27:54     self, url, "Read timed out. (read timeout=%s)" % timeout_value
21:27:54 urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='ec2.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)
21:27:54 
21:27:54 During handling of the above exception, another exception occurred:
21:27:54 
21:27:54 Traceback (most recent call last):
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/commands.py", line 283, in run
21:27:54     policy()
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 1045, in __call__
21:27:54     resources = PullMode(self).run()
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 288, in run
21:27:54     resources = self.policy.resource_manager.resources()
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/resources/ec2.py", line 93, in resources
21:27:54     return super(EC2, self).resources(query=query)
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 460, in resources
21:27:54     resources = self.source.resources(query)
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 230, in resources
21:27:54     return self.query.filter(self.manager, **query)
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 90, in filter
21:27:54     getattr(resource_manager, 'retry', None)) or []
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 69, in _invoke_client_enum
21:27:54     data = results.build_full_result()
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 449, in build_full_result
21:27:54     for response in self:
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
21:27:54     response = self._make_request(current_kwargs)
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/query.py", line 686, in _make_request
21:27:54     return self.retry(self._method, **current_kwargs)
21:27:54   File "/usr/local/lib/python3.7/site-packages/c7n/utils.py", line 390, in _retry
21:27:54     return func(*args, **kw)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
21:27:54     return self._make_api_call(operation_name, kwargs)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 573, in _make_api_call
21:27:54     operation_model, request_dict, request_context)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 592, in _make_request
21:27:54     return self._endpoint.make_request(operation_model, request_dict)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
21:27:54     return self._send_request(request_dict, operation_model)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in _send_request
21:27:54     success_response, exception):
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
21:27:54     caught_exception=caught_exception, request_dict=request_dict)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
21:27:54     return self._emitter.emit(aliased_event_name, **kwargs)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
21:27:54     return self._emit(event_name, kwargs)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
21:27:54     response = handler(**kwargs)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
21:27:54     if self._checker(attempts, response, caught_exception):
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
21:27:54     caught_exception)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
21:27:54     return self._checker(attempt_number, response, caught_exception)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
21:27:54     caught_exception)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
21:27:54     attempt_number, caught_exception)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
21:27:54     raise caught_exception
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
21:27:54     http_response = self._send(request)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 244, in _send
21:27:54     return self.http_session.send(request)
21:27:54   File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 289, in send
21:27:54     raise ReadTimeoutError(endpoint_url=request.url, error=e)
21:27:54 botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://ec2.us-east-1.amazonaws.com/"

**Comment by youguanxinqing** [comment]
> What version of boto3/botocore are you using? I'd double check your'e using the latest version. Botocore will catch the `ReadTimeoutError` and raise it's own version so if you're seeing a `ReadTimeoutError` from urllib3 it could mean you're using an old version of botocore that doesn't support read timeouts. I double checked that we are plumbing this value through to urllib3. This is what you should see on the latest version of botocore:
> 
> ```
> Traceback (most recent call last):
>   File "/tmp/a.py", line 5, in <module>
>     client.describe_images()
>   File "botocore/botocore/client.py", line 357, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "botocore/botocore/client.py", line 648, in _make_api_call
>     operation_model, request_dict, request_context)
>   File "botocore/botocore/client.py", line 667, in _make_request
>     return self._endpoint.make_request(operation_model, request_dict)
>   File "botocore/botocore/endpoint.py", line 102, in make_request
>     return self._send_request(request_dict, operation_model)
>   File "botocore/botocore/endpoint.py", line 137, in _send_request
>     success_response, exception):
>   File "botocore/botocore/endpoint.py", line 231, in _needs_retry
>     caught_exception=caught_exception, request_dict=request_dict)
>   File "botocore/botocore/hooks.py", line 356, in emit
>     return self._emitter.emit(aliased_event_name, **kwargs)
>   File "botocore/botocore/hooks.py", line 228, in emit
>     return self._emit(event_name, kwargs)
>   File "botocore/botocore/hooks.py", line 211, in _emit
>     response = handler(**kwargs)
>   File "botocore/botocore/retryhandler.py", line 183, in __call__
>     if self._checker(attempts, response, caught_exception):
>   File "botocore/botocore/retryhandler.py", line 251, in __call__
>     caught_exception)
>   File "botocore/botocore/retryhandler.py", line 277, in _should_retry
>     return self._checker(attempt_number, response, caught_exception)
>   File "botocore/botocore/retryhandler.py", line 317, in __call__
>     caught_exception)
>   File "botocore/botocore/retryhandler.py", line 223, in __call__
>     attempt_number, caught_exception)
>   File "botocore/botocore/retryhandler.py", line 359, in _check_caught_exception
>     raise caught_exception
> botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
> ```

Hi! My dependency is:
```
# pip list|grep boto
boto                     2.49.0
boto3                    1.14.47
botocore                 1.17.47
```

My code is:
