### ISSUE TITLE
default branch changed to develop?

### ISSUE THREAD

**Issue by 0xdabbad00** [boto/botocore#1713]
Looks like the default branch was changed within the past few hours from `master` to `develop`.  I'm not sure what that will impact, but I suspect it was a mistake.

**Comment by jamesls** [comment]
Can you give me more info here?  The `develop` branch has been the default branch ever since we set up botocore 6+ years ago.  AFAIK it's never changed to master.  Where were you seeing the default branch changing?

**Comment by 0xdabbad00** [comment]
If you visit https://github.com/boto/botocore it shows the default ` develop` branch. 
<img width="407" alt="Screen Shot 2019-04-12 at 3 10 20 PM" src="https://user-images.githubusercontent.com/1979334/56066498-2f510700-5d35-11e9-902e-21b0e555b512.png">

Similarly if you run `git remote show origin` it shows `HEAD branch: develop`

I believe the default branch used to be `master` as I check https://github.com/boto/botocore everyday to look at the commits and found it weird when the types of commits were different and then realized the default branch was no longer master.

**Comment by 0xdabbad00** [comment]
I don't think there is a way to see the history of changes to what the default branch is for a repo, but I swore it used to always be `master`.  Feel free to close this ticket, but I just wanted to point it out if it actually did change (as I believe) and the potential impact that could have for people.

**Comment by 0xdabbad00** [comment]
As some data points, it looks like all of the other language SDK's use `master` as their default branch. Example:
- https://github.com/aws/aws-sdk-js
- https://github.com/aws/aws-sdk-java
- https://github.com/aws/aws-sdk-go

**Comment by jamesls** [comment]
Looks like the autoclose label was never removed so this issue fell through the cracks.

Just to reiterate, the default branch in botocore has always been develop, I remember when we set it up years ago :)  Not sure if this was unintentionally changed for a period of time, but as far as I can tell, it was never switched to master, and it's currently on its intended default of "develop."

While this is different from other SDKs, a lot of our tooling relies on this gitflow branch structure.  If this is causing any issues for anyone, please let us know, but for now, this isn't something we plan on changing.

Let me know if you have any more questions.
