### ISSUE TITLE
botocore.config.Config(retries=dict(max_attempts=2)) doesn't work with sts client

### ISSUE THREAD

**Issue by jonassteinberg1** [boto/botocore#1714]
Maybe sts client doesn't work with `Config` yet at all, but the [botocore doc](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html) seems to imply that Config is available to all clients?  Although this [SO article](https://stackoverflow.com/questions/34003350/change-the-number-of-request-retries-in-boto3) seems to imply that this functionality is only available to certain clients...

Anyway:

```
boto3_config = Config(retries=dict(max_attempts=2))

aws_non_federated_account_numbers[section] = boto3.client("sts", config=boto3_config, \
                    aws_access_key_id=aws_access_key_id_val, \
                    aws_secret_access_key=aws_secret_access_key_val).get_caller_identity()["Account"]


### stdout ###

# this error occurs 30 or 50 times or something

Unexpected error: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
```
I think this is probably just because the sts client isn't implemented yet to have a max_attempts, but in case it is then a) what am I doing wrong? or b) is this an issue?

**Comment by joguSD** [comment]
This configuration should apply to all clients. 
Could you post the debug logs showing this?
You can turn them on by adding the following:
```
boto3.set_stream_logger('')
```
