### ISSUE TITLE
Updating model schema manually

### ISSUE THREAD

**Issue by cmenguy** [boto/botocore#1721]
I'm trying to repurpose some parts of botocore for my own API, and was wondering how the JSON files are generated and structured.

I couldn't find any info about it or a script, so I was wondering if this is something that is surfaced publicly or not.

I see the JSON files seem to be updated in a scripted manner in a CI cycle, and was curious if it is possible to expose the script generating those.

**Comment by joguSD** [comment]
The process for generating the models is a pretty deep rabbit hole that we aren't able to share on a public forum like GitHub. Further, the model schema isn't publicly defined and we can't make any guarantees that the schema wont change. This usage isn't really supported so do be careful.

That said, there's no reason you couldn't leverage botocore to do this. I would definitely recommend locking to a specific version of botocore and upgrading with a fair bit of caution. The best documentation we can provide is to look at the models in the SDK and if you have a specific question about something you see, we can probably answer it.
