### ISSUE TITLE
Add paginator for ConfigService select_resource_config

### ISSUE THREAD

**Issue by ajkerrigan** [boto/botocore#1722]
Hello maintainers! I'd like to add paginator support for ConfigService advanced queries (`select_resource_config`). I'm up for submitting a one-off PR (similar to #1520 and others), but I'm wondering if it's better to hold off in favor of a broader coordinated effort like the one proposed by @kapilt in #1462.

In either case I'm happy to pitch in, I get a ton of value out of this SDK :).

**Comment by JordonPhillips** [comment]
We do now have better generation support, but some things may still slip through the cracks for one reason or another. Those misses should go down over time. In the meantime feel free to open a pr if you find something missing.

**Comment by ajkerrigan-mdsol** [comment]
Ok cool, a one-off PR sounds like the best option here then. Thanks @JordonPhillips .
