### ISSUE TITLE
AWS_DEFAULT_PROFILE masks AWS_PROFILE

### ISSUE THREAD

**Issue by samanthaq** [boto/botocore#1725]
If one has both `AWS_DEFAULT_PROFILE` and `AWS_PROFILE` environment variables set in their environment, botocore will prefer the default profile. I believe the intended behaviour is to use `AWS_PROFILE` when set (similar to preferring a `profile` set in the config over the environment variables).

This can be confirmed by running the introduced `functional/test_session.py:test_default_profile_precedence` test from the [associated PR](https://github.com/boto/botocore/pull/1724), or by setting both environment variables to valid aws profiles and calling, e.g., `aws sts get-caller-identity`.

**Comment by joguSD** [comment]
These two environment variables are intended to be interchangeable. Supporting both of these is a result of different AWS SDKs using one vs the other and we've tried to drive consistency by looking at both. At this point, we can't swap the resolution order as that will break any customers who are relying on the fact we resolve the `AWS_DEFAULT_PROFILE` first.

**Comment by samanthaq** [comment]
I understand. Thanks for the quick response.
