### ISSUE TITLE
Broken links in STS' documentation

### ISSUE THREAD

**Issue by michael-k** [boto/botocore#1728]
https://github.com/boto/botocore/blob/e1a1652d5e432dbbcf482216fe16bcd202f845cf/botocore/data/sts/2011-06-15/service-2.json (rendered: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html) contains 12 instances of the following broken link:

- broken link: https://docs.aws.amazon.com/IAM/latest/UserGuide/IAM/latest/UserGuide/access_policies.html#policies_session
- should be: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#policies_session

The duplication of `/IAM/latest/UserGuide` does not appear anywhere else in the code.

The broken link is not specific to botocore, it also appears elsewhere, eg. in sentence “For more information, see Session Policies in the IAM User Guide” at
- https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html
- https://docs.aws.amazon.com/sdkforruby/api/Aws/STS/Client.html#assume_role-instance_method
- https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s_t_s_1_1_s_t_s_client.html

I'd love to open an issue/pull request at the source of this error, but I have no idea where this would be and if it's even open to the public or AWS internal.

**Comment by kyleknap** [comment]
@michael-k Thanks for pointing this out. You are correct. The documentation needs to be updated in our upstream source. I will raise this issue internally so the fix gets propagated to the other SDK documentation as well.

**Comment by swetashre** [comment]
@michael-k - Following up with old issue. It looks like the documentation is fixed here 
https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html

Please let me know if i am missing anything or if i missed any other broken link.
