### ISSUE TITLE
dynamodb.ServiceResource object has no attribute describe_table

### ISSUE THREAD

**Issue by Alonreznik** [boto/botocore#1729]
Hi There.
I'm trying to run a `describe_table` function from dynamodb client, and it raised an error:

`'dynamodb.ServiceResource' object has no attribute 'describe_table'`

My code:

```
import boto3

dynamodb = boto3.client('dynamodb')

dynamodb.describe_table(TableName='myTable')
```

Please advice

Thanks

**Comment by Alonreznik** [comment]
Please ignore.

**Comment by tanishqvyas** [comment]
@Alonreznik Could you explain what was the issue and how did you solve it?

**Comment by Alonreznik** [comment]
Hi @tanishqvyas
I had to upgrade my botocore lib, which madw my problem to be solved.

**Comment by tanishqvyas** [comment]
@Alonreznik To which version exactly?
