### ISSUE TITLE
create_assume_role_refresher has security concerns

### ISSUE THREAD

**Issue by chrisdlangton** [boto/botocore#1743]
referring to the function defined here;
https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L148

The first concern is the function is defining the `refresh` function, which is intended to be defined by user land code. Defining it in botocore internals is dogmatic and user land configurations cannot be defined correctly - i.e. SerialNumber parameter to `assume_role` can be stored as plain text in a profile from the credentials file, but to use MFA you also need the TokenCode parameter. From what i can see, there is no possibel way to use `create_assume_role_refresher` with a Role that has MFA. 
Why is this a big deal? MFA is a security control the AWS Well Architected Framework, CIS benchmarks, PCI DSS 3.2, FedRAMP, HIPPA, (list goes on). There are many times a human is responsible for providing the 6 digit code but in applications that use MFA-enabled IAM Roles the 6 digit code it can be derived from a secret key provided to the application using any form of secrets management tool such as Parameter Store. If any such application is on EC2 using instance profiles, this code will be run and be a bad day for said customer.

The second concern, and I must stress this is a concern also about AWS defined limitation intended as security controls. This is botocore, botocore is a framework with the goal of providing an SDK for the AWS API (Query Request) functionality. The `create_assume_role_refresher` serves as a utility that does not exist in the AWS API capabilities so should also probably not be exposed to user land. Being direct, having this callable by user land code permits downstream to run this code for reason other then the intention it was written (EC2 instance profiles). An example of this being misused is keeping a role being assumed alive beyond the AWS limitation of 1-12hrs.
While I personally write code to circumvent this limitation, that code is an intentional decision I have made after considering my use case and the limitation carefully, Had I known about this function from some guide or supplied public code I might not have ever encountered the 1-12hr limitations, not considered the security implications of circumventing AWS controls.
I urge botocore to consider removing this feature from user land while keeping the code callable for purposes intended (ec2 instance profile).

**Comment by chrisdlangton** [comment]
#https://github.com/boto/botocore/commit/2dae76f52ae63db3304b5933730ea5efaaaf2bfc

**Comment by JordonPhillips** [comment]
To be clear, those are non-documented apis which are not intended to be used directly by end-users. The function referenced is actually not used at all.

For MFA, we do support it but just not with refreshing.

I'm not sure I understand your second point. We're not doing anything to increase the duration of a session. If your permissions to assume a role are revoked in the middle of a session then the refresh will simply fail.

**Comment by chrisdlangton** [comment]
> To be clear, those are non-documented apis which are not intended to be used directly by end-users
It is callable by end users, therefore the implementation failed to meet the intention, should that have been merged? probably not.

> The function referenced is actually not used at all.
Unused functions, not intended for external use, that is a code smell, let's remove it as it was never intended for external use and was never internally used.

> For MFA, we do support it but just not with refreshing.
the `refresh` function is intended to be a user land definition - if the function is not removed from botocore, should botocore really be dogmatic to prevent user land from applying security controls? Therefore is the function remains in botocore it should be either fixed to meet the intention that users should be able to call it, but if users can in fact call it they should be able to define all supported configurations, specifically the ability to apply MFA (a security control) and botocore should not be dogmatic about reducing end user security controls that exist in AWS Well Architected Framework, CIS benchmarks, PCI DSS 3.2, FedRAMP, HIPPA, etc

> I'm not sure I understand your second point. We're not doing anything to increase the duration of a session. If your permissions to assume a role are revoked in the middle of a session then the refresh will simply fail.
refer to my clarity above, this provides the context to my second point.
