### ISSUE TITLE
[docs] Broken link render in docs

### ISSUE THREAD

**Issue by mattsb42** [boto/botocore#1755]
The link to the SSM docs from CloudFormation.create_stack.Parameters.ResolvedValue is failing to render correctly[1]. It looks like the `<code>` block[2] might be breaking the Sphinx render?

[1]
```
Read-only. The value that corresponds to a Systems Manager parameter key. This field is returned only for ` SSM parameter types <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types>`__ in the template.
```

[2] https://github.com/boto/botocore/blob/develop/botocore/data/cloudformation/2010-05-15/service-2.json#L2504

**Comment by stealthycoin** [comment]
Thanks for the find. You're right that code tags do not render inside of anchor tags.

**Comment by mattsb42** [comment]
Nope, still broken.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.create_stack

**Comment by RyanFitzSimmonsAK** [comment]
Closing this issue, as it has been fixed.  Thanks for reporting it!
