### ISSUE TITLE
botocore doesn't observe no_proxy

### ISSUE THREAD

**Issue by inksink** [boto/botocore#1766]
I have set http_proxy && no_proxy in my server(endpoint in no_proxy).
But aws_cli will go through http_proxy, it is strange.

Does botocore not support no_proxy?

**Comment by inksink** [comment]
Hmm it seems that it will only don't support wildcard no_proxy

**Comment by inksink** [comment]
In 1.8.50  botocore/endpoint.py :
`from botocore.vendored.requests.utils import get_environ_proxies`
It works well.

In 1.12.171 botocore/endpoint.py:
`from botocore.utils import is_valid_endpoint_url, get_environ_proxies`
In 1.12.171 botocore/util.py:
`from botocore.vendored.six.moves.urllib.request import getproxies, proxy_bypass`
It doesn't work.
Because this proxy_bypass has bug: it only can use dns wildcard no_proxy like "xxx.cn", but not ".xxx.cn"

**Comment by swetashre** [comment]
@inksink - Sorry for the late reply. As you have mentioned this is happening because of proxy_bypass not supporting dns wildcard i don't know what we can do anything on our end to fix this. Are you still seeing the issue with latest version of CLI ?

**Comment by inksink** [comment]
I found that latest botocore use urllib. And urllib in Python 3.5.2 can not recognize noproxy like ".xxx.com", but Python 3.5.3 works well.
Workaround: add an extra no_proxy "xxx.com" or use Python>3.5.2.

**Comment by swetashre** [comment]
I am glad you got it working. I am closing this issue as this has been resolved. Please let us know if you have any concerns.
