### ISSUE TITLE
[SES] Colon/: in From Address Name triggers "Local address contains illegal character"

### ISSUE THREAD

**Issue by ngandhy** [boto/botocore#1774]
If you use a colon in the name of the sender (NOT email) you get a ClientError(u'An error occurred (InvalidParameterValue) when calling the SendRawEmail operation: Local address contains illegal character',) error.

A colon in the name for the sender should work. 

`FROM = 'DEBUG: Bob <test@test.com>'`

**Comment by stealthycoin** [comment]
This is an error from the service side, we just surface it so this doesn't really have to do with the Python SDK. But colons are not allowed at least from my quick reading of the RFC. You can talk to the service team on the  [SES service forums](https://forums.aws.amazon.com/forum.jspa?forumID=90) if you want to.
