### ISSUE TITLE
security token invalid

### ISSUE THREAD

**Issue by waynehuang13** [boto/botocore#1775]
I'm getting the following error for AWS GovCloud:
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
10:52:06     raise error_class(parsed_response, operation_name)
10:52:06 botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the DescribeTrustedAdvisorChecks operation: The security token included in the request is invalid.

And I've given full permissions of support*, sts:* and trustedadvisor:*.
Anyone know what am I missing?

**Comment by waynehuang13** [comment]
and this is for aws govcloud

**Comment by jamesls** [comment]
It's hard to tell without more information.  How are you getting credentials?  You can enable debug logging via `session.set_debug_logger('')` and it will show you where we're sourcing credentials from.  I'd double check that it's from the location you expect.
