### ISSUE TITLE
Stubber SQS send_message_batch expected param issue

### ISSUE THREAD

**Issue by animaxcg** [boto/botocore#1782]
stubber always expects a "Failed" list for the response of a send_message_batch but AWS doesn't always return the "Failed" list.

**Comment by swetashre** [comment]
@animaxcg - Thank you for your post. I am able to reproduce the problem. Yes AWS doesn't return always a empty failed list but in the [service-2.json](https://github.com/boto/botocore/blob/develop/botocore/data/sqs/2012-11-05/service-2.json#L1200-L1205) file it marked as required field in response . So Stubber expects both list to be input.

I have already contacted the service team to get this fixed.
