### ISSUE TITLE
check_dns_name wrong check for bucket_name

### ISSUE THREAD

**Issue by codezapper** [boto/botocore#1785]
https://github.com/boto/botocore/blob/f0f2050c4d584d506dca842f81e03c794241cca7/botocore/utils.py#L873

The function `check_dns_name` is returning `False` when the length of the bucket name is less than `3`. This means that the check for when the length is equal to `1` will never be performed.

**Comment by swetashre** [comment]
@codezapper - Thank you for your post. Yes you are right this piece of code(https://github.com/boto/botocore/blame/369d2ac70142d07b33855a0fbc3d12132b523c6c/botocore/utils.py#L873) will never get executed.

We will look into get this one fixed.
