### ISSUE TITLE
Consider changing algorithm for generating cache key for assumable role STS creds

### ISSUE THREAD

**Issue by alex** [boto/botocore#1787]
https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L672-L692

The cache key is `sha1()` of the JSON containing the RoleARN and MFA serial (and any other args).

Unfortunately, this logic can be difficult to reproduce in other programming languages, specifically because Python's default `json.dumps()` places spaces after `:` and `,`. Example:

```pycon
>>> json.dumps({"RoleARN": "abc", "MFASerial": "def"}, sort_keys=True)
'{"MFASerial": "def", "RoleARN": "abc"}'
```

In Go for example, there's no real way to get these spaces -- making it difficult to share the cach between Python and Go tools.

A solution to this would be to pass `separators=(',', ':')` to `json.dumps`, this would produce compat output that is compatible with other JSON libraries.

If this is acceptable I'm happy to send a PR. (Note that it would means boto would not sure caches across this version boundary.)

**Comment by swetashre** [comment]
@alex - Thank you for your post. I understand what you are saying but unfortunately we can't pass separators to json.dumps because it can be possible that other libraries or tools may rely on current formatting. So it could lead to breaking change.

**Comment by alex** [comment]
Yes, that's an unavoidable problem (a generalization of the breaking sharing between versions thing I pointed out).

One option would be adding a new parameter somewhere, but that seems like overkill and difficult to wire through to places you'd need it (e.g. `awscli`). So I think just closing this is reasonable.
