### ISSUE TITLE
Assuming role and caching credentials outputs credential expiration with incorrect datetime format

### ISSUE THREAD

**Issue by ylac** [boto/botocore#1808]
Botocore: 1.12.206

When creating a botocore session and assuming a role, the outputted credential expiration datetime is in the incorrect format, eg: `2019-08-13T13:03:59UTC`, which is not a valid ISO 8601 datetime. This causes issues when trying to read the cached credentials using AWS cli, which expects a valid ISO 8601 datetime eg: `2019-08-13T13:03:59Z`.

The code used to create the cached credentials is below:
```
from botocore import credentials
from botocore.session import Session as botocore_Session

bc_session = botocore_Session(profile=aws_profile)
        credential_resolver = bc_session.get_component("credential_provider")
        assume_role_provider = credential_resolver.get_provider("assume-role")
        assume_role_provider.cache = credentials.JSONFileCache(
            os.path.join(os.path.expanduser("~"), ".aws/cli/cache")
        )
        session = Session(profile_name=aws_profile, botocore_session=bc_session)
```

This seems to be the PR that resulted in this issue: https://github.com/boto/botocore/pull/871/files.

The relevant test with an incorrect assertion: https://github.com/boto/botocore/blob/08fd50cdbb9f0dcd079b18696720faaaf583b12a/tests/unit/test_credentials.py#L1956.

https://github.com/boto/botocore/blob/08fd50cdbb9f0dcd079b18696720faaaf583b12a/tests/unit/test_credentials.py#L1971

**Comment by swetashre** [comment]
@ylac - Thank you for your post. I am not able to reproduce the issue. Yes, botocore expiration datetime format is in UTC but i am not getting any error when i run cli command with the cached  credentials. 
Can you please provide me the exact error you are getting ? It would be helpful if you can provide me the debug log.

**Comment by ylac** [comment]
Hi @swetashre, thanks for your response and effort in investigating.

Actually I made a mistake in my initial description. The error occurs in a bash script we use that expects the date to be in ISO 8601 date format.

In any case, the date format is invalid according to: https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC).

We could alter the bash script to handle this date but it'd be nicer if the root cause was addressed.

**Comment by benkehoe** [comment]
This is also a problem when trying to provide credentials to other AWS SDKs via `credential_process`. The Go SDK has a parsing error for expiration in the format `2016-11-06T01:30:00UTC`. This caused me [an error in a library I have to enable AWS SSO integration with other SDKs](https://github.com/benkehoe/aws-sso-credential-process/issues/1). It seems like `botocore.credentials._serialize_if_needed` should have its default as `iso=True`.

**Comment by benkehoe** [comment]
This is fixed by #2250.

**Comment by glenjamin** [comment]
Looks like this issue has been fixed by the above PR, and could be closed now.

I was a little confused by this because upgrading my CLI fixed the bug that this issue described, and it was only by reading all of the comments that I realised the issue state is out of date.

**Comment by benkehoe** [comment]
This issue should stay open, as it's fixed in the CLI v2 code, but those changes are not present in botocore v1. The behavior for the code in the original comment is still the same. I've also opened #2293, I guess that could be considered a duplicate of this issue if it stays open.
