### ISSUE TITLE
How to use generated exceptions

### ISSUE THREAD

**Issue by takeda** [boto/botocore#1814]
So I'm trying to use SSM and catch scenario where value doesn't exist. The call generates `botocore.errorfactory.ParameterNotFound: An error occurred (ParameterNotFound) when calling the GetParameter operation`

The thing is that ParameterNotFound does not exist the class with the error is dynamically generated and I can't reference it in the code (or at least not from `botocore.errorfactory.ParameterNotFound`). What's the point of having exceptions like this when they can't be caught?  Why bothering with dynamically generated class, when you could just have a generic error and inside of its properties I could extract the actual cause. Or is there a way to use it that I'm not aware of?

**Comment by swetashre** [comment]
@takeda - Thank you for your post. Basically this error comes from the service when the requested parameter does not exist. You can see in the [documentation](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameter.html) that what does the error means and what is the cause of this. You can find the root causes in the code for client errors only. 

Hope it helps and please let me know if you have any questions.

**Comment by takeda** [comment]
The problem I'm having is that I can't use such exception in try-except clause, so it has a little of use as an actual exception.

**Comment by swetashre** [comment]
@takeda - Modeled exceptions can be accessed through the client. Instead of ```botocore.errorfactory.ParameterNotFound``` you can do ```client.exceptions.ParameterNotFound```.
```python
client = boto3.client('ssm')

try:
   response = client.get_parameter(Name='sweta')
except client.exceptions.ParameterNotFound as e:
    print(e)
```
 I agree that this is confusing and the current documentation is insufficient. More information on this can be found at this pr: boto/botocore#1113 .

**Comment by swetashre** [comment]
More information on how to catch exceptions with boto3/botocore
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html

Closing this issue as it has been fixed. Please reopen if you have any more concerns.
