### ISSUE TITLE
Issues with botocore.response.StreamingBody iter_lines in AWS Glue Python Shell

### ISSUE THREAD

**Issue by dserrano1524** [boto/botocore#1819]
I am using Boto3 to read the results of my AWS Athena query in a python script.

I have the following code that works fine in AWS Lambda.

```
def get_athena_results(s3_bucket, s3_output_path, execution_id):
    s3client = boto3.client('s3')
    key = s3_output_path + '/' + execution_id + '.csv'
    obj = s3client.get_object(Bucket=s3_bucket, Key=key)
    results_iterator = obj['Body'].iter_lines()
    results = [r for r in results_iterator]
    return results
```

When I run the same function in AWS Glue Python Shell (Not a Spark job), I get the error:

Unexpected error: <class 'AttributeError'>
'StreamingBody' object has no attribute 'iter_lines'

This doesn't make sense to me as the `botocore.response.StreamingBody` class has an `iter_lines` method, and it works fine in AWS Lambda.

https://botocore.amazonaws.com/v1/documentation/api/latest/reference/response.html

**Comment by swetashre** [comment]
@dserrano1524 - Thank you for your post. I am not able to reproduce the issue. Can you please provide us the debug log ? Which version of boto3 and botocore are you using ?
