### ISSUE TITLE
AWS Cost Explorer get_cost_and_usage() LimitExceededException GetCostAndUsage

### ISSUE THREAD

**Issue by anjneeksharma** [boto/botocore#1820]
Hi,

client = boto3.client('ce')
response = client.get_cost_and_usage(TimePeriod={'Start': start, 'End': end},
                                                              Granularity='MONTHLY',
                                                               Metrics=['AmortizedCost'],
                                                              Filter={ 'Tags': { 'Key': tag['Key'], 'Values': [tag['Value'], ] } }

i am calling this function 400 times with different different tag so i am getting exception  LimitExceededException) when calling the GetCostAndUsage operation: Rate limit exceeded 

Please suggest me how can i handle this issue.

**Comment by swetashre** [comment]
@anjneeksharma - Thank you for your post. LimitExceededException occurs when you made too many calls in a short period of time. Can you confirm if its 400 times per second or per minute ? I would recommend try using 10 times per second. 

Hope it helps and please let me know if you have any questions.

**Comment by anjneeksharma** [comment]
@swetashre  Thanks a lot answering my question, there is no specific time just i am calling that function in for loop and that for loop execute 400 times.

**Comment by anjneeksharma** [comment]
so in for loop also i should not call it 400 times do i need to use some wait or something Please suggest me.

**Comment by swetashre** [comment]
@anjneeksharma - The Time Per Second(TPS) granted to each customer is between 1 to 100 based on the real-time traffic. To not receive RateLimitedException, we suggest customer to wait for at least 1 second between every call. 

I would suggest either re-try after 10 second if got throttle message or wait for at least 1 sec between every call. 

Hope it helps.

**Comment by anjneeksharma** [comment]
@swetashre 

Thanks a lot for this much clear cut answer, can you please also confirm this error i am not getting every time.

I got this error only 2 times out of 100 times. can you please confirm why so ?

**Comment by swetashre** [comment]
@anjneeksharma - This depend upon the real time traffic. Limit for GetCostAndUsage is 100TPS shared by customers. So this error basically depends upon the usage by customers. That's why sometimes you are getting error and sometimes not. 

Hope it makes sense to you.
