### ISSUE TITLE
Support custom SSLContext objects

### ISSUE THREAD

**Issue by chrisdlangton** [boto/botocore#1822]
Basically there is this [boto3/issues/1976](https://github.com/boto/boto3/issues/1976) where I asked for there to be PFS (perfect forward secrecy) in boto3, the response is a feature request to add support for a custom `SSLContext` to the `requests.adapters.HTTPAdapter`.

It's been identified the best place to introduce this is in the botocore class `URLLib3Session` because end-users can provide custom botocore session to boto3, and boto3 itself calls `botocore.session.get_session()` when an end-user custom botocore session is not provided.

To see if i might contribute a PR i forked botocore and dug through the codebase to look for usage of `requests.adapters.HTTPAdapter` and i found a very very scary pattern... there are  forked vendored libraries hardcoded in botocore, frozen without patches (including security no patches!!!), particularly i found requests `adapters.py` file, but it has been hacked to pieces and doesn't even represent anything close to what requests actually looks like today...

Putting aside my ranting about some of the worst appsec i've seen in a while.. Just don't ever embed deps in your repos..

So, looking at botocore/httpsession.py class `URLLib3Session` i can tell that this is the enabler of `HTTPAdapter` usage, awesome! good start.

However there is no ability to provide a HTTPAdapter with a custom end-user provided SSLContext, because there is no existence of the ssl context representation in this HTTPAdapter at all... it's not a HTTPAdapter at all close to what urllib3 or requests uses despite the botocore comments...

Moving on. Next i looked for where botocore might call a `create_urllib3_context`, and again i find a method that is called this but is not even close the the _real_ urllib3 method, acording to comments, because _reasons_;

```python
def create_urllib3_context(ssl_version=None, cert_reqs=None,
                           options=None, ciphers=None):
    """ This function is a vendored version of the same function in urllib3

        We vendor this function to ensure that the SSL contexts we construct
        always use the std lib SSLContext instead of pyopenssl.
    """
```

But this isn't true either... Worse, it allows `context.set_ciphers(ciphers or DEFAULT_CIPHERS)` and `DEFAULT_CIPHERS` comes from `urllib3` (Okay i guess... might be better to use the std lib SSL, see below) and `ciphers` is an argument with default `None` as you can see above, but the method `create_urllib3_context` is called by;

```python
class URLLib3Session(object):
    def _get_ssl_context(self):
        return create_urllib3_context()
```

Without giving it any arguments... Meaning the ssl_context provided by `_get_connection_manager` for the `URLLib3Session.send` method only supports ciphers from `urllib3`, not the std ssl lib or a custom provided set of ciphers (ergo this discussion).

Back to looking at the SSLContext, If we follow the imports to understand where exactly we can set the ciphers (assuming python 3.7, you'll see why);

1) `context = SSLContext` from `botocore/httpsession.py` which imports from
```python
try:
    # Always import the original SSLContext, even if it has been patched
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
except ImportError:
    from urllib3.util.ssl_ import SSLContext
```
2a) we follow `urllib3.contrib.pyopenssl.orig_util_SSLContext` to `/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py` which has `orig_util_SSLContext = util.ssl_.SSLContext` which is `/usr/lib/python3/dist-packages/urllib3/util/ssl_.py` import;
```python
try:
    from ssl import SSLContext  # Modern SSL?
except ImportError:
    import sys
    class SSLContext(object):  # Platform-specific: Python 2 & 3.1
    ...
    ...
    ...
```
So `Modern SSL?` line leads us to `2b` from our original content, and we will look at `Platform-specific: Python 2 & 3.1` as `2c`.

2b) Leads us to `/usr/lib/python3.7/ssl.py` awesome :+1: but...

2c) this is the urllib3 `ssl_.py` not the standard SSLContext library written by Bill Janssen. Doing a diff there are 171 vs 57 LOC and nothing is shared at all. It does do 1 thing the std lib doesn'r do, it TypeError's when SSLContext is used by 2.7, 3.2, or earlier versions of Python which did not support setting a custom cipher suite. 2a and 2b will instead ImportError for `import _ssl` even when openssl is installed. interestingly this non-standard SSLContext is it only imported when it is run from Python 2 (all versions it seems) & 3.1 (botocore will not support) therefore with v2 deprecated and EOL in 3 months i'll continue assuming we are running botocore supported python3.3 or higher only.

So, for the task of supporting custom ciphers in a botocore session, we are going to need only to expose the std SSL lib which provides SSLContext, because ciphers are set using the `wrap_socket` method.

**Looking good finally**

3) Let's learn where botocore utilises `wrap_socket` with regards to a `URLLib3Session`. Because `create_urllib3_context` is called from `URLLib3Session._get_ssl_context`. I can see `URLLib3Session` is used in `Endpoint` and interestingly represented as an argument `http_session`, it is also in `EndpointCreator.create_endpoint` (where Endpoint is also used).

So `ClientArgsCreator.get_client_args` seems to be a good place to provide an end-user configurable, let's name it `enforce_pfs`, which essentially instantiates a version of the botocore custom SSLContext using existing methods without deleting or modifying existing arguments. essentially making no side effects to ensure backwards compatibility.

Based on the rules of contributing, i've started the discussion. will push the PR that references this issue.

**Comment by joguSD** [comment]
Just to clear some things up: the vendored versions of `requests` and `urllib3` are not modified as far as I know (they're just *really* old), at least not in any significant capacity. Additionally, recent versions of `botocore` (within the past year or so) have used upstream `urllib3` directly. 

There are a couple copied functions from `urllib3` in `httpsession.py`, this was done to ensure backwards compatibility with how our old http client (vendored requests) used to work in relation to `PyOpenSSL` (we would't used it).

In general, I think we're okay with the feature request here: allow custom SSLContext objects.

**Comment by chrisdlangton** [comment]
>allow custom SSLContext objects
That would be great.. but first botocore needed to use the real urllib3 `create_urllib3_context` or a user supplied SSLContext would be incompatible with botocore...

It looks like there is a major refactor and PR to rid botocore of vendored requests, i'm going to refactor this over that and see what i come up with. Should be able to fit it in soon (big PCI project IRL)

**Comment by chrisdlangton** [comment]
>allow custom SSLContext objects

That would be great.. but first botocore needed to use the real urllib3 `create_urllib3_context` or a user supplied SSLContext would be incompatible with botocore...

It looks like there is a major refactor and PR to rid botocore of vendored requests, i'm going to refactor this over that and see what i come up with. Should be able to fit it in soon (big PCI project IRL)

**Comment by joguSD** [comment]
@chrisdlangton 

The refactor to move away from our vendored requests has already been done. The pending PR is simply removing the vendored dependency.

**Comment by chrisdlangton** [comment]
@joguSD are you saying this (forked) botocore runs vanilla requests? And therefore the urllib3 SSLContext is vanilla also? I.e. the pending PR is just cosmetic?
If this is true.. then I simpl ask if you read the discussion thread in my OP? Because i pseudo-traced the execution stack and _clearly_ explained where this opinion you have is untrue..

**Comment by chrisdlangton** [comment]
@joguSD are you saying this (forked) botocore #1823 runs vanilla requests? And therefore the urllib3 SSLContext is vanilla also? I.e. the pending PR #1829 is just cosmetic?

If this is true.. then I simply ask; did you read my OP?
Because i pseudo traced the execution stack and clearly explain where SSLContext is not the real SSLContext, where it is used now in botocore.
This opinion you have is simply untrue.. Sorry to point that out

**Comment by tachang** [comment]
This is a pretty old issue but it does seem that it is rather difficult to get the SSLContext being used by `boto3`. Unless I am missing something. What led me here was trying to answer the question: what ciphers/algorithms are being used for a boto3 connection.

**Comment by chrisdlangton** [comment]
there were the above PR's created and subsequently ignored until closed to try and get PFS support via SSLContext because it is demonstrated that boto3/botocore/awscli projects all implement dogmatic cipher suites and have no intention to move with the times

**Comment by claweyenuk** [comment]
It does look like develop branch does not use anything vendored anymore, so that changes a lot of things.

I found this issue looking for a way to disable TLS 1.0 and TLS 1.1. This issue may also be relevant: #2488

**Comment by chrisdlangton** [comment]
Closing
As explained here 
https://github.com/boto/boto3/issues/1976
