### ISSUE TITLE
What is the recommended way of checking if a Paginator is empty?

### ISSUE THREAD

**Issue by l1x** [boto/botocore#1824]
I am trying to improve on this code:

```python
def list_objects_in_s3(s3_client, s3_bucket, s3_object_prefix):
    paginator = s3_client.get_paginator('list_objects')
    filters = { 'Bucket': s3_bucket,
                'Prefix': s3_object_prefix }
    page_iterator = paginator.paginate(**filters)
    ret = []
    for page in page_iterator:
        if page.get('Contents',None):
            for content in page.get('Contents'):
                ret.append(content['Key'])
    return ret
```

Is there a way to do this better? I guess I could just return the paginator to the caller and iterate over there. Maybe use yield? I hope that somebody has some idiomatic way of doing this.

**Comment by swetashre** [comment]
Thank you for your post. The code you provided will return a empty list if the paginator does not contain any items. You can use [can_paginate](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.can_paginate) if you want to know whether the operation is pageable or not.  

Hope it helps and please let me know if you are asking for something else or i am understanding your question wrong.

**Comment by l1x** [comment]
Thanks @swetashre this is exactly I was looking for.  I wanted to collapse the following to a nested list comprehension but that fails. With can_paginate I can make it work though.

```Python
    for page in page_iterator:
        if page.get('Contents',None):
            for content in page.get('Contents'):
                ret.append(content['Key'])
```

**Comment by djsmith42** [comment]
This might help. I noticed that each page has a `KeyCount` key, which tells you how many S3 objects are contained in each page. So if the first page from the paginator has a `KeyCount` of `0`, then you know it's empty.

Like this:

```python
paginator = client.get_paginator('list_objects_v2')
for page in paginator.paginate(Bucket='my-bucket', Prefix='my-prefix'):
  if page['KeyCount'] == 0:
    continue # empty page (should be the only page in the paginator)
