### ISSUE TITLE
Spelling of parameter is wrong in the following places

### ISSUE THREAD

**Issue by mmontagna** [boto/botocore#1828]
https://github.com/boto/botocore/pull/1827

**Comment by swetashre** [comment]
@mmontagna - Thank you for your post. This file comes from upstream. I will let the service team know about the issue and make sure it will get fixed.

**Comment by mmontagna** [comment]
Thanks @swetashre !

**Comment by swetashre** [comment]
I have already let the service team know about the issue. I am closing this issue as this issue is related to service and service team is aware about this.

**Comment by swetashre** [comment]
This issue is now fixed.
