### ISSUE TITLE
Incorrect Route 53 Resolver documentation

### ISSUE THREAD

**Issue by mikkopiu** [boto/botocore#1831]
On the `route53resolver` documentation: https://github.com/boto/botocore/blob/29a293441704742c40e9b73755c2b1e27d5cd143/botocore/data/route53resolver/2018-04-01/service-2.json#L1614
it says:
> Get the IP addresses for the Resolver endpoints: get-resolver-endpoint --resolver-endpoint-id [resolver_endpoint_id]

**but** that endpoint does not return the IP addresses: https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverEndpoint.html

I believe it should instead be `list-resolver-endpoint-ip-addresses`: https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ListResolverEndpointIpAddresses.html

**Comment by swetashre** [comment]
@mikkopiu - Thank you for your post. Yes, you are right. We will look into get this fixed.
