### ISSUE TITLE
ACM TagList shape has incorrect minimum number of 1

### ISSUE THREAD

**Issue by dudebout** [boto/botocore#1836]
The [TagList shape in the ACM model](https://github.com/boto/botocore/blob/develop/botocore/data/acm/2015-12-08/service-2.json#L1110) has an incorrect minimum number of one element:
```
   "TagList":{
     "type":"list",
     "member":{"shape":"Tag"},
     "max":50,
     "min":1
   },
```
This is a problem for example for [ListTagsForCertificate](https://github.com/boto/botocore/blob/develop/botocore/data/acm/2015-12-08/service-2.json#L116), whose output shape is [ListTagsForCertificateResponse](https://github.com/boto/botocore/blob/develop/botocore/data/acm/2015-12-08/service-2.json#L847):
```
   "ListTagsForCertificateResponse":{
     "type":"structure",
     "members":{
       "Tags":{
         "shape":"TagList",
         "documentation":"<p>The key-value pairs that define the applied tags.</p>"
       }
     }
   },
```
but certificates do not always have tags.

**Comment by swetashre** [comment]
@dudebout - Thank you for your post. This file comes from upstream and i have already let the service team know about the issue.
