### ISSUE TITLE
Use XDG Base Directory Specification

### ISSUE THREAD

**Issue by pierreprinetti** [boto/botocore#1839]
The [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines where configuration files and credential files should be placed.

Following this standard ensures a clean home directory and some consistency across applications.

The default directory to _write_ configuration and credentials files should be `${XDG_CONFIG_HOME:-${HOME}/.config}/aws` (or `%LOCALAPPDATA%\aws\config`).

The default directory to _read_ configuration and credentials files should be `${XDG_CONFIG_HOME:-${HOME}/.config}/aws` (or `%LOCALAPPDATA%\aws\config`) first, then `${HOME}/.aws` to maintain backwards compatibility.

What do you think?

I am willing to file a change request if this design is accepted.

I hope the Windows values make some sense, as I am not an expert.

cf. https://github.com/aws/aws-cli/issues/2433

**Comment by pierreprinetti** [comment]
This proposal does not change the default override logic: the [environment variables](https://docs.aws.amazon.com/en_pv/cli/latest/userguide/cli-configure-envvars.html) `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` should maintain their precedence, just like the specific environment variables and command-line switches that refer to specific keys like `AWS_ACCESS_KEY_ID` or `--region <string>`.

The proposed change only affects the hardcoded default fallback locations.

**Comment by joguSD** [comment]
@pierreprinetti In general, I don't think we're against this change it's simply been more of a priority issue than anything else. There's a relatively high amount of friction in making a change like this as botocore and the AWS CLI aren't the only tools that look at these files. If we make this change it puts pressure on other tools to follow suite. To be blunt, we likely won't have much time to look into this anytime soon as it's functionally the same and there are workarounds (mentioned in the other thread) if one is really inclined on getting this behavior.

**Comment by pierreprinetti** [comment]
If this was possible with a small change (and I am not sure it is), would you accept a PR that:
* **on the write side**: does _not_ change where the credentials are created; but
* **on the read side**: looks into `~/.aws` _and_ into the XDG directory?

**Comment by tim-finnigan** [comment]
This feature request is now being tracked here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/30. Feature requests involving credentials/configuration need to be reviewed at a cross-SDK level, since other SDKs rely on those in addition to he CLI. Will close this issue to continue tracking there.
