### ISSUE TITLE
Rare failure to use IAM role credentials from instance metadata

### ISSUE THREAD

**Issue by rtkrruvinskiy** [boto/botocore#1840]
Python version: PyPy 6.0.0 with GCC 6.2.0 20160901
OS: Ubuntu 16.04.5 LTS
botocore version: 1.12.92

We bring up EC2 instances that use an IAM role for their credentials. Very rarely, we observe a situation when an instance comes up and starts up a service process (using systemd if that matters), and the services's AWS calls (specifically S3 HEAD requests) repeatedly fail with 403 response codes. Running a pcap against 169.254.169.254, I see frequent GET requests to /latest/meta-data/iam/security-credentials/<role_name>. The credentials in the responses are valid -- if I force the use of the credentials from the pcap using environment variables, the S3 operation works just fine. However, the service process continuously gets 403's and continuously refreshes credentials. As soon as I restart the service, the problem resolves itself.

I've reviewed the botocore changelog and saw some fixes for issues for fetching credentials from instance metadata in 1.12.20 (https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#11220), but we're running 1.12.92. (Also, FWIW, we run boto3 1.9.92.) I'd appreciate a pointer on how to investigate this issue further.

**Comment by swetashre** [comment]
@rtkrruvinskiy - Thank you for your post. Can you please provide me the exact error you are getting with the debug log ? Are you getting 403 response code when using any other service or this happens only with s3 ? You can enable debug log by adding ```boto3.set_stream_logger('')``` to your code.
