### ISSUE TITLE
ResourceGroupsTaggingAPI for AWS Neptune

### ISSUE THREAD

**Issue by tsiq-shiv** [boto/botocore#1843]
AWS Docs say that resource groups tagging API support AWS Neptune, however it does not work and returns with an `InvalidParameterException`
How to replicate:
`aws resourcegroupstaggingapi get-resources --resource-type-filters neptune-db` ->
```
An error occurred (InvalidParameterException) when calling the GetResources operation: Unsupported service=neptune-db in ResourceTypeFilter - neptune-db:
```

Running boto3 1.9.247 and botocore 1.12.247

**Comment by swetashre** [comment]
@tsiq-shiv - Thank you for your post. Neptune uses the same ARN format as RDS as defined here: https://docs.aws.amazon.com/neptune/latest/userguide/tagging.ARN.html

So you can use ```rds``` as ```--resource-type-filters``` to get neptune instances.

**Comment by tsiq-shiv** [comment]
Thanks!
