### ISSUE TITLE
Count/ScannedCount Result Keys for DynamoDB Scan not Iterable (Pagination)

### ISSUE THREAD

**Issue by HieronymusLex** [boto/botocore#1859]
When attempting to use `result_key_iters` for page iteration, the following error is thrown for DynamoDB scan operations: `TypeError: 'int' object is not iterable L676 in botocore/paginate.py`

The error is caused by the `result_keys` for the DDB Scan operation containing Count and ScannedCount in the [DDB pagination model](https://github.com/boto/botocore/blob/develop/botocore/data/dynamodb/2012-08-10/paginators-1.json#L32). [The paginator](https://github.com/boto/botocore/blob/develop/botocore/paginate.py#L676) expects all the value of a result key to be an iterable object, whereas Count/ScannedCount are of type `int`.

Happy to raise a PR for this to remove these keys if that's the correct fix, however I want to be sure it's not a usage error on my part first!

Here is a little script with which you can reproduce the issue:

```
import boto3

def paginate(client, method, **kwargs):
    paginator = client.get_paginator(method.__name__)
    for page in paginator.paginate(**kwargs).result_key_iters():
        for result in page:
            yield result

if __name__ == '__main__':
    client = boto3.client("dynamodb")
    results = paginate(client, client.scan, **{
        'TableName': "YOUR_DDB_TABLE_NAME"
    })
 
    for result in results:
        print(result)
```

**Comment by swetashre** [comment]
@HieronymusLex - Thank you for your post. The ```result_key_iters``` operation is specifically used for aws cli and this can't be used the way you are using. That's why you are getting error as it will be trying to iterate through every value including integer. 

This is the documentation for how to use paginator with boto3:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/paginators.html

you can use something like this:
```python
import boto3

client = boto3.client("dynamodb")
paginator = client.get_paginator('scan')
page_iterator = paginator.paginate(TableName='Music')
for page in page_iterator:
     print(page['Items'])  #to list only the item values otherwise you can do print(page)


```

Hope it helps and please let me know if you have any questions.

**Comment by HieronymusLex** [comment]
@swetashre I still think there is an issue here which is missing a unit test. If you look at the tests for `result_key_iters` it only caters for a scenario where 1 `result_key` is present in the paginator definition, and where that result_key is of type list.

https://github.com/boto/botocore/blob/7ab300620eff73ff82bdade4115ccbe94322cfc4/tests/unit/test_paginate.py#L693

If you added a test to cover multiple result keys where one of the result keys is of type `int` (as is the case in the Dynamo paginator), then it test fails e.g.

```
class TestKeyIterators(unittest.TestCase):
    def setUp(self):
        self.method = mock.Mock()
        self.model = mock.Mock()
        # This is something we'd see in DDB pagination.
        self.paginate_config = {
            "output_token": "Marker",
            "input_token": "Marker",
            "result_key": ["Users", "Count"] # added multiple keys as with DDB Scan
        }
        self.paginator = Paginator(self.method, self.paginate_config, self.model)

    def test_non_list_result_key_iters(self):
        responses = [
            {"Items": ["User1"], "Marker": "m1", "Count": 1},
            {"Items": ["User2"], "Marker": "m2", "Count": 1},
            {"Items": ["User3"], "Count": 1},
        ]
        self.method.side_effect = responses
        pages = self.paginator.paginate()
        iterators = pages.result_key_iters()
        self.assertEqual(len(iterators), 2) # updated as there are 2 result keys now
        self.assertEqual(list(iterators[0]),
                         ["Item1", "Item2", "Item3"])
        self.assertEqual(list(iterators[1]), [1, 1, 1]) # throws error
```

The same `TypeError: 'int' object is not iterable` is thrown when running this test. The existing test for `result_key_iters` only covers 1 result key with type list

Also, I couldn't find any instances of this method being used in boto3 or the CLI?

**Comment by stobrien89** [comment]
Hi @HieronymusLex,

Really sorry for the delayed response on this!  I don't think anything is missing in terms of the paginator model or a missing unit test.  These classes/methods were added in [this commit](https://github.com/boto/botocore/commit/2cb105b03239ac1e6a79dc77d9946869c158c682) to add support for providing multiple input tokens, which (as far as I know), only apply to certain s3 operations.
