### ISSUE TITLE
GlueVersion ParamValidationError

### ISSUE THREAD

**Issue by sema4-yunrougong** [boto/botocore#1862]
I try to update existing glue job by specify the GlueVersion parameter and got the following exception error:
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in JobUpdate: "GlueVersion", must be one of: Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, WorkerType, NumberOfWorkers, SecurityConfiguration, NotificationProperty

In the Documentation of AWS and Boto3,  said there is a pramater called GlueVersion;
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html

Please solve this issue.

**Comment by swetashre** [comment]
@sema4-yunrougong - Thank you for your post. This error generally comes if you are using older version of botocore. Please make sure you are using newer version of boto3 and botocore. You can update version by using ```pip install botocore --upgrade```.

If you are still getting the error even after upgrading your boto3 and botocore version , provide me the full debug log. You can enable log by adding ```boto3.set_stream_logger('')``` to your code.

**Comment by sema4-yunrougong** [comment]
Thanks so much. resolved.

**Comment by swetashre** [comment]
I am closing the issue as it has been resolved.

**Comment by kiranreddyfiza** [comment]
ParamValidationError: Parameter validation failed:. Note: This run was executed with Flex execution. Check the logs if run failed due to executor termination.

I am getting this error, BTW I am using latest version of boto3. Could you help me here
