### ISSUE TITLE
A subsequent request after a 100-expect failed requests fails incorrectly.

### ISSUE THREAD

**Issue by theanalyst** [boto/botocore#1863]
If a PUT request fails with a 4XX status where expect headers are set, then the next request if the same socket is reused seems to fail with the same 401 status even though the server actually responds with say a 200. We have a test case in test_aws_request.py test_state_reset_on_connection_close which seems to explicitly close the socket, though if the server actually responds without a Connection: close, then due to keepalives, when we read the next response we seem to incorrectly read the previous response

**Comment by theanalyst** [comment]
This behaviour isn't seen in most S3 regions as many of them return an explicit Connection:Close on 4XX statuses, though if that isn't done (as the specs do not mention close on error) and the connection is kept-alive, then you'd run into the next response being read incorrectly by httplib

**Comment by theanalyst** [comment]
I've some sort of code (tested against ceph-radosgw) which demonstrates the behaviour, 
https://gist.github.com/theanalyst/161d21767a78d2a9b4487c722aa6ea1a 

with asyncio aiohttp (which probably doesn't use python's httplib?) a reused TCP connection that sends a 4XX status and later success status seemed to work as expected, 
a boto client with a 400 (or any 4XX status) will actually raise an exception on the first successful request (wireshark logs show a 200) though requests after that will work as expected

aws-sdk-go also succeeds similar to aiohttp, and the network logs clearly in all cases show a 2XX status which boto seems to incorrectly parse.

 While aws services may force a Connection: Close header on 4XX status, nothing on the rfc or the api specs actually require this behaviour, so nothing prevents the socket from being kept open (provided the connection:close wasn't explicitly sent by the server) for services, so it is just a client error that hasn't been spotted yet

**Comment by swetashre** [comment]
@theanalyst - Thank you for your post. I would mark this as enhancement.

**Comment by swetashre** [comment]
@theanalyst - Thank you for providing detailed information on this issue. I will mark this as enhancement.

**Comment by theanalyst** [comment]
the issue still exists on a recent check
