### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by and-semakin** [boto/botocore#1869]
It looks like `botocore` is one of the most used Python packages according to the PyPI stats. And it lacks of PEP 484 type hints. I'm pretty sure that adding it here will evolve all the Python ecosystem, make it more usable, static code analyzers will become more smart and will help us write better code.

I see that `typeshed` repo already [has annotations for `boto`](https://github.com/python/typeshed/tree/master/third_party/2and3/boto) package but not for `boto3` or `botocore`. By the way it is preferable for packages to store and distribute type hints themselves, not via `typeshed`.

What do you think? Does adding type hints worth the effort?

**Comment by swetashre** [comment]
@and-semakin - Thank you for your post. We are already tracking this feature request under the github issue [#1725](https://github.com/boto/boto3/issues/1725). We also have a repo(https://github.com/boto/botostubs) supporting them but that is not recommended to use yet.

**Comment by swetashre** [comment]
I am closing this issue as a duplicate. Let's track the progress of this issue under the linked GitHub issue [#1725](https://github.com/boto/boto3/issues/1725)
