### ISSUE TITLE
Drop support for EOL Python 2.6 and Python 3.3

### ISSUE THREAD

**Issue by and-semakin** [boto/botocore#1873]
Python 2.6 reached its EOL in October, 2013. Python 3.3 reached its EOL in September, 2017. I guess that usage of `botocore` on this platform is really low (see [PyPI stats](https://pypistats.org/packages/botocore)). Is there a reason why `botocore` has to support this versions?

**Comment by swetashre** [comment]
@and-semakin - Thank you for your post. We are dropping support for Python 2.6 and Python 3.3. This blog post contains all the details : 
https://aws.amazon.com/blogs/developer/deprecation-of-python-2-6-and-python-3-3-in-botocore-boto3-and-the-aws-cli/

Hope it helps.

**Comment by and-semakin** [comment]
Yep, thank you! I think this issue may be closed :)
