### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by bgreen-litl** [boto/botocore#1885]
Referencing `collections.MutableMapping` rather than `collections.abc.MutableMapping` triggers a deprecation warning.

    >>> import botocore
    >>> botocore.__version__
    '1.13.15'
    >>> import collections
    >>> collections.MutableMapping
    __main__:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

The reference occurs here:
https://github.com/boto/botocore/blob/develop/botocore/awsrequest.py#L624

**Comment by kamikaze** [comment]
+1

**Comment by swetashre** [comment]
@bgreen-litl - Thank you for your post. Botocore moved off of using the vendored requests a while ago, it's only kept in for backwards compatibility of certain exceptions.

Currently botocore doesn't make any use of it but there is a warning added for customer that we are taking it away soon. This issue is related to botocore issue #1615

This PR contains every detail about the issue:
https://github.com/boto/botocore/pull/1829

**Comment by clifflu** [comment]
It seems to be a different issue as I got the same Deprecation Warning from [awsrequest.py:624](https://github.com/boto/botocore/blob/c2e337e3b0fd35e54f2f6b2b6a67dbb469fee0c9/botocore/awsrequest.py#L624) , not the vendored requests. botocore.__version__ = '1.13.16'

Changing

```
class HeadersDict(collections.MutableMapping):
...
```

to 

```
try:
    from collections.abc import MutableMapping
except ModuleNotFoundError:
    from collections import MutableMapping

class HeadersDict(MutableMapping):
...
```

fixes this warning and is pythonic IMHO. Pytest will then throw the same DeprecationWarning from [session.py:947](https://github.com/boto/botocore/blob/c2e337e3b0fd35e54f2f6b2b6a67dbb469fee0c9/botocore/session.py#L947) instead.

I can create a PR for it if you like : )

**Comment by bgreen-litl** [comment]
@clifflu is correct. This is not in the vendored requests module.  I had reviewed both #1615 and PR #1829 before filing this.  The deprecation warning I posted is coming from the botocore lib itself, not the older version of requests in the vendored directory.

**Comment by MihaiBojin** [comment]
I'm also seeing this error:

```
.../site-packages/botocore/awsrequest.py:624: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class HeadersDict(collections.MutableMapping):
```

**Comment by swetashre** [comment]
Sorry for the late reply. We are working on a fix for it. I will update here when it will be fixed.

**Comment by kapilt** [comment]
this pr thats been around for a few weeks will fix it https://github.com/boto/botocore/pull/1865

**Comment by terencehonles** [comment]
@swetashre perhaps you want to merge #1865 as @kapilt mentioned? It's a pretty small/simple change.

**Comment by swetashre** [comment]
Now i am not getting error with this code : 
```python
In [5]: import botocore                                                                                                

In [6]: botocore.__version__                                                                                           
Out[6]: '1.13.44'

In [7]: import collections                                                                                             

In [8]: collections.MutableMapping                                                                                     
Out[8]: collections.abc.MutableMapping
```
Please let me know if anyone is still getting the error. This issue is fixed with the merge of PR https://github.com/boto/botocore/pull/1922
