### ISSUE TITLE
Missing   required ContentMD5 PutBucketLifecycleConfigurationRequest on  botocore/botocore/data/s3/2006-03-01/service-2.json 

### ISSUE THREAD

**Issue by byterock** [boto/botocore#1888]
on 
https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json

this patch 

```
   "PutBucketLifecycleConfigurationRequest":{
      "type":"structure",
      "required":["Bucket","ContentMD5"],
      "members":{
+        "ContentMD5":{
+          "shape":"ContentMD5",
+          "documentation":"<p>Addeed autmatically by Paws</p>",
+          "location":"header",
+          "locationName":"Content-MD5"
+        },
        "Bucket":{
          "shape":"BucketName",
          "documentation":"<p/>",
          "location":"uri",
          "locationName":"Bucket"
        },
        "LifecycleConfiguration":{
          "shape":"BucketLifecycleConfiguration",
          "documentation":"<p/>",
          "locationName":"LifecycleConfiguration",
          "xmlNamespace":{"uri":"http://s3.amazonaws.com/doc/2006-03-01/"}
        }
      },
      "payload":"LifecycleConfiguration"
    },

```

will fix this errorl

`<Error><Code>InvalidRequest</Code><Message>Missing required header for this request: Content-MD5</Message><RequestId>B7CD91DC3BD5BB7B</RequestId><HostId>Vo5tNdYxG8rNLPcts9BkBssLuEHE6yFvIL4w1UUSs12hskouiGNS/zHtbtSS7K3l1YeYKo70Wq4=</HostId></Error>`

when one makes the call.

I also asked AWS to update thier docs as this is not a manditory field or enven mentioned there

**Comment by swetashre** [comment]
@byterock - Thank you for your post. I am able to use ```put_bucket_lifecycle_configuration``` api without specifying Content-MD5. Can you please provide me a code sample what you are using when you get error with the debug logs ? You can enable log by adding ```boto3.set_stream_logger('')``` to your code.

**Comment by byterock** [comment]
Actully has nothing to do with with the CLI it is missing  or boto3

We use boto to generate our classes in Perl, Raku, and D  adding the  'ContentMD5' fixes the problem.

I think the AWS Doc is wrong (https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html) as it does not sate the field is required in the header.  

As for exmaple in https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html

The CLI from my reading of the code sends the 'ContentMD5' on all requests hence it is not a problem for the CLI, I beleive the JAVA does the same.

We would like to avoid sending it when not required.

**Comment by swetashre** [comment]
@byterock - Sorry for the late reply. Can you please give me a code sample what you are using so that i can reproduce the issue ? 

According to this code ```PutBucketLifecycleConfiguration``` use Content-MD5 in header 
https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L947
https://github.com/boto/botocore/blob/543853505ad800956008cca317fdb06f8a627938/botocore/handlers.py#L187

 It would be very helpful if you can provide me the code sample and debug log so that i can reproduce the issue.

**Comment by byterock** [comment]
Ok 

As I stated earlier there is no problem with the python code or the CLI as Py adds in the MD5 header.

The problem is with Boto.  

The MD5 header is required by the call but Boto says it is not.

Use 'Boto' to generate our classess for  Perl, Raku, and D code bases thus when we generate our classes we are missing the field and thus the call will faill.


If it helps this is the Perl generated class  

`package Paws::S3::PutBucketLifecycleConfiguration;
  use Moose;
      has Bucket => (is => 'ro', isa => 'Str', uri_name => 'Bucket', traits => ['ParamInURI'] , required => 1);
      has LifecycleConfiguration => (is => 'ro', isa => 'Paws::S3::BucketLifecycleConfiguration'  );
  use MooseX::ClassAttribute;
  class_has _namspace_uri => (isa => 'Str', is => 'ro', default => 'http://s3.amazonaws.com/doc/2006-03-01/');
  class_has _api_call => (isa => 'Str', is => 'ro', default => 'PutBucketLifecycleConfiguration');
  class_has _api_uri  => (isa => 'Str', is => 'ro', default => '/{Bucket}?lifecycle');
  class_has _api_method  => (isa => 'Str', is => 'ro', default => 'PUT');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::API::Response');
  class_has _result_key => (isa => 'Str', is => 'ro');

1;`

when the 'ContentMD5'  is missing and  failing.  

This

`package Paws::S3::PutBucketLifecycleConfiguration;
  use Moose;
      has Bucket => (is => 'ro', isa => 'Str', uri_name => 'Bucket', traits => ['ParamInURI'] , required => 1);
      has LifecycleConfiguration => (is => 'ro', isa => 'Paws::S3::BucketLifecycleConfiguration'  );

  has ContentMD5 => (is => 'ro', isa => 'Str', header_name => 'Content-MD5', auto => 'MD5', traits => ['AutoInHeader'] );

  use MooseX::ClassAttribute;
  class_has _namspace_uri => (isa => 'Str', is => 'ro', default => 'http://s3.amazonaws.com/doc/2006-03-01/');
  class_has _api_call => (isa => 'Str', is => 'ro', default => 'PutBucketLifecycleConfiguration');
  class_has _api_uri  => (isa => 'Str', is => 'ro', default => '/{Bucket}?lifecycle');
  class_has _api_method  => (isa => 'Str', is => 'ro', default => 'PUT');
  class_has _returns => (isa => 'Str', is => 'ro', default => 'Paws::API::Response');
  class_has _result_key => (isa => 'Str', is => 'ro');

1;`

is the working generated code when the JSON patch is added into BOTO.


As you point out this should not cause a problem with the Python code as you by defuault add that MD5 in there.  This change to boto will greatly help in getting our Perl, Raku and D code working correctly.

**Comment by swetashre** [comment]
@byterock -  This has to be updated by s3 team on their model and have that get propagated down to us. So i will recommend contacting the service team either on their [forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) or you can create a ticket to AWS Support.

**Comment by byterock** [comment]
Ok will see if I can have any luck there. 

I will close this one for you
