### ISSUE TITLE
IoT Service : ConfirmTopicRuleDestination operation, Request URI typo

### ISSUE THREAD

**Issue by Cox65** [boto/botocore#1896]
https://github.com/boto/botocore/blob/ae41ef199de6b8acaf9bbaaded83716a601d8d68/botocore/data/iot/2015-05-28/service-2.json#L259

Looks there is a typo for "ConfirmTopicRuleDestination" operation. The requestUri contains a "+" for confirmationToken parameter.

**Comment by swetashre** [comment]
@Cox65 - Thank you for your post. I contacted the service team as this file comes from upstream and according to the service team It is not a typo. The uri should be: "/confirmdestination/{confirmationToken+}"
