### ISSUE TITLE
cfnresponse could not be used after the botocore version 1.13.0

### ISSUE THREAD

**Issue by tp6m4fu6250071** [boto/botocore#1909]
Hi, 

I'm using the python package cfnresponse ( https://pypi.org/project/cfnresponse/ ) to implement Custom Resources in CloudFormation. And I would like to use EKS create_nodegroup ( https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.create_nodegroup ) in the Lambda code. I know this attribute is only supported in the latest version of boto3.
However, I found the latest botocore version 1.13.* conflicts with cfnresponse.
If I use the botocore version 1.13.*, cfnresponse will show the error message when sending response to CFN:
send(..) failed executing requests.put(..): 'module' object has no attribute 'put' 

These my testing versions:
1) keep encountering the error message "send(..) failed executing requests.put(..): 'module' object has no attribute 'put'" when sending response to CFN:

Experiment 1:
boto3.__version__ ---> 1.10.34
botocore.__version__ ---> 1.13.34

Experiment 2:
boto3.__version__ ---> 1.9.0
botocore.__version__ ---> 1.13.34

2) However, if the botocore version is too old, it doesn't have the attribute create_nodegroup of EKS:

Traceback (most recent call last):
  File "/var/task/index.py", line 34, in handler
    response = client.create_nodegroup(
  File "/var/task/botocore/client.py", line 601, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'EKS' object has no attribute 'create_nodegroup'

Experiment 3:
boto3.__version__ ---> 1.10.0
botocore.__version__ ---> 1.12.253

Experiment 4:
boto3.__version__ ---> 1.10.34
botocore.__version__ ---> 1.12.253

3) Has both error:

Experiment 5:
boto3.__version__ ---> 1.10.34
botocore.__version__ ---> 1.13.0

**Comment by tp6m4fu6250071** [comment]
Sorry I found a related issue here: https://github.com/awslabs/aws-cloudformation-templates/issues/196

**Comment by gmagella-ca** [comment]
This issue was closed with the other one, and no solution has been implemented. There's a deadline to implement changes from the message:

> This dependency was removed from Botocore and will be removed from Lambda after 2020/03/31.

Can we get this re-opened?
