### ISSUE TITLE
S3Control Listjobs Param name do not match the AWS Spect

### ISSUE THREAD

**Issue by byterock** [boto/botocore#1924]
All of the 'locationName' attributes for the 'ListJobsRequest'  are out of sync with the current AWS API and Docs

For exmaple

``
 "JobStatuses":{
          "shape":"JobStatusList",
          "documentation":"<p>The <code>List Jobs</code> request returns jobs that match the statuses listed in this element.</p>",
          "location":"querystring",
          "locationName":"jobStatuses"
        },``

the "locationName":"jobStatuses"  should be "locationName":"JobStatuses"

according this this API doc

https://docs.aws.amazon.com/AmazonS3/latest/API/API_control_ListJobs.html

> Request Syntax

GET /v20180820/jobs?JobStatuses=JobStatuses&MaxResults=MaxResults&NextToken=NextToken HTTP/1.1
x-amz-account-id: AccountId

for exmaple this direct call will work

https://11111111111.s3-control.us-east-1.amazonaws.com/v20180820/jobs?NextToken=dddd&JobStatuses=Active%2CCancelled%2CCancelling%2CComplete%2CCompleting%2CFailed%2CFailing%2CNew%2CPaused%2CPausing%2CPreparing%2CReady%2CSuspended&MaxResults=5

while this call will fail

https://1111111111.s3-control.us-east-1.amazonaws.com/v20180820/jobs?jobStatuses=Active%2CCancelled%2CCancelling%2CComplete%2CCompleting%2CFailed%2CFailing%2CNew%2CPaused%2CPausing%2CPreparing%2CReady%2CSuspended&maxResults=5&nextToken=dddd'

**Comment by swetashre** [comment]
@byterock - Thank you for your post. As this file comes from upstream, i have already let the team know about the issue. I will post here when i get any update.
