### ISSUE TITLE
RFE: store resource files compressed

### ISSUE THREAD

**Issue by danbst** [boto/botocore#1926]
I've noticed that `data` directory is 39Mb. I think it can be compressed with e.g. zstd and decompressed on the fly, without large performance penalties, but with 7x size reduction (up to 5.3Mb):
```
$ cat lib/python3.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json | pv >/dev/null
1.52MiB 0:00:00 [1.19GiB/s] [  <=>                                                                                                             ]

$ cat lib/python3.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json | zstd -9 - > /tmp/compressed-services.json.zstd

$ ls -lh /tmp/compressed-services.json.zstd 
-rw-r--r-- 1 danbst users 148K гру 28 03:01 /tmp/compressed-services.json.zstd

$ cat /tmp/compressed-services.json.zstd | zstd -d - | pv > /dev/null
1.52MiB 0:00:00 [ 474MiB/s] [  <=>                                                                                                             ]
```
Perhaps this should only be done for python package, but source should be left in JSON.

**Comment by dacut** [comment]
I suspect the performance penalty will be larger than you expect. This decompression would be done when a client is initially created, which is frequent when boto is instantiated from a shell (e.g. AWS CLI). From my interactions with customers, there are a number of folks who rely on the AWS CLI (perhaps more than they should) because the shell is all they know.

Also, note that this saves ~25 MB in disk space (only). When installed over the network (`pip3 install botocore`), the package is transferred in ZIP format.

Do you have measurements on what the performance penalty is (e.g., in Lambda)?

**Comment by danbst** [comment]
@dacut Sorry, no real tests, I just found that this package is one of largest on my node. I've made a test with `timeit`. With plain JSON:
```
In [33]: print(timeit.timeit('loaders.JSONFileLoader().load_file("botocore/data/ec2/2016-11-15/service-2")', setup="import botocore.loaders as loaders",number=1000))                                                                                                                  
19.12820653000381
```
With zstd decompress:
```
In [32]: print(timeit.timeit('loaders.JSONFileLoader().load_file("botocore/data/ec2/2016-11-15/service-2")', setup="import botocore.loaders as loaders",number=1000))                                                                                                                  
20.060755500977393
```
I'm very surprised zstd decompress adds very little time. Maybe there is performance bottleneck in JSON parsing.

The patch used is:
```
index 24f47a63..a61c2701 100644
--- a/botocore/loaders.py
+++ b/botocore/loaders.py
@@ -104,6 +104,8 @@ which don't represent the actual service api.
 import os
 import logging
 
+import zstd
+
 from botocore import BOTOCORE_ROOT
 from botocore.compat import json
 from botocore.compat import OrderedDict
@@ -163,14 +165,14 @@ class JSONFileLoader(object):
         :return: The loaded data if it exists, otherwise None.
 
         """
-        full_path = file_path + '.json'
+        full_path = file_path + '.json.zst'
         if not os.path.isfile(full_path):
             return
 
         # By default the file will be opened with locale encoding on Python 3.
         # We specify "utf8" here to ensure the correct behavior.
         with open(full_path, 'rb') as fp:
-            payload = fp.read().decode('utf-8')
+            payload = zstd.loads(fp.read()).decode('utf-8')
             logger.debug("Loading JSON file: %s", full_path)
             return json.loads(payload, object_pairs_hook=OrderedDict)
```

**Comment by dacut** [comment]
Interesting. I get similar results (a tad slower; 20 msec and 21 msec) on my likely more dated laptop (MacBookPro11,3; 2.3 GHz i7-4850HQ). It's not really adding anything significant, though it does point out potential slowness in JSON processing. Hmm...

My only (very minor, and happy to defer to others here) concern is that zstd requires the use of a binary-compiled library, which is sometimes problematic; currently, `pip3 install boto3` installs on systems that don't have a C compiler installed. Using a `gzip -8` compressed JSON file (220 kB vs 214 kB for EC2's service-2.json) does slow it down more (26 msec); `gzip -1` doesn't affect decompression time, but does make a larger file (304 kB).

**Comment by dacut** [comment]
In case you're curious: pickling (instead of JSON) reduces the file load time for zstd from 21 msec to 13 msec on my laptop.

**Comment by danbst** [comment]
yeah, pickle+zlib is an optimization on both sides - performance and disk size.

Another disk space hole is in number of data files. 1116 files in total. Given that each occupies an FS block (on ext4), it results into 2Mb overhead:
```
[danbst@station:~/dev/botocore/botocore/data]$ du -sc --si .
45M     .
45M     total

[danbst@station:~/dev/botocore/botocore/data]$ du -scb .
42907818        .
42907818        total
```

Making one large archive will remove this overhead:
```
$ du -sch data*
43M     data
5,3M    data.zip
3,9M    data.zst
```
If there was a way to use both `pickle`+`zipfile` styled entries, it would also reduce time to load, yeah.

**Comment by swetashre** [comment]
I don't think this issue is a SDK issue. We use this GitHub for tracking bug and feature request related to botocore. I am closing this issue. Please reopen if you have any concerns.
