### ISSUE TITLE
botocore42?

### ISSUE THREAD

**Issue by alexlatchford** [boto/botocore#1930]
Sorry for the bug report, wasn't sure where else to post this.

Searching for "botocore" on PyPI comes up with `botocore42` as the first result: https://pypi.org/project/botocore42/ See [here](https://pypi.org/search/?q=botocore).

From what I can tell this has no relation to the official `botocore`, might want to check on the status of that project with PyPI. Got me a little confused, wondered if this was a new version I should be using.

**Comment by swetashre** [comment]
@alexlatchford - Thank you for your post and thanks for letting us know. This [botocore42](https://pypi.org/project/botocore42/) is not mentioned by AWS. We will see what we can do to remove that package from pypi.

**Comment by swetashre** [comment]
It looks like this package is no longer present in pypi. Closing this issue as it has been resolved. Please let us know if you have any more concerns.
