### ISSUE TITLE
LexModelBuildingService Exceptions do not pull information from response body

### ISSUE THREAD

**Issue by DeanGaffney** [boto/botocore#1937]
# Issue
The order to delete all resources associated with a lex bot you must do the following:
* Delete all aliases associated with a bot in order to delete the bot itself
* Delete the bot in order to delete intents
* Delete intents in order to delete slot types
* Delete slot types

If you attempt to delete a lex resource which references another lex resource a `ResourceInUseException` is returned. The response body from AWS is in the following format:
```json
{
    "exampleReference": {
        "name": "mycoolbotalias",
        "version": null
    },
    "referenceType": "BotAlias"
}
```
The above AWS response was from attempting to delete a Lex bot when an alias existed for the bot. Botocore prints out the following when the `ResourceInUseException` is throw:
```
An error occurred (ResourceInUseException) when calling the DeleteBot operation:
```
As you can there's no information about the alias which must first be deleted to delete the bot, but the documentation states that if this exception is throw you will be given a reference to the resource that needs to be deleted. This can be seen here https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/lex-models.html#LexModelBuildingService.Client.delete_slot_type

I believe the issue is coming from some inconsistency in the Lex API, as botocore looks for any error messages in the body under a `message` or `Message` key, which in this case is not being returned. This can be seen in the BaseJsonParser class here https://github.com/boto/botocore/blob/develop/botocore/parsers.py#L602
```python
error['Error']['Message'] = body.get('message',
                                             body.get('Message',''))
```
As you can see if nothing is found the message is set to an empty string, a quick solution I mocked up locally to get around this, was to add the body as the default value if the `message` or `Message` key does not exist.
```python
error['Error']['Message'] = body.get('message',
                                             body.get('Message', body))
```
Running the code above results in the following being printed out:
```
An error occurred (ResourceInUseException) when calling the DeleteBot operation: {'exampleReference': {'name': 'mycoolbotalias', 'version': None}, 'referenceType': 'BotAlias'}
```

This issue is also in the aws cli (with current code)
![image](https://user-images.githubusercontent.com/9123129/72205644-6cd9f080-347d-11ea-9c87-861aad0ba35f.png)

With proposed code:
![image](https://user-images.githubusercontent.com/9123129/72205648-8e3adc80-347d-11ea-973c-28c4671b05c8.png)

If you are happy with this solution I can open a pull request with this change, if there is another solution you would prefer, please let me know. 

Thanks!

**Comment by swetashre** [comment]
Thank you for your post. Marking this as feature request for adding support for modeled exceptions. If you are interested in implementing modeled exceptions then you can submit a PR for it. 
Adding the body to the exception is not the correct thing to do here.

**Comment by DeanGaffney** [comment]
Hi @swetashre, thank you for the response! I definitely agree, that adding the body to the exception is not the correct thing to do here and modeled exceptions would be better suited for this. I am interested in implementing this feature, but I am relatively new to the botocore codebase. Is there a particular way in which you would see modeled exceptions being implemented within botocore? Some discussion around this would be really appreciated.
