### ISSUE TITLE
provide structured Protocol definitions

### ISSUE THREAD

**Issue by dazza-codes** [boto/botocore#1940]
If there is a way to auto-generate structured Protocol support [1], please do; e.g. a partial `Protocol` is defined for AWS batch client in Apache Airflow [2].  I don't understand enough about how botocore is dynamically generated from JSON-API specs, but if it's possible to add `Protocol` support into these dynamic generators, it could really help python development with this library.  One of the problems with the library is that many of the generated objects have no easy support for introspections, such as `isinstance`, and exception handling; maybe the `Protocol` approach could help with this?

[1] https://www.python.org/dev/peps/pep-0544/
[2] https://github.com/apache/airflow/blob/master/airflow/providers/amazon/aws/hooks/batch_client.py#L50

PS, the `Protocol` typing could help IDE support and `mypy` type checking; it would be awesome if `Protocol` definitions could solve inspections like this too (but this may not be the target of protocol definitions at runtime).

```
import botocore.session
session = botocore.session.get_session()
s3_client = session.create_client('s3', region_name='us-east-1')
type(s3_client) # -> botocore.client.S3
isinstance(s3_client, botocore.client.S3)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-6b77c1057909> in <module>
----> 1 isinstance(s3_client, botocore.client.S3)

AttributeError: module 'botocore.client' has no attribute 'S3'
```

**Comment by swetashre** [comment]
@dazza-codes - Thank you for your post. Marking this as feature request. We are using stubs instead of protocol for this purpose. We have a working implementation of boto3 type stubs, its located here: https://github.com/boto/botostubs. Its not production ready yet but you can see our approach at least and how it should work. 
It still needs some work and of course tests. Feel free to send PRs to that repo if you would like to contribute.

**Comment by dazza-codes** [comment]
Just checked, did not add any unit tests on the protocol used in Airflow
- https://github.com/apache/airflow/blob/master/tests/providers/amazon/aws/hooks/test_batch_client.py
