### ISSUE TITLE
Automatic retry fails if Comprehend returns 400 TooManyRequestsException

### ISSUE THREAD

**Issue by woolinsilver-kainos** [boto/botocore#1946]
We are trying to invoke `start_entities_detection_job` on the Comprehend client.

The default quota prevents more than 10 of these invocations per second.

If we exceed this quota, sometimes Comprehend will respond `429` `ThrottlingException`, which boto handles correctly.

However, sometimes Comprehend will instead respond `400` `TooManyRequestsException`, and boto will not attempt any retry.

This smells very much like a bug in Comprehend.
However, we are forced to wrap boto's error handling in our own, to work around this problem.

Here is what we expect to see, when boto is handling automatic retry:
```
{ 
   'Error':{ 
      'Message':'Rate exceeded',
      'Code':'ThrottlingException'
   },
   'ResponseMetadata':{ 
      'RequestId':'794d8a71-be8d-4f78-a515-50ddb2ae21d9',
      'HTTPStatusCode':429,
      'HTTPHeaders':{ 
         'x-amzn-requestid':'794d8a71-be8d-4f78-a515-50ddb2ae21d9',
         'content-type':'application/x-amz-json-1.1',
         'content-length':'58',
         'date':'Mon, 20 Jan 2020 13:04:41 GMT'
      },
      'MaxAttemptsReached':True,
      'RetryAttempts':1
   }
}
```

Here is the less frequent case, which boto is not handling:
```
{
   'Error':{
      'Message':'ACTIVE_JOB_COUNT_LIMIT_EXCEEDED: Active job limit for this account is 10.',
      'Code':'TooManyRequestsException'
   },
   'ResponseMetadata':{
      'RequestId':'ad8c563a-5cc6-4d55-8cfc-41fdf2b2fdfd',
      'HTTPStatusCode':400,
      'HTTPHeaders':{
         'x-amzn-requestid':'ad8c563a-5cc6-4d55-8cfc-41fdf2b2fdfd',
         'content-type':'application/x-amz-json-1.1',
         'content-length':'123',
         'date':'Mon, 20 Jan 2020 13:07:22 GMT',
         'connection':'close'
      },
      'RetryAttempts':0
   }
}
```

We can repro' this quite easily, by:
- configuring maximum retries very low, e.g. 1 retry
- despatching 20 requests concurrently, using a Python ThreadPoolExecutor
- examining the exceptions thrown by boto

The first bunch of requests will succeed, as they're within the quota.

If you're lucky, Comprehend will give `429` for the others, and boto will handle everything.
Because maximum retry was set low, you will see ThrottlingException, once boto has tried to retry and failed.

If you're unlucky, Comprehend will give `400` for at least one of them, and boto will immediately fail, it will not attempt any retry.

**Comment by woolinsilver-kainos** [comment]
Note that Comprehend's own documentation on errors is incorrect.
https://docs.aws.amazon.com/comprehend/latest/dg/CommonErrors.html

That document says `ThrottlingException` is status code `400`, but it is actually (and correctly) `429`.

The document doesn't say anything at all about `TooManyRequestsException` !

**Comment by swetashre** [comment]
@woolinsilver-kainos - Thank you for your post. Marking this as enhancement.
