### ISSUE TITLE
ECR Throwing Exception "ValueError: Waiter does not exist: image_scan_complete"

### ISSUE THREAD

**Issue by Millerborn** [boto/botocore#1947]
note sure if I'm missing something basic but I'm getting an unexpected waiter error. This is my code,

```python
import boto3

client = boto3.client('ecr')
waiter = client.get_waiter('image_scan_complete')
waiter.wait(
    registryId='account-Id',
    repositoryName='repo-name',
    imageId={
        'imageTag': 'image-tag'
    },
    maxResults=123,
    WaiterConfig={
        'Delay': 5,
        'MaxAttempts': 20
    }
)
```

When I run my script locally it throws the `ValueError: Waiter does not exist: image_scan_complete.`
But without the waiter, I can get the scan data from my image using the same ( registryId=, repoName=, ...) config through `client.describe_image_scan_findings` 

This is the whole error I recieved,
```bash
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    waiter = client.get_waiter('image_scan_complete')
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 823, in get_waiter
    raise ValueError("Waiter does not exist: %s" % waiter_name)
ValueError: Waiter does not exist: image_scan_complete
```

again, not sure if I have something misconfigured or if this is a bug

**Comment by swetashre** [comment]
@Millerborn - Thank you for your post. This change was introduced in botocore version 1.13.46. So if you are using botocore version older than 1.13.46 then this can be the cause of error. Can you please let me know which version of botocore are you using ? Please try running the code by using latest boto3 and botocore version.

**Comment by Millerborn** [comment]
Hi @swetashre thanks for the quick reply. I was using botocore version 1.13.26, a quick update fixed the problem!
