### ISSUE TITLE
alternate resource loaders for model files

### ISSUE THREAD

**Issue by mattsb42-aws** [boto/botocore#1950]
I've been poking around trying to use PyOxidizer[1] to create a self-contained binary for a project of mine that uses boto3. Unfortunately, because PyOxidizer (and most other similar tools) load Python modules from memory rather than a filesystem, the model file loading that botocore and boto3 do for the built-in models breaks when you attempt to load anything.

I've been digging into this, and the simplest solution I've been able to come up with to create a branching path in the model loaders: if running in (iirc) CPython 3.7+, we can use a `ResoureLoader` to load data files contained in a Python module. On older versions of CPython and for custom models in `$AWS_DATA_PATH` we would still need the file loader, but this would remove the need for the relative filepath loading that botocore/boto3 currently do.

The way I've been thinking this would manifest is to take `Loader`[2] and turn it into a wrapper on top of two new loaders: a `FileLoader` that works everywhere but only looks at the extra search paths, and (depending on Python version) either a `FileLoader` that does what the current `Loader` does but only for the built-in model files or a `MemoryLoader` that loads the built-in models directly from memory via `ResourceLoader`s.

There is one caveat to this: doing this would require sprinkling `__init__.py` files throughout all directories in `data`, to turn them into Python modules from which data can be loaded.

boto3 would need similar changes for the loaders and data files that it uses.

Is this a change that you all would be interested in? Any additional concerns that I should keep in mind if I start hacking on this?

[1] https://pyoxidizer.readthedocs.io
[2] https://botocore.amazonaws.com/v1/documentation/api/latest/reference/loaders.html?highlight=model#botocore.loaders.Loader.load_service_model

**Comment by swetashre** [comment]
Thank you for the post. Currently we are not willing to make these changes unless there is a strong need for it.  
For now it is possible to create a self contained binary with PyInstaller. Here is the link : 
https://github.com/aws/aws-cli/blob/v2/scripts/installers/make-exe
