### ISSUE TITLE
Intermittent  NoCredentialsError('Unable to locate credentials') error

### ISSUE THREAD

**Issue by AndreyMatveyev** [boto/botocore#1965]
The application reads a small S3 object and parses it. The functionality is part of simple Web service. In the course of 10 minutes, under the moderate and constant load, the application throws an error "NoCredentialsError('Unable to locate credentials')" on call to s3_client.get_object().

python interpreter: 3.6.8
OS: amazon-linux
boto3==1.11.9
AWS Credentials mode: AWS IAM role based security
The application runs on AWS EKS 1.14 in K8s pods as Docker containers. There is no sidecar containers for these pods. 

The rate of failures: One out of 100 calls fails with named above error
I have found a post that reports about the same issue: [Boto intermittent “unable to load credentials” with EC2 IAM roles](https://stackoverflow.com/questions/58210314/boto-intermittent-unable-to-load-credentials-with-ec2-iam-roles/60199286#60199286)

Example of the code that fails:

```
def get_job_status(job_id):
    job_status_aws_bucket_region = app_config['job_status_aws_bucket_region']
    job_status_aws_bucket_name = app_config['job_status_aws_bucket_name']

    s3_session = boto3.Session(region_name=job_status_aws_bucket_region)
    s3_client = s3_session.client('s3')

    # The point of failure
    response = s3_client.get_object(
        Bucket=job_status_aws_bucket_name,
        Key=job_id
    )

    job_record = json.loads(response['Body'].read().decode('utf-8'))

    result = {
        'jobId': job_record.get('job_id'),
        'jobLifeStatus': job_record.get('job_life_status'),
        'jobProcessingStatus': job_record.get('job_processing_status'),
        'createdTime': job_record.get('created_time'),
        'completionTime': job_record.get('completion_time'),
    }

    return result

```

ERROR log:
`ERROR 2020-02-05 02:44:22 svc_controller.py {'error': NoCredentialsError('Unable to locate credentials',), 'module': 'svc_controller', 'error_id': 'a4dee180-bbd0-441c-8d47-3be1a71727ea', 'error_datetime': datetime.datetime(2020, 2, 5, 2, 44, 22, 837650, tzinfo=datetime.timezone.utc), 'extra_info': None, 'tt': <class 'botocore.exceptions.NoCredentialsError'>, 'value': NoCredentialsError('Unable to locate credentials',), 'tb_list': ['Traceback (most recent call last):', ' File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request\n rv = self.dispatch_request()', ' File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request\n return self.view_functions[rule.endpoint](**req.view_args)', ' File "/usr/local/job-status/svc_controller.py", line 87, in get_job_status\n job_status = svc_provider.get_job_status(job_id)', ' File "/usr/local/job-status/svc_provider.py", line 126, in get_job_status\n Key=job_id', ' File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 276, in _api_call\n return self._make_api_call(operation_name, kwargs)', ' File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 573, in _make_api_call\n operation_model, request_dict, request_context)', ' File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 592, in _make_request\n return self._endpoint.make_request(operation_model, request_dict)', ' File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request\n return self._send_request(request_dict, operation_model)', ' File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request\n request = self.create_request(request_dict, operation_model)', ' File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request\n operation_name=operation_model.name)', ' File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit\n return self._emitter.emit(aliased_event_name, **kwargs)', ' File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit\n return self._emit(event_name, kwargs)', ' File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit\n response = handler(**kwargs)', ' File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler\n return self.sign(operation_name, request)', ' File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 160, in sign\n auth.add_auth(request)', ' File "/usr/local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth\n raise NoCredentialsError', 'botocore.exceptions.NoCredentialsError: Unable to locate credentials']}`

**Comment by swetashre** [comment]
@AndreyMatveyev - Thank you for your post. Can you please provide me full debug logs. You can enable log by adding ```boto3.set_stream_logger('')``` to your code.

**Comment by AndreyMatveyev** [comment]
We have applied a workaround (retry on error) and it will take time to rollback to the old code and reproduce it in our QA environment. Taking into account the long weekend, in the worst-case scenario we'll provide the log by 02/19

**Comment by Phandora** [comment]
Hi!

I'm having the same issue since a few weeks ago.

- **Code that fails:**
```
def decrypt_data_key(data_key_encrypted, region_name):

    """
    Decrypt an encrypted data key
    :param data_key_encrypted: Encrypted cyphertext data key.
    :param region_name: KMS region
    """

    # Decrypt the data key
    client = boto3.client('kms', region_name=region_name)
    try:
        response = client.decrypt(CiphertextBlob=data_key_encrypted)
    except ClientError as e:
        print(e)
        return None

    # Return plaintext base64-encoded binary data key
    return base64.b64encode((response['Plaintext']))
```

- **Error log:**
```
  File "/docker/src/decrypt.py", line 62, in decrypt_data_key
    response = client.decrypt(CiphertextBlob=data_key_encrypted)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 613, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 632, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
- **Versions:**

  - _boto3_:                    1.12.2
  - _botocore_:              1.15.2

It happens just as @AndreyMatveyev mentioned, the error happens intermittently and its frequency is low. 

We usually solve it by restarting the affected pod.

**Comment by biroeng** [comment]
I have same problem 

File "/usr/local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by Renganath-cloud** [comment]
> I have same problem
> 
> File "/usr/local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
> raise NoCredentialsError
> botocore.exceptions.NoCredentialsError: Unable to locate credentials
> 
> some traces:
> 
> The full traceback is:
> Traceback (most recent call last):
> File "/home/forgerock/.ansible/tmp/ansible-tmp-1586574098.7921138-226906948196708/AnsiballZ_ec2_instance.py", line 102, in
> _ansiballz_main()
> File "/home/forgerock/.ansible/tmp/ansible-tmp-1586574098.7921138-226906948196708/AnsiballZ_ec2_instance.py", line 94, in _ansiballz_main
> invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
> File "/home/forgerock/.ansible/tmp/ansible-tmp-1586574098.7921138-226906948196708/AnsiballZ_ec2_instance.py", line 40, in invoke_module
> runpy.run_module(mod_name='ansible.modules.cloud.amazon.ec2_instance', init_globals=None, run_name='**main**', alter_sys=True)
> File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
> return _run_module_code(code, init_globals, run_name, mod_spec)
> File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/tmp/ansible_ec2_instance_payload_325opghg/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py", line 1710, in
> File "/tmp/ansible_ec2_instance_payload_325opghg/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py", line 1681, in main
> File "/tmp/ansible_ec2_instance_payload_325opghg/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py", line 1302, in find_instances
> File "/usr/local/lib/python3.6/site-packages/botocore/paginate.py", line 322, in search
> for page in self:
> File "/usr/local/lib/python3.6/site-packages/botocore/paginate.py", line 255, in **iter**
> response = self._make_request(current_kwargs)
> File "/usr/local/lib/python3.6/site-packages/botocore/paginate.py", line 332, in _make_request
> return self._method(**current_kwargs)
> File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
> return self._make_api_call(operation_name, kwargs)
> File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 613, in _make_api_call
> operation_model, request_dict, request_context)
> File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 632, in _make_request
> return self._endpoint.make_request(operation_model, request_dict)
> File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
> return self._send_request(request_dict, operation_model)
> File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
> request = self.create_request(request_dict, operation_model)
> File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
> operation_name=operation_model.name)
> File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
> return self._emitter.emit(aliased_event_name, **kwargs)
> File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
> return self._emit(event_name, kwargs)
> File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
> response = handler(**kwargs)
> File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
> return self.sign(operation_name, request)
> File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 160, in sign
> auth.add_auth(request)
> File "/usr/local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
> raise NoCredentialsError
> botocore.exceptions.NoCredentialsError: Unable to locate credentials
> fatal: [laptop]: FAILED! => {
> "changed": false,
> "module_stderr": "Traceback (most recent call last):\n File "/home/forgerock/.ansible/tmp/ansible-tmp-1586574098.7921138-226906948196708/AnsiballZ_ec2_instance.py", line 102, in \n _ansiballz_main()\n File "/home/forgerock/.ansible/tmp/ansible-tmp-1586574098.7921138-226906948196708/AnsiballZ_ec2_instance.py", line 94, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File "/home/forgerock/.ansible/tmp/ansible-tmp-1586574098.7921138-226906948196708/AnsiballZ_ec2_instance.py", line 40, in invoke_module\n runpy.run_module(mod_name='ansible.modules.cloud.amazon.ec2_instance', init_globals=None, run_name='**main**', alter_sys=True)\n File "/usr/lib64/python3.6/runpy.py", line 205, in run_module\n return _run_module_code(code, init_globals, run_name, mod_spec)\n File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code\n mod_name, mod_spec, pkg_name, script_name)\n File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code\n exec(code, run_globals)\n File "/tmp/ansible_ec2_instance_payload_325opghg/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py", line 1710, in \n File "/tmp/ansible_ec2_instance_payload_325opghg/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py", line 1681, in main\n File "/tmp/ansible_ec2_instance_payload_325opghg/ansible_ec2_instance_payload.zip/ansible/modules/cloud/amazon/ec2_instance.py", line 1302, in find_instances\n File "/usr/local/lib/python3.6/site-packages/botocore/paginate.py", line 322, in search\n for page in self:\n File "/usr/local/lib/python3.6/site-packages/botocore/paginate.py", line 255, in **iter**\n response = self._make_request(current_kwargs)\n File "/usr/local/lib/python3.6/site-packages/botocore/paginate.py", line 332, in _make_request\n return self._method(**current_kwargs)\n File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call\n return self._make_api_call(operation_name, kwargs)\n File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 613, in _make_api_call\n operation_model, request_dict, request_context)\n File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 632, in _make_request\n return self._endpoint.make_request(operation_model, request_dict)\n File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request\n return self._send_request(request_dict, operation_model)\n File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request\n request = self.create_request(request_dict, operation_model)\n File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request\n operation_name=operation_model.name)\n File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit\n return self._emitter.emit(aliased_event_name, **kwargs)\n File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit\n return self._emit(event_name, kwargs)\n File "/usr/local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit\n response = handler(**kwargs)\n File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler\n return self.sign(operation_name, request)\n File "/usr/local/lib/python3.6/site-packages/botocore/signers.py", line 160, in sign\n auth.add_auth(request)\n File "/usr/local/lib/python3.6/site-packages/botocore/auth.py", line 357, in add_auth\n raise NoCredentialsError\nbotocore.exceptions.NoCredentialsError: Unable to locate credentials\n",
> "module_stdout": "",
> "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
> "rc": 1
> }



So wht is the fix - Please let me know

**Comment by JoeZ99** [comment]
same here.
  - several (from 2 to 10) ec2 instances with a role that has `S3FullAccess` policy, to make sure it's not a policies issue
  - botocore==1.17.26
  - linux ubuntu

the instances upload or retrieve feeds from s3

sporadically, "credentials not found" error. 

anybody knows a workaround???

**Comment by ninedigits** [comment]
I was having the same issue. It seems to have resolved by passing in boto3.Session in for read/writing data to S3.
