### ISSUE TITLE
add error code to exception classes

### ISSUE THREAD

**Issue by kapilt** [boto/botocore#1976]
currently given an exception instance/class there isn't a straightforward way to map it back to its exception code. the errorfactory should just annotate this on to the class.

```python
import boto3
client = boto3.clients('sqs')
err = client.exceptions.QueueDoesNotExist
# looking for error code hypothetically, this doesn't work, but currently looking for
err.code == 'AWS.SimpleQueueService.NonExistantQueue'
# the only way to map it back at the moment is the following requires poking at private implementation details.
err_map = {v: k for k, v in client.exceptions._code_to_exception.items()}
err_map[err] ==  'AWS.SimpleQueueService.NonExistantQueue'
```

**Comment by zdutta** [comment]
Hello @kapilt, for instantiated errors, you should be able to map them back to the error code. From the error, you can use the response attribute to get the code.
```
response["Error"].get('Code', 'Unknown')
```
(similarly done [here](https://github.com/boto/botocore/blob/develop/botocore/exceptions.py#L413))
Are you looking for a way to access the code without receiving a response? Trying to gauge the use case in which adding a class attribute is necessary.
