### ISSUE TITLE
No "host" field in HTTP header in https proxy session

### ISSUE THREAD

**Issue by siradori** [boto/botocore#1981]
With the assumption, the https connection with proxy has a session to use "CONNECT" method.
"CONNECT" method is available in http since version 1.1.
>(https://tools.ietf.org/html/rfc7231#section-4)

However, in botocore, the https connection with "CONNECT" use HTTP/1.0
This problem is caused by Python's standard library
(the pull and request are already sent to github: https://github.com/python/cpython/pull/8305)
In addion to that, there is no "Host" field in https session in Botocore in spite of the description in RFC7230 that "Host" field is required in HTTP/1.1.
>A client MUST send a Host header field in all HTTP/1.1 request messages.

It causes the failure of proxy routing.

**Comment by siradori** [comment]
Hi.
I've actually tried it with the AWS CLI, so you can see it.

This screenshot is the result of a packet capture of the `aws s3 ls` command.
![noHostHeader](https://user-images.githubusercontent.com/954771/79105686-1c3f9f80-7dac-11ea-8d44-7e48d26698ec.png)

And this screenshot is another CONNECT METHOD packet capture.
![HostHeader](https://user-images.githubusercontent.com/954771/79106381-5a898e80-7dad-11ea-93cc-31126421ae92.png)

The host field must be included like this.

Some proxy servers use a "host field" for proxy-to-proxy forwarding on multiple proxies, which causes proxy-to-proxy forwarding to fail.

Therefore, AWS CLI is not available in this environment.

**Comment by stobrien89** [comment]
Hi @siradori,

My apologies for the lack of response on this.  Thanks for bringing it to our attention!  This was reported to us in [#2846](https://github.com/boto/boto3/issues/2846) (boto3) as well— I think this is a more appropriate place to track it, given the shared functionality between the CLI and Boto3. 

There were some concerns about about race conditions in multi-threaded environments where the wrong host header may be sent, with regard to the current methods available to resolve this using urllib3, but I'll see if I can get the team's thoughts on your PR.
