### ISSUE TITLE
Invalid Header value in request for credentials

### ISSUE THREAD

**Issue by LeonardAukea** [boto/botocore#2001]
It seems like the Generated header based on credentials includes `\n` characters. I'm pretty sure this is a bug. 

```
botocore.exceptions.HTTPClientError: An HTTP Client raised and unhandled exception: Invalid header value b'AWS4-HMAC-SHA256 Credential=-n ACCESS_KEY\n/00000000/eu-west-1/athena/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=XXXXXXXXXX'
```

**Comment by swetashre** [comment]
@LeonardAukea - Thank you for your post. I would need some more information in order to debug the issue. How have you configured credentials ? Can you provide code sample you are using ? It would be helpful if you could provide me debug log. You can enable log by adding ```boto3.set_stream_logger('')``` to your code.

**Comment by LeonardAukea** [comment]
@swetashre  understandable, the credentials are picked up as envs `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` by boto3. In addtion to the providing the workgroup in the below func `query`

```
import argparse
import json
import logging
import time
import re

import boto3


def get_client(region=None):
    """Builds a client to the AWS Athena API."""
    client = boto3.client("athena", region_name=region)
    return client


def query(client, query, database, output, workgroup=None):
    """Executes an AWS Athena query."""
    params = dict(
        QueryString=query,
        QueryExecutionContext={"Database": database},
        ResultConfiguration={"OutputLocation": output,},
    )
    if workgroup:
        params.update(dict(WorkGroup=workgroup))

    response = client.start_query_execution(**params)

    execution_id = response["QueryExecutionId"]
    logging.info("Execution ID: %s", execution_id)

    # Athena query is aync call, we need to fetch results and wait for execution
    state = "RUNNING"
    max_execution = (
        5  # TODO: this should be an optional parameter from users. or use timeout
    )

    while max_execution > 0 and state in ["RUNNING"]:
        max_execution = max_execution - 1
        response = client.get_query_execution(QueryExecutionId=execution_id)

        if (
            "QueryExecution" in response
            and "Status" in response["QueryExecution"]
            and "State" in response["QueryExecution"]["Status"]
        ):
            state = response["QueryExecution"]["Status"]["State"]
            if state == "FAILED":
                raise Exception("Athena Query Failed")
            elif state == "SUCCEEDED":
                s3_path = response["QueryExecution"]["ResultConfiguration"][
                    "OutputLocation"
                ]
                # could be multiple files?
                filename = re.findall(".*\/(.*)", s3_path)[0]
                logging.info("S3 output file name %s", filename)
                break
        time.sleep(5)

    # TODO:(@Jeffwan) Add more details.
    result = {
        "total_bytes_processed": response["QueryExecution"]["Statistics"][
            "DataScannedInBytes"
        ],
        "filename": filename,
    }

    return result
```

I'll look through the debug log and see if I find anything interesting.  Although, it does not look correct that `\n` is in the generated header `ACCESS_KEY\n`
```
 b'AWS4-HMAC-SHA256 Credential=-n ACCESS_KEY\n/XXXXXXXX/eu-west-1/athena/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=XXXXXXXXXX'
```

**Comment by swetashre** [comment]
In your case a new line is getting appended at the end of env vars. Are you using any tool to manage the credentials ? 

Have you tried passing credentials directly during client creation ?

**Comment by LeonardAukea** [comment]
@swetashre they are being picked up from a kubernetes secret using the following pattern.

```
def use_aws_secret(secret_name='aws-secret', aws_access_key_id_name='AWS_ACCESS_KEY_ID', aws_secret_access_key_name='AWS_SECRET_ACCESS_KEY'):
    """An operator that configures the container to use AWS credentials.
        AWS doesn't create secret along with kubeflow deployment and it requires users
        to manually create credential secret with proper permissions.
        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: aws-secret
        type: Opaque
        data:
          AWS_ACCESS_KEY_ID: BASE64_YOUR_AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: BASE64_YOUR_AWS_SECRET_ACCESS_KEY
    """

    def _use_aws_secret(task):
        from kubernetes import client as k8s_client
        (
            task.container
                .add_env_variable(
                    k8s_client.V1EnvVar(
                        name='AWS_ACCESS_KEY_ID',
                        value_from=k8s_client.V1EnvVarSource(
                            secret_key_ref=k8s_client.V1SecretKeySelector(
                                name=secret_name,
                                key=aws_access_key_id_name
                            )
                        )
                    )
                )
                .add_env_variable(
                    k8s_client.V1EnvVar(
                        name='AWS_SECRET_ACCESS_KEY',
                        value_from=k8s_client.V1EnvVarSource(
                            secret_key_ref=k8s_client.V1SecretKeySelector(
                                name=secret_name,
                                key=aws_secret_access_key_name
                            )
                        )
                    )
                )
        )
        return task

    return _use_aws_secret
```

**Comment by LeonardAukea** [comment]
@swetashre

**Comment by swetashre** [comment]
@LeonardAukea - Sorry for replying late. How are you converting your credentials to base64 format ? I found the same issue in kubernetes GitHub that might be helpful:
https://github.com/kubernetes/kubernetes/issues/23404

**Comment by LeonardAukea** [comment]
@swetashre the credentials are converted correctly and work just fine in other contexts using other `boto3` `botocore` resources. What differs here is the addition of `workgroup`.

**Comment by micromoses** [comment]
I don't know if it helps, but I've encountered a similar issue. The problem I had was that I downloaded a new key as CSV from AWS console, and it contained CRLF. Bash hides it when running `env`, but reading `os.environ` in python includes these at the end.
What I did to resolve it is creating a new file on the target platform, and pasted the characters there. You can also use the `dos2unix` utility if it's available (`sudo apt-get install dos2unix` on ubuntu).

If you plan on fixing this in botocore, I suggest using `str.strip()`, which also helped me when reading the variables from the environment. I'm pretty sure that having whitespace/unprintables around the credentials is not something that should ever happen.

**Comment by oloidadmin** [comment]
this generally happens when you have a trailing space in your secret keys

**Comment by swetashre** [comment]
@LeonardAukea - Were you able to solve the problem ? Did any of the problem suggested above work for you ?

**Comment by mrbobfrog** [comment]
I inherited a kubernetes secret that was base64 encoded with a final newline and it generated a similar error -- I was able to resolve the issue by re-encoding the secret without the newline.

**Comment by sagarkar10** [comment]
Faced the same problem, where ever you are reading aws keys from environment k8 use `.strip("\n")`
eg: 
``` python
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID").strip("\n")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY").strip("\n")
```

**Comment by kdaily** [comment]
Hi all, looks like this is resolved. If you are still encountering issues with this, please open up a new issue and refer to this one. Thanks for your comments to help resolve!
