### ISSUE TITLE
All client's endpoint is an incorrect string

### ISSUE THREAD

**Issue by datarina** [boto/botocore#2008]
Hello!

I'm using boto for getting my aws credentials. It used to work just  fine but now I run into this issue when all the endpoints strings are wrong. Instead of getting 'sts.aws.com' i get 'sts.q.aws.com'.
And this extra 'q' in every endpoint string. What might be the reason for it? How can it be fixed?

Detected single role: arn:aws:iam::------------:role/--------------
> /usr/local/lib/python3.8/site-packages/botocore/httpsession.py(284)send()
-> raise EndpointConnectionError(endpoint_url=request.url, error=e)
(Pdb) u
> /usr/local/lib/python3.8/site-packages/botocore/endpoint.py(244)_send()
-> return self.http_session.send(request)
(Pdb) request.url
'https://sts.q.amazonaws.com/'

Thank you!

**Comment by swetashre** [comment]
@datarina - Thank you for your post. Can you please provide me the command you are using with the debug log ? You can enable log by adding ```boto3.set_stream_logger('')``` to your code.
