### ISSUE TITLE
vpc endpoint service configuration for PrivateDnsName or TagSpecifications getting ParamValidationError

### ISSUE THREAD

**Issue by pmankad96** [boto/botocore#2022]
I am trying to create VPC Endpoint Service using [create_vpc_endpoint_service_configuration()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_vpc_endpoint_service_configuration) api call. 

When I try to pass PrivateDnsName and/or TagSpecifications, I am getting botocore ParamValidationError:

$: 
Creating VPCE Service:
**boto3 version: 1.12.39
botocore version: 1.15.39**
Traceback (most recent call last):
  File "./networking/privatelink/vpceService.py", line 61, in <module>
    main()
  File "./networking/privatelink/vpceService.py", line 46, in main
    dbUpload=useDb, dbDict=dynamoDict)
  File "/automation/aws-python-sdk/lib/awsPrivateLinkUtils.py", line 53, in createVpceService
    NetworkLoadBalancerArns=nlbList,
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 599, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 647, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "PrivateDnsName", must be one of: DryRun, AcceptanceRequired, NetworkLoadBalancerArns, ClientToken
$:

Both botocore and boto3 are running the latest version:

$: python -c 'import botocore,boto3; v1=botocore.__version__;v2=boto3.__version__;print(f"botocore version: {v1}, boto3 version: {v2}")'
botocore version: 1.15.39, boto3 version: 1.12.39
$:

**Comment by swetashre** [comment]
@pmankad96 - Thank you for your post. Botocore validates the parameter from ```Users/user1/anaconda3/lib/python3.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json```  file. So please make sure ```CreateVpcEndpointServiceConfigurationRequest``` in this file contains all the parameter that you are specifying.

Please make sure you don't have any old model in that path and your code is using the latest version of botocore.

**Comment by pmankad96** [comment]
Thanks for taking a look and for your response.

To eliminate any old model, I had uninstalled and re-installed botocore. But, I still get the same ParamValiationError. And re-installed did install the latest version of botocore:

$: python -c 'import botocore; v1=botocore.__version__; print(f"botocore version: {v1}")'
botocore version: 1.15.39
$:

**Comment by pmankad96** [comment]
And as per the [boto3 api](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_vpc_endpoint_service_configuration) create_vpc_endpoint_service_configuration does support PrivateDns and TagSpecifications as a parameter.

**Comment by swetashre** [comment]
@pmankad96 - yeah it supports both the parameter and you should be able to use that. Here the problem is that your code is using a botocore ec2 api model which does not contain these two parameter and that's why you are getting error. 

Can you create a virtual environment and try running the code again ? As you are using conda these are the steps : 
```python
conda create -n env37 python=3.7
#you can use any python version

conda activate env37

python -c 'import botocore'
#you should get error as you don't have boto3 installed yet in your environment

pip install boto3
```
After all these steps then try running your code.

**Comment by pmankad96** [comment]
Thanks, I will follow the steps and update the issue before end of day pst.

**Comment by pmankad96** [comment]
I followed the steps and still getting the same error:

$: conda create -n env37 python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

\## Package Plan ##
!
!
!
\#
\# To activate this environment, use
\#
\#     $ conda activate env37
\#
\# To deactivate an active environment, use
\#
\#     $ conda deactivate

\$: conda env list
\# conda environments:
\#
**base                  *  /Users/user1/anaconda3**
env37                    /Users/user1/anaconda3/envs/env37
py2                      /Users/user1/anaconda3/envs/py2
py3                      /Users/user1/anaconda3/envs/py3

$: conda activate env37
$: conda env list
\# conda environments:
\#
base                     /Users/user1/anaconda3
**env37                 *  /Users/user1/anaconda3/envs/env37**
py2                      /Users/user1/anaconda3/envs/py2
py3                      /Users/user1/anaconda3/envs/py3

$: python -c 'import boto3; print(boto3.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'boto3'
$: python -c 'import botocore; print(botocore.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'botocore'
$: pip install boto3
Collecting boto3
  Using cached boto3-1.12.40-py2.
!
!
!
Installing collected packages: jmespath, six, python-dateutil, docutils, urllib3, botocore, s3transfer, boto3
Successfully installed boto3-1.12.40 botocore-1.15.40 docutils-0.15.2 jmespath-0.9.5 python-dateutil-2.8.1 s3transfer-0.3.3 six-1.14.0 urllib3-1.25.9
$: python -c 'import boto3; print(boto3.__version__)'
**1.12.40**
$: python -c 'import botocore; print(botocore.__version__)'
**1.15.40**
$: ./networking/privatelink/vpceService.py --action 'create' --useDb --topologyName 'testPl'
Creating VPCE Service:
Traceback (most recent call last):
  File "./networking/privatelink/vpceService.py", line 49, in <module>
    main()
  File "./networking/privatelink/vpceService.py", line 34, in main
    dbUpload=useDb, dbDict=dynamoDict)
  File "/<path_to>/aws-python-sdk/lib/awsPrivateLinkUtils.py", line 49, in createVpceService
    NetworkLoadBalancerArns=nlbList,
  File "/<path_to>/anaconda3/envs/env37/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/<path_to>/anaconda3/envs/env37/lib/python3.7/site-packages/botocore/client.py", line 599, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/<path_to>/anaconda3/envs/env37/lib/python3.7/site-packages/botocore/client.py", line 647, in _convert_to_request_dict
    api_params, operation_model)
  File "/<path_to>/anaconda3/envs/env37/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "PrivateDnsName", must be one of: DryRun, AcceptanceRequired, NetworkLoadBalancerArns, ClientToken
$:

**Comment by swetashre** [comment]
@pmankad96 - Thank you for trying those steps. I am not able to reproduce the issue with the below code:
```python
import boto3
ec2 = boto3.client('ec2')

ec2.create_vpc_endpoint_service_configuration(PrivateDnsName='string',NetworkLoadBalancerArns=['string'])
```
 Can you please provide me the exact code sample you are using ?

**Comment by pmankad96** [comment]
@swetashre you are right, I tried it on a fresh install of amazon linux 2 instance and it worked. For some reason it is not working when I try to do it through my mac. Everything seems to be in place but still it's failing - seems like there is a residual implementation of ec2 api model that is obstructing. But I am not able to figure it out.

Since it works as desired, if you can help guide debug ec2 api model reference issues, that be great. If not, I can understand.

I have attached the script that I am using. 

I also tried through python interpreter and it gives exact same error:

`$: python
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> ec2 = boto3.client('ec2')
>>> ec2.create_vpc_endpoint_service_configuration(PrivateDnsName='acme.example.com', NetworkLoadBalancerArns=['arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:loadbalancer/net/elbTestnlb1/xxxxxxxxxxxxba72'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 599, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/client.py", line 647, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/user1/anaconda3/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "PrivateDnsName", must be one of: DryRun, AcceptanceRequired, NetworkLoadBalancerArns, ClientToken
>>> ec2.create_vpc_endpoint_service_configuration(NetworkLoadBalancerArns=['arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:loadbalancer/net/elbTestnlb1/xxxxxxxxxxxxba72'])
{'ServiceConfiguration': {'ServiceType': [{'ServiceType': 'Interface'}], 'ServiceId': 'vpce-svc-0ee77734efe6da02a', 'ServiceName': 'com.amazonaws.vpce.us-west-2.vpce-svc-0ee77734efe6da02a', 'ServiceState': 'Available', 'AvailabilityZones': ['us-west-2a', 'us-west-2b'], 'AcceptanceRequired': True, 'NetworkLoadBalancerArns': ['arn:aws:elasticloadbalancing:us-west-2:558283194989:loadbalancer/net/elbTestnlb1/xxxxxxxxxxxxba72'], 'BaseEndpointDnsNames': ['vpce-svc-0ee77734efe6da02a.us-west-2.vpce.amazonaws.com']}, 'ResponseMetadata': {'RequestId': '48135c5c-bc20-44e6-9ab4-453abf2fd33f', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '48135c5c-bc20-44e6-9ab4-453abf2fd33f', 'content-type': 'text/xml;charset=UTF-8', 'transfer-encoding': 'chunked', 'vary': 'accept-encoding', 'date': 'Fri, 17 Apr 2020 19:26:03 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}
>>>`

**Comment by pmankad96** [comment]
**Test Script:**

`#! /usr/bin/env python

import argparse
import boto3
import logging
from botocore.exceptions import ClientError

ec2 = boto3.client('ec2')


def createVpceService(name, nlbList, acceptance=True, privateDns=''):
    """
    Function creates VPC Endpoint Service. Accepts list of NLB ARNs
    as the argument: ["nlb1arn, nlb2arn"]
    """
    try:
        if privateDns:
            response = ec2.create_vpc_endpoint_service_configuration(
                AcceptanceRequired=acceptance,
                PrivateDnsName=privateDns,
                NetworkLoadBalancerArns=nlbList,
                # TagSpecifications=[
                #     {
                #         'ResourceType': 'vpc-endpoint',
                #         'Tags': [{'Key': 'Name', 'Value': name}]
                #     },
                # ]
            )
        elif not privateDns:
            response = ec2.create_vpc_endpoint_service_configuration(
                AcceptanceRequired=acceptance,
                NetworkLoadBalancerArns=nlbList,
            )
        serviceId = response['ServiceConfiguration']['ServiceId']
        serviceName = response['ServiceConfiguration']['ServiceName']
        return response, serviceId, serviceName
    except ClientError as e:
        logging.error(e)
        return None


def deleteVpceService(name, serviceId):
    """
    Function Deletes one or more VPC endpoint service configurations in your
    account. 
    """
    logging.info(f"Deleting VPCE Service: {name}")
    try:
        response = ec2.delete_vpc_endpoint_service_configurations(
            ServiceIds=[serviceId]
        )
        return response
    except ClientError as e:
        logging.error(e)
        return None


def main():
    """
    VPCE Service:
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--action', default='create', nargs='?', const=1,
                        help='specify action: create|delete', type=str)
    args = parser.parse_args()
    action = args.action
    vpceServiceName = 'service1'
    nlbArn = ['arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:loadbalancer/net/elbTestnlb1/xxxxxxxxxxxxba72']

    if action == 'create':
        print(f"Creating VPCE Service:")
        service1 = createVpceService(vpceServiceName, nlbArn, True,
                                     'acme.cloudpoc.net')
    elif action == 'modify':
        print(f"Code not implemented:")
    elif action == 'describe':
        print(f"Code not implemented")
    elif action == 'delete':
        print(f"Deleting VPCE Service:")
        serviceId = 'vpce-svc-0815772982641dd81'
        delService1 = deleteVpceService(vpceServiceName, serviceId)


if __name__ == '__main__':
    main()
`

**Comment by pmankad96** [comment]
I think at this point it is fair enough to say that it has something to do with my setup - conda in particular. I will go ahead and close this issue. 

I will update with what I find.

**Comment by pmankad96** [comment]
@swetashre it was indeed an issue with using an old ec2 api model. I was able to find it, removed it and it is now working as desired. Thanks a lot for all your help, appreciate it.
