### ISSUE TITLE
IAM failures as of 1.13.23 with role based auth

### ISSUE THREAD

**Issue by jsmodic** [boto/botocore#2023]
After running with 1.13.22 for a long time, I tried to update to latest (1.15.x)... but saw a lot of IAM issues (using role based auth). I bisected that back to 1.13.23 as the latest version that shows problems (coincidentally just one later version).

This is using the s3 client with boto3==1.10.22 in a multi threaded, multi container on a single EC2 node setup. Changing the boto3 version seemed to have no effect.

It's not consistent as some requests will function properly. But there's a significant uptick of failed requests with no credentials attached. When I get on the machine itself to curl it, there's sporadic 429s and that's what I saw in cloudtrail as well. I don't have the boto debug logs... but it all points to getting throttled with a much higher IAM request volume.

Downgrading to 1.13.22 removes the symptoms.

There's some obviously suggestive changes in https://github.com/boto/botocore/blob/develop/botocore/utils.py that landed in 1.13.23, but I can't speak to how it all fits together to alter the shape of IAM requests.

**Comment by swetashre** [comment]
@jsmodic - Thank you for your post. I don't see any significant change in the version 1.13.23 that can impact the shape of IAM request. 
https://github.com/boto/botocore/blob/develop/.changes/1.13.23.json

Can you please provide me the code sample you are using ? It would be helpful if you could provide me the exact error you are getting with botocore version 1.13.23.

**Comment by jsmodic** [comment]
It would be a standard usage of the boto s3 client. Only thing notable for IAM is setting:

botocore_session.set_config_variable("metadata_service_timeout", 5)
botocore_session.set_config_variable("metadata_service_num_attempts", 5)

The general error comes out as "botocore.exceptions.NoCredentialsError"... and it's not easy to prove if that cascades into further errors and getting throttled by IAM on retries from initial errors.

**Comment by jsmodic** [comment]
It turns out that you definitely can not use one boto3/botocore session per thread as recommended in [the documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html?highlight=multithreading#multithreading-multiprocessing) in a multi threaded, multi tenant architecture or you will quickly get yourself into trouble with IAM.

Boto documentation should probably clarify somewhere that role based auth has some definite gotchas.
