### ISSUE TITLE
Support payload streaming for json protocol responses

### ISSUE THREAD

**Issue by oliora** [boto/botocore#2025]
It would be nice to support payload streaming for json protocol responses in the same way as it is supported for rest-json protocol.

**Comment by swetashre** [comment]
@oliora - Thank you for your post. Can you please provide me some more details on your use case ? for example - the problem you are facing or issue you are trying to resolve.

**Comment by oliora** [comment]
Hi!

We have service that speaks json protocol. Now we need to add an API that responds with a large binary data (like file content) so we want to return it as a streamable payload rather than as a base64-encoded member of json response.

**Comment by swetashre** [comment]
Thanks for responding. At this moment we are not thinking of adding streaming body support for the JSON protocol unless an AWS service needs it.

**Comment by oliora** [comment]
What’s a procedure to discuss this internally on Chime?

**Comment by swetashre** [comment]
Closing this issue as we can't do anything on our end to fix this issue.
