### ISSUE TITLE
Support querying codecommit of partition 'aws-cn' in session

### ISSUE THREAD

**Issue by zxkane** [boto/botocore#2026]
**AWS CodeCommit** is GA in AWS China(for both `cn-north-1` and `cn-northwest-1`).

Above regions are not available when querying regions for service 'codecommit' for 'aws-cn'.

```python
>>> import botocore.session
>>> session = botocore.session.Session(profile = 'default')
>>> session.get_available_partitions()
['aws', 'aws-cn', 'aws-us-gov']
>>> session.get_available_regions('codecommit', 'aws-cn')
[]
>>> session.get_available_regions('codecommit', 'aws')
['ap-northeast-1', 'ap-northeast-2', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'sa-east-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
```

**Comment by swetashre** [comment]
@zxkane - Thank you for your post. This change was introduced yesterday here:
https://www.amazonaws.cn/en/new/2020/aws-codecommit-available-aws-china-beijing-sinnet-ningxia-nwcd/

As this is recent change, those region has not included in the endpoints.json file.  The ```endpoints.json``` file comes from upstream. So the service team will eventually include those regions as they are available now. I think it only matters of time.
