### ISSUE TITLE
Batch's JobDetail requires optional field `startedAt`

### ISSUE THREAD

**Issue by schmidmt** [boto/botocore#2030]
Requests to `https://batch.us-east-1.amazonaws.com/v1/describejobs` may return 

```json
{
    "jobs":[
        {
            "jobName":"123",
            "jobId":"some-id",
            "jobQueue":"arn:aws:batch:us-east-1:XXX:job-queue/a-job-queue",
            "status":"FAILED",
            "attempts":[],
            "statusReason":"Cancelled via console.",
            "createdAt":1587767042358,
            "dependsOn":[],
            "jobDefinition":"arn:aws:batch:us-east-1:XXX:job-definition/a-job-def:1",
            "parameters":{},
            "container":{
                "image":"XXX.dkr.ecr.us-east-1.amazonaws.com/some-image:1.0.0",
                "vcpus":8,
                "memory":2048,
                "command":["some command"],
                "volumes":[],
                "environment":[],
                "mountPoints":[],
                "ulimits":[],
                "networkInterfaces":[],
                "resourceRequirements":[]
            }
        }
    ]
}
```

in the situation where a job had failed before it started (e.g. canceled from the console).
The response lacks the `startedAt` field within the `JobDetail` structure.
This causes a deserilization error as the specification lists `startedAt` as a required field (see [link](https://github.com/boto/botocore/blob/676ff0136944e64c784772771c0b25c681e117a5/botocore/data/batch/2016-08-10/service-2.json#L1196)).

**Comment by swetashre** [comment]
@schmidmt - Thank you for your post. According to the [documentation](https://docs.aws.amazon.com/batch/latest/APIReference/API_JobDetail.html) ```startedAt``` value will populate when the job transitioned from the STARTING state to the RUNNING state. So if job had failed before it started then the service won't send that parameter in the response. 

So the behavior you are getting is the expected behavior. Can you please give me some more detail on the error you are getting ?

**Comment by schmidmt** [comment]
@swetashre - Thanks for the help on this. The specification of the object `JobDetail` requires the presence of the field `startedAt`. Code that uses this specification may fail if the field is not present even though the `JobDetail` object is valid without it.

**Comment by swetashre** [comment]
@schmidmt - Thank you for the reply. I agree this is inconsistent as not all the job contain the ```startedAt``` field. I will reach out to the service team about the issue as this file comes from upstream and they will be the one to decide how to fix this. I will post here when i get any update.
