### ISSUE TITLE
Elastisearch Service generate_presigned_url

### ISSUE THREAD

**Issue by beugene-orcher** [boto/botocore#2031]
Hello,

Is there any way to generate presigned url for get requests to an ES instance?

Description:
I can get data under my master account and it works.
```
awsauth = AWSRequestsAuth(
    aws_access_key=AWS_ACCESS_KEY,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    aws_host=ES_HOST,
    aws_region=REGION,
    aws_service='es'
)
es = Elasticsearch(
    hosts=[{'host': ES_HOST, 'port': ES_PORT}],
    http_auth=awsauth,
    use_ssl=True,
    verify_certs=True,
    connection_class=RequestsHttpConnection
)
print(es.get(index='services', doc_type='employee', id=1))
```

The next step is getting presigned url to the index. I've checked out this (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/es.html#ElasticsearchService.Client.generate_presigned_url).
I've got the two problems:
1) which ClientMethod value I need to use for viewing index?
2) I've tried to generate url, but the given url returns 403 ("The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.").

get presigned url:
```
client = boto3.client(
    service_name='es',
    aws_access_key_id=AWS_ACCESS_KEY,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=REGION,
    endpoint_url=ES_HOST
)
print(client.generate_presigned_url('list_domain_names', Params=None, ExpiresIn=3600, HttpMethod='GET'))
```

**Comment by swetashre** [comment]
@beugene-orcher - Thank you for your post. I don't see any api method [here](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions) to use with sdk for viewing index. 

If it helps, you can use this:
https://elasticsearch-py.readthedocs.io/en/master/api.html#cat

For your 2nd question, I am not able to reproduce the issue. Can you please provide me the url you are getting ? Are you using that url with python ```requests``` module or in a browser ?
