### ISSUE TITLE
Add custom request headers

### ISSUE THREAD

**Issue by glonlas** [boto/botocore#2050]
**Is your feature request related to a problem? Please describe.**
Botocore seems to not support custom headers yet. For some application we will need additional headers like [`X-Amz-Date`](https://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html), `Accept-Encoding`, `Connection`, and so on. 

**Describe the solution you'd like**
I would like to propose a pull-request adding to extend [JSONSerializer#serialize_to_request](https://github.com/boto/botocore/blob/develop/botocore/serialize.py#L332-L335) with the ability to receive custom headers via a [Serializer attribute (Dict)](https://github.com/boto/botocore/blob/develop/botocore/serialize.py#L71) we can customize. So applications using Botocore can decide what additional headers they want/need.

This will increase Botocore's flexibility.

Is there any concern about such a new feature?

**Comment by swetashre** [comment]
@glonlas - Thank you for your post. Marking this as feature request.

Currently you can inject custom headers to an api call by registering it with boto3 events. Here is the link to the documentation with example:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/events.html

Hope it helps.

**Comment by Frederik-Baetens** [comment]
Hi, I'd like to have this feature request re-opened as it is indeed possible to add headers to a request, but there's no way to set a different header with each call, which I don't think is possible as of now with the current extensibility mechanism.

**Comment by mullenkamp** [comment]
Yes, this would be very useful. Unfortunately, this issue got passed off from https://github.com/boto/boto3/issues/2889 (with quite a bit of interest) then died here...
