### ISSUE TITLE
Update to the describe tags method for all the servies

### ISSUE THREAD

**Issue by lovepurohit** [boto/botocore#2057]
**Different describe tags response for different services**
The issue is that there is **no definite structure** for the **describe tags API** method. For some services, it uses resource names to get the tags for the particular resource while for some it can be used without passing any arguments to list the tags of all resources in that service.

As there isn't a definite structure, it becomes really hard to use the combination of those services as it varies a lot. To name a few services, **EC2** has a different structure than **ELB** or **ELBv2**. 
As **EC2**, describe tags method can directly be called to get the tags of all the resources. While for **ELB** and **ELBv2** we have to specify the **Resource ID** to fetch the tags for the resource.

Below are the boto3 links for both the tags method:
**EC2**: [Describe Tags](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_tags)
**ELB**: [Describe Tags](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elb.html#ElasticLoadBalancing.Client.describe_tags)

**Proposed Solution**
To solve this issue, we can opt for the structure as the same goes for the **ELB** or **ELBv2** as it is easier to use that structure in which we have to pass the Resource ID to get the tags. Rather than getting all the tags. 
This structure can also be helpful if the developer is building something on top of the API as generally everything works on the resource by resource basis.

Kindly look into the request and let me know if you need some clarity on the issue.

Thank you

**Comment by swetashre** [comment]
@lovepurohit - Thank you for your post. Marking this as feature request.
