### ISSUE TITLE
No way to make anonymous API call

### ISSUE THREAD

**Issue by garnaat** [boto/botocore#206]
STS calls like AssumeRoleWithSAML and AssumeRoleWithWebIdentity either require or allow anonymous calls.  We need to provide a way to support these types of calls in botocore, similar to what we did for [boto](https://github.com/boto/boto/issues/1556)

**Comment by philarmour** [comment]
This fix appears to be no longer be a part of botocore after the refactor (~0.66.0).  Is this something that needs a new issue or can we re-open this one?
