### ISSUE TITLE
Like is present in boto library, add support for X-Robots-Tag header

### ISSUE THREAD

**Issue by dnk8n** [boto/botocore#2067]
**Is your feature request related to a problem? Please describe.**
There is an undocumented feature that boto library picked up on, see https://github.com/boto/boto/search?q=X-Robots-Tag

Available in file, [boto/s3/key.py](https://github.com/boto/boto/blob/9e1cd3bd76e738d80630f1bd9160fd87c8eab865/boto/s3/key.py) is:

```
base_user_settable_fields = set(["cache-control", "content-disposition",
                                    "content-encoding", "content-language",
                                    "content-md5", "content-type",
                                     "x-robots-tag", "expires"])
```

**Describe the solution you'd like**
Similarly, I would like to see this functionality in botocore, and therefore boto3.

This would allow users to reupload their S3 files to include `X-Robots-Tag: noindex,nofollow` for example.

Additionally, any tooling options would be useful. For example, it would be great if the following code could be used downstream in boto3 so that the X-Robots-Tag header can be conveniently edited on an existing file (saves having to download and reupload) and not only PUT on new s3 objects:

```
import sys
from typing import Dict, Iterable, Iterator

import boto3
import requests
from requests.structures import CaseInsensitiveDict

S3_CLIENT = boto3.client('s3')
S3_BUCKET = "header-change-test"
BASE_URL = f"https://{S3_BUCKET}.s3-eu-west-1.amazonaws.com"


def get_s3_key_headers(s3_key: str) -> CaseInsensitiveDict:
    url = f"{BASE_URL}/{s3_key}"
    response = requests.head(url)
    if response.status_code == 200:
        headers = response.headers
        return headers
    else:
        print(f"Invalid response status code, {response.status_code} while calling {url}")
        sys.exit(1)


def set_s3_object_noindex_headers(s3_key: str):
    s3_object_head = S3_CLIENT.head_object(Bucket=S3_BUCKET, Key=s3_key)
    metadata = s3_object_head["Metadata"]
    metadata['X-Robots-Tag'] = 'noindex'
    S3_CLIENT.copy_object(
        Bucket=S3_BUCKET,
        Key=s3_key,
        CopySource={'Bucket': S3_BUCKET, 'Key': s3_key},
        Metadata=metadata,
        MetadataDirective='REPLACE'
    )

def verify_s3_object_noindex_headers(s3_key: str):
    current_headers = get_s3_key_headers(s3_key)
    if current_headers.get('X-Robots-Tag') == 'noindex':
        print(f"Successful: X-Robots-Tag: noindex header is present on s3 object: {s3_key}.")
    else:
        print(f"Unsuccessful: X-Robots-Tag: noindex header is NOT present on s3 object: {s3_key}.")


def main():
    test_keys = ['test1', 'test2']
    for key in test_keys:
        set_s3_object_noindex_headers(s3_key)
        verify_s3_object_noindex_headers(s3_key)

if __name__ == "__main__":
    main()
```

Currently when above code is executed, you get back header: `x-amz-meta-x-robots-tag` instead of `X-Robots-Tag`

**Comment by swetashre** [comment]
@dnk8n - Thank you for your post. When you upload objects using the REST API, the optional user-defined metadata names must begin with "x-amz-meta-" to distinguish them from other HTTP headers. When you retrieve the object using the REST API, this prefix is returned and Amazon S3 stores user-defined metadata keys in lowercase. 
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

This is the behavior i observed with different call:
```python
res = requests.head(url)

In [91]: res.headers
Out[91]: { 'Content-Type': 'binary/octet-stream', 'x-amz-meta-x-robots-tag': 'noindex', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'Accept-Ranges': 'bytes', 'x-amz-meta-meta1': 'This is my metadata value', 'Content-Length': '0'}
```
```python
response = client.head_object(Bucket='name',Key='key_name')

In [97]: response['Metadata']
Out[97]: {'meta1': 'This is my metadata value', 'x-robots-tag': 'noindex'}

In [96]: response['ResponseMetadata']['HTTPHeaders']
Out[96]: 
{'accept-ranges': 'bytes',
 'content-length': '0',
 'content-type': 'binary/octet-stream',
 'etag': '"d41d8cd98f00b204e9800998ecf8427e"',
 'last-modified': 'Fri, 12 Jun 2020 19:29:38 GMT',
 'server': 'AmazonS3',
 'x-amz-meta-meta1': 'This is my metadata value',
 'x-amz-meta-x-robots-tag': 'noindex'}
```
If you want to check for user defined metadata you can use the ```response['Metadata']``` section of ```head_object``` api call. 

I don't know what we can do on client side to change/improve this behavior. In general you can use any user defined metadata with a s3 object and every metadata will follow the same behavior. Trying to understand the ask here. Please let me know if i misunderstood anything.

**Comment by dnk8n** [comment]
Try PUT an object through the API with X-Robots-Tag set. You will then see
that a GET/HEAD of that object returns without the aws meta prefix,
`x-amz-meta-`

It is an undocumented feature that boto2 realised and made a solution for.

**Comment by dnk8n** [comment]
To clarify, the above undocumented feature only happens through API. Not
the AWS frontend.

**Comment by swetashre** [comment]
Currently the SDK don't support it by default and even i don't see in the AWS Console. When we set it via REST apis then the it is considered as an optional user-defined metadata and must begin with "x-amz-meta-" to distinguish them from other HTTP headers. 

Like other metadata such as ContentLength, ContentMD5 if this tag can be supported by the rest api then it would not have to begin with "x-amz-meta-". I will reach out to the service team about the issue so that it can be supported in the aws console and rest apis. It would be a feature request for service team to support this tag. 

In the mean time you can try this : 

```python
res = s3.head_object(Bucket='bucketname',Key='test')
metadata = res['Metadata']
```
