### ISSUE TITLE
How do I pass an empty timeout to batch submit_job in batch?

### ISSUE THREAD

**Issue by nh13** [boto/botocore#2075]
```python
client.submit_job(
  ... 
  timeout={}
)
```

gives

```bash
botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the SubmitJob operation: Error executing request, Exception : At least one attribute in Timeout must be specified, RequestId: <redacted>
```

```python
client.submit_job(
  ... 
  timeout=None
)
```

gives

```bash
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter timeout, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
```

This applies to `nodeOverrides` and `retryStrategy` too.  I am not sure what the defaults are (`None`, empty dictionary?) for those arguments, or if the method is just a `kwargs`.  For the latter, I guess it could just be looking for the existence or non-existence of the given keyword argument (ex. `timeout`).  So I could come up with a way to not specify `timeout` if the value is `None` or an empty dictionary.  But that feels very brittle and puts extra burden on the caller to groom the `kwargs` passed to the `submit.job`.

I would recommend supporting `None` as "this keyword argument should be ignored" and an empty dictionary as "this keyword argument is to be used, and its value is empty".

**Comment by swetashre** [comment]
@nh13 - Thank you for your post. According to [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.submit_job) the minimum value for the timeout is 60 seconds. 
And you have to pass the timeout in a dictionary format. Something like this:
```python
timeout={'attemptDurationSeconds':65}
```
This parameter is not required so you can omit this parameter during the api call and in that case the task will not be timed out. But as far as supporting the None value or the empty value concerned, we can't change the shape of a parameter on the client side. It has to be first supported by service.

**Comment by nh13** [comment]
If `timeout` is given as `None`, then `boto` should not specify the parameter in the JSON passed to the underlying service.  I think that supporting `None` for these keyword arguments removes a significant burden on the caller of `boto`, where currently we have to have either conditional logic to omit the `timeout ` keyword argument (and others!), or we have to build our own `kwargs` dictionary.  When wrapping the `boto` API, this becomes very burdensome, and replicated across all users of `boto`.

**Comment by swetashre** [comment]
Currently we are not thinking of supporting argument value passed as None at least not in the sense that passing None is the same as not passing it. Technically lack of presence and null are different and i don't think we want to conflate them.

**Comment by nh13** [comment]
I am disappointed by this decision but I'll add the following for posterity and continue on my way.  

This adds burden to ALL clients who use `botocore` to make sure that if no timeout is desired, then the `timeout` parameter isn't added as a keyword argument. In contrast, if `None` was supported as I describe, then this is (IMHO properly) centralized into `botocore`.  This decision forces client implementations that wrap a `submit_job` call to either contain this conditional logic (ex. 1)( or use `kwargs` similar to `botocore` (ex. 2)

```python
def ex1(timeout: Optional[int] = None) -> None:
  kwargs = {}
  if timeout is not None:
    kwargs["timeout"] = timeout
  submit_job(**kwargs)
```
^ Ugly, since every user of botocore has to wrap it this way

```python
def ex2(**kwargs: Dict[str, Any] = {}) -> None:
  submit_job(**kwargs)
```
^ just pushes the problem to the user of this method

**Comment by swetashre** [comment]
Thanks for providing your detailed analysis. At this moment we are not going to change this behavior so i am closing this issue. But in future if we change the behavior then will reopen the issue and update.

**Comment by swetashre** [comment]
Let's track this feature request under boto3 issue https://github.com/boto/boto3/issues/2667
