### ISSUE TITLE
Return the response when the task is complete

### ISSUE THREAD

**Issue by patricio-astudillo** [boto/botocore#2077]
It would be useful for the end-user to have some information about the task when everything goes well. The `response` is already send in the exception when something goes wrong.
```python
waiter = client.get_waiter('tasks_stopped') 
waiter.wait(cluster='my-cluster', tasks=[arn])  
```

Fix: adding `return response` instead of `return` at the following line: https://github.com/boto/botocore/blob/0dba414a47220da13fa69984236a5bb84b147fcb/botocore/waiter.py#L318

**Comment by swetashre** [comment]
Thank you for your post. Currently we are not thinking of returning response with waiter because we need to depend upon the api behavior for response. It is not guaranteed that the underlying api will always return the response in a same way.
