### ISSUE TITLE
Endpoints for EU Changed - Now don't work with GetProducts API

### ISSUE THREAD

**Issue by AMMullan** [boto/botocore#2078]
I, and many others, refer to the endpoints.json file in botocore/data/ in order to build a JSON mapping of the AWS regions (because you can't use the region code in the GetProducts API for some odd reason) and this used to work perfectly, however in the last couple of months this file has been changed and now instead of, for example, eu-west-1 being "EU (Ireland)" in that file it's now "Europe (Ireland)" (same for Frankfurt, Stockholm, London and Paris) - though Milan does seem to use Europe (Milan).

Is this a bug in botocore or is that file just not meant to be referred to for this kind of operation? If not it'd be incredibly useful if there was any info on how we could dynamically get the location names by AWS region.

Thanks in advance.

**Comment by swetashre** [comment]
@AMMullan - Thank you for your post. Can you please provide me some more details on how you are using the region code with GetProducts API ? 

Unfortunately i don't find a way to get the location names by AWS region. We have [get_available_regions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.get_available_regions) which will give you only the region name.

**Comment by AMMullan** [comment]
Thanks for the quick response @swetashre :)

So this is an abstract of what I'm doing...

```python
import json

import boto3
from pkg_resources import resource_filename

check_region = 'eu-west-1'


def get_region_name(region_code):
    default_region = 'EU (Ireland)'
    endpoint_file = resource_filename('botocore', 'data/endpoints.json')
    try:
        with open(endpoint_file, 'r') as f:
            data = json.load(f)
        return data['partitions'][0]['regions'][region_code]['description']
    except IOError:
        return default_region


pricing = boto3.client('pricing', region_name='us-east-1')
location_name = get_region_name(check_region)

products = pricing.get_products(
    ServiceCode='AmazonEC2',
    Filters=[
        {'Type': 'TERM_MATCH', 'Field': 'volumeType', 'Value': 'General Purpose'},
        {'Type': 'TERM_MATCH', 'Field': 'location', 'Value': location_name}
    ]
).get('PriceList')

if not products:
    print(f'No data for {check_region} ({location_name})')
```

For the time being I've hard coded in the corrections and it works, i.e.

```python
    aws_region_map['eu-west-1'] = 'EU (Ireland)'
    aws_region_map['eu-north-1'] = 'EU (Stockholm)'
    aws_region_map['eu-west-2'] = 'EU (London)'
    aws_region_map['eu-central-1'] = 'EU (Frankfurt)'
    aws_region_map['eu-west-3'] = 'EU (Paris)'
```
(in the actual code I've got logic to build up this aws_region_map from the ec2.describe_regions() call)

**Comment by swetashre** [comment]
@AMMullan - Thank you for the details response. It is helpful. I am able to reproduce this behavior. I am getting an empty list while using "Europe (Ireland)" instead of "EU (Ireland)". 
I don't know what we can do here to fix this issue as the endpoint file comes from upstream and we are getting an empty list from the service. I have reached out to the service team about the issue . I will post here when i get any update.

**Comment by AMMullan** [comment]
Thanks for the update @swetashre :) If you've got an internal case feel free to ping the number to me and our AWS TAM can help chase them lol

Do you know if there's any other way to get the location names?

**Comment by swetashre** [comment]
@AMMullan - I don't have any best way to get location name other than the way you are doing currently. Service team is aware of this issue but we don't have any timeline when they are going to change the name as many customers built their system with old data.

**Comment by AMMullan** [comment]
But the old way WAS to have EU, you look at any older articles, everyone does it the way I'm doing it, it's only relatively recent they changed them to Europe, thus why Milan works with Europe and the others work with EU...

**Comment by swetashre** [comment]
Unfortunately we can't do anything on client side to resolve this issue. It has to be fixed on the service side as they are still using old region name so when we query using new region name(in this case Europe instead of EU) we are getting empty list. They need to update their data store with new region information. 
According to the service team they are aware of the issue but they won't be changing this behavior anytime soon.
