### ISSUE TITLE
NTLM Proxy support

### ISSUE THREAD

**Issue by IyadKandalaft** [boto/botocore#2083]
**Is your feature request related to a problem? Please describe.**
Using the AWS CLI in a Microsoft dominated organization that leverages a forwarding proxy that requires authentication means that I have to declare an environment variable such as HTTPS_PROXY=https://<credentials>@proxy.myorg.com 
This would mean that my credentials are either stored as clear text in an environment setup file or I have to prompt for them every time I open powershell, bash, etc.  Even then, they are stored as clear text in as environment variables.  

**Describe the solution you'd like**
Using intermediate proxies like cntlm is a half-baked solution.

Ideally, botocore builds in support for the evil authentication-requiring proxies that support NTLM authentication.  In theory, this can be achieved by using urllib3.contrib.ntlm .  However, some github issues note that urllib3.contrib.ntlm needs work.

**Comment by swetashre** [comment]
Thank you for your post. This is all managed in urllib3 and urllib3 does not support NTLM at that moment. We don't have enough bandwidth to to fix that and we are not thinking of writing our own NTLM implementation. Unfortunately we can't do anything at this moment to address this issue.
