### ISSUE TITLE
[Documentation] SSM GetParametersByPath MaxResults Value is Incorrect

### ISSUE THREAD

**Issue by rp4fx12** [boto/botocore#2086]
**Describe the bug**

The documentation on SSM GetParametersByPath does not reference an appropriate value for MaxResults. This leads to confusion when invoking the API. The value in the document is specified as 123 when at max it can be 10.

**Steps to reproduce**

View document here: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.get_parameters_by_path

**Expected behavior**

Update to the documentation with an appropriate value in the MaxRequests Section. In addition, it would be nice to specify the limits on the MaxRequests call in the documentation.

**Debug logs**

N/A

**Comment by rp4fx12** [comment]
I may be wrong but I believe the 123 comes from this block of code - https://github.com/boto/botocore/blob/879f8440a4e9ace5d3cf145ce8b3d5e5ffb892ef/botocore/docs/shape.py#L93.

**Comment by swetashre** [comment]
@rp4fx12 - Thank you for your post. We are using 123 as a general value for integer type in every request syntax in the documentation. This request syntax does not contain the actual value. So if you can see for string type parameter we are using ```string``` as value in there. In this case what we can do is update our documentation clarifying about 123. 

Boto3 documentation is generated from API reference https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html
