### ISSUE TITLE
kms encryption fails on "key does not exist" but key deletion succeeds 

### ISSUE THREAD

**Issue by eranreshef** [boto/botocore#2107]
**Describe the bug**
There is some inconsistency in kms usage. I create a key, get its key id and when I try to use it for encryption I get a "key does not exist" error. When I later try to delete it, the key does exist.

**Steps to reproduce**
1. Create a kms cmk.
2. Extract the `KeyId` from the `create_key` response.
3. Use this `KeyId` to encrypt some text.

**Expected behavior**
The encryption request should succeed and the response will include the `CipherTextBlob`.
My **suspicion** is that perhaps I need to wait some time between key creation and encryption usage. There is a slight possibility that once the key is created it is not immediately in "enabled" state hence using it should return `DisabledException` (according to https://docs.aws.amazon.com/kms/latest/developerguide/key-state.html) but in this case I get ```04:21:37  botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the Encrypt operation: Key 'arn:aws:kms:us-east-1:5*************2:key/e11f1804-f93a-4c67-be21-dd963d667090' does not exist```

**Debug logs**
The issue doesn't reproduce on demand, it happens once in a while.

**Comment by swetashre** [comment]
@eranreshef - Thank you for your post. Please make sure the region where you are using the key is the same region where the key has been created. 
If you are using the same region then i would recommend contacting [AWS Support](https://aws.amazon.com/contact-us/). It is very difficult to find the exact root cause on the client side as this error is coming from service. 
Please let us know if you have any questions.

**Comment by eranreshef** [comment]
@swetashre I think this issue should be divided to 2:
1. Understand why AWS returns an error - to be resolved by AWS.
2. Understand if the error returned by AWS is accurately reflected in the botocore exception. I didn't mention it in the issue description, but immediately after creating the KMS key (and before calling `encrypt` command), I also call `create_alias` command and it passes successfully. So what I suspect here, is that AWS returns `DisabledException` for the `decrypt` command (see the key state documentation I pasted above) but botocore modifies it to a `NotFoundException` .

**Comment by swetashre** [comment]
@eranreshef - Thank you for the response. Can you please provide me debug log of ```encrypt``` api call ? You can enable log by adding ```boto3.set_stream_logger('')``` to your code. So that we can know what is the exact error you are getting from service.

**Comment by eranreshef** [comment]
@swetashre I would love to, but this issue doesn't reproduce on demand. I will add the code you mentioned and hopefully it reproduce sometime

**Comment by swetashre** [comment]
It is difficult to find out the root cause of the issue without debug logs. I am adding closing-soon for now. Please add debug log when you will be able to reproduce the issue or reopen if it has been already closed by the bot.
