### ISSUE TITLE
AWS::SNS::Topic is an approved config resource and should be added the to resourceType shape. 

### ISSUE THREAD

**Issue by anovis** [boto/botocore#2111]
AWS::SNS::Topic is an approved config resource and should be added the to resourceType shape. 

https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#amazonsimplenotificationservice

https://github.com/boto/botocore/blob/b264715942b7f022e5fc8cf9862f13980a93f27c/botocore/data/config/2014-11-12/service-2.json#L5972

submitted a pr #2110 , but not sure if this should be an upstream fix.

**Comment by kapilt** [comment]
its already present

**Comment by anovis** [comment]
ah i guess there is already an issue #2010

**Comment by kapilt** [comment]
yeah.. was just noting it looks like its in the file https://github.com/boto/botocore/blob/b264715942b7f022e5fc8cf9862f13980a93f27c/botocore/data/config/2014-11-12/service-2.json#L6065

**Comment by kapilt** [comment]
oh.. it got added in the last two hrs, my mistake ;-) its fixed in the latest release 1.17.27

**Comment by swetashre** [comment]
@anovis - Thank you for your post. It got added in the latest release as stated by @kapilt 
https://github.com/boto/botocore/blob/develop/botocore/data/config/2014-11-12/service-2.json#L6076

Please use the latest botocore version to use this feature.

**Comment by anovis** [comment]
thanks! @swetashre

**Comment by swetashre** [comment]
I am closing this issue as it has been resolved. Please let us know if you have any concerns.
