### ISSUE TITLE
Cap on docutils < 0.16 prevents co-installability

### ISSUE THREAD

**Issue by dchichkov** [boto/botocore#2120]
**Describe the bug**
I observe the following dependency conflict: 
  botocore 1.17.37 requires docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.

Strangely, pipdeptree doesn't show constraints on docutils that prevent it from going to 0.15.  
But for some reason the constraints solver keeps docutils at 0.16.0 (current release on pip)

**Expected behavior**
Is constraint to <0.16 arbitrary?  It seems this constraint was placed there by:
https://github.com/boto/botocore/commit/a8bbf60b665efee53f5a5d2cbbeb6e5e9e0838f2

And constraining docutils was problematic before.

**Comment by dchichkov** [comment]
Associated pull request - https://github.com/boto/botocore/pull/2121
No testing was performed.

**Comment by erdseb** [comment]
This comment is related: https://github.com/boto/botocore/pull/2121#issuecomment-686762476

**Comment by swetashre** [comment]
This issue is related to issue https://github.com/boto/botocore/issues/1942

**Comment by nateprewitt** [comment]
This issue should now be resolved in Botocore 1.18.0.
