### ISSUE TITLE
Max retries in boto3

### ISSUE THREAD

**Issue by dm-2111** [boto/botocore#2122]
Please fill out the sections below to help us address your issue.

**What issue did you see ?**
I need to set max retries in my boto3 client. Based on the AWS documentation present [here](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html#botocore-config), my code is below. However, I end up with an error: Cannot provide retry configuration for "mode". Valid retry configuration options are: 'max_attempts'.
 
**Steps to reproduce**
```
from botocore.config import Config

    config = Config(
            retries = {
            'max_attempts': 10,
            'mode': 'standard'
            }
        )
    
    identity = boto3.client("cognito-identity", region_name='us-east-1', config=config)
```

**Comment by swetashre** [comment]
@dm-2111 - Thank you for your post. I am not able to reproduce the issue. Can you please provide me debug logs ? You can enable log by adding ```boto3.set_stream_logger('')``` to your code.
