### ISSUE TITLE
Engine parameter rejected with `StartSpeechSynthesisTask`

### ISSUE THREAD

**Issue by mattlinares** [boto/botocore#2136]
**Describe the bug**
botocore version e.g. 1.17.45 `StartSpeechSynthesisTask` should accept the `Engine` parameter but boto issues a ParameterInvalid error when making a request with the Engine parameter defined.

Works with version 1.12.253.

**Steps to reproduce**
`polly = session.client("polly")
response = polly.start_speech_synthesis_task(Engine='neural', Text=text, OutputFormat="mp3", OutputS3BucketName="text-to-speech-polly", VoiceId="Emma", TextType='ssml')`

**Expected behavior**
A response including a neural-engine-produced mp3 audio file.

**Comment by mattlinares** [comment]
Referenced here too: https://github.com/home-assistant/core/issues/27418

**Comment by swetashre** [comment]
@mattlinares - Thank you for your post. I am not able to reproduce the issue with latest version of botocore. When a command is executed in boto3, botocore validates the parameter with [service2.json](https://github.com/boto/botocore/blob/develop/botocore/data/polly/2016-06-10/service-2.json) file and if mismatch occurs then you will get parameter validation failed error.

Engine parameter is introduced [here](https://github.com/boto/botocore/commit/3ee55b6154e85812ea47f55c1da48777b360f8ee). So it should work with botocore version >=1.12.199

Can you please provide me the exact error you are getting ? Please make sure your code is using latest version of botocore. Are you running this in local environment or somewhere else ?
