### ISSUE TITLE
Xcode app simulation subprocess popen error

### ISSUE THREAD

**Issue by sonukick** [boto/botocore#2138]
I built an app on kivy -ios using python. I used boto3 for some operations.  While simulating the app on xcode, The app crashed and generated the following error 
line 937 in botocore/credentials.py
def __init__(self, profile_name, load_config, popen=subprocess.Popen):

Attribute error:
subprocess has no attribute Popen

**Comment by swetashre** [comment]
@sonukick - Thank you for your post. Can you please provide any stack trace ?
