### ISSUE TITLE
Update SQS endpoints

### ISSUE THREAD

**Issue by benoit74** [boto/botocore#2151]
I'm opening this issue to try to get some attention on https://github.com/boto/botocore/issues/1418 which is Closed but should be reopened according to my PoV and the one of other users. I know this is not a good habit but I'm quite desperate to have some attention since it has been more than 8 months since my original request to reopen this. 

A small explanation :
- Botocore as of 1.9.15 still returns SQS queue URLs according to the `{region}.queue.{suffix}` pattern
- This is legacy according to AWS
- The new pattern is `sqs.{region}.amazonaws.com`
- This causes issues in some cases (e.g. when using an SQS VPC Endpoint which supports only the new URL)
- This was kept as is in 2018 due to Python 2.6 support. Since then, Python 2.6 support has been dropped and there is hence probably no more blocker to change this

Any chance to have someone look into it and fix this? Thank you very much in advance

**Comment by swetashre** [comment]
@benoit74 - Thank you for your post. We would need to drop support for python 2.6-2.7.8. Even then it would still be a breaking change because people have whitelists for particular urls, so changing what we use would break them.

For workaround you can use endpoint_url. Something like this:
```python
sqs = boto3.client('sqs',endpoint_url='https://sqs.us-west-2.amazonaws.com')
sqs.list_queues()
Out[87]: 
{'QueueUrls': ['https://sqs.us-west-2.amazonaws.com/12345678901/myqueue'],}
```
This issue is related to issue https://github.com/boto/boto3/issues/1900

**Comment by czechnology** [comment]
Manually setting `endpoint_url` parameter is surely a solution (which I also use to be able to use the SQS VPC endpoint).
However, I wonder if a solution similar to the `sts_regional_endpoints` would be applicable here. Keep `legacy` option as the default value but let users opt in for the new pattern, using config or environment variable.

**Comment by swetashre** [comment]
Let's track this issue under the Github issue https://github.com/boto/boto3/issues/1900. I am closing this one as duplicate.
