### ISSUE TITLE
METADATA_BASE_URL = 'http://169.254.169.254/' please make this configurable.

### ISSUE THREAD

**Issue by rathankalluri** [boto/botocore#2152]
**Is your feature request related to a problem? Please describe.**
Hello, There are many issues being raised by Sonarqube when we try to do our code analysis with botocore and boto3 modules being one of them.
and mostly we see the above-mentioned kind of vulnerabilities getting reported.

![image](https://user-images.githubusercontent.com/1715889/93192513-61a13800-f763-11ea-9db9-3101894dbefe.png)

**Describe the solution you'd like**
 If you can fix these kinds of issues that would be great from a security assessment point of view.

**Comment by nateprewitt** [comment]
Hi @rathankalluri, it looks like your tool may not be able to take in the full context of the code. This is a constant value that's already configurable [here](https://github.com/boto/botocore/blob/e70cc1d46d9301cc12266c4666759de4afec9dbb/botocore/utils.py#L273-L287). I don't believe there's more we'd be able to change in this case. Do you have a concrete idea of what you'd expect to be different?

**Comment by rathankalluri** [comment]
@nateprewitt  Thanks for the response. Yes you are right that the tool may not take the full context. We at our end may need to tweak the Sonarqube tool to skip checking out the boto3 files. Please close this.
