### ISSUE TITLE
Use of the word 'slave'

### ISSUE THREAD

**Issue by shiftbreak** [boto/botocore#2155]
Several components make use of the term "slave" within configuration files.

The following instances were identified:

```
data/ecs/2014-11-13/service-2.json
data/emr/2009-03-31/service-2.json
data/elasticache/2015-02-02/examples-1.json
```

**Comment by swetashre** [comment]
@shiftbreak - Thank you for bringing this up. These files comes from upstream. I will forward this issue to the service team.
