### ISSUE TITLE
Automatically use RefreshableCredentials when appropriate

### ISSUE THREAD

**Issue by nvllsvm** [boto/botocore#2158]
Adds support for credential refreshing to SharedCredentialProvider. 

If a new configuration key aws_expiration is present, RefreshableCredentials will be returned. Otherwise, standard Credentials will be returned. Credentials will be refreshed by re-parsing the file.

Solution available in https://github.com/boto/botocore/pull/1853

**Why?**
Ease of use.

**Comment by kdaily** [comment]
Thanks for the feature request, @nvllsvm. I apologize for the delay in response.

Can you provide more examples of the scenarios that this would make it easier to use?

**Comment by nvllsvm** [comment]
@kdaily Apologies for the delay in responding.

The main reason I desire this feature is that I have a number of long-running applications which need to perform refreshing of credentials (ex. HTTP services). PR https://github.com/boto/botocore/pull/1853 solves this nicely.
