### ISSUE TITLE
Allow ANY in the response parameter for Stubber.add_response()

### ISSUE THREAD

**Issue by bosatsu** [boto/botocore#2184]
**Is your feature request related to a problem? Please describe.**
The `Stubber.add_response()` method accepts `stub.ANY` for the `expected_params`, [described here](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html#botocore.stub.Stubber.add_response).  It would be helpful to have this same feature available for the `response` parameter as well.  I often have boto3 client calls where I need to test validation for the expected parameters, but have no need to validate the response.   [This is a good example](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-creating-buckets.html#create-an-amazon-s3-bucket)

**Describe the solution you'd like**

I would like to essentially be able to do the following:

Normal test setup:
```
import botocore.session
from botocore.stub import Stubber

s3 = botocore.session.get_session().create_client('s3')
stubber = Stubber(s3)
```

Simple response using `ANY`:
```
response = {'Location': ANY}
```

The rest of the test:
```
expected_params = {'Bucket': 'test-bucket, 'CreateBucketConfiguration'='test-location''}
stubber.add_response('create_bucket', response, expected_params)
stubber.activate()
service_response = s3.create_bucket(Bucket='test-bucket', CreateBucketConfiguration='test-location')
assert service_response == response
```

In this particular case for `create_bucket`, the gain for using `ANY` in the response isn't much, but when you look at the response required for something like the `create_db_cluster` in the rds_client which is a dictionary of around 40 items, the gain is clear.

**Comment by bosatsu** [comment]
I realized that this isn't necessary, since it is possible to pass an empty dictionary as a response.  For example:

`stubber.add_response('create_bucket', {}, expected_params)`

It just isn't clear in the documentation this is p.  I would be happy to make a PR to help update the documentation if that is helpful.  Otherwise feel free to close this request.

**Comment by swetashre** [comment]
@bosatsu - Thank you for providing your findings. According to the [documentation](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html#botocore.stub.Stubber.add_response) 
```
It should be noted, however, that while missing attributes are often considered correct, your code may not function properly if you leave them out. 
```
I am closing this issue. Please let us know if you have any concerns.
