### ISSUE TITLE
ImportError: cannot import name 'IPV6_ADDRZ_RE'

### ISSUE THREAD

**Issue by Inumedia** [boto/botocore#2187]
**Describe the bug**
I use awscli which uses botocore, I also install awsebcli. The most recent release of botocore seems to have broken my deploy process.

My issue is very similar to #2186 but isn't the same.

https://github.com/boto/botocore/commit/81768347efe3806decbbc43a61d3816620ee9ce9#diff-d5dc8bb337890042943977b62e8bb2e7db71415d35bb17a41ad4bf4780fb3617R30

**Steps to reproduce**
Build a docker image currently:

```dockerfile
FROM python:latest
RUN pip install awscli awsebcli --upgrade
```

Use the docker image to run `aws s3 cp`

See:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in 
    import awscli.clidriver
  File "/usr/local/lib/python3.9/site-packages/awscli/clidriver.py", line 17, in 
    import botocore.session
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 30, in 
    import botocore.credentials
  File "/usr/local/lib/python3.9/site-packages/botocore/credentials.py", line 34, in 
    from botocore.config import Config
  File "/usr/local/lib/python3.9/site-packages/botocore/config.py", line 16, in 
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.9/site-packages/botocore/endpoint.py", line 22, in 
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.9/site-packages/botocore/awsrequest.py", line 25, in 
    import botocore.utils
  File "/usr/local/lib/python3.9/site-packages/botocore/utils.py", line 30, in 
    from urllib3.util.url import IPV6_ADDRZ_RE
ImportError: cannot import name 'IPV6_ADDRZ_RE' from 'urllib3.util.url' (/usr/local/lib/python3.9/site-packages/urllib3/util/url.py)
```

**Expected behavior**
`aws s3 cp` to copy files and succeed

**Debug logs**
Unfortunately this isn't my code and I'm not super familiar with Python or awscli. If this is required, please let me know so I can attempt to do so.

Full stack trace by adding 
```
import botocore.session
botocore.session.Session().set_debug_logger('')
```
to your code.

**Comment by Inumedia** [comment]
As a note, updating my Dockerfile to:

```dockerfile
FROM python:latest
RUN pip install awscli awsebcli botocore==1.18.18 --upgrade
```

Fixes it locally, and this problem only showed up today, so it seems to be from this most recent release

**Comment by dilanSachi** [comment]
i faced this issue too
seemed like an issue with **urllib3** version
using `pip install urllib3==1.25.10` fixed my problem

**Comment by JimNero009** [comment]
Hey ^^ I can second @dilanSachi's conclusion. If you have a version of urllib3 being resolved (in whatever way) to something less than version **1.25.4**, then you will encounter this issue. In my case, I had three different libraries all demanding directly incompatible urllib3 versions :D

**Comment by netizen136** [comment]
I faced this issue too

**Comment by nateprewitt** [comment]
Hi @Inumedia,

This is esssentially the same underlying issue as #2186. `awebcli` has a pretty restrictive version range on urllib3 and are overriding the install requirements for `awscli`. If you want to upgrade to the latest release of `awscli`, you'll need to have `urllib3 >= 1.25.4` that we have declared in the installer. `pip` isn't great about this but does issue an error message when you perform your current install. It won't however stop you from finishing an incomplete/incompatible install.

The immediate fix here would be to pin urllib3 to `>=1.25.4` to stop `awsebcli` from uninstalling your requirements. You could alternatively use a version of the CLI that shares compatibility with `awsebcli`.

**Comment by nateprewitt** [comment]
As a quick update, we're working with the `awsebcli` team to see if they can relax some of their declared constraints and only rely on botocore like the `awscli` does. That should help reduce the amount of friction with pip in future releases.

**Comment by Inumedia** [comment]
FYI,

I tried your suggestion of pinning urllib3 at `>=1.25.4`: 

`pip install awscli awsebcli urllib3>=1.25.4 --upgrade`

That seems to have fixed it for the immediate for me. I'll keep an eye on this issue for when this gets resolved.

Thanks for letting me know

**Comment by Tahmid12Khan** [comment]
> i faced this issue too
> seemed like an issue with **urllib3** version
> using `pip install urllib3==1.25.10` fixed my problem

This actually saved my problem too!! This was so frustrating!
