### ISSUE TITLE
Cross dependence problem

### ISSUE THREAD

**Issue by vector-mricote** [boto/botocore#2207]
**Describe the bug**
I try to use this library, but when i try to use in pipenv its generate this error.

[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches urllib3!=1.25.0,!=1.25.1,<1.25,<1.26,>=1.21.1,>=1.24.2,>=1.25.4 (from elasticsearch-curator-api==5.8.3->-r /tmp/pipenvmg3mDorequirements/pipenv-VMuu2x-constraints.txt (line 3))
Tried: 0.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1.2.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.7.1, 1.8, 1.8.2, 1.8.3, 1.9, 1.9.1, 1.9.1, 1.10, 1.10, 1.10.1, 1.10.1, 1.10.2, 1.10.2, 1.10.3, 1.10.3, 1.10.4, 1.10.4, 1.11, 1.11, 1.12, 1.12, 1.13, 1.13, 1.13.1, 1.13.1, 1.14, 1.14, 1.15, 1.15, 1.15.1, 1.15.1, 1.16, 1.16, 1.17, 1.17, 1.18, 1.18, 1.18.1, 1.18.1, 1.19, 1.19, 1.19.1, 1.19.1, 1.20, 1.20, 1.21, 1.21, 1.21.1, 1.21.1, 1.22, 1.22, 1.23, 1.23, 1.24, 1.24, 1.24.1, 1.24.1, 1.24.2, 1.24.2, 1.24.3, 1.24.3, 1.25, 1.25, 1.25.1, 1.25.1, 1.25.2, 1.25.2, 1.25.3, 1.25.3, 1.25.4, 1.25.4, 1.25.5, 1.25.5, 1.25.6, 1.25.6, 1.25.7, 1.25.7, 1.25.8, 1.25.8, 1.25.9, 1.25.9, 1.25.10, 1.25.10, 1.25.11, 1.25.11
There are incompatible versions in the resolved dependencies:
  urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.24.0->elasticsearch-curator-api==5.8.3->-r /tmp/pipenvmg3mDorequirements/pipenv-VMuu2x-constraints.txt (line 3))
  urllib3<1.25,>=1.24.2 (from elasticsearch-curator-api==5.8.3->-r /tmp/pipenvmg3mDorequirements/pipenv-VMuu2x-constraints.txt (line 3))
  urllib3<1.26,>=1.25.4 (from botocore==1.19.12->boto3==1.16.12->-r /tmp/pipenvmg3mDorequirements/pipenv-VMuu2x-constraints.txt (line 2))
  urllib3>=1.21.1 (from elasticsearch==7.9.1->elasticsearch-curator-api==5.8.3->-r /tmp/pipenvmg3mDorequirements/pipenv-VMuu2x-constraints.txt (line 3))

As you can see the dependences from botocore and elasticsearch-curator-api have an inconsistence.

Thanks

**Comment by nateprewitt** [comment]
Hi @vector-mricote,

I believe this was resolved in elastic/curator#1562. I would assume it will be available in their next release.
