### ISSUE TITLE
[ERROR] AttributeError: module 'botocore.vendored.requests' has no attribute 'post' despite having import requests

### ISSUE THREAD

**Issue by DaniyalDhz** [boto/botocore#2217]
**Describe the bug**
`[ERROR] AttributeError: module 'botocore.vendored.requests' has no attribute 'post'
`
**Steps to reproduce**
```
import requests
import json
def resume(url, headers):
    requests.post(url, data={}, headers=headers)
def scheduleResumption(api_access_token, session_id):
    headers = {
        'Authorization': f'Bearer {api_access_token}',
        'Content-Type': 'application/json',
    }
    t = Timer(interval=30.0,
          function=resume,
          args=(f'https://api.amazonalexa.com/v1/_customSkillSessions/{session_id}/resume/', headers)
          )
    t.start()
```
**Expected behavior**
for it to POST
**Debug logs**
```
2020-11-13T02:23:33.842-05:00	[ERROR] AttributeError: module 'botocore.vendored.requests' has no attribute 'post'
                             	Traceback (most recent call last):
                             	  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
                             	    return load_source(name, filename, file)
                             	  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
                             	    module = _load(spec)
                             	  File "<frozen importlib._bootstrap>", line 702, in _load
                             	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                             	  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
                             	  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                             	  File "/var/task/lambda_function.py", line 86, in <module>
                             	    requests.post(url, data = myobj)
```
#### Runtime: 
tried with python `3.8 `& `3.7` & have a layer that had requests library in it.

**Comment by nateprewitt** [comment]
Hi @DaniyalDhz,

Requests was removed from botocore a little over a year ago in version [Botocore 1.13.0](https://github.com/boto/botocore/blob/1.13.0/CHANGELOG.rst). We released a [blog post](https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/) on October 1, 2019 which has full details on the change. Going forward, you'll want to install requests separately with `pip install requests`.

**Comment by DaniyalDhz** [comment]
Hi there,
Thanks for getting back,
`requests` library is already in my lambda's layers. Nonetheless, I manually pip installed it to my lambda per your recommendation, as can be seen:
![image](https://user-images.githubusercontent.com/58639693/99122821-0d80cb80-25cd-11eb-96c3-b0460ba91e12.png)
Nonetheless, the same error is presisting.

**Comment by swetashre** [comment]
@DaniyalDhz - I am using layer to add dependency to my lambda function and its working correctly. This is how i am uploading my dependency to my lambda function:
```python
pip install requests --target python

zip -r dependency.zip python
```
Then create a layer using this zip file and use this layer in your lambda function. In order for the dependency to work you have to put Python dependencies into either a ```python``` directory or into ```python/lib/python<3.x>/site-packages```.

Let us know if you are still facing any issues.

**Comment by DaniyalDhz** [comment]
@swetashre Thanks for getting back. I followed that too. Sorry, I forgot to close it.
