### ISSUE TITLE
Update BatchRetryStrategy

### ISSUE THREAD

**Issue by Fuuzetsu** [boto/botocore#2233]
**Is your feature request related to a problem? Please describe.**
In current master we see https://github.com/boto/botocore/blob/ab8ab9ed2a55fb8a69e5537332fd07197dba240e/botocore/data/events/2015-10-07/service-2.json#L785

However if we look on API documentation on AWS site, we see `evaluateOnExit` field: https://docs.aws.amazon.com/batch/latest/APIReference/API_RetryStrategy.html

**Describe the solution you'd like**
Being able to access this field is important for using Spot instances on AWS Batch as it allows much more accurate job restarting in case AWS reclaims capacity from Spot instances.

It would be great if the field was added. The type for it already seems to exist: https://github.com/boto/botocore/blob/master/botocore/data/batch/2016-08-10/service-2.json#L1182

**Comment by swetashre** [comment]
@Fuuzetsu - Thank you for your post. The service-2.json file you are looking, is for Amazon EventBridge service. But the api document is for AWS batch service and the model for AWS batch service already contains the  evaluateOnExit field.
https://github.com/boto/botocore/blob/develop/botocore/data/batch/2016-08-10/service-2.json#L1975

This the API documentation for BatchretryStrategy which does not contain that field:
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_BatchRetryStrategy.html

**Comment by Fuuzetsu** [comment]
@swetashre You're absolutely right, sorry, I'm not sure how I messed this up. Here's the commit I failed to find initially https://github.com/boto/botocore/commit/05675703205a21e882bdb78f3f173d2f5ffe9cbf

I'm closing the ticket, sorry for the noise.
