### ISSUE TITLE
Support AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN in Environment credentials source

### ISSUE THREAD

**Issue by vladdy** [boto/botocore#2245]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need to run AWS CLI (which uses botocore underneath) in a Kubernetes pod managed by EKS. The CLI needs to assume a role different from what is assigned to the container via [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html). Unfortunately, it looks like `credential_source = Environment` does not recognize `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` variables exported in the container's environment. As the result, the CLI fails to find credentials to assume the required role specified in the profile. As a workaround I had to specify web identity details directly in the profile to make it working:

```
[profile env]
role_arn=arn:aws:iam:012345678901:role/pod-role
web_identity_token_file=/var/run/secrets/eks.amazonaws.com/serviceaccount/token

[default]
role_arn=arn:aws:iam::012345678901:role/cli-role
source_profile=env
```

**Describe the solution you'd like**
I wonder if it can be considered to add a support of web identity into the `Environment` credential source to use those similarly as they can be set in the profile. It would simplify the way to run the CLI and other python libraries inside Kubernetes pods when IRSA is used and a separate role needs to be assumed.

If it is something possible to be added, I would be happy to work on a PR.

**Comment by vladdy** [comment]
@swetashre Any thoughts on this?

**Comment by kdaily** [comment]
Hi @vladdy, I think this is similar to the following feature requests:

- #2360
- #3875 (from the AWS CLI)

I will need to look into it further.

**Comment by vladdy** [comment]
@kdaily, probably, you referenced #2360 by mistake as it looks to be about EBS volume types. https://github.com/aws/aws-cli/issues/3875, maybe touching the same part of the code.

Thanks for looking into this! Btw, I would be happy to work of this if you need a help and the change makes sense.

**Comment by kdaily** [comment]
Closing this as a duplicate. Please 👍🏻 the original post of either https://github.com/boto/boto3/issues/2360 or https://github.com/aws/aws-cli/issues/3875 and add any specific use cases there. Thanks!
