### ISSUE TITLE
Enable setting tcp_keepalive and duration_seconds via botocore.config.Config object

### ISSUE THREAD

**Issue by eyager1** [boto/botocore#2249]
**Is your feature request related to a problem? Please describe.**
Network connection parameters `tcp_keepalive` and `duration_seconds` are only settable via `~/.aws/config` file and not the `botocore.config.Config` object.  Projects like home-assistant can only configure boto3 via the python API and not any configuration files.

**Describe the solution you'd like**
Expand `tcp_keepalive` and `duration_seconds` parameters to be settable via `botocore.config.Config`.

**Comment by swetashre** [comment]
@eyager1 - Thank you for your post. Marking it as a feature request.

**Comment by sebtrack** [comment]
I wondered how is it, that it can't be set programmatically but in a global config file!

**Comment by yuji-hatakeyama** [comment]
I hope `tcp_keepalive = True` programmatically too !

**Comment by frederick-wang** [comment]
I also hope tcp_keepalive = True programmatically too

**Comment by macsir** [comment]
Hi, is there any update on this? Thanks.

**Comment by dlm6693** [comment]
@macsir I've opened a PR that adds `tcp_keepalive`. We've decided not to do the same for `duration_seconds`. If you wish to see that added as well please comment here and/or open up a new ticket.

**Comment by macsir** [comment]
Hi, @dlm6693  Thanks for that. Yes, tcp_keepalive is the one I need.

**Comment by dlm6693** [comment]
Hi all. tcp_keepalive is now accessible on the config object thanks to https://github.com/boto/botocore/pull/2766. If you would like to see duration_seconds added as well, please open up a new ticket.
