### ISSUE TITLE
Add __delitem__ to JSONFileCache

### ISSUE THREAD

**Issue by benkehoe** [boto/botocore#2255]
It would be nice if `botocore.credentials.JSONFileCache` supported the `__delitem__` method, so that cache entries could be programmatically removed from the on-disk cache (in particular, I'm implementing a programmatic version of `aws sso logout`).

**Comment by benkehoe** [comment]
I would still like to see this implemented.

**Comment by nateprewitt** [comment]
Thanks for the check-in, @benkehoe. I've put together #2579 to at least serve as a talking point. We can follow up there in the new year. Happy Holidays!

**Comment by nateprewitt** [comment]
We've merged #2579 which should add the desired behavior. It will be included in the next release, presumably today. I'm going to resolve this as being addressed. Thanks!
