### ISSUE TITLE
Botocore ParamValidationError when Calling `fit` on SageMaker Estimator Object 

### ISSUE THREAD

**Issue by evakravi** [boto/botocore#2260]
I'm a developer working on AWS SageMaker Studio. We have two environments that have `botocore==1.19.48` and `sagemaker==2.23.1` installed, and one system is able to call the [SageMaker function `fit`
](https://sagemaker.readthedocs.io/en/stable/api/training/estimators.html#sagemaker.estimator.EstimatorBase.fit) on an estimator object, while the other system produces the following botocore error: 

```botocore.exceptions.ParamValidationError: Parameter validation failed:\nUnknown parameter in input: 'ProfilerRuleConfigurations', must be one of: TrainingJobName, HyperParameters, AlgorithmSpecification, RoleArn, InputDataConfig, OutputDataConfig, ResourceConfig, VpcConfig, StoppingCondition, Tags, EnableNetworkIsolation, EnableInterContainerTrafficEncryption, EnableManagedSpotTraining, CheckpointConfig, DebugHookConfig, DebugRuleConfigurations, TensorBoardOutputConfig, ExperimentConfig\nUnknown parameter in input: 'ProfilerConfig', must be one of: TrainingJobName, HyperParameters, AlgorithmSpecification, RoleArn, InputDataConfig, OutputDataConfig, ResourceConfig, VpcConfig, StoppingCondition, Tags, EnableNetworkIsolation, EnableInterContainerTrafficEncryption, EnableManagedSpotTraining, CheckpointConfig, DebugHookConfig, DebugRuleConfigurations, TensorBoardOutputConfig, ExperimentConfig```

To solve this issue, we have tried re-installing the libraries and confirming that the versions are up-to-date, but the problem persists. Are there other dependencies that must be checked, or is there any way to identify why this problem occurs on just 1 system? We do not know how to reproduce this problem on another system. 

Thanks!

**Comment by swetashre** [comment]
Thank you for your post. It looks like you are using Sagemaker python sdk not boto3. 
This is the github repo for sagemaker python sdk 
https://github.com/aws/sagemaker-python-sdk

I would say let's follow up there. We use this GitHub for tracking bug and feature requests related to boto3/botocore.
