### ISSUE TITLE
test functional/retries/test_bucket.py : test_stress_test_token_bucket intermittent failure in Fedora koji

### ISSUE THREAD

**Issue by limburgher** [boto/botocore#2262]
**Describe the bug**
Failure of this test causes sporadic RPM build failures in koji.

**Steps to reproduce**
Local build always succeeds. Koji build fails about 1/3 of the time.

**Expected behavior**
Build success.

FAIL: test_stress_test_token_bucket (tests.functional.retries.test_bucket.TestTokenBucketThreading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/botocore-1.19.49/tests/functional/retries/test_bucket.py", line 109, in test_stress_test_token_bucket
    self.assertTrue(not any(x < (0.2 * mean) for x in distribution))
AssertionError: False is not true

I suspect tweaking the threshold here is probably OK but I'm not sure.

**Comment by swetashre** [comment]
@limburgher - Thank you for your post. Yes, you can tweak the threshold. I think an additional .1 is fine since we're not really concerned about the time.

**Comment by limburgher** [comment]
Should I submit a patch here or just patch it within Fedora?

**Comment by limburgher** [comment]
Adding .1 increases the success rate. Do you think going further is acceptable?

**Comment by stobrien89** [comment]
Hi @limburgher,

Sorry for the delay!  I think it'd be reasonable to add another .1 - .15 to the threshold if you haven't tried doing so already.  Like @swetashre mentioned, we're not really concerned about the time here.
