### ISSUE TITLE
Suggestion:  Add an aditional check that an "_event_emitter" returns the expected type

### ISSUE THREAD

**Issue by EmperorArthur** [boto/botocore#2269]
Please fill out the sections below to help us address your issue.

**What issue did you see ?**
In upgrading botocore, the 'before-send' event hook I had in place broke.

This was because the system expected an AWSResponse, but I was actually providing it an HTTPResponse.
It then failed with an "AttributeError" in `botocore.endpoint.convert_to_response_dict`.

**Steps to reproduce**

```python
import boto3
from botocore.client import BaseClient
from urllib3 import HTTPResponse


client: BaseClient = boto3.client(
            's3',
            region_name=AWS_REGION,
            aws_access_key_id=AWS_ACCESS_KEY_ID,
            aws_secret_access_key=AWS_SECRET_ACCESS_KEY
        )
aws_request = None

def request_faker(self, params=None, **kwargs):
    aws_request = kwargs['request']
    response = HTTPResponse()  # Should be AWSResponse(...)
    response.status_code = 200
    return response

event_system = self.client.meta.events
event_system.register('before-send.s3.UploadPart', request_faker)
self.client.upload_part(
            Bucket=AWS_S3_BUCKET_NAME,
            Key=key,
            UploadId=upload_id,
            PartNumber=part_number,
            ContentLength=content_length,
            ContentMD5='',
        )
```

**Suggested Improvement**
Adjust either `botocore.hooks.first_non_none_response` or `botocore.endpoint.Endpoint._do_get_response` to check the response type.  It currently checks if it is not None, but an additional `raise` on an unexpected type would save significant headaches in the future.

This would allow quick and easy debugging.  Instead of parsing through logs trying to figure out what went wrong, and then further trying to understand what type the function expected.

An alternative approach would be to type hint functions such as `convert_to_response_dict`, so at the least we can know what the function expected to see in the first place.

**Comment by EmperorArthur** [comment]
Also, it might be worth it to document `AWSRequest` a bit better.  Certainly, it's somewhat annoying to stub it since raw is not documented at all, and it took some trial and error to determine that raw.stream() must be implemented.

**Comment by swetashre** [comment]
@EmperorArthur - Thank you for your post. AWSResponse is a data class representing an HTTP response. I am marking it as feature request for adding an additional condition to check the response type. 

This is the documentation about AWSRequest if it helps:
https://botocore.amazonaws.com/v1/documentation/api/latest/reference/awsrequest.html
