### ISSUE TITLE
since botocore version 1.20.0 there are errors in eb cli and python six module

### ISSUE THREAD

**Issue by fortunejuggle** [boto/botocore#2288]
**Describe the bug**
We have some CI scripts to setup elastic beanstalk. There we run `apk add --no-cache bash git gettext py3-pip build-base python3-dev python3 libffi-dev libressl-dev musl-dev && pip3 install awsebcli awscli` 

Since today this does not work anymore and it leads to error: `ERROR: MissingServiceIdError - The model being used for the service elasticbeanstalk is missing the serviceId metadata property, which is required.`

However there were problems with `python six` also. 

**Expected behavior**
eb deploy and all other eb options will work without errors

**Debug logs**
```
eb deploy $APP-NAME-$AWS_TAG -r $AWS_DEFAULT_REGION
ERROR: MissingServiceIdError - The model being used for the service elasticbeanstalk is missing the serviceId metadata property, which is required.
```
Log Output from python six errors
```
Collecting six>=1.5
  Downloading six-1.11.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, websocket-client, requests, python-dateutil, jmespath, docker-pycreds, wcwidth, texttable, PyYAML, pyasn1, jsonschema, docopt, dockerpty, docker, cached-property, botocore, termcolor, tabulate, semantic-version, s3transfer, rsa, pathspec, docutils, docker-compose, colorama, cement, blessed, awsebcli, awscli
  Attempting uninstall: six
    Found existing installation: six 1.15.0
ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Current fix**
pin botocore to version `1.19.63`
`
`apk add --no-cache bash git gettext py3-pip build-base python3-dev python3 libffi-dev libressl-dev musl-dev && pip3 install awsebcli awscli botocore==1.19.63 `

this solves the `six` and the `eb <option>` error

**Comment by kdaily** [comment]
Looking into this. Looks like the EB CLI requires `botocore<1.20.0`:

https://github.com/aws/aws-elastic-beanstalk-cli/blob/c79d899ec83e178f699e2bd8d844eab36a3c7a55/setup.py#L22

**Comment by kdaily** [comment]
Looks like this was reported at the EB CLI too:

https://github.com/aws/aws-elastic-beanstalk-cli/issues/63
