### ISSUE TITLE
Merge JSONFileCache change from v2 to v1

### ISSUE THREAD

**Issue by benkehoe** [boto/botocore#2293]
In v2, [a constructor argument `dumps_func`](https://github.com/boto/botocore/blob/7dddd5069370c716273e34f0676fd5e338baa53a/botocore/credentials.py#L286) was added to allow control over serialization (in particular, to allow the CLI v2 to [cache AWS SSO tokens with actually ISO8601-compliant timestamps](https://github.com/aws/aws-cli/blob/d9e54feb2c6ae4c4c1d7675a54aacfdc17f44713/awscli/customizations/sso/utils.py#L46)). However, this code has not been ported over to botocore v1, and because of this, [`aws-sso-util`](https://github.com/benkehoe/aws-sso-util) is still writing timestamps that are not ISO8601-compliant. The reason ISO8601-compliant timestamps are important here is because of this issue in the Go SDK: https://github.com/aws/aws-sdk-go/issues/3324

**Comment by nateprewitt** [comment]
Apologies @benkehoe, this appears to have been lost in the fray. The fix was merged back in February with #2302, I'll plan to close this tomorrow if you don't have other concerns. It looks like you managed to get this added to `aws-sso-util`.

**Comment by benkehoe** [comment]
Yep, I should have closed this when I saw that merge and started using it
