### ISSUE TITLE
Support caching of API call response based on set time expiry as part of botocore.session.Session

### ISSUE THREAD

**Issue by rams3sh** [boto/botocore#2296]
I have created the same issue in boto3. Raising it here for visibility as I am not sure where this feature request would exactly fit in.
Link to that issue : https://github.com/boto/boto3/issues/2723

**Is your feature request related to a problem? Please describe.**

I have a scheduled trigger based serverless app running from a central account running on lambda(s)  which has to assume role across around 1k accounts and carry out certain actions. Each task within the app runs as separate process and may have to repeat some boto3 api calls within same account.  This results in same api calls being called multiple times resulting in IO wait  / throttling (which involves sleeping to initiate the next call) increasing the execution time which does sometime lead to lambda timeouts. Writing a function cache wrapper for each boto3 method didn't feel as a scalable solution for me.

This feature request proposes to have a setting where one could set a cache directory with cache expiry timeout. Boto3 package can use that path to store all cached response (something like picked files). Whenever an api call is initiated through a session object ,  the cache will be checked and the response will be returned if the last cached response is within the cache expiry from the cache file.

The scope of cache would be limited only to that given session.

**Describe the solution you'd like**
A sample code snippet to give idea about the expected solution is given below :- 

```python
cache_enabled_session = botocore.session.Session(cache_path="/.cache/", cached_response_expiry=15)  # 15 minutes
iam_client = cache_enabled_session.client("iam")
users_from_api_call = iam_client.list_users()
users_from_cached_response = iam_client.list_users()

s3 _client  = cache_enabled_session.client("s3", region_name="eu-west-1")
buckets_from_api_call = s3_client.list_buckets()
buckets_from_cached_response = s3_client.list_buckets()

# After 13 minutes , if another session is initiated with same params and same cache, it should fallback to previous session i.e. cache_enabled_session
time.sleep(13*60)
cache_enabled_session_2 = botocore.session.Session(cache_path="/.cache/", cached_response_expiry=15)
iam_client = cache_enabled_session_2.client("iam")
users_from_cached_response_2 = iam_client.list_users() # Response will be fetched from same cache

# The below session would not have any access to that cache and would not use cached response.

cache_disabled_session = botocore.session.Session()
users_from_api_call = iam_client.list_users()
```

**Comment by rams3sh** [comment]
Until this issue is triaged / accepted for development. I found an interim solution using python unittest.mock 's patch. 

Below a sample snippet. I have used [memoization](https://github.com/lonelyenvoy/python-memoization), but however one may use other custom caching mechanisms for the same.
```python
from unittest.mock import patch
from boto3.session import Session
from botocore.client import BaseClient
import memoization
import time


class ResponseCachingProxyClient(BaseClient):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @memoization.cached(ttl=900, thread_safe=True, order_independent=True)  # 15 minutes
    def _make_api_call(self, *args, **kwargs):
        return super()._make_api_call(*args, **kwargs)


with patch('botocore.client.BaseClient', new=ResponseCachingProxyClient):
    session = Session()
    client = session.client('iam')
    paginator = client.get_paginator('list_users')
    start = time.time()
    for page in paginator.paginate():
        print(page)
    print("Time taken before cache:", time.time()-start)
    start = time.time()
    for page in paginator.paginate():
        print(page)
    print("Time taken after cache:", time.time()-start)
   # Futher Business logic ..... 
```
Thought of posting it here, if anyone else is looking for an interim solution for this problem.

**Comment by zdutta** [comment]
Thank you for your post @rams3sh. I would also like to point you to an external tool for application side caching: [cachetools](https://github.com/tkem/cachetools). There are [interfaces](https://github.com/tkem/cachetools/blob/master/cachetools/func.py) within this lib that may support your use case. For the time being I will close this issue (as well as https://github.com/boto/boto3/issues/2723). If we decide to take further action, will reopen and update.

**Comment by rams3sh** [comment]
Thanks @zdutta  for the response. 

I created a new project to solve this issue called botocache. 
For other's having a similar use case  can check out the project  [here](https://github.com/rams3sh/botocache).
