### ISSUE TITLE
Postgresql specific error codes missing from exceptions

### ISSUE THREAD

**Issue by mat100payette** [boto/botocore#2300]
After a bunch of searches, I've found no way to grab a SQLSTATE code from the rds client using postgres (serverless aurora).

It seems like the MySql flavor does return an error code, as per [this aurora-data-api internal function](https://github.com/chanzuckerberg/aurora-data-api/blob/509cefe2645af0d9cc21449fb739a18b13410062/aurora_data_api/__init__.py#L205), but only a message is returned for Postgresql.

Naturally, this is not ideal since parsing DB-API exception messages is subject to breaking changes due to localization and updates, whereas an error code map such as [this one for psycopg2](https://www.psycopg.org/docs/errors.html) provides much better support. [This SO answer](https://stackoverflow.com/a/11662246/6923568) also mentions this.

So, am I missing something ? Is this in the works already ? If not, are there plans for it ?
Thanks

**Comment by mat100payette** [comment]
I confirmed with RDS support and Lambda support that the SQLSTATE is not exposed by Data API. Word is this should now be in AWS backlog.

If anyone here can confirm this it would be greatly appreciated, as it's currently preventing us from properly managing all exceptions coming from it.

**Comment by zdutta** [comment]
Thank you for your post @mat100payette. I have taken a look and I am currently tracking the ticket on the service side. I will mark this as a feature request and post here when I get an update.

**Comment by mat100payette** [comment]
@zdutta Any progress at all on this ?

**Comment by mat100payette** [comment]
More than half a year and still nothing on this ? What a shame...

**Comment by tim-finnigan** [comment]
Hi @mat100payette thanks for your patience and sorry for not following up sooner. That team said a fix that includes SQLState in the error message was recently deployed. Can you confirm that?

**Comment by mat100payette** [comment]
Yes given the fact that I could make the necessary PRs where needed, this can be closed. Thanks for the support.
