### ISSUE TITLE
waiter.py: Error in wait(): raise WaiterError - RedshiftDataApi DescribeStatement FAILED status causes AttributeError

### ISSUE THREAD

**Issue by adam-kellam-ACA** [boto/botocore#2310]
I am not sure whether this belongs here or if an update to botocore is preferable to pass the expected output to waiter.py but here goes:
I am calling RedshiftDataApi in a Python3.8 Lambda and everything works fine until my statement hits the FAILED state (presumably ABORTED would cause this issue as well in my code). I am defining a custom_waiter as outlined in this [article](https://aws.amazon.com/blogs/big-data/using-the-amazon-redshift-data-api-to-interact-from-an-amazon-sagemaker-jupyter-notebook/). I am submitting queries to RedshiftDataApi via execute_statement() then using a custom_waiter to poll describe_statement() until finished state is reached. I am using Status [FAILED, ABORTED] to go to the failure state but when FAILED is reached RedshiftDataApi's describe_statement() returns a dict() with the item "Error" as expected by waiter.py but the Error (as defined in the [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift-data.html#RedshiftDataAPIService.Client.describe_statement)) returns a String value instead of the dict() value for "Error" expected by waiter.py. Currently I have coded around this with a tertiary except clause to catch the AttributeError being raised by the raiseWaterError() code block when it attempts to do: response['Error'].get('Message', 'Unknown') but it sure would be neater to get the intended WaiterError.

**Steps to reproduce**
I cannot include my full working example as it is proprietary but here is my waiter config:
    ```def get_custom_waiter(self):
        delay = 1
        max_attempts = 15
        waiter_model = WaiterModel({
            'version': 2,
            'waiters': {
                'DataAPIExecution': {
                    'operation': 'DescribeStatement',
                    'delay': delay,
                    'maxAttempts': max_attempts,
                    'acceptors': [
                        {
                            "matcher": "path",
                            "expected": "FINISHED",
                            "argument": "Status",
                            "state": "success"
                        },
                        {
                            "matcher": "pathAny",
                            "expected": ["PICKED", "STARTED", "SUBMITTED"],
                            "argument": "Status",
                            "state": "retry"
                        },
                        {
                            "matcher": "pathAny",
                            "expected": ["FAILED", "ABORTED"],
                            "argument": "Status",
                            "state": "failure"
                        }
                    ],
                },
            },
        })
        return create_waiter_with_client(waiter_name="DataAPIExecution", waiter_model=waiter_model, client=self._redshift_data_client)```
Using this waiter when I:
- Submit a SQL query with a syntax error
- Use the waiter to wait for the results of that query OR attempt to access data on a schema my IAM role is not authorized for
The Error in the debug logs below is encountered. As a workaround I have to implement a manual loop to call describe_statement and log out the string result of describe_statement()['Error'] once FAILED state is encountered.

**Expected behavior**
WaiterError should be raised instead of the AttributeError being raised in the raise WaiterError block.
Again, either string handling could be added here in waiter.py or in the RedshiftDataApi client code the error type needs to be changed to return 'dict()' as expected here instead of 'str'; but that seems like a bigger and more breaking change.
Instead the more useful error from the RedshiftDataApi client should be surfaced to assist in debugging.

**Debug logs**
Full stack trace by adding 
```
[ERROR]	2021-02-24T21:21:22.525Z	d79b5d8c-af76-4f63-af89-b27390bf67a1	'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/python/aca/customerreportsclients/redshift_history_client.py", line 62, in get_query_results
    self._custom_waiter.wait(Id=query_id)
  File "/var/runtime/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/var/runtime/botocore/waiter.py", line 312, in wait
    reason=response['Error'].get('Message', 'Unknown'),
```

**Comment by FaridNeshat-TomTom** [comment]
We also have this problem and it is very annoying.

**Comment by kdaily** [comment]
Hi @adam-kellam-ACA, we’re looking into this. Can you confirm what version you’re seeing this with? Thanks!

**Comment by adam-kellam-ACA** [comment]
@kdaily sure, it's a Python 3.8 Lambda I am getting this error deployed in our dev environment in us-east-1; here is what I get from the following code snippet in a test lambda:

from pip._internal.utils.misc import get_installed_distributions

**Code:**
from pip._internal.utils.misc import get_installed_distributions


def lambda_handler(event, context):
    print_log = ''
    for module in sorted(get_installed_distributions(), key=lambda x: x.key): 
        print_log +=  module.key + '~=' + module.version  + '\n'
    print(print_log)

**Result:**
Function Logs
START RequestId: 90dbf718-095b-4013-aff6-5955fc6d45b6 Version: $LATEST
boto3~=1.16.31
botocore~=1.19.31
jmespath~=0.10.0
pip~=20.2.3
python-dateutil~=2.8.1
rapid-client~=0.0.0
s3transfer~=0.3.3
setuptools~=49.2.1
six~=1.15.0
urllib3~=1.26.2

**Comment by zdutta** [comment]
@adam-kellam-ACA . We are looking into resolving this issue.

**Comment by kdaily** [comment]
Hi @adam-kellam-ACA,

There is a PR to address this:

https://github.com/boto/botocore/pull/2314

**Comment by adam-kellam-ACA** [comment]
Cool! OK so not sure whether to put myself out there and put this on the review for that PR or comment here; looking over the PR this appears to resolve the issue of getting an unexpected error from my custom_waiter, but I do not believe it will surface the underlying Error string being presented on the RedshiftDataAPI response; instead it appears I will get a waiter_error with the reason being "terminal failure state encountered". Once I get that error I would then have to finagle my code again to manually loop and poll RedshiftDataAPI for the response of describe_statement until it fails to see whether my issue was SQL syntax, permissions issue etc.

Is this because the onus of presenting a valid Error object should lie on the developers of the RedshiftDataAPI and not on waiter.py as the behavior here in waiter.py is absolutely correct for any valid Error response?

**Comment by zdutta** [comment]
@adam-kellam-ACA thank you for following up. So we have actually found a potential discrepancy in the custom waiter config. We believe this is why you will get a `WaiterError` with the reason being "terminal failure state encountered". We are working with them to get this fixed. We recommend custom polling logic for this case, which seems like you have already implemented. The existence of the `Error` key in the response does not by default mean that an Error object is due, in some cases the key exists and the API call is successful.

**Comment by adam-kellam-ACA** [comment]
@zdutta Makes sense! At any rate for our use case we ended up switching from the Data API to direct queries against Redshift as the performance on the Data API was substantially slower (3-600%) and our volume is such that we need the faster turnaround time.

Good to know in future other developers working with Data API will have the full response surfaced so they can read the Error string via custom_waiter instead of having to write their own polling loop. Thanks all!

**Comment by stobrien89** [comment]
Closing, as fix has been merged.  Let us know if you have any questions!
