### ISSUE TITLE
ECS Task definition doesn't show up in the list of config supported resources

### ISSUE THREAD

**Issue by PratMis** [boto/botocore#2323]
**Is your feature request related to a problem? Please describe.**
We're trying to add a functionality that would let Cloud Custodian rule engine query ECS task definitions from Config CMDB. We use shape to validate all config supported resources. 

**Describe the solution you'd like**
Would be great if this list would be updated to reflect ECS(https://github.com/boto/botocore/blob/a8d13bb5b70283f69dd518f277b050a86a40a794/botocore/data/config/2014-11-12/service-2.json#L6238)

**Comment by kdaily** [comment]
Hi @PratMis,

Thanks for the request. This change to the API would need to be made by the service team. I'm passing this request on to them.

**Comment by PratMis** [comment]
Thanks @kdaily
