### ISSUE TITLE
Personalize client list_filters cannot be paginated

### ISSUE THREAD

**Issue by plynch-chwy** [boto/botocore#2329]
**Describe the bug**
The `client.list_filters()` is the only `list_` method from the Personalize client that cannot be paginated.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/personalize.html

**Expected behavior**
I can use `paginator = client.get_paginator('list_filters')`

**Comment by kdaily** [comment]
Thanks @plynch-chwy, marking as a feature request.
