### ISSUE TITLE
IAM.Paginator.ListUserTags paginator is missing

### ISSUE THREAD

**Issue by avoidik** [boto/botocore#2345]
**Is your feature request related to a problem? Please describe.**

`ListUserTags` mapping is available, but relevant `IAM.Paginator.ListUserTags` is not

```
>>> import boto3
>>> iam = boto3.client('iam', region_name='eu-west-1')
>>> iam.get_paginator('list_user_tags')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 750, in get_paginator
    raise OperationNotPageableError(operation_name=operation_name)
botocore.exceptions.OperationNotPageableError: Operation cannot be paginated: list_user_tags
```

**Describe the solution you'd like**

`IAM.Paginator.ListUserTags` paginator as per https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListUserTags.html

```json
    "ListUserTags": {
      "input_token": "Marker",
      "limit_key": "MaxItems",
      "more_results": "IsTruncated",
      "output_token": "Marker",
      "result_key": "Tags"
    },
```

**Comment by kdaily** [comment]
@avoidik,

Thanks for the feature request. Paginators are managed by the service team so that all AWS SDKs can use them. I'll let them know of this request!
