### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token'

### ISSUE THREAD

**Issue by callum-tait-pbx** [boto/botocore#2351]
**Describe the bug**
I am trying to use an app which uses boto to assume roles in GitHub Actions. The app is running on a docker in docker setup on EKS which is setup with IRSA. I am passing through to my app container the web identity token as a volume mount 

I know you can't really help with the specifics on Actions but I was wondering if you could confirm how the error `IsADirectoryError` could crop up. I confirmed on the conatiner that the token is readable with `cat`, and a `ls -al` shows the permissions are the below. Our user in the container is root so it should be able to access the file (which `cat` confirms)

`-----    0 root     1447          1081 Apr 13 16:18 /var/run/secrets/eks.amazonaws.com/serviceaccount/token`

```yaml
jobs:
  deploy:
    runs-on: [ 'iam' ]
    container: 
      image: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/sre/cfr-deployer:1.5.0
      env:
        AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        AWS_ROLE_ARN: arn:aws:iam::$ACCOUNT_ID:role/$ROLE
      volumes:
        - /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/botocore/credentials.py", line 502, in _protected_refresh
    metadata = self._refresh_using()
  File "/usr/lib/python3.8/site-packages/botocore/credentials.py", line 643, in fetch_credentials
    return self._get_cached_credentials()
  File "/usr/lib/python3.8/site-packages/botocore/credentials.py", line 653, in _get_cached_credentials
    response = self._get_credentials()
  File "/usr/lib/python3.8/site-packages/botocore/credentials.py", line 858, in _get_credentials
    kwargs = self._assume_role_kwargs()
  File "/usr/lib/python3.8/site-packages/botocore/credentials.py", line 868, in _assume_role_kwargs
    identity_token = self._web_identity_token_loader()
  File "/usr/lib/python3.8/site-packages/botocore/utils.py", line 1722, in __call__
    with self._open(self._web_identity_token_path) as token_file:
IsADirectoryError: [Errno 21] Is a directory: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token'
```

I'm mainly asking for information around how boto determines whether the `_web_identity_token_path` provided is a file or a directory?

**Comment by callum-tait-pbx** [comment]
My file had a hard link count of 0 due to a rights issue when mounting the token.

**Comment by xlagg55** [comment]
What exactly have you done? I have the same error and on my gitlab-runner pod I can see: 

`bash-5.1$ ls -la /var/run/secrets/eks.amazonaws.com/serviceaccount/token
lrwxrwxrwx    1 root     root            12 Jul 14 14:02 /var/run/secrets/eks.amazonaws.com/serviceaccount/token -> ..data/token
bash-5.1$ ls -la /var/run/secrets/eks.amazonaws.com/serviceaccount/..data/token
-rw-r-----    1 gitlab-r nogroup       1010 Jul 15 09:15 /var/run/secrets/eks.amazonaws.com/serviceaccount/..data/token`

but what i should do to mount "token" as file with token, not the empry dir?
