### ISSUE TITLE
ap-northeast-3 missing from the return of session.session.get_available_regions("guardduty")

### ISSUE THREAD

**Issue by csvowles** [boto/botocore#2354]
**Describe the bug**
GuardDuty is now available in ap-northeast-3 (Osaka) and I've verified manually that it is available there, 
announcement:
https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-guardduty-now-available-in-aws-asia-pacific-osaka-region/

**Steps to reproduce**

```
session = boto3.Session()
gd_regions = session.get_available_regions('guardduty')
print(gd_regions)
```
which doesn't return ap-northeast-3

**Expected behavior**
ap-northeast-3 should be included in the list of guardduty available regions

Suspect the static file

https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L3228-L3237

requires updating so the newly available region is added to GuardDuty list

Similar to Issue  
https://github.com/boto/botocore/issues/2332

**Comment by stobrien89** [comment]
Hi @csvowles,

Thanks for pointing this out! I see this is a pretty recent update— It sometimes takes service teams a while to get endpoints updated for SDKs, but I'll reach out and ask them to comment on when they'll be releasing this endpoint.

**Comment by stobrien89** [comment]
P46270386

**Comment by stobrien89** [comment]
Hi @csvowles,

Thanks for your patience.  The GuardDuty team looked into it and it turns out `ap-northeast-3` made it into our endpoints.json file yesterday.  Closing for now, but let us know if anything else comes up!
