### ISSUE TITLE
Include gp3 Volume type in `create_launch_configuration`

### ISSUE THREAD

**Issue by free88dom** [boto/botocore#2360]
As AWS come up with new Volume type, the "gp3" is missing as option in `create_launch_configuration` - `VolumeType`

**Comment by stobrien89** [comment]
Hi @free88dom,

Thanks for pointing this out!  Just to clarify, are you suggesting we add the `gp3` value to our documentation, or does the `gp3` value not work when provided (or both)?  I looked at the botocore model for autoscaling and it appears the values for `BlockDeviceMappings` -> `Ebs` -> `VolumeType` are not defined there, but rather validated by the service itself.

**Comment by free88dom** [comment]
Hi @stobrien89,
it's missing completely there, you can't use it if you provide it as an option. The botocore raises an error. By now, at BlockDeviceMappings -> Ebs -> VolumeType are defined only `Valid Values: standard | io1 | gp2 | st1 | sc1`

**Comment by stobrien89** [comment]
Hi @free88dom,

I did some testing this morning and confirmed that it looks like this is a matter of implementation by the service:

```
<ErrorResponse xmlns="http://autoscaling.amazonaws.com/doc/2011-01-01/">\n  <Error>\n    <Type>Sender</Type>\n
<Code>ValidationError</Code>\n    <Message>gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
</Message>\n  </Error>\n  <RequestId>RequestID</RequestId>\n</ErrorResponse>\n'
```

Most of the code in botocore service models is generated by the service, but you've still reached the right place!  I'm going to send a feature request to the autoscaling team.  I can't guarantee response/implementation time on their behalf, but I'll let you know as soon as I have an update.

**Comment by stobrien89** [comment]
P46519029

**Comment by stobrien89** [comment]
Hi @free88dom,

I heard back from the service team— They are currently working on adding the additional `gp3` VolumeType.  I wasn't given a timeline for implementation, but I'll let you know as soon as I have an update!

**Comment by CA096339** [comment]
Hi AWS Team,
We have a customer requirement inorder to enable the launch Configuration to support gp3 in CloudFormation. Please let us know the current update!!

**Comment by stobrien89** [comment]
Hi @CA096339, 

Thanks for reaching out.  It's still a work in progress, but I'm tracking their ticket on this issue and will provide any updates I can once received!
