### ISSUE TITLE
Reopen and review PR-1921

### ISSUE THREAD

**Issue by dazza-codes** [boto/botocore#2362]
A github-bot closed this PR for no good reason
- https://github.com/boto/botocore/pull/1921/files

**Comment by kdaily** [comment]
Hi @dazza-codes, I responded on the PR:

https://github.com/boto/botocore/pull/1921#issuecomment-833741247

I proposed that the original feature request #1915 remains open but reframed to see if other users are impacted by the limitations of the waiter implementation.
