### ISSUE TITLE
AssumeRoleCredentialFetcher's _create_client() doesn't have an endpoint_url argument

### ISSUE THREAD

**Issue by kbalk** [boto/botocore#2364]
**Is your feature request related to a problem? Please describe.**

We test our lambda using LocalStack, where LocalStack provides a mock AWS stack.  In order to use LocalStack, the lambda must instantiate AWS clients with the appropriate LocalStack endpoint URL (e.g., "http://localstack:4566").  This work's fine except when we use botocore's `AssumeRoleCredentialFetcher` class.  We use the `AssumeRoleCredentialFetcher` class to create a session which provides refreshable credentials for an assumed role.  In the process,  `AssumeRoleCredentialFetcher` creates an STS client for us.

One of the arguments for the `AssumeRoleCredentialFetcher` class is `client_creator`.  When `AssumeRoleCredentialFetcher` executes the class method `_client_creator()` (shown below), it invokes the function provided by the `client_creator` argument.  `_client_creator()` does not allow an `endpoint_url` argument.  

As we are unable to provide `_client_creator()` with a LocalStack endpoint when it creates a STS client, testing the lambda is no longer straightforward.

https://github.com/boto/botocore/blob/4f23912b3bf2fef504b5476d92f7c75597de10db/botocore/credentials.py#L833-L841

**Describe the solution you'd like**

There is an `extra_arg` argument fo `AssumeRoleCredentialFetcher` that could be used to supply an `endpoint_url` argument, which could then be passed to `_client_creator()`.  However, as `extra_arg` is used for extra arguments to `assume_role()`, either an `endpoint_url` argument would have to be extracted from the rest of the `extra_arg` values or another parameter would need to be added to `AssumeRoleCredentialFetcher` to be used as extra arguments to `_client_creator()` (this is probably the optimal solution).

https://github.com/boto/botocore/blob/4f23912b3bf2fef504b5476d92f7c75597de10db/botocore/credentials.py#L764-L767

**Comment by stobrien89** [comment]
Hi @kbalk,

Thanks for the feature request!  I'll review this with the team, although I can't make any guarantees as to when/if this would be implemented.
