### ISSUE TITLE
Add waiters for Imagebuilder.

### ISSUE THREAD

**Issue by OrEisenberg** [boto/botocore#2383]
It's come to my attention in the course of my trying to build out an automated image creation pipeline the `botocore` does not currently have any waiters for the imagebuilder service. As such, unless I want to use the Java SDK or Ruby SDKs (which from what I can tell allow for the ability to wait for the creation of an image to complete in their own ways), then I would have to do something pretty gross like write a loop which continually tries to use the `get_image` method of the `boto3` imagebuilder client and check the state in order to achieve this functionality. SOS! 

**Describe the solution you'd like**
Addition of a `waiter` to the imagebuilder functionality which allows one to await the creation of an image. Either that or a recommendation of how to effectively achieve the same end result! 

**Update**: I've found the `WaiterModel` class which can be used to define custom waiters. Please let me know if after I've written my custom waiter, you would be interested in my creating a pull request.

**Comment by kdaily** [comment]
Hi @OrEisenberg,

Thanks for the request. Waiters are implemented by the service team so that all SDKs that support them have the same model. I will forward this request to the Image Builder team for consideration.
