### ISSUE TITLE
Migrate to pytest

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [boto/botocore#2388]
I noticed there is a branch https://github.com/boto/botocore/tree/pytest_migration which was contributed by one of my teammates (Hi @mcepl!), and I'd like to offer to help to get it merged to develop. What do you think the next steps are? Should we break it up into bitesized chunks, or merge develop into it and swallow the pain?

**Comment by mcepl** [comment]
branch rebased on the top of the current `develop` as https://github.com/mcepl/botocore/tree/pytest_migration

**Comment by stobrien89** [comment]
Hi @mcepl and @s-t-e-v-e-n-k,

Thanks for re-surfacing this!  I'll review with the team tomorrow to get their thoughts on this.

**Comment by s-t-e-v-e-n-k** [comment]
@stobrien89 Hi! Was there anything for us to do here?

**Comment by stobrien89** [comment]
Hi @s-t-e-v-e-n-k ,

My apologies, I reviewed this with the team a few weeks ago and forgot to provide an update.  Nothing needs to be done on your end for right now— We basically need to update some of our internal tooling for use with pytest, which is no small task, but it is something we are planning to do in the near future.  I'll let you know when I have another update!

**Comment by mcepl** [comment]
@stobrien89 Could you please elaborate on that “near future”, please? botocore is the last package which still holds nose in openSUSE/Factory, and I would LOVE to kill it (for many including some important reasons).

Also, concerning #2458, somebody mentioned nose2pytest there. Please, just don’t. Conversion from nose to unittest or pytest is not that horribly complicated  (especially when run at runtime trying to convert tests on the fly, which in itself is a frightful idea) and nose2pytest will still keep nose around.

**Comment by stobrien89** [comment]
Hi @mcepl,

Thanks for reaching out.  As far as I know, there are no plans to utilize nose2pytest.  It's really tough to say right now what *near future* is.  I'd imagine by the end of this year/early next year, but there are some internal hurdles we have to face before we're able to do this.  https://github.com/boto/boto3/issues/2963#issuecomment-907533798 pretty much sums it up.

**Comment by nateprewitt** [comment]
Alright, thanks everyone for the patience here. We've finally been able to resolve our issues with the testing infrastructure and successfully completed the migration to pytest this week. As of boto/boto3#3000 and #2495, we should be finished. There are still some minor warnings that need to be resolved and general testing optimizations to be made but I think the core of the request in this ticket should be resolved.

We'll track remaining work separately. Please feel free to open a new ticket if you have further feature requests around this.
