### ISSUE TITLE
Expose the exception type (and other helpful information) from configparser

### ISSUE THREAD

**Issue by skyzyx** [boto/botocore#2395]
**Is your feature request related to a problem? Please describe.**

I am a user of AWS Organizations, as well as having multiple AWS-using freelance clients, and my own personal AWS account. As a result I have over 160 profiles in my `~/.aws/config` file.

Today, after adding  a couple dozen more profiles for recently-provisioned accounts, I started getting the following error from the AWS CLI.

```plain
Unable to parse config file: /Users/{me}/.aws/config
```

However, there was no additional information to help me debug. Was it an issue with line endings? Spacing around `=` signs? A typo somewhere?

After a few hours of poking around, I tracked it down to this line in `botocore`: https://github.com/boto/botocore/blob/6451ae1fad57f4453af97649e7ed9192b0f623be/botocore/configloader.py#L147-L152

The issue was that I'd inadvertently duplicated a key (similar to #2311).

**Describe the solution you'd like**

Looking at [the read() method of configparser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read), and in-turn [configparser exceptions](https://docs.python.org/3/library/configparser.html#configparser.DuplicateSectionError), I'd like to see a little more information exposed from the underlying `configparser` class when an exception occurs, so that it doesn't take so long to track down the source of the problem.

With AWS continuing to get exponentially more complex over the years, I'm certainly not the only one responsible for managing hundreds of accounts.

Thank you.

**Comment by stobrien89** [comment]
Hi @skyzyx,

Thanks for the feature request!  Sorry you had to spend such a long time troubleshooting.  I'll make sure the team sees this.
