### ISSUE TITLE
S3 uses path-style URLs

### ISSUE THREAD

**Issue by AriFordsham** [boto/botocore#2397]
**Describe the bug**
The models in botocore/data/s3/2006-03-01/service-2.json describe path-stype URLs, which are deprecated (<https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/>). This breaks [amazonka](https://github.com/brendanhay/amazonka) which relies on them, and cannot process the 301 redirects used in eu-west-2.

**Expected behavior**
The models should describe virtual-hosting URLs, which are current best practice for AWS.

**Comment by AriFordsham** [comment]
Ah. I see. boto deals with this in code. https://github.com/boto/botocore/pull/52

**Comment by kdaily** [comment]
Hi @AriFordsham,

As you've found this is implemented in the code. The models here come from upstream and are shared across all AWS SDKs. Can you clarify a line of the model that you're referring to? I'm not sure what I can do to make any changes here, as they come from the S3 team. Thanks!

**Comment by AriFordsham** [comment]
https://github.com/boto/botocore/blob/2a04c69389446b6cffd6972f00aec5b74bdd5639/botocore/data/s3/2006-03-01/service-2.json#L20
https://github.com/boto/botocore/blob/2a04c69389446b6cffd6972f00aec5b74bdd5639/botocore/data/s3/2006-03-01/service-2.json#L35
https://github.com/boto/botocore/blob/2a04c69389446b6cffd6972f00aec5b74bdd5639/botocore/data/s3/2006-03-01/service-2.json#L46
...and ~91 others.

These  models describe path-style URLs, which are on the deprecation path. Boto corrects for this, and defaults to virtual-hosting style using hard-coded logic that corrects URLs before request.

The correction logic essentially does two tasks:
1. Prepends the bucket name to the hostname
2. Strips the bucket name prefix from the URL.

It would arguably cleaner design if this could be reflected in the model itself (This would also make it easier for third-party consumers of the models). Of course, this would be subject to the limitations of the model format - I don't know if this is documented anywhere.

(1) could be achieved by prepending the bucket name to https://github.com/boto/botocore/blob/2a04c69389446b6cffd6972f00aec5b74bdd5639/botocore/data/s3/2006-03-01/service-2.json#L6-L7, conditional on a URL style variable (or  prepending a variable which is conditionally set to either the bucket name or empty conditional on the path style).

(2) could be acheived similarly by making the bucket field (e.g. https://github.com/boto/botocore/blob/2a04c69389446b6cffd6972f00aec5b74bdd5639/botocore/data/s3/2006-03-01/service-2.json#L20) conditional on a path-style flag.

I have created PRs to illustrate these two approaches (only modifying one operation out of ~94 as an example):

- #2399 assumes a ternary operator in the JSON template format

- #2400 assumes two new variables:
  - `vhBucket` is the empty string in case of path-style, or the bucket name appended with a `.` in the event of virtual-hosting style
  - `pathBucket` is the bucket name appended with `/` in case of path-style, or the empty string in the event of virtual-hosting style

**Comment by AriFordsham** [comment]
Ping @garnaat @jamesls because they were involved with #52

**Comment by kdaily** [comment]
Hi @AriFordsham,

Thanks for opening this. Unfortunately there isn't anything that the Python SDK can do here to help. As an example, the .NET SDK uses the same upstream information for their own models:

https://github.com/aws/aws-sdk-net/blob/cac3cf7e0bbb150bcd671eb9a92980001cb5a19e/generator/ServiceModels/s3/s3-2006-03-01.api.json#L20

This decision is with the S3 team. Based on current information from the blog posts you've linked, path-style URLs won't be "deprecated" for at least a year from September 2020, and likely longer than that:

> We have also heard feedback from customers that virtual hosted-style URLs should support buckets that have dots in their names for compatibility reasons, so we’re working on developing that support. Once we do, we will provide at least one full year prior to deprecating support for path-style URLs for new buckets.

I will pass along your sentiment to the S3 team. If you want to follow up with S3 engineers directly, I would suggest the AWS Developer Forum for S3:

https://forums.aws.amazon.com/forum.jspa?forumID=24
