### ISSUE TITLE
Support for python3.9

### ISSUE THREAD

**Issue by sahilvv** [boto/botocore#2405]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Need botocore library supported for python3.9. Currently setup.py lists the max version supported as python3.8

**Describe the solution you'd like**
Support botocore on python3.9

**Comment by stobrien89** [comment]
Hi @sahilvv,

Thanks for the feature request! I'll make sure the team sees this.

**Comment by nateprewitt** [comment]
This was resolved with #2498. Python 3.9 is officially supported in botocore 1.21.49 and later.
