### ISSUE TITLE
[consent request] I added botocore-stubs package to PyPI

### ISSUE THREAD

**Issue by vemel** [boto/botocore#2408]
Hello,

In order to have type checking and code auto-complete in IDE while working with `boto3`/`botocore`, I created type annotations package for `botocore` in a scope of [mypy_boto3_builder](https://github.com/vemel/mypy_boto3_builder) project.

Package has to be named `botocore-stubs` to be recognized by type checkers as type annotations for `botocore`. So please let me know if it is okay to use `botocore` in the name of the package.

Thank you!

**Comment by kdaily** [comment]
Hi @vemel, I'm still waiting to hear back from the legal team regarding this request (from https://github.com/boto/boto3/issues/2213). I'll let you know when I hear more.

**Comment by kdaily** [comment]
Hi @vemel,

Thanks again for your patience.

We have concluded that the use of the name is OK as long as it’s explicitly made clear that it is not endorsed or affiliated with AWS.
