### ISSUE TITLE
New botocore 1.20.96 is not listed in the pypi index and is causing issues

### ISSUE THREAD

**Issue by sudopla** [boto/botocore#2418]
**Describe the bug**
We have a local python repo that is using `pypi` as upstream. The latest `boto3` version requires botocore>=1.20.96 but the problem is that this version is not listed in `pypi` and that's causing problems.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/20730079/122297633-bed04280-cec9-11eb-8f42-ddeef83c7178.png">

Could you please check why the latest botocore version is not there? https://pypi.org/search/?q=botocore&o=

**Debug logs**
ERROR: Could not find a version that satisfies the requirement botocore==1.20.96
ERROR: No matching distribution found for botocore==1.20.96

**Comment by nateprewitt** [comment]
Hi @sudopla,

I'm seeing botocore 1.20.96 [uploaded on PyPI](https://pypi.org/project/botocore/#history) as of 2 hours ago. I'm also getting botocore 1.20.96 when performing both:

```
pip install --upgrade botocore
```
and
```
pip install botocore==1.20.96
```

Could you provide more info about what version of Python and pip you're using?

**Comment by sudopla** [comment]
Thanks @nateprewitt, I'm wondering why the latest version is not listed here https://pypi.org/search/?q=botocore&o= and if that's affecting the way a local repo look for packages in pypi? 
I do see the latest version for boto3 listed https://pypi.org/search/?q=boto3&o=

**Comment by nateprewitt** [comment]
The search functionality should not be tied to the PyPI simple index which standard package mirrors should be pulling from. You can also see the package correctly listed [there](https://pypi.org/simple/botocore/). It's possible there may be a replication delay/issue that's preventing front end search index from catching up.

We've tried pulling the latest release from multiple geographic locations and platforms, but are unable to reproduce this issue using the standard PyPI index.

**Comment by sudopla** [comment]
Thank you very much for the explanation @nateprewitt! I'll try to figure out then what's happening on my side.
