### ISSUE TITLE
Mask proxy credentials before raising exception

### ISSUE THREAD

**Issue by RJKeane2000** [boto/botocore#2422]
**Describe the bug**
When the proxy fails, an exception is raised which displays the proxy_url. For secured proxies, the proxy_url may contain the credentials in the format https://appId:password@myproxy.com.  In the pipeline, the credentials will be provided as variables so they are not visible in the logs but if an exception happens, httpSession.py raises an exception that includes the true proxy url in the error message.

Example:

In pipeline the proxy url would looke like this: https://$APP_ID:$PASSWORD@myproxy.com 

In the exception it looks like this:

`Failed to connect to proxy URL: https://sampleAppId:monkey123@myproxy.com`

Connection issues can be caused by network problems as well as invalid id and password. 

**Steps to reproduce**
Try to hit an endpoint through a secured proxy but put in a bogus id/password. 

I ran into this in a Gitlab pipeline executing the aws cli which uses botocore.

**Expected behavior**

The same exception is produced but the credentials are masked. This prevents exposing credentials in Git pipelines when there are issues with the proxy.

Example:

`Failed to connect to proxy URL: https://****:******@myproxy.com`

**Debug logs**
N/A

**Comment by stobrien89** [comment]
Hi @RJKeane2000,

Thanks for reaching out!  Marking this as a feature request.

**Comment by RJKeane2000** [comment]
Thank you!

**Comment by jonchapmansai** [comment]
@zhan9san I was having the same issue as @RJKeane2000 
Your PR seems to fix the issue

**Comment by RJKeane2000** [comment]
Thank you @zhan9san for the fix. Sorry I missed your request. I didn't receive a notification for some reason. Thanks for verifying the fix @jonchapmansai!

**Comment by nateprewitt** [comment]
Hello @RJKeane2000, @zhan9san, @jonchapmansai,

Thank you for bringing this to our attention. As you’ve probably seen, we were able to review the PR yesterday and merged the necessary changes. We completed a release today that includes the required updates. Here is a quick summary for future readers:

Prior to the release of Botocore 1.23.41, customers using the AWS CLI and Boto3 could potentially receive errors containing their full proxy URL when failing to connect to a proxy. If the proxy URL contained user information, this may have been included in logs where exceptions are recorded. We have improved ProxyConnectionError to programmatically strip user information from all URLs before raising an exception, and we recommend customers upgrade to Boto3 1.20.41 and AWS CLI 1.22.41.

Please let us know if you have any more questions or concerns.
