### ISSUE TITLE
add waiters for RDS Export Snapshot to S3

### ISSUE THREAD

**Issue by miketheman** [boto/botocore#2434]
**Is your feature request related to a problem? Please describe.**
We can already initiate an RDS Snapshot Export to S3 via the API
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.start_export_task

We can also use a `describe` call to tell us whether it's completed or not.

**Describe the solution you'd like**

A [Waiter](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#waiters) that a client can call after issuing a `start` export command that can wait until the export task is completed.

My understanding is that these kinds of requests cannot be added in this repo, rather the JSON must be modified upstream of botocore.

**Comment by stobrien89** [comment]
Hi @miketheman,

Thanks for reaching out!  You're correct in your understanding of these types of requests— waiters and paginators are the responsibility of the corresponding service team, as they know best what the appropriate number of timeouts/retries, etc. should be.  

I've opened an internal ticket with the RDS team to relay your request.  I'll let you know as soon as I've heard back!

**Comment by stobrien89** [comment]
P49551612

**Comment by miketheman** [comment]
> Did this issue was really implemented in the end?

It doesn't appear so. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#waiters

@stobrien89 I guess the internal ticket died out?
