### ISSUE TITLE
TransportError ... is now earlier than... occurring irregularly

### ISSUE THREAD

**Issue by risoms** [boto/botocore#2465]
**Describe the bug**

We are seeing a regular occurrence of `TransportError` using boto3. This can occur in the magnitude of minutes as well as days.

**Steps to reproduce**
```py
import boto3
from elasticsearch.helpers import scan

credentials = boto3.session.Session().get_credentials()
auth = AWS4Auth(credentials.access_key, credentials.secret_key...)
es = Elasticsearch(http_auth=auth....)
scan(client=es, query=body)
```

**Expected behavior**
When using elasticsearch.helpers.scan, we're expecting to see an abstraction of elasticsearch scroll() API. Usually this works.

**Debug logs**
```py
Signature expired: 20210805T032751Z is now earlier than 20210817T205124Z (20210817T205624Z - 5 min.)
```

**Comment by stobrien89** [comment]
Hi @risoms,

Sorry to hear you're having issues.  Have you ruled out clock skew as a possible cause?  This seems to be the most common culprit for the `Signature expired` message you're seeing there.  Could you provide a detailed overview of your environment? Thanks!

**Comment by ssukang** [comment]
Hi @stobrien89 thanks for your input! 
And yes that was our original suspicion as well, but we found this in our log system: 

recorded 7/22/21 3:45:53.142 PM
`{"@time": "2021-07-22T20:45:53.142044", "@level": "INFO", "@remote_address": "XX", "@process": 12, "@hostname": "XXX", "@user": "XXXX", "@method": "GET", "@path": "[some_api]", "@url": "[some_url]", "@filename": "connection.py", "@funcname": "set_auth", "@message": "Current time: 2021-07-22 20:45:53.141861; expiry_time: 2021-07-23 02:18:32+00:00; time_fetcher: 2021-07-22 20:45:53.141889+00:00"}`

recorded 7/22/21 3:47:18.448 PM
`{"@time": "2021-06-27T23:55:00", "@level": "ERROR", "@remote_address": "XX", "@process": 15, "@hostname": "XX", "@user": "XXXX", "@method": "GET", "@path": "[some_api]", "@url": "[some_url]", "@filename": "views.py", "@funcname": "get_context_data", "@message": "TransportError(403, '{\"message\":\"Signature expired: 2021-06-27T23:55:00Z is now earlier than 2021-07-22T20:42:18Z (2021-07-22T20:47:18Z - 5 min.)\"}')"}`

We see here that somehow the time went from `2021-07-22T20:45:53.142044` -> `2021-06-27T23:55:00`, and can confirm that these two come from the same time source. 

This is running in AWS Ubuntu 16.04.3 LTS xenial, and we are syncing time with chronyc 2.1.1. Please let me know if you need any other environment specs.

**Comment by stobrien89** [comment]
Hi @ssukang,

Thanks for the additional information!  It definitely appears something is amiss with chrony— I'd suggest [configuring it to use the Amazon Time Sync Service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service-ubuntu#configure-amazon-time-service-ubuntu) if you haven't already.  Let me know if you already have!

**Comment by stobrien89** [comment]
Hi @ssukang,

Sorry for the delay. I'm assuming you meant the `expiry_time`, but let me know if I'm mistaken.  The `expiry_time` is just sourced from refreshable credentials (i.e. whenever they are set to expire by IAM).  How are you sourcing your credentials?

I know you mentioned that you followed the steps in the article I linked, but could you confirm that you still see  `169.254.169.123` as a source when running `chrony sources -v`?
