### ISSUE TITLE
Enforcing TLS 1.2+ when connecting to AWS

### ISSUE THREAD

**Issue by mmlado** [boto/botocore#2488]
In the Boto3 documentation there is a chapter describing how to enforce TLS 1.2+ for the connection to an AWS service.
[https://boto3.amazonaws.com/v1/documentation/api/latest/guide/security.html#enforcing-tls-1-2](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/security.html#enforcing-tls-1-2)
This is a good security practice. To solution in this documentation is to compile OpenSSL without lower versions of TLS and then compile Python using that OpenSSL.
I know that the highest version of the protocol will be negotiated. AWS updates it's services to use the latest version and modern Pyhton is also supporting the latest versions. I theory it won't happen that a lower version is used.

Enforcing TLS 1.2+ can be also done on the code level with modern Python versions.
A custom SSLContext is already created in botocore: [https://github.com/boto/botocore/blob/bec6621ef0e515267f106ce4b8ab56dfd3c57e6d/botocore/httpsession.py#L56](https://github.com/boto/botocore/blob/bec6621ef0e515267f106ce4b8ab56dfd3c57e6d/botocore/httpsession.py#L56)
This context already has some of the protocols disabled, like: SSLv2/3
It could be checked if the `minimum_version` property is available and set if to: `TLSVersion.TLSv1_2`. This should be available from Python 3.7.
Other suggestion would be to add: `OP_NO_TLSv1 | OP_NO_TLSv1_1` to options dependent on Python version.
Not sure if there's a way to detect the available protocols.
It would be possible to pass ssl_version into the function, but that is not used and would require a lot of change.
[https://github.com/boto/botocore/blob/bec6621ef0e515267f106ce4b8ab56dfd3c57e6d/botocore/httpsession.py#L243](https://github.com/boto/botocore/blob/bec6621ef0e515267f106ce4b8ab56dfd3c57e6d/botocore/httpsession.py#L243)

I can send a pull request with the changes. I was wondering if there is a reason to not add a change and increase the security of the system.

**Comment by nateprewitt** [comment]
Hi @mmlado,

Thanks for the feature request! This is definitely on our radar for improving in the near future. We'd originally been waiting to implement changes around this until Python 2.7 was dropped. Now that that's out of the way though, I think we'll likely want to look at adding an opt-in config option to preserve backwards compatibility. We'll provide an update once we have more specifics on design.

**Comment by philippsimon** [comment]
Hi @nateprewitt 

Is there a roadmap for this issue? We have the requirement at the Volkswagen Group to connect to AWS with TLS 1.2+ and I guess it's the same in many other companies, too.

**Comment by nateprewitt** [comment]
Hi @philippsimon, thanks for checking in! This feature doesn't have a strict timeline at the moment that I can share. We'd like to add broader functionality to allow customers to provide their own SSLContext with whatever configurations fit their needs but it's a non-trivial change.

To clarify the situation, AWSCLI/Boto3/Botocore all support TLS 1.2 and 1.3 out of the box. We should negotiate a connection using those for standard requests to AWS if the host allows it.

For companies enforcing strict TLS 1.2+ compliance, we'd _strongly_ recommend disabling older TLS versions at the interpreter level. We provide a guide on doing so [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/security.html#enforcing-tls-1-2). This prevents risk of misconfigurations in source code, and is usually the required approach for companies implementing compliance requirements.

I'll provide an update here for SSLContext configuration options once we have a clearer timeline.

**Comment by philippsimon** [comment]
@nateprewitt thanks a lot!!

**Comment by mmlado** [comment]
Has there been made any decision on this issue? Python 3.6 has also reached the end-of-life date. As I can see botocore minimum version has been also set for Python 3.7.
