### ISSUE TITLE
Missing `subtitles` params in `start_transcription_job` method

### ISSUE THREAD

**Issue by CzBiX** [boto/botocore#2506]
**Describe the bug**
Missing `subtitles` params in `start_transcription_job` method

**Steps to reproduce**
https://docs.aws.amazon.com/transcribe/latest/dg/subtitles.html#subtitles-howto-sdk

**Expected behavior**
Works

**Debug logs**
```
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Subtitles", must be one of: TranscriptionJobName, LanguageCode, MediaSampleRateHertz, MediaFormat, Media, OutputBucketName, OutputKey, OutputEncryptionKMSKeyId, Settings, ModelSettings, JobExecutionSettings, ContentRedaction, IdentifyLanguage, LanguageOptions
```

**Comment by CzBiX** [comment]
Found it already fixed in repo😅

**Comment by Alavi1412** [comment]
I'm using boto3 version '1.21.0' and have the same problem.
