### ISSUE TITLE
easy_install boto3 1.18.60 broken dependency on botocore 1.21.60

### ISSUE THREAD

**Issue by sigJoe** [boto/botocore#2530]
**Describe the bug**
AWS Elastic Beanstalk deployments are trying (and failing) to run easy_install boto3:
`No local packages or working download links found for botocore<1.22.0,>=1.21.60`

It's checking the pypi repo (https://pypi.org/simple/botocore/) which has the whl but is missing a tar.gz for the latest (1.21.60) release.

I don't know if this is more a boto3 problem or a botocore problem, but it seemed right to put it here

**Steps to reproduce**
- Execute `easy_install boto3`

**Expected behavior**
Install!

**Debug Logs**
```
$ sudo easy_install boto3
Password:
Searching for boto3
Reading https://pypi.org/simple/boto3/
Downloading https://files.pythonhosted.org/packages/27/98/c9f627e7017ab4191818ef08a345390689b66e45d6fa3f4a57d1aa8c9a25/boto3-1.18.60.tar.gz#sha256=45709a04ec5fb67ce5a8eaade3eb0ab24d6eb08d9a9ca6bdb2153047896197fc
Best match: boto3 1.18.60
Processing boto3-1.18.60.tar.gz
Writing /tmp/easy_install-tipgbV/boto3-1.18.60/setup.cfg
Running boto3-1.18.60/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tipgbV/boto3-1.18.60/egg-dist-tmp-uZK9pK
zip_safe flag not set; analyzing archive contents...
boto3.session: module references __file__
boto3.docs.service: module references __file__
creating /Library/Python/2.7/site-packages/boto3-1.18.60-py2.7.egg
Extracting boto3-1.18.60-py2.7.egg to /Library/Python/2.7/site-packages
Adding boto3 1.18.60 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/boto3-1.18.60-py2.7.egg
Processing dependencies for boto3
Searching for s3transfer<0.6.0,>=0.5.0
Reading https://pypi.org/simple/s3transfer/
Downloading https://files.pythonhosted.org/packages/88/ef/4d1b3f52ae20a7e72151fde5c9f254cd83f8a49047351f34006e517e1655/s3transfer-0.5.0.tar.gz#sha256=50ed823e1dc5868ad40c8dc92072f757aa0e653a192845c94a3b676f4a62da4c
Best match: s3transfer 0.5.0
Processing s3transfer-0.5.0.tar.gz
Writing /tmp/easy_install-y7Qz1i/s3transfer-0.5.0/setup.cfg
Running s3transfer-0.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y7Qz1i/s3transfer-0.5.0/egg-dist-tmp-7um8Q3
zip_safe flag not set; analyzing archive contents...
Copying s3transfer-0.5.0-py2.7.egg to /Library/Python/2.7/site-packages
Adding s3transfer 0.5.0 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/s3transfer-0.5.0-py2.7.egg
Searching for botocore<1.22.0,>=1.21.60
Reading https://pypi.org/simple/botocore/
No local packages or working download links found for botocore<1.22.0,>=1.21.60
error: Could not find suitable distribution for Requirement.parse('botocore<1.22.0,>=1.21.60')```

**Comment by joguSD** [comment]
I'm investigating this... it's strange that the source dist is available here:
https://pypi.org/project/botocore/#files
But not via `pip` or `easy_install` https://pypi.org/simple/botocore/

Trying to determine if this is an issue on the PyPI side or something we did.

It's worth noting though that this version of `botocore` / `boto3` are not supported on Python 2.
You should pin to the last supported version of `boto3` using: `boto3==1.17.112`, which was the last version to support Python 2.

It's also worth noting `easy_install` is deprecated as well:
https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Can you provide more context on your setup?
