### ISSUE TITLE
Add cloudtrail endpoint for ap-northeast-3

### ISSUE THREAD

**Issue by 0xdabbad00** [boto/botocore#2555]
**Describe the bug**
Cloudtrail exists in ap-northeast-3, but there is no end-point for it listed in the endpoints file: https://github.com/boto/botocore/blob/742df860f38bc3d70a0a74a1cf7efdb3bed776fb/botocore/data/endpoints.json#L1736

As a result, tooling that calls get_available_regions is not able to know Cloudtrail exists there.

**Comment by tim-finnigan** [comment]
Hi @0xdabbad00, thanks for bringing this to our attention. Endpoints are generated upstream by service teams so I created a ticket for the Cloudtrail team to add this endpoint. I'll post an update here when I hear back from them.

**Comment by tim-finnigan** [comment]
P54774474

**Comment by tim-finnigan** [comment]
The ap-northeast-3 endpoint has been added for Cloudtrail [here](https://github.com/boto/botocore/blob/d0b5610106428d471abee1883f877f6ca6ce2cab/botocore/data/endpoints.json#L1952). Thanks for reporting this, closing the issue now.
