### ISSUE TITLE
Cloudfront documentation - Field marked as optional when it isn't

### ISSUE THREAD

**Issue by bblommers** [boto/botocore#2570]
Service: Cloudfront
Feature: CreateDistribution
Field: Comment

This field is required, but the documentation says it is 'An optional comment':
https://github.com/boto/botocore/blob/develop/botocore/data/cloudfront/2020-05-31/service-2.json#L3658

**Comment by tim-finnigan** [comment]
Thanks @bblommers for pointing this out! That documentation is generated upstream by service teams so I will reach out to the Cloudfront team to correct this.

**Comment by tim-finnigan** [comment]
P55751302

**Comment by bblommers** [comment]
Thanks @tim-finnigan. 
If there are other improvements in the Cloudfront-docs, do you prefer to have separate tickets for them, or can they be accumulated here?

E.g. https://github.com/boto/botocore/blob/develop/botocore/data/cloudfront/2020-05-31/service-2.json#L3588
The field 'ActiveTrustedSigners' in the GetDistribution request contains this documentation:

`CloudFront automatically adds this field to the response if you’ve configured a cache behavior in this distribution to serve private content using trusted signers`

This is false - the field is always returned, but marked as `<Enabled>False</Enabled>` if no such cache behaviour exists.

The same goes for the `ActiveTrustedKeyGroups`-field - same documentation, but it's always returned.

**Comment by bblommers** [comment]
There is another.. I'm just going to list them here until I hear otherwise :slightly_smiling_face: 

Action: `DeleteDistribution`
Field: `IfMatch`

https://github.com/boto/botocore/blob/develop/botocore/data/cloudfront/2020-05-31/service-2.json#L3329

This field is not listed as `required`, but I always get an error when this parameter is not provided.
`The If-Match version is missing or not valid for the resource.`

**Comment by tim-finnigan** [comment]
Thanks @bblommers - I have passed along your comments to the Cloudfront team. Please feel free to list any more related feedback here in this issue.

**Comment by tim-finnigan** [comment]
Thanks for your patience - I have been advised the the documentation issues have been fixed. If there are still any issues you see with documentation, we recommend reaching out via the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=CloudFront&topic_url=http://docs.aws.amazon.com/en_us/cloudfront/latest/APIReference/API_CreateDistribution.html) links at the bottom of API documentation pages such as [CreateDistribution](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateDistribution.html). This is the most direct way to assure that your feedback reaches the appropriate team, as the documentation for SDKs like boto3 is pulled from models generated updated by service teams. If you have a support plan with AWS then you can also consider reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for issues such as these.
