### ISSUE TITLE
change the default to use regional endpoints for sts

### ISSUE THREAD

**Issue by mmerickel** [boto/botocore#2577]
**Is your feature request related to a problem? Please describe.**

Related to the outages in us-east-1, it was identified that boto3/botocore is using the global sts endpoint (`AWS_STS_REGIONAL_ENDPOINTS=legacy`) by default. This affected code running in other regions, causing them to fail to use IRSA in EKS to `AssumeRoleWithWebIdentity`.

**Describe the solution you'd like**

AWS CLI v2 already changed the default to "regional" [1]. boto should follow suit and do the same as it's clearly a better default.

https://github.com/boto/botocore/blob/e0e8e1c656ef15fa44299f58c89faf9278e357ba/botocore/configprovider.py#L107-L110

[1] https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-config-sts_regional_endpoints

**Comment by tim-finnigan** [comment]
Hi @mmerickel, thanks for reaching out. You make a good point and using regional endpoints is also recommended [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) for STS:

> AWS recommends using Regional AWS STS endpoints instead of the global endpoint to reduce latency, build in redundancy, and increase session token validity. 

However, it would be a breaking change for users who expect and rely on the current behavior. But this is something that can be addressed in the next major version of boto3, similar to how it was introduced in CLI v2 as noted [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-sts-regional-endpoint). 

In the meantime you can specify the regional endpoint in boto3 as described here in [this comment](https://github.com/boto/boto3/issues/1859#issuecomment-461622548).

**Comment by mmerickel** [comment]
Why close this issue? Is there another place where the boto roadmap is tracked? The ticket was labeled a feature request and it sounds like it is acknowledged to be a good request…

**Comment by tim-finnigan** [comment]
@mmerickel The reason for closing this is because we generally keep feature requests open to track community demand and discuss use cases. In this case I think you have a valid ask, but due to the breaking change issue mentioned earlier it would have to wait until the next major version. And we can’t guarantee timelines for version updates but it may not be for a while. But the team is aware of this request and can plan for consistency with the CLI v2 here in the future.
