### ISSUE TITLE
Support gov bucket arn

### ISSUE THREAD

**Issue by jeffg2k** [boto/botocore#2587]
**Is your feature request related to a problem? Please describe.**
When using the ARN `arn:aws-us-gov:s3:::accesspoint` it states it's an invalid bucket name and doesn't match the regex (botocore/handlers.py line 243).

**Describe the solution you'd like**
Support this type of arn?

**Comment by kdaily** [comment]
Hi @jeffg2k,

It looks like your ARN isn't formatted quite correctly: a `:` or a `/` should follow the `accesspoint`. Can you confirm what your full ARN looks like?

**Comment by jeffg2k** [comment]
I think I understand.. this is a bucket ARN, not an Access Point ARN.  Sorry for the confusion.. just learning how this all works.

**Comment by kdaily** [comment]
Glad you got it straightened out, @jeffg2k!
