### ISSUE TITLE
An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [EnvironmentName] must have values

### ISSUE THREAD

**Issue by Mrigbozurike** [boto/botocore#2598]
aws cloudformation create-stack \
                     --stack-name ourfirsttest \
                     --template-body file://./network.yml \
                     --capabilities CAPABILITY_NAMED_IAM \
                     --region us-west-2 \

**Comment by kdaily** [comment]
Hi @Mrigbozurike,

Sorry to hear you're having an issue. This looks like a problem for the AWS CLI. Can you please open an issue that GitHub repository (https://github.com/aws/aws-cli/issues), and please use the issue template to provide the information required so we can help you best!
