### ISSUE TITLE
correctly convert non-string header fields in parsers

### ISSUE THREAD

**Issue by thrau** [boto/botocore#2609]
**Is your feature request related to a problem? Please describe.**
Some output shapes have non-string header fields. Currently shapes exist with `integer`, `long`, `boolean`, or `timestamp` headers, see [here](https://gist.github.com/thrau/eb93d0def52d2c4a23abba4efea5e126#header-types). Those are not converted correctly by the parser because there are no handlers for non-string shapes in the base parser.

An example is `HostedConfigurationVersion` of appconfig. 
https://github.com/boto/botocore/blob/188dac64e10cd9db82ba0d3b58cbac85edcc563d/botocore/data/appconfig/2019-10-09/service-2.json#L1516-L1520

```python
response = appconfig_client.create_hosted_configuration_version(
    ApplicationId="applicationid",
    ConfigurationProfileId="configprofileid",
    Content=b'{"foo":"bar"}',
    ContentType="application/json",
)
assert response["VersionNumber"] == 1  # fails. actually "1"
```
this assert will fail, because "VersionNumber" is actually not converted to `int`, and remains a string value, because `_default_handle` is called in the parser, even though `VersionNumber` is of type `integer`. https://github.com/boto/botocore/blob/b540fbe861f230b1835154376b3bb875f7c85a4a/botocore/parsers.py#L323-L324

**Describe the solution you'd like**
It seems the base `ResponseParser` should have `_handle_integer`, `_handle_long`, `_handle_boolean` and `_handle_timestamp` methods to correctly convert non-string types from headers. However I don't understand what the implications of that would be.

**Comment by kdaily** [comment]
Hi @thrau, thanks for bringing this to our attention. It appears that services using the REST protocol may be affected by this. First pass analysis by our team identified the following services and operations with scalar values in header responses:

```
ServiceModel(appconfig) OperationModel(name=CreateHostedConfigurationVersion) <Shape(Integer)>
ServiceModel(appconfig) OperationModel(name=GetHostedConfigurationVersion) <Shape(Integer)>
ServiceModel(appconfigdata) OperationModel(name=GetLatestConfiguration) <Shape(Integer)>
ServiceModel(ebs) OperationModel(name=GetSnapshotBlock) <Shape(DataLength)>
ServiceModel(medialive) OperationModel(name=DescribeInputDeviceThumbnail) <Shape(__long)>
ServiceModel(medialive) OperationModel(name=DescribeInputDeviceThumbnail) <Shape(__timestamp)>
ServiceModel(mediastore-data) OperationModel(name=DescribeObject) <Shape(NonNegativeLong)>
ServiceModel(mediastore-data) OperationModel(name=DescribeObject) <Shape(TimeStamp)>
ServiceModel(mediastore-data) OperationModel(name=GetObject) <Shape(NonNegativeLong)>
ServiceModel(mediastore-data) OperationModel(name=GetObject) <Shape(TimeStamp)>
ServiceModel(polly) OperationModel(name=SynthesizeSpeech) <Shape(RequestCharacters)>
```

We will investigate further the scope of the problem and the impact on changing it.
