### ISSUE TITLE
Include RequestID in str() for ClientError

### ISSUE THREAD

**Issue by tdriscoll** [boto/botocore#2610]
**Is your feature request related to a problem? Please describe.**

When raising a ticket with AWS Support, they may ask for the RequestID before triaging further. Logging the botocore exception doesn't give you the RequestID (as far as i can tell). 

I see two alternatives to this feature request:

- Using try/except and catching the ClientError. This is hard because I need to add the try/except in many places. With my luck I will forget the one place that I needed it. 
- Enable DEBUG. Unfortunately, this creates much more logging than just the RequestID for errors. 

Also in my use case, the error was hard to reproduce. This is why I am suggesting it as a default behavior (although enabling this change behind an environment variable or flag would be fine).

**Describe the solution you'd like**

I'd like to include the RequestId in the string of the error. This way I will have it when i use log.exception()

I have a suggested implementation but I am open to whatever:
https://github.com/boto/botocore/pull/2605

**Comment by kdaily** [comment]
Hi @tdriscoll, thanks for the request. This primarily affects `boto3`, and there's a feature request there:

https://github.com/boto/boto3/issues/1143

Using the suggestion there (getting it from the metadata) is probably what you're doing. Can you please add in your vote on the initial comment, and any other details there? I'll link this issue as a duplicate.

Thanks!
