### ISSUE TITLE
botocore vendored AWS cert bundle does not include us-iso root CA or use system trusted CA roots

### ISSUE THREAD

**Issue by archoversight** [boto/botocore#2611]
**Describe the bug**

At the moment botocore vendors its own copy of `cacert.pem` which does not include the CA root for the us-iso partition. While we have trusted it in our systems CA root, botocore does not pick this up unless we explicitly pass the CA root to the tooling or set the `ca_bundle` flag in the config.

This does not seem to be an issue with the official Go SDK as that trusts the system root store and only if there is a custom ca_bundle set will it attempt to use it instead.

**Steps to reproduce**

Attempt to use the aws tooling/botocore through Ansible on us-iso partition.

**Expected behavior**

If the CA root is added to the system store, the connection should succeed.

**Related**

This was previously brought up in 2017: https://github.com/boto/botocore/issues/1332 when the landscape for the system managed CA roots was vastly different from today.

**Comment by kdaily** [comment]
Hi @archoversight,

Thanks for your post.

We had a [similar request](https://github.com/aws/aws-cli/issues/6193#issuecomment-850700363) to using the system root store for the AWS CLI, with a potential workaround of using `python-certifi-win32` to access the Windows certificate store through `certifi`. It will require more discussion, but I will re-open a tracking issue for that request.

For issues related to the `us-iso` partition, please contact AWS through an account manager or by opening a case with AWS support.

**Comment by archoversight** [comment]
The issue is that the default `aws` tooling does not support contacting the `us-iso` endpoints with the included `cacert.pem` since that does not include the CA root used for those endpoints (AFAIK they do not use commercial CA root).

This is not something that my AWS account manager or AWS support is able to help with.

We have been provided the appropriate CA certs and roots, and added them to our systems CA roots, however the `aws` utility and `botocore` does not consider those roots thereby causing failures and having to manually set `AWS_CA_BUNDLE` or setting `ca_bundle` in the AWS configuration to the appropriate CA roots. This is not necessary for Go tooling which uses the official AWS SDK since the Go AWS SDK does not bundle its own `cacert.pem`.

I am asking for this change in `botocore` to fix the issue in the underlying library. If you believe an active AWS support case or reaching out to my TAM will help expedite fixes in `botocore` for this issue, I am happy to pursue that avenue.

**Comment by nateprewitt** [comment]
Hi @archoversight,

The use of the system trust store (as the AWS Go SDK does) isn't an option for Python currently. The language at a base API level doesn't provide support for it. There were undocumented, experimental APIs ([ref](https://sethmlarson.dev/blog/experimental-python-3.10-apis-and-trust-stores)) recently added in Python 3.10 but they aren't meant for public use. This may point to this being an option in the future though. For the time being, this functionality is still at least a couple years away.

There should be clear documentation for using botocore outside of the default `aws` region and that's currently the best option. If you have any questions around that process, that is something you AWS account manager should be able to assist with.

**Comment by kdaily** [comment]
@archoversight, if there's further discussion or clarification needed, please have your account manager reach out to me internally; my username is the same.

Going to close this issue given the response from @nateprewitt on the viability of the system trust store.
