### ISSUE TITLE
Allow User-Agent To Be Configurable Via Custom Function 

### ISSUE THREAD

**Issue by Acehaidrey** [boto/botocore#2615]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

The issue is that we would like the ability to overwrite the user-agent. There is a way to add a suffix extension but we want to be able to have it a system level where this config applies to all calls of the boto clients. Right now the work requires monkey patching a solution to do this. 

**Describe the solution you'd like**
What we want is a way to have a config to be able to pass a custom user_agent logic (it will use env variables to construct) and we want this to apply to all boto calls so we can more easily figure out access patterns from different systems.

I can work on this if we can get assurance that this can fit in here and get guidance on what things to watch out for.

**Comment by Acehaidrey** [comment]
Hi @tim-finnigan! Thank you for the additional response!
I agree appending to the user agent would be great. I think the case for us, is that we want to even allow for a suffix extension, but based off a function to get the information since it is dynamically changing depending on who is submitting the request. The issue as a platform maintainer (such as a workflow platform in our case), is that we have many users who can commit their own workflows and call the boto3.client without passing the Config. We want to somehow at a platform level, make sure that information is passed without having to fork the botocore library if that makes sense.
Can you think of ways to support this?

**Comment by tim-finnigan** [comment]
Hi @Acehaidrey thanks for following up. Can you set up different profiles for your users? If you’re trying to figure out access patterns you could try [configuring profiles](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html) and using a service like [IAM Access Analyzer](https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html) collect access information.
