### ISSUE TITLE
Docs for iot-data publish() method are incorrect

### ISSUE THREAD

**Issue by joshfriend** [boto/botocore#2619]
**Describe the bug**
The documentation for iot-data `publish()` method says:

> The message body. MQTT accepts **text**, binary, and empty (null) message payloads. 

Which is correct (emphasis mine), however, the parameter types listed in the docs are:

`payload=b'bytes'|file`

Which is incorrect, `publish()` does accept text. Libraries like boto3-stubs use these docs to generate type stubs, which in this case causes mypy to indicate a type error on this code:

```python
mqtt.publish(
    topic=topic,
    qos=1,
    payload=json.dumps(payload)  # Argument "payload" to "publish" of "IoTDataPlaneClient" has incompatible type "str"; expected "Union[bytes, IO[bytes], StreamingBody]"  [arg-type]
)
```

Honestly, I have no idea where this should be reported since the botocore methods and docs are all generated from JSON files that come from elsewhere, but this seems like a good place to start.

**Comment by kdaily** [comment]
Hi @joshfriend,

Thanks for your comment. The reason it shows as `b'bytes'|file` is because the API model shape for this property is a blob:

https://github.com/boto/botocore/blob/10a6b17198c6765828a2d5ce8f924f2e22338164/botocore/data/iot-data/2015-05-28/service-2.json#L380

**Comment by joshfriend** [comment]
> It's been left for backwards compatibility but isn't strictly "intended".

Thanks for the explanation! I'm going to close this and just make sure I encode to bytes to avoid mypy errors since I get the sense that this could change in the future 😄
