### ISSUE TITLE
Include `pattern` in Shape.METADATA_ATTRS

### ISSUE THREAD

**Issue by thrau** [boto/botocore#2623]
Many `StringShape` instances describe a `pattern` as part of their type metadata. Here is an example: https://github.com/boto/botocore/blob/e720eefba94963f373b3ff7c888a89bea06cd4a1/botocore/data/opensearch/2021-01-01/service-2.json#L4371-L4376

While `min` and `max` are part of the default `METADATA_ATTRS`, `pattern` is not:  https://github.com/boto/botocore/blob/e720eefba94963f373b3ff7c888a89bea06cd4a1/botocore/model.py#L57-L59

I'm therefore not able to access the `pattern` attribute of a `StringShape` through `string_shape.metadata.get("pattern")`, as I would min or max.

**Comment by tim-finnigan** [comment]
Hi @thrau thanks for reaching out. These patterns change over time and there are often inconsistencies between services. We also have to ensure backwards compatibility with the patterns. There may be some alternative approach to do this but I’m not sure if supporting building on shape parsers is something the team would consider.

**Comment by thrau** [comment]
Thanks for the response. I think I did a bad job articulating my request. All I'm asking is to add `'pattern'` to the list of `METADATA_ATTRS`, s.t. when I use botocore to access service specs, I can access the pattern property of string types.

this code here will print `14 18 None`:
```python
from botocore.loaders import create_loader
from botocore.model import ServiceModel, Shape

loader = create_loader()

service_description = loader.load_service_model("opensearch", "service-2")
service_model = ServiceModel(service_description)

shape = service_model.shape_for("VersionString")
print(shape.metadata.get("min"), shape.metadata.get("max"), shape.metadata.get("pattern"))
```

if i add `Shape.METADATA_ATTRS.append('pattern')` before loading the shape, then it will print
`14 18 ^Elasticsearch_[0-9]{1}\.[0-9]{1,2}$|^OpenSearch_[0-9]{1,2}\.[0-9]{1,2}$`

as expected.

I hope it is clearer now. It has nothing to do with the particular pattern, just a way to access the StringShape property.

**Comment by tim-finnigan** [comment]
Hi @thrau thanks for following up. Since this isn’t a public interface, that kind of change is not typically something the team would consider. However, in this case it is such a minor change that if you want to create a PR the team seemed willing to merge it.
