### ISSUE TITLE
Credentials logged in plain text

### ISSUE THREAD

**Issue by dmerz75** [boto/botocore#2626]
The debug logging reports all of the response content with the access key revealed in plain text. Should the logger just report the response code, or perhaps the xml could be parsed to exclude the access key?

- Confirmed behavior in 1.23.51 and 1.24.8.

```
2022-02-28 13:22:03|DEBUG|endpoint:236|_do_get_response(): Sending http request:
```
This logger prints the AccessKeyId:
```
logger.debug("Sending http request: %s", request)
```
Output:
```
Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://sts.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'Boto3/1.21.8 Python/3.7.11 Windows/10 Botocore/1.24.8', 'X-Amz-Date': b'20220228T182203Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=***ACTUAL_KEY***
```

```
2022-02-28 13:22:03|DEBUG|parsers:234|parse():
```
This logger prints the AccessKeyId as well:
```
LOG.debug('Response body:\n%s', response['body'])
```
Output:
```
Response body: <GetSessionTokenResult>\n    <Credentials>\n      <AccessKeyId>***ACTUAL_KEY***
```

**Comment by nateprewitt** [comment]
Hi @dmerz75,

Debug logging in Botocore produces wire level logs for http which we have called out in the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/boto3.html). These are intended to be left untouched as raw bytes off the wire.

> ### Warning
> Be aware that when logging anything from 'botocore' the full wire trace will appear in your logs. If your payloads contain sensitive data this should not be used in production.

This is done prior to any parsing on the response, so we have no way to know what is "sensitive" at that point. This has been raised in a few issues previously, but we've arrived at keeping the current functionality as it's a requirement for many use cases. We could implement a general scrubber that tries to redact things that _look_ sensitive but this is imprecise, leading to obscuring relevant information.

**Comment by dmerz75** [comment]
That's fine! Thanks - I think I'll end up using a decorator too, to prevent logging below INFO level. Users won't have access to this authorization portion. Resolved.
```
def info_logging_only(func):
    """Decorator that uses info level logging only."""

    def wrapper(*args, **kwargs):
        logger.info(f"Current log level: {logger.root.level}")
        current_log_level = logger.root.level
        logger.root.level = 20 # INFO = 20
        logger.info(f"Set log level: {logger.root.level}")
        result = func(*args, **kwargs)
        logger.root.level = current_log_level
        logger.info(f"Returning to previous log level: {logger.root.level}")
        return result

    return wrapper
```
