### ISSUE TITLE
nose in requirements-dev.txt

### ISSUE THREAD

**Issue by andriyor** [boto/botocore#2629]
I don't know why nose is still in requirements-dev.txt
however it seems like will be removed

[`b438f67` (#2134)](https://github.com/boto/botocore/pull/2134/commits/b438f6765c7040af7986fd576462923f04d49763)

and still mentioned in this file
https://github.com/boto/botocore/tree/develop/tests/unit/response_parsing

**Comment by kdaily** [comment]
Hi @andriyor,

Thanks for bringing this to our attention. We transitioned to `pytest` and looks like this can still be cleaned up a bit.

**Comment by nateprewitt** [comment]
This will be addressed in all of our packages after the following PRs are merged. We'll go ahead and resolve this, tracking progress in the related PRs.

#2634 
boto/boto3#3186
boto/s3transfer#236
aws/aws-cli#6775
