### ISSUE TITLE
Invalid bucket name "": Bucket name must match the regex - AWS s3

### ISSUE THREAD

**Issue by spanwarcw** [boto/botocore#2633]
Please fill out the sections below to help us address your issue.
I'm running gitlab pipeline for cloudformation template getting above issue. And my bucket name is pf-data-airflow-1bjme
**What issue did you see ?**

**Steps to reproduce**
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

**Debug logs**
Full stack trace by adding 
```
import botocore.session
botocore.session.Session().set_debug_logger('')
```
to your code.

**Comment by kdaily** [comment]
Hi @spanwarcw,

Sorry to hear you're having a problem. Unfortunately without more information, like debug logs and a reproducible example, I'm not able to help further. Please provide this information and we can take a further look. Thanks!
