### ISSUE TITLE
Is adaptive retry meant to catch 429 Too Many Requests errors?

### ISSUE THREAD

**Issue by timj** [boto/botocore#2635]
**Describe the bug**

We have a client configured with `retries={"mode": "adaptive", "max_attempts": 10}`

In some situations we are seeing the following response:

```
DEBUG  botocore.retries.standard (standard.py:90) - Not retrying request.
<stack trace>
botocore.exceptions.ClientError: An error occurred (429) when calling the GetObject operation: Too Many Requests
```

The implication is that for standard retries http error 429 (Too Many Requests) is not handled. Am I reading things correctly? Am I meant to do backoff retry myself?

`botocore/data/_retry.json` does list 429:

```
    "too_many_requests": {
      "applies_when": {
        "response": {
          "http_status_code": 429
        }
      }
    },
```
but does that not apply to adaptive retries?

Sorry if I've missed some documentation.

**Expected behavior**

Sorry if I've missed some documentation. Is there some configuration I'm meant to set to enable retries? 429 Too Many Requests seems like it's something that should be handled automatically by the retry infrastructure. 

**Debug logs**

I enabled debug logging and it reports "Not retrying request".

**Comment by tim-finnigan** [comment]
Hi @timj thanks for reaching out. Here is the boto3 documentation on retries: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html

It notes that the Adaptive mode includes all the features of Standard mode. And for Standard mode it does retry attempts on HTTP status codes: 500, 502, 503, 504. But the default Legacy makes retry attempts on 429 as well as those other status codes.

**Comment by timj** [comment]
Okay. Thanks. So if I want 429 I have to use Legacy. Legacy seemed like something I should never use in new systems. It seems like "standard" does not have a configuration option to use 429 so my choices are to use legacy or write my own retry backoff layer.

**Comment by tim-finnigan** [comment]
Hi @timj it looks like the TooManyRequestsException is actually listed in the Standard retry mode [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#standard-retry-mode) (and therefore should apply to the Adaptive mode as well), it just doesn’t list the status code there. Sorry about that! Which service are you using? If you can provide the full stack trace that could help us better understand what’s going on here.

**Comment by timj** [comment]
This is with Google cloud storage.

Here's the trace:

```
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-0.8.0/Linux64/daf_butler/g6b22db343a+d18c45d440/python/lsst/daf/butler/core/_butlerUri/s3.py", line 193, in _as_local
    self.client.download_fileobj(self.netloc, self.relativeToPathRoot, tmpFile)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/boto3/s3/inject.py", line 679, in download_fileobj
    return future.result()
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/s3transfer/download.py", line 511, in _main
    response = client.get_object(
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.8.0/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (429) when calling the GetObject operation: Too Many Requests```

Does it matter that this is reported as a ClientError and not a TooManyRequestsException?

**Comment by tim-finnigan** [comment]
Thanks @timj for following up. In the boto3 [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html) on error handling it says:

> AWS service exceptions are caught with the underlying botocore exception, ClientError. After you catch this exception, you can parse through the response for specifics around that error, including the service-specific exception.

So ClientError is just a general exception when an error response is provided by an AWS service to your boto3 client’s request. I assumed you are using the GetObject API of the S3 service but I didn’t see TooManyRequests in these S3 error docs: https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList. It seems like the 503 Slow Down error should occur instead in that scenario. Can you provide a code snippet or give us more context on what your code does?

**Comment by timj** [comment]
The code uses `download_fileobj`: https://github.com/lsst/resources/blob/main/python/lsst/resources/s3.py#L213-L215

I think you are saying that a general http error code of 429 is not handled by the new retry code because 429 is not listed by the AWS error codes. Maybe the Google implementation of AWS is not fully compliant with the Amazon one? Would it be possible to add 429 to the list of standard retry codes? [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) clearly implies a retry is desirable (I do not know if a `retry-after` header is included in the response from Google).

**Comment by tim-finnigan** [comment]
The TooManyRequestsException is retried in [Standard](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#standard-retry-mode) mode. But in this case it is a ClientError because the TooManyRequests occurs upstream in the service. There are articles for triaging this error in [Lambda](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-throttling/) and [AWS Batch](https://aws.amazon.com/premiumsupport/knowledge-center/aws-batch-requests-error/) but again it’s not an error we would expect to see with S3. I don’t know the specifics of how this is integrated with Google Cloud but it is definitely possible that there are incompatibilities.

**Comment by timj** [comment]
One final note motivated by the bot.

429 seems like the right error code to use because that's the code that indicates that you specifically have to slow down. It's why the code was created (my understanding is that it's from 2012). 503 means that the server is having problems and please try again. It sounds like AWS had always used 503 so decided to keep 503 because using 429 might break people's services. Google decided to do the correct thing with their services and use 429 but of course they always have the option of telling you to switch to native GCS if the S3 client library can't handle 429. It doesn't seem like it would be wrong for botocore to add 429 to the retry list in standard mode -- it won't break AWS users but would allow people to use botocore on Google.

**Comment by tim-finnigan** [comment]
I think my initial confusion threw off this discussion. The 429 TooManyRequestsException is [documented](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html) in the retry modes for Legacy, Standard, and by extension Adaptive. It is defined [here](https://github.com/boto/botocore/blob/0cc671363e27bd620917414215f6d71026384682/botocore/data/_retry.json#L35-L39) in botocore.

Since 429 isn’t a documented S3 error code, my guess is that something in your integration relies on another service like Lambda. I thought you might be exceeding API rate limits but from [this article](https://aws.amazon.com/blogs/mt/managing-monitoring-api-throttling-in-workloads/) it looks like that would result in a ThrottlingException or RequestLimitExceeded error instead. It could depend on the service. I’m going to close this issue but feel free to respond or create a new issue and we can continue to discuss.

**Comment by timj** [comment]
I am using botocore in some code that connects directly to the bucket. Lambda is not involved.

I do not understand why you can't add 429 to the retry list explicitly. It won't harm anyone and will help Google users. Given the conversation on this ticket I have to abandon using botocore on Google and am rewriting my client to use google-cloud-storage APIs directly.

**Comment by beddari** [comment]
I fully agree with @timj and this should have been an easy fix. Sad for interop and software quality that it wasn't.

**Comment by BrandonY** [comment]
@tim-finnigan, would y'all be open to a pull request adding 429 to the list of retryable codes?

**Comment by cyounkins** [comment]
Reading this thread it is unclear to me whether 429 is retried or not. 

@tim-finnigan wrote:
> The 429 TooManyRequestsException is [documented](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html) in the retry modes for Legacy, Standard, and by extension Adaptive. It is defined [here](https://github.com/boto/botocore/blob/0cc671363e27bd620917414215f6d71026384682/botocore/data/_retry.json#L35-L39) in botocore.

In the linked documentation, it _does_ include `TooManyRequestsException` in the list under "Standard mode’s functionality includes". But it _does not_ specify error code 429, explicitly writing "Retry attempts on nondescriptive, transient error codes. Specifically, these HTTP status codes: 500, 502, 503, 504."

BUT in the linked `_retry.json` file, it has
```
    "too_many_requests": {
      "applies_when": {
        "response": {
          "http_status_code": 429
        }
      }
    },
```
Which suggests that it will be handled, where the OP indicates it is not.
