### ISSUE TITLE
S3 generate_presigned_url - Allow for custom "now" date / truncated dates

### ISSUE THREAD

**Issue by cristianoccazinsp** [boto/botocore#2647]
**Is your feature request related to a problem? Please describe.**

`generate_presigned_url` generates signatures using the current date, which works most of the time. However, it is sometimes required to use a "truncated date" in order to not blow up caches with new urls every time. For instance, one would like to create signed urls with a 10 minute truncated date, so all urls for the same object within a 10 minute window end up with the same signature and parameters.

**Describe the solution you'd like**

I think the implementation should be fairly easy, just allow receiving a "current utc time" parameter to customize what the current date is when creating the signature.

Better implementations would be to add new methods with this kind of truncated datetime feature, but may require more work and documentation.

Some ideas grabbed from here: https://advancedweb.hu/cacheable-s3-signed-urls/

Thoughts?

**Comment by kdaily** [comment]
Hi @cristianoccazinsp,

Thanks for writing! This is an interesting idea. I see you noted an implementation that shows how to use this with the AWS Javascript SDK, but this uses a mocking library to produce this behavior. No other AWS SDK currently supports this pattern either, so this is something that we would need to discuss across teams. I'm not even certain that this behavior could be guaranteed to work by the S3 team and API - providing a date in the past could carry some risks.

I'm going to close this here and link and re-open a feature request at the AWS SDK repository where we can get some more feedback and provide any updates.

**Comment by cristianoccazinsp** [comment]
Awesome, thanks for reading through this and proposing a new feature.

In the meantime, I’ve basically re implemented the signature code following AWS examples that are on the web, but supporting date truncation parameters, it’s some boilerplate but not too hard if you have basic understanding of signatures and hmac.

**Comment by kdaily** [comment]
You're welcome! You can see the implementation of request signing here for the Python SDK:

https://github.com/boto/botocore/blob/43b16b37289d9e25230a70f71b0acb77f476c3ef/botocore/signers.py#L97-L98

Which uses the signing functions here:

https://github.com/boto/botocore/blob/develop/botocore/auth.py
