### ISSUE TITLE
sso-oidc exceptions don't translate "error_description" into ClientError message field

### ISSUE THREAD

**Issue by benkehoe** [boto/botocore#2651]
Re-opening #2216

The `sso-oidc` method [CreateToken](https://docs.aws.amazon.com/singlesignon/latest/OIDCAPIReference/API_CreateToken.html) returns an error response that looks like:
```json
{
  "error": "invalid_grant",
  "error_description": "Invalid grant provided"
}
```
but on the `botocore.errorfactory.InvalidGrantException` object, the `error.response["Error"]["Code"]` is correct but `error.response["Error"]["Message"]` is an empty string.

This is using botocore 1.24.28.

The `sso-oidc` API is compliant with the OAuth Device Grant spec https://tools.ietf.org/html/rfc6749#section-5.2, so it has to use a field called `error_description`. The API could in theory duplicate that into a `message` field in the response, but as-is, botocore is not translating this service's return values correctly.

**Comment by kdaily** [comment]
Hi @benkehoe, thanks for this. I reopened the original issue.
