### ISSUE TITLE
Route53 change_resource_record_sets() does not accept Govcloud regions

### ISSUE THREAD

**Issue by SeraphShroud** [boto/botocore#2661]
### Describe the bug

When attempting to create a resource record with a region **us-gov-west-1** or **us-gov-east-1**, you get a [Cannot find region 'us-gov-west-1'. No changes made.] error.

### Expected Behavior

The region us-gov-west-1 and us-gov-east-1 would be accepted and the resource record would be created. 

### Current Behavior

Traceback (most recent call last):
  File "chalicelib/aws_util.py", line 177, in <module>
    resp = client.change_resource_record_sets(
  File ".../lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "...lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Cannot find region 'us-gov-west-1'. No changes made.]

### Reproduction Steps

> resp = client.change_resource_record_sets(
>             HostedZoneId=id,
>             ChangeBatch={
>                 'Changes': [
>                     {
>                         'Action': 'CREATE',
>                         'ResourceRecordSet': {
>                             'Name': 'test',
>                             'Type': 'A',
>                             'SetIdentifier': 'TEST',
>                             'Region': 'us-gov-west-1',
>                             'AliasTarget': {
>                                 'HostedZoneId': 'Z1K6XKP9SAGWDV',
>                                 'DNSName': 'test.domain.name.com',
>                                 'EvaluateTargetHealth': True
>                             }
>                         }
>                     }
>                 ]
>             }
>         )

### SDK version used

botocore 1.24.19

### Environment details (OS name and version, etc.)

macOs Catalina 10.15.7, python 3.8.6

**Comment by tim-finnigan** [comment]
Hi @SeraphShroud thanks for reaching out. Which version of boto3 are you using? The latest version is 1.21.38.

Can you also confirm that you have met the requirements here for using Route 53 with GovCloud: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/setting-up-route53.html

**Comment by SeraphShroud** [comment]
I was using boto3 version 1.21.19, but even after I upgrade to 1.21.38 I still get the [Cannot find region 'us-gov-west-1] error. I am also within the requirements for using Route53 in Govcloud. The use case is one stated in the Documentation @tim-finnigan linked.

`If you want to use the Route 53 console to create alias records in a public hosted zone that route traffic to resources in the GovCloud Region, such as an ELB load balancer or an S3 bucket, you can't choose the resource from the Alias Target list. You must enter the applicable domain name in the Alias Target field. For information about which value to specify for each type of resource and where to get that value, see [Values for Alias Records documentation ](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-alias.html#rrsets-values-alias-alias-target)in the Amazon Route 53 Developer Guide.`

I am trying to set up Route53 in a non-Govcloud space to redirect traffic to a Govcloud hosted API Gateway using a custom domain name. On the AWS Web Console, I see the us-gov-west-1 and us-gov-east-1 regions under the drop down menu when selecting a region. I also checked the botocore/data/endpoints.json and saw there are Govcloud supported regions for Route53 in the current botocore version.
![Screen Shot 2022-04-11 at 4 09 17 PM](https://user-images.githubusercontent.com/9344666/162847830-c7252ceb-dd19-45f6-a387-056d39898e11.png)

**Comment by tim-finnigan** [comment]
@SeraphShroud Looking at the [change_resource_record_sets](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53.html#Route53.Client.change_resource_record_sets) documentation I don’t see `us-gov-west-1` in the Request Syntax or [API documentation](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ResourceRecordSet.html#API_ResourceRecordSet_Contents) although it is there for other Route 53 commands. I’m going to reach out to the Route53 team to get clarity on this and will let you know when I hear back.

**Comment by tim-finnigan** [comment]
P62703310

**Comment by tim-finnigan** [comment]
Hi @SeraphShroud I heard back from a member of the Route 53 team. They said it looks like you are trying to use [Latency-based routing](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-latency), which is not available in GovCloud regions. The region field in a ChangeResourceRecordSets request is for Latency-based routing only.

**Comment by SeraphShroud** [comment]
Thanks for the follow-up @tim-finnigan. I removed the SetIdentifier and Region from the ResourceRecordSet and I was able to set up the Route53 Resource Record successfully.

Here is my new payload:
```
        resp = client.change_resource_record_sets(
            HostedZoneId=id,
            ChangeBatch={
                'Changes': [
                    {
                        'Action': 'CREATE',
                        'ResourceRecordSet': {
                            'Name': 'test.domain.com',
                            'Type': 'A',
                            'AliasTarget': {
                                'HostedZoneId': 'Z1K6XKP9SAGWDV',
                                'DNSName': 'd-lo4vmnbr12.execute-api.us-gov-west-1.amazonaws.com',
                                'EvaluateTargetHealth': True
                            }
                        }
                    }
                ]
            }
        )
```

Thank you for the clarification.
