### ISSUE TITLE
ECR full name is wrong: not EC2, should be Elastic

### ISSUE THREAD

**Issue by jon-trust** [boto/botocore#2663]
### Describe the issue

In ECR definition file the full name is:
`"serviceFullName":"Amazon EC2 Container Registry"`
But should be
`"serviceFullName":"Amazon Elastic Container Registry"`
as per official doc https://aws.amazon.com/ecr/

### Links

https://github.com/boto/botocore/blob/master/botocore/data/ecr/2015-09-21/service-2.json

**Comment by tim-finnigan** [comment]
Thanks @jon-trust for bringing this to our attention. Based on this [doc history](https://docs.aws.amazon.com/AmazonECR/latest/userguide/doc-history.html), the name change occurred on November 21st, 2017. 

Our service models are generated upstream so I will reach out to the ECR team to update those. Thanks!
