### ISSUE TITLE
Unable to use AWSRequest params with duplicate query keys

### ISSUE THREAD

**Issue by zrsmithson** [boto/botocore#2667]
### Describe the bug

When trying to make a generic `AWSRequest` so I can add a `SigV4Auth` from IAM policy (which is required as per #1784), I'm unable to use the `params` attribute with duplicate keys because it only works with `dict` objects. Instead I have manually build the query string and append it to the url before instantiating the `AWSRequest` object

This might actually be a feature request, but the documentation seems to indicate that it should behave similarly to `requests`:
> This class was originally inspired by requests.models.Request, but has been boiled down to meet the specific use cases in botocore. That being said this class (even in requests) is effectively a named-tuple.

`requests` allows `params` to be a dictionary or list of tuples, which allows for keys to be repeated.

### Expected Behavior

``` python
import boto3
from botocore.awsrequest import AWSRequest
from botocore.auth import SigV4Auth
from botocore.endpoint import URLLib3Session

url = "http://some-api-endpoint.com"
creds = boto3.Session().get_credentials()
region = "us-west-1"
query_params = [
    ("eq", "attr1:value1"),
    ("eq", "attr2:value2"),
]

request = AWSRequest(method="GET", url=url, params=query_params)
SigV4Auth(creds, "execute-api", region).add_auth(request)
response = URLLib3Session().send(request.prepare())
```

### Current Behavior

As it is, I have to use `urlencode` to manually add a "?" and the query string to the end of the url

``` python
import boto3
from botocore.awsrequest import AWSRequest
from botocore.auth import SigV4Auth
from botocore.endpoint import URLLib3Session
from botocore.compat import urlencode

url = "http://some-api-endpoint.com"
creds = boto3.Session().get_credentials()
region = "us-west-1"
query_params = [
    ("eq", "attr1:value1"),
    ("eq", "attr2:value2"),
]

encoded_url = f"{url}?{urlencode(dt)}"

request = AWSRequest(method="GET", url=encoded_url)
SigV4Auth(creds, "execute-api", region).add_auth(request)
response = URLLib3Session().send(request.prepare())
```

### Reproduction Steps

See the examples above, but note that an actual api endpoint url is required to test it.

### Possible Solution

There might be other places that would need to change, but currently it fails because it tries to make a list of key/value tuples in `botocore.auth.SigV4Auth._canonical_query_string_params` without handling the case that they already are in the correct form. There is a comment that mentions repeated keys, but it would not be possible the way it is parsed.

Current:
``` python
def _canonical_query_string_params(self, params):
    # [(key, value), (key2, value2)]
    key_val_pairs = []
    for key in params:
        value = str(params[key])
        key_val_pairs.append((quote(key, safe='-_.~'),
                                quote(value, safe='-_.~')))
    ...
```

All that needs to change is to use `params.items()` if params is a dictionary(or more generally `typing.Mapping`), to essentially turn it into a list of tuples.:
``` python
if isinstance(value, Mapping):
        value = value.items()
def _canonical_query_string_params(self, params):
    # [(key, value), (key2, value2)]
    key_val_pairs = []
    if isinstance(params, typing.Mapping):
        params = params.items()
    for key, value in params:
        key_val_pairs.append(
            (quote(key, safe='-_.~'), quote(value, safe='-_.~'))
        )
    ...
```
Note that this is pretty much [what the requests library does](https://github.com/psf/requests/blob/2a6f290bc09324406708a4d404a88a45d848ddf9/requests/utils.py#L335) whenever dealing with params

### SDK version used

1.25.6

### Environment details (OS name and version, etc.)

macos 12, python 3.10.4

**Comment by nateprewitt** [comment]
Hi @zrsmithson,

Thanks for opening an issue. While we could probably make a change for this, it's important to note that both `AWSRequest` and `SigV4Auth` are not considered public interfaces. They're specifically excluded from the public documentation and aren't guaranteed to be backwards compatible between releases. We wouldn't recommend building anything that requires stability using these classes without strict pinning.

There are some plans in place to start providing SDK independent signers in Python, but we don't have a timeline to share on when those will be available.

**Comment by dlm6693** [comment]
Hi @zrsmithson,

Thanks for reporting this. While we don't recommend using this low level interface to make requests, it now supports query parameters as a list of tuples in addition to a dictionary. As a result, you can now provide multiple values for the same parameter key (https://github.com/boto/botocore/pull/2679).
