### ISSUE TITLE
SSO cache & credentials directories inside `botocore`?

### ISSUE THREAD

**Issue by nazarewk** [boto/botocore#2668]
### Describe the feature

I did not research the details, but author of https://github.com/benkehoe/aws-sso-util suggested moving my functionality of configurable SSO directories https://github.com/benkehoe/aws-sso-util/pull/63 into the `botocore` and on the first glance it looks like a good idea.

Will add more info when i have time.

### Use Case

Currently most (probably all?) of the SSO/sessions code is using in-memory credentials, requiring new credentials to be fetched for every CLI/tool invocation. Storing those values locally for reuse would help a lot with tooling responsiveness.

### Proposed Solution

This is already a part of https://github.com/benkehoe/aws-sso-util/blob/master/lib/aws_sso_lib/sso.py

### Other Information

Such credentials & cache could probably use the secrets management system used by the machine (keychain, secret-service etc.) possibly through https://pypi.org/project/keyring/ instead of forcing dependent SSO projects to do so themselves, like:
- https://github.com/Nike-Inc/gimme-aws-creds for Okta SSO
- https://github.com/benkehoe/aws-sso-util for AWS SSO

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

any

### Environment details (OS name and version, etc.)

any

**Comment by tim-finnigan** [comment]
Hi @nazarewk thanks for the feature request. I think this overlaps with https://github.com/boto/botocore/issues/1923. Have you read through the comments in that issue? If there are any distinctions between these two issues you would like to make please let us know.

**Comment by tim-finnigan** [comment]
Ok thanks for confirming, I'll go ahead and close this issue but please 👍 or comment on #1923 if you have additional feedback.
