### ISSUE TITLE
health client describe_events raises InvalidSignatureException

### ISSUE THREAD

**Issue by btemplep** [boto/botocore#2686]
### Describe the bug

When calling `describe_events` with a "health" client, an InvalidSignatureException is raised when it previously was not. 

reproduced the bug on botocore==1.26.7

reproduced the bug on boto3 versions
- 1.23.4
- 1.23.6
- 1.23.7

### Expected Behavior

Normal response from health client "describe_events" call

### Current Behavior

raises an InvalidSignatureException 

```text
Traceback (most recent call last):
  File "boto_tester.py", line 5, in <module>
    resp = health_client.describe_events(filter={ "eventStatusCodes": ["upcoming","open"]})
  File "/workspaces/venv/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/workspaces/venv/lib/python3.8/site-packages/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the DescribeEvents operation: Credential should be scoped to a valid region. 
```

### Reproduction Steps

Setup up AWS creds and run:

```python
import botocore.session

sess = botocore.session.get_session()
health_client = sess.create_client("health", region_name="us-east-1")
resp = health_client.describe_events(filter={ "eventStatusCodes": ["upcoming","open"]})
print(resp)
```

### SDK version used

1.26.7

### Environment details (OS name and version, etc.)

Amazon Linux 2, Debian Buster

**Comment by tim-finnigan** [comment]
Hi @btemplep thanks for reporting this. It appears that there was a recent change in the Health service endpoint configuration that is affecting boto3 and CLI users. This is actively being tracked internally. A temporary solution would be to revert to the previous version of boto3/botocore. I will let you know when there are any updates on this issue. If anyone else is affected by this please 👍 this issue and leave a comment if you have any additional information to share.
