### ISSUE TITLE
Allow for using session policies together with source_profile+role_arn

### ISSUE THREAD

**Issue by reegnz** [boto/botocore#2687]
### Describe the feature

When assuming roles, you have the possibility to define session policies, potentially limiting the original permissions of the role to be assumed: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#policies_session

You can assume a role in ~/.aws/profile like this:

```ini
[default]

[profile my_profile]
source_profile=default
role_arn=arn....role/MyAdminRole
```

What would be nice is to also allow for a policy_arn field so that one can limit permissions with different profiles, while still using only a single role. Eg.:

```ini
[default]

[profile my_profile]
source_profile=default
role_arn=arn....role/MyAdminRole

[profile my_profile_myapp]
source_profile=default
role_arn=arn....role/MyAdminRole
policy_arn=arn:aws:iam::aws:policy/MyAppPolicy
```

### Use Case

When developing applications that interact with AWS API-s it's quite common to test them locally. Currently it is not easy to test the application policies locally though.
I would like a simple way of testing IAM policies locally that don't require setting up new user-facing IAM Roles, but that could reuse existing roles that have already been built out. By simply utilizing the session policy feature using the same policy the application will also use (with it's own instance profile for example), it would be easy to test these policies when running the app locally.

### Proposed Solution

Add a new field to aws profiles called `policy_arn`. This, used together with source_profile and role_arn could allow for limiting the session policy to the policy of a to-be-tested policy.

```ini
[profile my_profile_myapp]
source_profile=default
role_arn=arn....role/MyAdminRole
policy_arn=arn:aws:iam::aws:policy/MyAppPolicy
```

### Other Information

I've written a script to work around this issue, but it's clunky and just feels dirty:

```sh
#!/usr/bin/env bash

# This script allows for limiting the permissions of the target_profile to 
# the policy provided in the argument.
# put it at ~/.local/bin/profile-with-policy

set -euo pipefail

source_profile=$1
target_profile=$2
policy_arn=$3
shift 3

unset AWS_PROFILE

assume_role() {
  role_arn=$(aws configure get role_arn --profile "${target_profile}")
  role_session_name=$(aws configure get role_session_name --profile "${target_profile}")
  region=$(aws configure get region --profile "${target_profile}")
  aws sts assume-role --profile "${source_profile}" \
    --role-arn "${role_arn}" \
    --role-session-name "${role_session_name}" \
    --region "${region}" \
    --policy-arns arn="${policy_arn}"
}

to_export() {
  jq -r '.Credentials|{
    AWS_ACCESS_KEY_ID: .AccessKeyId, 
    AWS_SECRET_ACCESS_KEY: .SecretAccessKey,
    AWS_SESSION_TOKEN: .SessionToken
  }|to_entries[]|"export \(.key)=\(.value)"'
}

eval "$(assume_role|to_export)"

exec "$@"
```

And then invoke this script with 
```sh
profile-with-policy default my_profile_myapp arn:of:the:policy my-code-using-the-policy
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

boto3 1.25.13

### Environment details (OS name and version, etc.)

MacOS 12.4

**Comment by tim-finnigan** [comment]
Hi @reegnz thanks for the feature request. I think this is an interesting idea and can see the value in what you’re proposing. But this would have to be a cross-SDK feature request as we’re aiming to keep the SDKs aligned when it comes to introducing new functionality. I created a feature request here in our shared SDK repository: https://github.com/aws/aws-sdk/issues/272

Anyone else interested in seeing this feature should should 👍 that issue and leave a comment there if they have any additional information to share. I also created an internal item so that teams can discuss this and weigh in. I’ll post any updates in that new GitHub issue as soon as I have any. Thanks!
