### ISSUE TITLE
`verify=False` not work with python bug PHA

### ISSUE THREAD

**Issue by yywing** [boto/botocore#2702]
### Describe the bug

python has ssl bug: https://bugs.python.org/issue37428

This commit try fix it: https://github.com/boto/botocore/commit/e97f5cbb08c509931731b2ec198869f2c0991e97

but `create_urllib3_context` has default args and  `context.post_handshake_auth`  is always `True`.

![image](https://user-images.githubusercontent.com/22928185/174835561-b84ba917-ad47-4dbe-bd75-a54b3a565392.png)

![image](https://user-images.githubusercontent.com/22928185/174835911-f51b1eef-8013-4f4a-a772-b061d8b4c78c.png)

### Expected Behavior

`verfity=False` not validate cert.

### Current Behavior

When ? (3.6 or smaller )< python version < 3.7.4 and openssl > 1.1.1, then always verfity ssl cert.

### Reproduction Steps

--

### Possible Solution

[https://github.com/boto/botocore/pull/2703](https://github.com/boto/botocore/pull/2703)

### SDK version used

>= this commit (https://github.com/boto/botocore/commit/e97f5cbb08c509931731b2ec198869f2c0991e)

### Environment details (OS name and version, etc.)

- (3.6 or smaller )< python version < 3.7.4  (suuport PHA)
- openssl > 1.1.1 (support PHA)
- server support tls1.3

**Comment by tim-finnigan** [comment]
Hi @yywing thanks for your patience. I wanted to confirm that this is still an issue you are seeing. Support for Python 3.6 has since been deprecated as of May 2022 per [this announcement](https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/). If this is still an issue in Python 3.7+ please let us know.

**Comment by yywing** [comment]
> (3.6 or smaller )< python version < 3.7.4 and openssl > 1.1.1

So python 3.7.1 will be affect

**Comment by tim-finnigan** [comment]
Thanks again for your patience and for creating that [PR](https://github.com/boto/botocore/pull/2703). In the [announcement](https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/) linked earlier, the planned end of support for Python 3.7 is December 2023. And in the meantime Python 3.7.4+ can be used. For these reasons the team has not prioritized this issue or PR.
