### ISSUE TITLE
Default Proxy Config is not respected

### ISSUE THREAD

**Issue by areazus** [boto/botocore#2707]
### Describe the bug

We have a use-case to use HTTPs Proxies to validate requests to AWS Resources. We found the support for being able to add [proxy configs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html). It seems like we should be able to set '''proxy_use_forwarding_for_https=True''', in our ~/.aws/config file and the argument should be picked up as listed in default config [here](https://github.com/boto/botocore/blob/develop/botocore/configprovider.py#L195).

However, it is not respected and only way to set the argument is programmatically passing the Config object when creating a client. Looking into the code further, I validated that scoped_config passed to this [method](https://github.com/boto/botocore/blob/develop/botocore/args.py#L83) contains a key proxy_use_forwarding_for_https=True. However, it is disregarded when [compute_client_args](https://github.com/boto/botocore/blob/develop/botocore/args.py#L164) method is invoked. Hence [proxies config](https://github.com/boto/botocore/blob/develop/botocore/args.py#L134) is set to None.

## Testing Done:

```
  import boto3
  from botocore.config import Config
  
  proxy_definitions = {
      'https': 'https://3c22fb655f50.ant.amazon.com:8081',
      'http': 'http://3c22fb655f50.ant.amazon.com:8082',
  }
  
  
  \# Doesn't forward requests
  client_1 = boto3.client('s3', config=Config(proxies=proxy_definitions), verify=False)
  client_1.get_bucket_location(Bucket='my-bucket')
  
  
  \# Does forward requests
  client_2 = boto3.client('s3', config=Config(proxies_config={'proxy_use_forwarding_for_https': True},
                                              proxies=proxy_definitions), verify=False)
  client_2.get_bucket_location(Bucket='my-bucket')
```

### ~/.aws/config

```
[default]
region=us-west-2
output=json
proxy_use_forwarding_for_https=True
```

### Expected Behavior

Setting proxy_use_forwarding_for_https=True in the ~/.aws/config should use https forwarding proxy.

 

### Current Behavior

Setting proxy_use_forwarding_for_https=True in the ~/.aws/config doesn't set proper proxy config.

### Reproduction Steps

Set proxy_use_forwarding_for_https=True in aws config and then execute:

```
import boto3
from botocore.config import Config

proxy_definitions = {
    'https': '<HTTPS_PROXY>',
    'http': '<HTTPS_PROXY>',
}


# Doesn't forward requests
client_1 = boto3.client('s3', config=Config(proxies=proxy_definitions), verify=False)
client_1.get_bucket_location(Bucket='my-bucket')
```

### Possible Solution

One possible solution would be to populate https://github.com/boto/botocore/blob/develop/botocore/args.py#L210 with values from scoped_config.

### SDK version used

 boto3 1.24.16 

### Environment details (OS name and version, etc.)

OSX 12.4

**Comment by tim-finnigan** [comment]
Hi @areazus thanks for reaching out. An issue involving the proxy configuration was also recently raised here: https://github.com/boto/botocore/issues/2644. I’m going to close this as a duplicate but I will link to this issue since you provided some helpful context for framing the problem. Thanks again and please refer to that issue for updates going forward.
