### ISSUE TITLE
ResourceRequestSuccess waiter should succeed when OperationStatus == 'CANCEL_COMPLETE`

### ISSUE THREAD

**Issue by alinabuzachis** [boto/botocore#2710]
### Describe the bug

`ResourceRequestSuccess` waiter should also succeed when `ProgressEvent.OperationStatus` reaches `CANCEL_COMPLETE` (see https://github.com/boto/botocore/blob/develop/botocore/data/cloudcontrol/2021-09-30/waiters-2.json for details). 

### Expected Behavior

The waiter `resource_request_success` should wait until the requests reaches `CANCEL_COMPLETE` and does not throw any error.

### Current Behavior

`botocore.exceptions.WaiterError: Waiter ResourceRequestSuccess failed: Waiter encountered a terminal failure state: For expression "ProgressEvent.OperationStatus" we matched expected path: “CANCEL_COMPLETE"`

### Reproduction Steps

Suppose we want to cancel an IN_PROGRESS and PENDING resource request using `cancel_resource_request()`. After we'd like to use the waiter

```
            self.client.get_waiter("resource_request_success").wait( ...)
```
to wait until the request reaches `CANCEL_COMPLETE` state - meaning that the request has been successfully cancelled.

### Possible Solution

```
...      
}, {
        "matcher" : "path",
        "argument" : "ProgressEvent.OperationStatus",
        "state" : "success",
        "expected" : "CANCEL_COMPLETE"
      } ]
}
```

### SDK version used

boto3==1.21.36 botocore==1.24.36

### Environment details (OS name and version, etc.)

macOS Monterey 12.4

**Comment by tim-finnigan** [comment]
Thanks @alinabuzachis for reaching out. Our waiter models are shared across SDKs and owned upstream by service teams, so I created a new issue to address this here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/295. I'll contact the service team regarding this and will update that issue when I hear back.
