### ISSUE TITLE
NetworkInterfaceAvailable waiter doesn't retry when facing InvalidNetworkInterfaceID.NotFound

### ISSUE THREAD

**Issue by romos** [boto/botocore#2717]
### Describe the bug

NetworkInterfaceAvailable waiter doesn't retry when facing InvalidNetworkInterfaceID.NotFound, it just fails immediately with the corresponding exception.

### Expected Behavior

NetworkInterfaceAvailable waiter should keep retrying according to the waiter config when facing InvalidNetworkInterfaceID.NotFound.

### Current Behavior

NetworkInterfaceAvailable waiter doesn't retry when facing InvalidNetworkInterfaceID.NotFound, it just fails immediately with the corresponding exception:
```
botocore.exceptions.WaiterError: Waiter NetworkInterfaceAvailable failed: Waiter encountered a terminal failure state: Matched expected service error code: InvalidNetworkInterfaceID.NotFound
```

### Reproduction Steps

The issue is sporadic and appears pretty rarely (I believe once AWS is kinda overloaded a bit?).
Any simple piece of code can hit it all of a sudden when creating an ENI and then immediately calling a waiter to wait for it to become 'available'.
e.g.
```python
import boto3

ec2_client = boto3.client('ec2')
ec2 = boto3.resource('ec2')

response = ec2_client.create_network_interface(
    Description="eni-test",
    InterfaceType="interface",
    SubnetId="subnet-xxx",
    TagSpecifications=[
        {
            'ResourceType': 'network-interface',
            'Tags': [{'Key': 'Name', 'Value': "eni-test"}]
        }
    ])

eni = ec2.NetworkInterface(response["NetworkInterface"]["NetworkInterfaceId"])

ec2_client.get_waiter('network_interface_available').wait(
            NetworkInterfaceIds=[ eni.id ],
            WaiterConfig={
                'Delay': 5,
                'MaxAttempts': 5
            })

print("ENI %s is available" % eni.id)
```

### Possible Solution

I tried to look up waiter metadata across boto repositories - I'm not very familiar with it yet, so the only place I came across is https://github.com/boto/botocore/blob/23ee17f5446c78167ff442302471f9928c3b4b7c/botocore/data/ec2/2016-11-15/waiters-2.json

In that file, ".NotFound" states usually have "_retry_" action when waiting for _availability_ of a resource, but NetworkInterfaceAvailable waiter has "_failure_" instead, which may be the root cause (see [here](https://github.com/boto/botocore/blob/23ee17f5446c78167ff442302471f9928c3b4b7c/botocore/data/ec2/2016-11-15/waiters-2.json#L352) )

### SDK version used

1.19.5 (but may happen on later versions as well, I believe)

### Environment details (OS name and version, etc.)

Linux

**Comment by aBurmeseDev** [comment]
Thanks @romos for reaching out!
Since our waiter models are shared across SDKs and owned by their service teams, I've contacted them regarding this and opened a new issue in our [cross-SDK repo](https://github.com/aws/aws-sdk) to address this issue. 
I will close this and please refer to that issue for updates going forward: https://github.com/aws/aws-sdk/issues/301
