### ISSUE TITLE
Cost Explorer Reports support

### ISSUE THREAD

**Issue by jjshoe** [boto/botocore#2720]
### Describe the feature

Cost explorer has an ability to save reports in the web console

There is no cli support
There is no botocore support

There is no documented API

### Use Case

Our billing group needs an easy way to get started in cost explorer. The easiest way to do this is to save reports. However we use terraform to automate everything we do in the web interface. Without this, there is no way to periodically check that changes haven't been made.

### Proposed Solution

1. Add the api documentation to the aws cost explorer website
2. Implement support for it in botocore (I'd like to take a crack at this)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

2

### Environment details (OS name and version, etc.)

n/a

**Comment by jjshoe** [comment]
Approval seems needed before I try to put up a PR because there is no documented API for this.

Using the network tab of the console I see things like:

http method: PUT
endpoint: https://us-east-1.console.aws.amazon.com/cost-management/data/report/v2/createReport
```
{
  "reportName": "jjshoe-test",
  "reportType": "COST_USAGE",
  "chartStyle": "GROUP",
  "queryAttributes": {
    "filter": null,
    "granularity": "MONTHLY",
    "metrics": [
      "NET_UNBLENDED_COST"
    ],
    "historicalTimePeriod": {
      "historicalOption": "LAST_3_MONTHS"
    }
  }
}
```

http method: GET
endpoint: https://us-east-1.console.aws.amazon.com/cost-management/data/report/v2/getReports
```
[
  {
    "reportId": "changed",
    "reportName": "jjshoe-test",
    "queryAttributes": {
      "historicalTimePeriod": {
        "historicalOption": "LAST_3_MONTHS"
      },
      "metrics": [
        "NET_UNBLENDED_COST"
      ],
      "granularity": "MONTHLY"
    },
    "createdAt": 1658252203443,
    "updatedAt": 1658252203443,
    "isDefault": false,
    "default": false,
    "reportType": "COST_USAGE",
    "chartStyle": "GROUP"
  }
]
```

**Comment by jjshoe** [comment]
@tim-finnigan it would be additions to the CE space. Cost and usage reports, as far as I understand, generates data which gets delivered to an s3 bucket, and not viewable int he web like reports in CE are.

**Comment by jjshoe** [comment]
@tim-finnigan it would also be great to know if the calls I documented above are part of the API, but not documented, or in fact are not part of the "official" api.

**Comment by tim-finnigan** [comment]
Hi @jjshoe thanks for following up. I don't know the answers to your questions but reached out to the Cost Explorer team to try and get more information. I also created a new issue for this in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/315. Please refer to that issue for updates going forward.
