### ISSUE TITLE
SQS.Queue.receive_messages AttributeNames argument has incorrect type

### ISSUE THREAD

**Issue by vemel** [boto/botocore#2726]
### Describe the bug

Here is a shape for AttributeNames:

```json
    "AttributeNameList":{
      "type":"list",
      "member":{
        "shape":"QueueAttributeName",
        "locationName":"AttributeName"
      },
      "flattened":true
    },
    ...
    "QueueAttributeName":{
      "type":"string",
      "enum":[
        "All",
        "Policy",
        "VisibilityTimeout",
        "MaximumMessageSize",
        "MessageRetentionPeriod",
        "ApproximateNumberOfMessages",
        "ApproximateNumberOfMessagesNotVisible",
        "CreatedTimestamp",
        "LastModifiedTimestamp",
        "QueueArn",
        "ApproximateNumberOfMessagesDelayed",
        "DelaySeconds",
        "ReceiveMessageWaitTimeSeconds",
        "RedrivePolicy",
        "FifoQueue",
        "ContentBasedDeduplication",
        "KmsMasterKeyId",
        "KmsDataKeyReusePeriodSeconds",
        "DeduplicationScope",
        "FifoThroughputLimit",
        "RedriveAllowPolicy",
        "SqsManagedSseEnabled"
      ]
    },
```

### Expected Behavior

According to [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Queue.receive_messages),  `AttributeNames = ["SenderId"]` should be accepted

### Current Behavior

`SenderId` is not in the list of accepted values. However, passing it works as expected.

### Reproduction Steps

```python
import boto3

resource = boto3.resource("sqs")

# client.create_queue(QueueName="test")
queue.send_message(
    MessageBody="test"}
)
result = queue.receive_messages(AttributeNames=["SenderId"])
```

While this code passes `botocore` param validation, `SenderId` is not the list of accepted values.

### Possible Solution

According to [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Queue.receive_messages), it should be smth like

```json
    "AttributeNameList":{
      "type":"list",
      "member":{
        "shape":"AttributeNameFilter",
        "locationName":"AttributeName"
      },
      "flattened":true
    },
    ...
    "AttributeNameFilter":{
      "type":"string",
      "enum":[
        "All",
        "SenderId",
        "SentTimestamp",
        "ApproximateReceiveCount",
        "ApproximateFirstReceiveTimestamp",
        "SequenceNumber",
        "MessageDeduplicationId",
        "MessageGroupId",
        "AWSTraceHeader",
        "SqsManagedSseEnabled"
      ]
    },
```

### SDK version used

1.24.42

### Environment details (OS name and version, etc.)

Ubuntu Linux

**Comment by tim-finnigan** [comment]
Hi @vemel thanks for reporting this. Since service teams own their model definitions, I reached out to the SQS team regarding this. I also created a new issue for tracking this in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/310. Please refer to that issue for updates going forward.
