### ISSUE TITLE
Support S3 Bucket ARNs

### ISSUE THREAD

**Issue by Patricol** [boto/botocore#2728]
### Describe the feature

Support S3 bucket ARNs in the format
`arn:aws-us-gov:s3:::bucket-name`, `arn:aws:s3:::bucket-name`, etc.

### Use Case

Being able to pass around and use disambiguated bucket names without needing to create `accesspoint`s etc. is rather convenient for applications that need to interact with buckets both inside and outside of govcloud.

Some buckets will share identical names in their respective 'global' namespaces.

### Proposed Solution

adjust `VALID_S3_ARN` in `botocore/handlers.py` to include something like `r'^arn:(aws).*:s3:::[a-zA-Z0-9.\-_]{1,255}$'`.

That would at least fix the `validate_bucket_name` function in the same file.

I'm not sure what other parts of botocore would need to be adjusted to handle buckets presented as ARNs rather than as raw names; but I imagine it'll be simpler than any special-casing that might exist already for treating `accesspoint`s etc. as buckets.

### Other Information

If the change is as simple as fixing `validate_bucket_name` as described above, I could open a PR for it. Otherwise I'm not very familiar with the botocore codebase.

Thank you for your time!

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.27.41

### Environment details (OS name and version, etc.)

various (I can provide more info if desired)

**Comment by Patricol** [comment]
The main issue is being able to validate and use a disambiguated bucket identifier.

The use case involves user-entry of bucket names and paths for data ingestion, in an app that is deployed separately both inside and outside of govcloud. I understand that many operations involving resources both inside and outside of govcloud are invalid for data security reasons, but some appear to not be, and users may not be aware of the nuances. Having a functional upstream bucket string validator, and being able to more easily give the user correct errors ('cannot access govcloud bucket from this environment' rather than 'bucket does not exist') is rather valuable. So is not needing to write custom code just to allow users to specify buckets as ARNs.

Some users may also have identically named buckets that exist both inside and outside of govcloud.

Another possible use would be a user working in an environment inside govcloud that wants to ingest files from a public non-govcloud bucket. Public, thus not requiring an (invalid) IAM relationship etc. between a govcloud and non-govcloud account.

The credentials used by the app for ingestion may differ per user and also differ from the user's main credentials; with a deployed environment having access to multiple sets of credentials.

**Comment by tim-finnigan** [comment]
Thanks @Patricol for following up. My understanding is that any restrictions related to GovCloud regions are necessary for security reasons as you alluded to. This documentation could be a helpful reference: [How Amazon Simple Storage Service Differs for AWS GovCloud (US)](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-s3.html#govcloud-S3-diffs). 

But I reached out to the S3 team regarding your request and created a new issue for tracking in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/314. Please refer to that issue for updates going forward and let us know if had any additional questions or feedback.
