### ISSUE TITLE
Connection broken: IncompleteRead(0 bytes read)

### ISSUE THREAD

**Issue by ahmed-sharief5** [boto/botocore#2745]
### Describe the bug

I am using multiprocessing to run few of my computations to run parallelly in which i have reading file from s3 for which i am using boto3 as a client. But unfortunately instead of reading the file it throws me the below error

`botocore.exceptions.ResponseStreamingError: An error occurred while reading from response stream: ('Connection broken: IncompleteRead(0 bytes read, 403 more expected)', IncompleteRead(0 bytes read, 403 more expected))`

Below is the code snippet to read file from s3
`S3 = boto3.client('s3', region_name=os.environ["REGION"],config=Config(signature_version='s3v4', retries={'max_attempts': 3}))
data = BytesIO(S3.get_object(Bucket=bucket, Key=key)['Body'].read())`

### Expected Behavior

Read a file from s3 without any ResponseStreamingError

### Current Behavior

Not reading the file from s3 throwing botocore.exceptions.ResponseStreamingError error

### Reproduction Steps

1. Create a multiprocessing processes 
2. Add read file from s3 code (added the snippet above)

### SDK version used

boto3==1.20.2

### Environment details (OS name and version, etc.)

AWS ECS container image, Python 3.8

**Comment by aBurmeseDev** [comment]
Hi @ahmed-sharief5, thanks for reaching out.

Sorry to hear you're having an issue. Can you please post full debug logs by adding `boto3.set_stream_logger('')` to your script, redacting any sensitive information? I was not able to reproduce, though I found this [stackOverflow post](https://stackoverflow.com/questions/56367785/incompletereaderror-when-reading-file-from-s3-on-aws-lambda) that might be worth checking out.
