### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by limburgher** [boto/botocore#2752]
### Describe the bug

A test fails on 1.27.63 and up. Currently using Fedora 36-38, Python3.10 and 3.11.

### Expected Behavior

Test passes

### Current Behavior

tests/unit/test_client.py:1650: AssertionError
________________ TestClientErrors.test_BOTO_DISABLE_COMMONNAME _________________

self = <tests.unit.test_client.TestClientErrors testMethod=test_BOTO_DISABLE_COMMONNAME>

    @mock.patch.dict(os.environ, {'BOTO_DISABLE_COMMONNAME': 'true'})
    def test_BOTO_DISABLE_COMMONNAME(self):
        creator = self.create_client_creator()
        self.endpoint_data['sslCommonName'] = 'bar'
    
        with pytest.warns(None) as warning:
            creator.create_client(
                'myservice', 'us-west-2', credentials=self.credentials
            )
>           self.assertEqual(len(warning), 0)
E           AssertionError: 1 != 0

tests/unit/test_client.py:1650: AssertionError

### Reproduction Steps

pytest

### SDK version used

1.27.63-65

### Environment details (OS name and version, etc.)

Fedora 36-37-38

**Comment by tim-finnigan** [comment]
Hi @limburgher thanks for reaching out. The unit test succeeded in all of the test builds so there may be something in your environment causing the test to fail. There may be another environment variable causing the issue. If you could share any relevant environment variables (with sensitive ones redacted) then that is something we could look more into.

**Comment by tim-finnigan** [comment]
Hi @limburgher thanks for reaching out. The unit test succeeded in all of the test builds so there is likely something in your environment causing this. You could be getting an unrelated warning that is making the test fail. We’d need to know what the warning this which would require a further inspection of your code. Are you able to print the warning value?

**Comment by limburgher** [comment]
[2507.patch.txt](https://github.com/boto/botocore/files/9478347/2507.patch.txt)
[build-1.27.65-1.fc38.log](https://github.com/boto/botocore/files/9478407/build-1.27.65-1.fc38.log)
Attaching the only patch we carry and the complete build log.

FYI this is failing during the RPM build, I'm one of the Fedora package maintainers.

**Comment by glaubitz** [comment]
Tests are failing in openSUSE as well:

```
[  354s] =================================== FAILURES ===================================
[  354s] _____________ TestAutoGeneratedClient.test_BOTO_DISABLE_COMMONNAME _____________
[  354s] 
[  354s] self = <tests.unit.test_client.TestAutoGeneratedClient testMethod=test_BOTO_DISABLE_COMMONNAME>
[  354s] 
[  354s]     @mock.patch.dict(os.environ, {'BOTO_DISABLE_COMMONNAME': 'true'})
[  354s]     def test_BOTO_DISABLE_COMMONNAME(self):
[  354s]         creator = self.create_client_creator()
[  354s]         self.endpoint_data['sslCommonName'] = 'bar'
[  354s]     
[  354s]         with warnings.catch_warnings(record=True) as captured_warnings:
[  354s]             creator.create_client(
[  354s]                 'myservice', 'us-west-2', credentials=self.credentials
[  354s]             )
[  354s]     
[  354s]         deprecated_endpoint_warnings = [
[  354s]             w
[  354s]             for w in captured_warnings
[  354s]             if w.category == FutureWarning
[  354s]             and 'deprecated endpoint' in str(w.message)
[  354s]         ]
[  354s] >       self.assertEqual(len(deprecated_endpoint_warnings), 0)
[  354s] E       AssertionError: 1 != 0
[  354s] 
[  354s] tests/unit/test_client.py:1656: AssertionError
[  354s] ________________ TestClientErrors.test_BOTO_DISABLE_COMMONNAME _________________
[  354s] 
[  354s] self = <tests.unit.test_client.TestClientErrors testMethod=test_BOTO_DISABLE_COMMONNAME>
[  354s] 
[  354s]     @mock.patch.dict(os.environ, {'BOTO_DISABLE_COMMONNAME': 'true'})
[  354s]     def test_BOTO_DISABLE_COMMONNAME(self):
[  354s]         creator = self.create_client_creator()
[  354s]         self.endpoint_data['sslCommonName'] = 'bar'
[  354s]     
[  354s]         with warnings.catch_warnings(record=True) as captured_warnings:
[  354s]             creator.create_client(
[  354s]                 'myservice', 'us-west-2', credentials=self.credentials
[  354s]             )
[  354s]     
[  354s]         deprecated_endpoint_warnings = [
[  354s]             w
[  354s]             for w in captured_warnings
[  354s]             if w.category == FutureWarning
[  354s]             and 'deprecated endpoint' in str(w.message)
[  354s]         ]
[  354s] >       self.assertEqual(len(deprecated_endpoint_warnings), 0)
[  354s] E       AssertionError: 1 != 0
[  354s] 
[  354s] tests/unit/test_client.py:1656: AssertionError
```

**Comment by dlm6693** [comment]
@glaubitz could you share a bit more information on how you're running the test? I'm unable to reproduce using openSUSE and python in a docker container.

**Comment by glaubitz** [comment]
> @glaubitz could you share a bit more information on how you're running the test? I'm unable to reproduce using openSUSE and python in a docker container.

You need to run a package build.

To reproduce on openSUSE:

```
# zypper in osc
```

and

```
$ osc co devel:languages:python:aws python-botocore
$ cd python-botocore
$ osc build
```

**Comment by jonemo** [comment]
Hi @glaubitz, thank you for providing those details. I attempted to reproduce the test failure with your instructions above on a fresh SUSE instance (using the "SUSE Linux Enterprise Server 15 SP4 (HVM)" AMI available on EC2). I am very new to these tools and may be misunderstand the process, but it looks to me as if the build was a success. Here are the last few lines of the output of `osc build`:

```
[  194s] ip-172-31-63-218 finished "build python-botocore.spec" at Mon Sep 12 16:57:56 UTC 2022.
[  194s]

/var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/SRPMS/python-botocore-1.27.64-0.src.rpm

/var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/RPMS/noarch/python38-botocore-1.27.64-0.noarch.rpm
/var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/RPMS/noarch/python39-botocore-1.27.64-0.noarch.rpm
/var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/RPMS/noarch/python310-botocore-1.27.64-0.noarch.rpm
```

I did notice that the command `osc co devel:languages:python:aws python-botocore` downloads the file `botocore-1.27.64.tar.gz`. Version 1.27.64 is newer than the version reported as failing tests by @limburgher but older than the version that generated your test output [above](https://github.com/boto/botocore/issues/2752#issuecomment-1236275405).

Do you have any suggestions for what I can do to get closer to reproducing the error?

Notes for anyone else attempting to reproduce this:
* An account for openSUSE is required as documented [on the openSUSE Wiki here](https://en.opensuse.org/openSUSE:OSC#Authentication).
* I had to place [this file](https://github.com/openSUSE/osc-plugin-install/blob/master/osc-install.py) in my `~/.osc-plugins` directory and then used it to `osc in obs-service-format_spec_file`. I'm sure there is an easier way to achieve this, but this is the one I figured out...

**Comment by limburgher** [comment]
For completeness, all versions since the one I reported have this issue for me.

**Comment by glaubitz** [comment]
> Hi @glaubitz, thank you for providing those details. I attempted to reproduce the test failure with your instructions above on a fresh SUSE instance (using the "SUSE Linux Enterprise Server 15 SP4 (HVM)" AMI available on EC2). I am very new to these tools and may be misunderstand the process, but it looks to me as if the build was a success.

Apologies, my mistake. I forgot that `python-botocore` is a multibuild package where the testsuite is a separate package build.

Try building with:

```
$ osc build -M test
```

and to ensure it really builds inside Tumblweed, build with:

```
$ osc build -M test openSUSE_Tumbleweed
```

**Comment by jonemo** [comment]
@glaubitz Could you please also advise on how I can get `osc` to use the latest version of botocore instead of 1.27.64?

**Comment by glaubitz** [comment]
> @glaubitz Could you please also advise on how I can get `osc` to use the latest version of botocore instead of 1.27.64?

Install `py2pack`:

```
# zypper in python3-py2pack
```

then run:

```
$ py2pack fetch botocore
$ osc addremove
```

Edit the spec file to update the version field to the version that you just downloaded. Then try building again.

The current version of `python-botocore` has not been updated due to this bug report.

**Comment by jonemo** [comment]
The root cause turned out to be something unrelated to the build environments: There had been leakage of test setup between tests. The new test surfaced this for the first time, but only when functional tests are run before unit tests and in the same test session. 

#2761 addresses that and, barring further surprises, should fix these test failures once released. I also audited the use of similar code patterns in the botocore test code and made some improvements to reduce the likelihood of something similar happening again. 

Note that this test failure was due to testing code only, this was not an issue with botocore functionality itself.

Thank you @limburgher and @glaubitz for reporting the problem and sharing detailed information!

**Comment by limburgher** [comment]
Thank you, applyng 2761 to 1.27.71 works!

**Comment by glaubitz** [comment]
Good to hear the issue has been resolved. Could you release a new version with the patch included soonish? Then I can just update the package in openSUSE and don't need to cherry-pick the patch.

**Comment by jonemo** [comment]
Version 1.27.72 was. released approximately an hour ago and contains this change. 

Out of curiosity: How often does this process of making new botocore versions in openSUSE and Fedora happen? (In times when there is no test failure that is blocking the process.)

**Comment by limburgher** [comment]
I typically update Fedora rawhide and occasionally rawhide-1 within 48 hours of each release.
