### ISSUE TITLE
Boto client instantiation hangs for ~5 seconds on Azure function app.

### ISSUE THREAD

**Issue by nsight1** [boto/botocore#2755]
### Describe the bug

When creating a new boto3.client() object within a python3.8 Azure Function app, the process hangs for approximately 5 seconds always on the same line.  The quickest i have seen the step run is about 3 seconds, and have seen it take up to 8 seconds, but normally around 5.  When running the code locally it takes <1s as you would expect for this library.

help!

### Expected Behavior

Not to wait 5 seconds for the client object.

### Current Behavior

my code:

```
import boto3
import logging
boto3.set_stream_logger(name="", level=logging.DEBUG)
session = boto3.Session()
logging.debug("Getting sqs client")
sqs_client = session.client("sqs")
logging.debug("Got sqs client")
```
Extract from logging:
```
[INFO] 2:39:11.698 PM  -  Getting sqs client
[DEBUG] 2:39:11.907 PM  -  IMDS ENDPOINT: http://169.254.169.254/
[DEBUG] 2:39:11.995 PM  -  Looking for credentials via: env
[INFO] 2:39:12.038 PM  -  Found credentials in environment variables.
[DEBUG] 2:39:12.166 PM  -  Loading JSON file: /home/site/wwwroot/.python_packages/lib/site-packages/botocore/data/endpoints.json
[DEBUG] 2:39:12.181 PM  -  Loading JSON file: /home/site/wwwroot/.python_packages/lib/site-packages/botocore/data/sdk-default-configuration.json
[DEBUG] 2:39:12.183 PM  -  Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f2ec8050ca0>
[DEBUG] 2:39:17.292 PM  -  Loading JSON file: /home/site/wwwroot/.python_packages/lib/site-packages/botocore/data/sqs/2012-11-05/service-2.json
[DEBUG] 2:39:17.320 PM  -  Event creating-client-class.sqs: calling handler <function add_generate_presigned_url at 0x7f2ec80cf1f0>
[DEBUG] 2:39:17.359 PM  -  Setting sqs timeout as (60, 60)
[DEBUG] 2:39:17.389 PM  -  Loading JSON file: /home/site/wwwroot/.python_packages/lib/site-packages/botocore/data/_retry.json
[DEBUG] 2:39:17.398 PM  -  Registering retry handlers for service: sqs
[INFO] 2:39:17.406 PM  -  Got sqs client
```

The line `Event choose-service-name: calling handler` takes consistently five seconds every time I run this. As you can see the timestamp `2:39:12.183 PM` jump to `2:39:17.292 PM` on the next line.

I have also tried using boto3.client() using default session and it makes no difference to the behaviour.

I have no idea what to do next, aside from adding more logging into a copy of the botocore library.  Any advice on what is happening in that specific line?

### Reproduction Steps

deploy the above code on to an azure function app to get a boto3 client.

### SDK version used

boto3==1.24.67   botocore==1.27.67

### Environment details (OS name and version, etc.)

Azure Function app, linux.

**Comment by tim-finnigan** [comment]
Hi @nsight1 thanks for reaching out. Does the occur with other services besides SQS? If this works fine locally then the issue may relate to Azure Functions. You could consider creating an issue in their repository: https://github.com/Azure/Azure-Functions. For more context here is where that line is logged: https://github.com/boto/botocore/blob/develop/botocore/client.py#L111. I also created a feature request a while ago related to improving the documentation on what is involved in the botocore startup process: https://github.com/boto/botocore/issues/2553.

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a few weeks I'm going to close this issue. If you are still affected by this please refer to the comment above and follow up here. Thanks!

**Comment by jimdigriz** [comment]
@raptorworks try setting `os.environ['AWS_METADATA_SERVICE_NUM_ATTEMPTS'] = '0'` before you call `boto3.client()` or `boto3.resource()`.
