### ISSUE TITLE
 boto streaming_body.iter_lines() results in root [ERROR] Read timeout on endpoint URL: "None"

### ISSUE THREAD

**Issue by OleksiiYeromenko** [boto/botocore#2764]
### Describe the bug

From time to time AWS Lambda throws such errors when trying to read a file with a list of JSONs from s3.   
There is no clear pattern, hard to reproduce it looks like it's related with the load on s3.

### Expected Behavior

Normal processing of iter_lines() or meaningful error description.

### Current Behavior

3-5 times per day  receiving such errors:
```
[ERROR] ReadTimeoutError: Read timeout on endpoint URL: "None"
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 234, in lambda_handler
    raise e
  File "/var/task/lambda_function.py", line 230, in lambda_handler
    jsons_list = read_json_data(boto_streaming_body)
  File "/var/task/lambda_function.py", line 46, in read_json_data
    for line in body.iter_lines():
  File "/var/runtime/botocore/response.py", line 118, in iter_lines
    for chunk in self.iter_chunks(chunk_size):
  File "/var/runtime/botocore/response.py", line 131, in iter_chunks
    current_chunk = self.read(chunk_size)
  File "/var/runtime/botocore/response.py", line 85, in read
    raise ReadTimeoutError(endpoint_url=e.url, error=e)
```

File on s3 is ok, if copy it again - all fine.  Issue could be with very frequent and heavy reading from s3, but can't debug as it's unstable happens not frequently.  

File name and bucket in `s3.get_object(Bucket=bucket, Key=key)` - is correct.

Code example:
```
  for record in records:
        data = json.loads(record['Sns']['Message'])
        bucket = data['Records'][0]['s3']['bucket']['name']
        key = unquote_plus(data['Records'][0]['s3']['object']['key'], encoding='utf-8')
        logging.info(f"### bucket: {bucket} \n file: {key}")    
        try:
            response = s3.get_object(Bucket=bucket, Key=key)
            boto_streaming_body = response['Body']  
            
            
            jsonsList =[]
            for line in boto_streaming_body.iter_lines():
                try:
                    data_json = json.loads(line)
                    jsonsList.append(data_json) 
                except:
                    logging.info(f'Error in json.loads reading json transaction from a file')   
                
            
 
        except Exception as e:
            logging.error(e)
            logging.error('Error getting object {} from bucket {}. Make sure they exist and your bucket is in the same region as this function.'.format(key, bucket))
            raise e

```

### Reproduction Steps

It's hard to reproduce as it happens randomly few times per day. But could be related that we have multiple lambdas reading frequently files up to 25Mb from s3.

```
 response = s3.get_object(Bucket=bucket, Key=key)
 boto_streaming_body = response['Body']  
 for line in boto_streaming_body.iter_lines()::
...
```

### Additional Information/Context

Need to understand the reason for this error.

### SDK version used

boto3.__version__: 1.20.32

### Environment details (OS name and version, etc.)

Windows 11

**Comment by tim-finnigan** [comment]
Hi @OleksiiYeromenko thanks for reaching out. Here is an article on troubleshooting timeout errors in Lambda functions that may help: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/

Have you tried updating the boto3 timeout and retry configurations? Here is the boto3 documentation on [configuration](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html) and [retries](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html).

**Comment by OleksiiYeromenko** [comment]
Thank you, will check now.
I had following config: `Config(connect_timeout=30, retries={'max_attempts': 4})`

> Hi @OleksiiYeromenko thanks for reaching out. Here is an article on troubleshooting timeout errors in Lambda functions that may help: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/
> 
> Have you tried updating the boto3 timeout and retry configurations? Here is the boto3 documentation on [configuration](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html) and [retries](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html).

**Comment by OleksiiYeromenko** [comment]
After switching from `body.iter_lines()` to  `body._raw_stream.readlines()`, Error changed from `Read timeout on endpoint URL: "None"` to `ReadTimeoutError: AWSHTTPSConnectionPool`.  
So that's mean I have issues reading file from s3,  I changed config to   
`Config(connect_timeout=100,read_timeout=100, retries={'max_attempts': 10})`.

Will highly appreciate advice on how to troubleshoot the reasons why it happens.


```
[ERROR] ReadTimeoutError: AWSHTTPSConnectionPool(host='xxx.eu-west-1.amazonaws.com', port=443): Read timed out.
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 240, in lambda_handler
    raise e
  File "/var/task/lambda_function.py", line 236, in lambda_handler
    jsons_list = read_json_data(boto_streaming_body)
  File "/var/task/lambda_function.py", line 52, in read_json_data
    all_body_lines = body._raw_stream.readlines()
  File "/opt/python/urllib3/response.py", line 811, in __iter__
    for chunk in self.stream(decode_content=True):
  File "/opt/python/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/python/urllib3/response.py", line 544, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/var/lang/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/python/urllib3/response.py", line 446, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
```

**Comment by tim-finnigan** [comment]
@OleksiiYeromenko thanks for following up. Could you share the logs prior to the read timeout occurring? And can you confirm if the function works locally outside of Lambda? If this is a long-running task then another services such as AWS Fargate may be better suiting for accomplishing it since the max Lambda runtime is 15 minutes.

**Comment by OleksiiYeromenko** [comment]
> @OleksiiYeromenko thanks for following up. Could you share the logs prior to the read timeout occurring? And can you confirm if the function works locally outside of Lambda? If this is a long-running task then another services such as AWS Fargate may be better suiting for accomplishing it since the max Lambda runtime is 15 minutes.

Yes, thanks.
Function works fine locally and during tests in Lambda, it happens from time to time. Runtime is fine, current Lambda configuration timeout - 5min, but execution usually takes 2-3min.

In debug see that `botocore.retryhandler [DEBUG] No retry needed.`, in Response metadata also `'RetryAttempts': 0`. So it's very strange. 
Any ideas how I can debug this Read timed out?


Logs from start:
![image](https://user-images.githubusercontent.com/50664057/191668952-8e6b68ea-5a2d-4f26-a9f6-083dd60a7315.png)

**Comment by OleksiiYeromenko** [comment]
Additionally -I've checked all files form S3 which got ERROR, in 1 minute later were triggered again and processed successfully.  
The source for Lambda is SNS, triggered by updates in S3.   
So main question - how properly debug the reason why we are having these errors reading by boto from s3..

**Comment by tim-finnigan** [comment]
Have you ruled out network issues as a possible cause for this? Since the issue occurs randomly as you mentioned. To get the boto3 logs you can add `boto3.set_stream_logger('')` to your script. That might provide more insight into what's going on. Also what is the highest value you've increased your `connect_timeout` and `read_timeout` to?

**Comment by OleksiiYeromenko** [comment]
Recent Error with logs from boto:
![image](https://user-images.githubusercontent.com/50664057/192726187-172f9de9-7306-4483-b706-9bcae18be7d6.png)

**Comment by tim-finnigan** [comment]
Are you using the same region where your bucket is located? Also have you tried using `tcp_keepalive` as mentioned in https://github.com/boto/boto3/issues/2510#issuecomment-1163825488. See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html?highlight=tcp_keepalive#configuration-file

**Comment by OleksiiYeromenko** [comment]
Yep, all in same region.  I will try `tcp_keepalive`

**Comment by OleksiiYeromenko** [comment]
Sorry, @tim-finnigan , thank you for your support, we've fixed an issue, it was indeed related to the VPC endpoint - requests to s3 were going through internal network, external Internet and then hit S3, very long trip. After switching to VPC endpoint no errors anymore.

**Comment by tim-finnigan** [comment]
Thanks @OleksiiYeromenko for letting us know! I'll go ahead and close this issue.
