### ISSUE TITLE
S3 copy_object fail between cross account S3 buckets

### ISSUE THREAD

**Issue by littlenine** [boto/botocore#2773]
### Describe the bug

Assume 2 account: 
- SOURCE: allow get s3 object
- TARGET:  allow put s3 object

When SOURCE assume role to TARGET and call `s3_client.copy_object`, exception occurs.
```
[ERROR] dict' object has no attribute 'split'
```

Same behavior when using `put_object`.
No error shows under no cross-account scenario.

### Expected Behavior

no exception

### Current Behavior

Traceback
```
assumed_s3_client.copy_object(CopySource=copy_source, Bucket='my-target-bucket', Key='whatever')
File "/var/runtime/botocore/client.py", line 391, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 705, in _make_api_call
http, parsed_response = self._make_request(
File "/var/runtime/botocore/client.py", line 725, in _make_request
return self._endpoint.make_request(operation_model, request_dict)
File "/var/runtime/botocore/endpoint.py", line 104, in make_request
return self._send_request(request_dict, operation_model)
File "/var/runtime/botocore/endpoint.py", line 134, in _send_request
request = self.create_request(request_dict, operation_model)
File "/var/runtime/botocore/endpoint.py", line 117, in create_request
self._event_emitter.emit(event_name, request=request,
File "/var/runtime/botocore/hooks.py", line 357, in emit
return self._emitter.emit(aliased_event_name, **kwargs)
File "/var/runtime/botocore/hooks.py", line 228, in emit
return self._emit(event_name, kwargs)
File "/var/runtime/botocore/hooks.py", line 211, in _emit
response = handler(**kwargs)
File "/var/runtime/botocore/signers.py", line 93, in handler
return self.sign(operation_name, request)
File "/var/runtime/botocore/signers.py", line 165, in sign
auth.add_auth(request)
File "/var/runtime/botocore/auth.py", line 384, in add_auth
canonical_request = self.canonical_request(request)
File "/var/runtime/botocore/auth.py", line 326, in canonical_request
cr.append(self.canonical_headers(headers_to_sign) + '\n')
File "/var/runtime/botocore/auth.py", line 268, in canonical_headers
value = ','.join(self._header_value(v) for v in
File "/var/runtime/botocore/auth.py", line 268, in <genexpr>
value = ','.join(self._header_value(v) for v in
File "/var/runtime/botocore/auth.py", line 279, in _header_value
return ' '.join(value.split())
AttributeError: 'dict' object has no attribute 'split'
```

### Reproduction Steps

in AWS Lambda with Py3.9
```
for record in event['Records']:
                _bucket = record['s3']['bucket']['name']
                _path = record['s3']['object']['key']
                
                copy_source = {
                    'Bucket': _bucket,
                    'Key': _path
                }
                assumed_s3_client.copy_object(CopySource=copy_source, Bucket='my-target-bucket', Key=_path)
}
```

### SDK version used

1.20.32

### Environment details (OS name and version, etc.)

AWS Lambda Py 3.9

**Comment by tim-finnigan** [comment]
Hi @littlenine thanks for reaching out. This appears to be a general Python error rather than a boto3 issue. Have you tried searching on platforms such as StackOverflow for guidance? For example [this post](https://stackoverflow.com/questions/61973622/attributeerror-dict-object-has-no-attribute-split). But if that doesn't help could you share your full debug logs (with sensitive info redacted) by adding `boto3.set_stream_logger('')` to your script?

**Comment by Caitlyn-Wu** [comment]
hello @tim-finnigan ,

Thanks for suggestions, `boto3.set_stream_logger` doesn't provide any more information than traceback above.

While s3 client correctly receive assume role credential, it doesn't looks like error came from there.
The only `dict` in the code were `copy_source`, which was told to be a dict on doc.
```
copy_source = { 'Bucket': record['s3']['bucket']['name'],  'Key': record['s3']['object']['key'] }
assumed_s3_client.copy_object(CopySource=copy_source, Bucket='my-target-bucket', Key='whatever')
```
Therefore I submit bug here cause obviously it turns out handle `put-object` failed when handling http headers.

Here's the `record`, which is auto generated example from Lambda Test for fake S3 PUT event for reference.
```
{
  "Records": [
    {
      "eventVersion": "2.0",
      "eventSource": "aws:s3",
      "awsRegion": "ap-southeast-1",
      "eventTime": "1970-01-01T00:00:00.000Z",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "EXAMPLE"
      },
      "requestParameters": {
        "sourceIPAddress": "127.0.0.1"
      },
      "responseElements": {
        "x-amz-request-id": "EXAMPLE123456789",
        "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH"
      },
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "testConfigRule",
        "bucket": {
          "name": "my-source-bucket",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          },
          "arn": "arn:aws:s3:::my-source-bucket"
        },
        "object": {
          "key": "helloworld",
          "size": 14,
          "eTag": "74c7c6c4b67ddcbcfb74a07fa7500dc3"
        }
      }
    }
  ]
}
```

**Comment by littlenine** [comment]
hello @tim-finnigan ,

Thanks for suggestions, `boto3.set_stream_logger` doesn't provide any more information than traceback above.

While s3 client correctly receive assume role credential, it doesn't looks like error came from there.
The only `dict` in the code were `copy_source`, which was told to be a dict on doc.
```
copy_source = { 'Bucket': record['s3']['bucket']['name'],  'Key': record['s3']['object']['key'] }
assumed_s3_client.copy_object(CopySource=copy_source, Bucket='my-target-bucket', Key='whatever')
```
Therefore I submit bug here cause obviously it turns out `put-object` failed when handling http headers.

Here's the `record`, which is auto generated example from Lambda Test for fake S3 PUT event for reference.
```
{
  "Records": [
    {
      "eventVersion": "2.0",
      "eventSource": "aws:s3",
      "awsRegion": "ap-southeast-1",
      "eventTime": "1970-01-01T00:00:00.000Z",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "EXAMPLE"
      },
      "requestParameters": {
        "sourceIPAddress": "127.0.0.1"
      },
      "responseElements": {
        "x-amz-request-id": "EXAMPLE123456789",
        "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH"
      },
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "testConfigRule",
        "bucket": {
          "name": "my-source-bucket",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          },
          "arn": "arn:aws:s3:::my-source-bucket"
        },
        "object": {
          "key": "helloworld",
          "size": 14,
          "eTag": "74c7c6c4b67ddcbcfb74a07fa7500dc3"
        }
      }
    }
  ]
}
```

**Comment by tim-finnigan** [comment]
Hi @littlenine thanks for your patience.  Did you have any updates on your end? It would still help to have the debug logs in order to get more insight into this issue.

I also recommend updating your version of boto3 as 1.20.32 is quite old. The latest version is 1.26.37 per the [CHANGELOG](https://github.com/boto/boto3/blob/master/CHANGELOG.rst). And if you're having trouble updating on Lambda specifically then I suggest referring to this guide: https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-runtime-errors/

**Comment by Caitlyn-Wu** [comment]
@tim-finnigan thanks for your update and suggestion.   
Due to the schedule, we just workaround with AWS CLI.  I will see if I could give it a test for a newer boto3 version.

**Comment by littlenine** [comment]
@tim-finnigan thanks for your update and suggestion.   
Due to the schedule, we just workaround with AWS CLI.  I will see if I could give it a test for a newer boto3 version.
Feel free to close this issue, thanks again.
