### ISSUE TITLE
Incorrect removal of fsx supported region in endpoints.json file

### ISSUE THREAD

**Issue by darrendao** [boto/botocore#2781]
### Describe the bug

With release https://github.com/boto/botocore/releases/tag/1.27.76, the list of fsx supported endpoints were incorrectly removed in many regions. For example, fsx is supported in us-west-1 and yet, it is no longer listed there in endpoints.json https://github.com/boto/botocore/blob/0492a8cb3b53383822dbb25729e938bb576ad02a/botocore/data/endpoints.json.  This then affects other tools/libraries that rely on botocore endpoints.json file. Specific, we're using cloud-custodian (https://github.com/cloud-custodian/cloud-custodian) and this bug has prevented us from being able to deploy fsx-related policies to regions that were incorrectly removed.

### Expected Behavior

endpoints.json file should include correct list of supported region endpoint for fsx

### Current Behavior

endpoint.json doesn't include the full list of supported regions for fsx.

### Reproduction Steps

Install botocore version `1.27.76`, boto3 version `1.24.44`. Then run

```
>>> import boto3
>>> boto3.session.Session().get_available_regions('fsx')
['ap-northeast-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1', 'eu-west-1', 'eu-west-2', 'us-east-1', 'us-east-2', 'us-west-2']
```

That is the wrong list. Here's the correct list if we're. using botocore version `1.27.75`
```
>>> import boto3
>>> boto3.session.Session().get_available_regions('fsx')
['af-south-1', 'ap-east-1', 'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1', 'eu-north-1', 'eu-south-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'me-south-1', 'sa-east-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
```

### Additional Information/Context

I believe the incorrect removal of the support regions for fsx is related to this feature: https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-file-cache-generally-available/. This new file cache feature is only available in a subset of regions. fsx as a service though should still be considered supported/available in the original list of regions and the removal should not have been done.

### SDK version used

1.27.76

### Environment details (OS name and version, etc.)

mac osx 11.7

**Comment by nateprewitt** [comment]
Hi @darrendao, thanks for bringing this to our attention. It appears the service team had incorrectly removed regions from their configuration for fsx. We've remedied the issue in all SDKs this morning with botocore 1.27.94 in af200ef1091ff4759649a34d3813db4dd97c5272.

Please let us know if you have any other concerns, otherwise I'll mark this as resolved. Thanks!
