### ISSUE TITLE
ResponseParserError: Unable to parse response when sending a message over ~2MB through SNS

### ISSUE THREAD

**Issue by adrianespejo** [boto/botocore#2784]
### Describe the bug

SNS has a [message size limit of 256KB](https://docs.aws.amazon.com/sns/latest/dg/large-message-payloads.html), and to work around that I'm catching the exception and uploading the message to S3 as the [Amazon SNS Extended Client Library for Java](https://github.com/awslabs/amazon-sns-java-extended-client-lib/) does.

This works for messages between 256KB and ~2MB, I'm not sure at exactly what size this starts to fail.

I'm using an SNS FIFO topic with content-based deduplication.

### Expected Behavior

I expected botocore to be able to parse the response and raise the expected exception: `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Message too long`.

### Current Behavior

For messages over ~2MB, the error is `botocore.parsers.ResponseParserError: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed: b''`.

### Reproduction Steps

Example message: [message.txt](https://github.com/boto/botocore/files/9838162/message.txt)

```python
import boto3

sns_client = boto3.client("sns", region_name="eu-west-1")
with open("message.txt", "r") as message_file:
    message = message_file.read().strip()
    sns_client.publish(TopicArn="...", Message=message, MessageGroupId="0")
```

### Additional Information/Context

I've had a chat with AWS support and they could replicate this error, but they informed me that this limitation pertains to boto3 or botocore libraries.

### SDK version used

1.24.21

### Environment details (OS name and version, etc.)

EKS service in AWS using a custom Python image based on "python:3.9.14-slim"

**Comment by tim-finnigan** [comment]
Hi @adrianespejo thanks for reaching out. I was having trouble reproducing this issue. It looks like that `ResponseParserError` error has been [reported a few times](https://github.com/issues?q=is%3Aissue+%22botocore.parsers.ResponseParserError%3A%22+repo%3Aboto%2Fboto3+repo%3Aboto%2Fbotocore) before but those issues involve other services/APIs. If you could provide the full debug logs (with any sensitive info redacted) by adding `boto3.set_stream_logger('')` to your script that might help give more insight into what's going on. Were you able to run this command successfully in other AWS SDKs aside from boto3?

**Comment by adrianespejo** [comment]
Hi @tim-finnigan, these are the debug logs:

```
> Event before-call.sns.Publish: calling handler <function inject_api_version_header_if_needed at 0x7f69368f7550>
> Event before-parameter-build.sns.Publish: calling handler <function generate_idempotent_uuid at 0x7f69368f0ca0>
> Event before-call.sns.Publish: calling handler <function add_recursion_detection_header at 0x7f69368f0940>
> (large blob)
> {"level": "DEBUG", "logger_name": "botocore.endpoint:make_request", "message": "Making request for OperationModel(name=Publish) 
with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; 
charset=utf-8', 'User-Agent': 'Boto3/1.21.21 Python/3.9.13 Linux/5.4.209-116.363.amzn2.x86_64 Botocore/1.24.21'}, 
'body': {'Action': 'Publish', 'Version': '2010-03-31', 'TopicArn': 'arn:aws:sns:eu-west-1:558096356967:topic.fifo', 'Message': large blob}
> Event choose-signer.sns.Publish: calling handler <function set_operation_specific_signer at 0x7f69368f0b80>
> Event request-created.sns.Publish: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f692f777d60>>
> Calculating signature using v4 auth.
> CanonicalRequest:
  POST
  /

  content-type:application/x-www-form-urlencoded; charset=utf-8
  host:sns.eu-west-1.amazonaws.com
  x-amz-date:20221017T101625Z
  x-amz-security-token: ...

  content-type;host;x-amz-date;x-amz-security-token
  ...
> StringToSign: AWS4-HMAC-SHA256 20221017T101625Z 20221017/eu-west-1/sns/aws4_request ...
> Signature: ...
> Event request-created.sns.Publish: calling handler <function add_retry_headers at 0x7f69368f7c10>
> Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://sns.eu-west-1.amazonaws.com/, 
headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 
'User-Agent': b'Boto3/1.21.21 Python/3.9.13 Linux/5.4.209-116.363.amzn2.x86_64 Botocore/1.24.21', 'X-Amz-Date': b'20221017T101625Z', 
'X-Amz-Security-Token': b'...', 'Authorization': b'AWS4-HMAC-SHA256 Credential=.../20221017/eu-west-1/sns/aws4_request, 
SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=...', 'amz-sdk-invocation-id': b'...', 
'amz-sdk-request': b'attempt=1', 'Content-Length': '4032742'}>
> Resetting dropped connection: sns.eu-west-1.amazonaws.com
> https://sns.eu-west-1.amazonaws.com:443 "POST / HTTP/1.1" 413 0
> Response headers: {'Content-Length': '0', 'Date': 'Mon, 17 Oct 2022 10:16:24 GMT', 'Connection': 'close'}
> Response body: b''
> botocore.parsers.ResponseParserError: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:
b''
```

**Comment by adrianespejo** [comment]
> Were you able to run this command successfully in other AWS SDKs aside from boto3?

I didn't try, sorry. From my conversation with AWS support I understood that the standard way of doing this is with the Java SDK, so I suppose it works there. I don't know about other SDKs.

**Comment by tim-finnigan** [comment]
Hi @adrianespejo thanks for following up. Can you confirm that the size of the file is causing the error and not some special formatting in your messages.txt file? Several users have reported "invalid XML" errors before but they generally seem due to something related to formatting/encoding such as special characters (for example see: https://github.com/boto/boto3/issues/581).

Also if Java has a special client for handling this scenario then this issue would likely be a feature request for consistent functionality, which would likely have to occur at the cross-SDK level.

**Comment by adrianespejo** [comment]
> Hi @adrianespejo thanks for following up. Can you confirm that the size of the file is causing the error and not some special formatting in your messages.txt file? Several users have reported "invalid XML" errors before but they generally seem due to something related to formatting/encoding such as special characters (for example see: [boto/boto3#581](https://github.com/boto/boto3/issues/581)).
> 
> Also if Java has a special client for handling this scenario then this issue would likely be a feature request for consistent functionality, which would likely have to occur at the cross-SDK level.

Hi @tim-finnigan, yes, our messages are simple b64-encoded text so it doesn't have any special characters. I tried with many different messages and the only thing the failed ones shared was that they were greater than ~2MB.

**Comment by tim-finnigan** [comment]
Hi @adrianespejo thanks for following up. After attempting this again I could reproduce the invalid XML error with a ~3MB file, but after reducing the file to 350KB the error was as expected: 
>`botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Message too long`

The [Publish API](https://docs.aws.amazon.com/sns/latest/api/API_Publish.html#API_Publish_RequestParameters) documentation says "messages must be UTF-8 encoded strings and at most 256 KB in size", so I'd also expect to see the error above for >2MB files.

I'm going to try reaching out to the SNS team for clarification on this behavior. I'll share any updates here.

**Comment by adrianespejo** [comment]
I also reached out to AWS support which redirected me here. Sorry I forgot to upload this earlier, but this is the reason they said this was happening, maybe this helps:

> We have received an update form the SNS Service Team. 
> They have mentioned that as the publish call doesn't return a request id for requests greater than a certain size,in this case greater than 2MB, requests that are too large and likely don't reach the SNS service at all which is why you are seeing a different exception.

**Comment by tim-finnigan** [comment]
Thanks @adrianespejo for letting me know. It sounds like the SNS team would have to add an exception to handle this kind of scenario. But I was informed that the team is planning to release an extended client similar to Java for Python and JavaScript. I recommend checking in with AWS Support for updates going forward.
