### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'last_response'

### ISSUE THREAD

**Issue by hb2638** [boto/botocore#2820]
### Describe the bug

Am getting the below in my STDOUT and have no idea where it's originating from

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/usr/local/lib/python3.9/site-packages/botocore/exceptions.py", line 28, in _exception_from_packed_args
    return exception_cls(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'last_response'
```

I then ran it under a debugger and see the following in _exception_from_packed_args

```
def _exception_from_packed_args(exception_cls, args=None, kwargs=None):
    # This is helpful for reducing Exceptions that only accept kwargs as
    # only positional arguments can be provided for __reduce__
    # Ideally, this would also be a class method on the BotoCoreError
    # but instance methods cannot be pickled.
    if args is None:
        args = ()
    if kwargs is None:
        kwargs = {}
    return exception_cls(*args, **kwargs)
```

args=None
kwargs={'name': 'lambda::FunctionStateIsActive', 'reason': 'Waiter encountered a terminal failure state: For expression "Configuration.State" we matched expected path: "Inactive"'}
exception_cls=<class 'botocore.exceptions.WaiterError'>

but the WaiterError wants a last_response argument

```
class WaiterError(BotoCoreError):
    """Waiter failed to reach desired state."""

    fmt = 'Waiter {name} failed: {reason}'

    def __init__(self, name, reason, last_response):
        super().__init__(name=name, reason=reason)
        self.last_response = last_response
```

### Expected Behavior

should be able to create the WaitError

### Current Behavior

It fails to create the WaitError

### Reproduction Steps

I'm really sorry about this but I don't know how to replicate it because it occurs asynchronously on a thread that's not created by me

### SDK version used

boto3 1.24.66 botocore 1.27.96

### Environment details (OS name and version, etc.)

Happens in Linux and Windows

**Comment by hb2638** [comment]
I upgraded to the latest boto3 and it's still failing.

boto3==1.24.66      
(It pulled in botocore-1.29.15)

Below is my waiter config
```
 "lambda::FunctionStateIsActive": {
    "delay": 1,
    "maxAttempts": 600,
    "operation": "GetFunction",
    "description": "Waits for the function state to be active.",
    "acceptors": [
      {
        "state": "success",
        "matcher": "error",
        "expected": "ResourceNotFoundException"
      },
      {
        "state": "success",
        "matcher": "path",
        "argument": "Configuration.State",
        "expected": "Active"
      },
      {
        "state": "failure",
        "matcher": "path",
        "argument": "Configuration.State",
        "expected": "Failed"
      },
      {
        "state": "failure",
        "matcher": "path",
        "argument": "Configuration.State",
        "expected": "Inactive"
      },
      {
        "state": "retry",
        "matcher": "path",
        "argument": "Configuration.State",
        "expected": "InProgress"
      }
    ]
  },
```

**Comment by tim-finnigan** [comment]
Hi @hb2638 thanks for reaching out. Here are the documented waiters for Lambda: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#waiters

The corresponding waiter models can be found here: https://github.com/boto/botocore/blob/develop/botocore/data/lambda/2015-03-31/waiters-2.json.

It looks like you may want to use the [FunctionActive](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Waiter.FunctionActive) or [FunctionActiveV2](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Waiter.FunctionActiveV2) waiter. Can you confirm?

**Comment by hb2638** [comment]
Hi @tim-finnigan I'm actually a big users of custom waiter logic. Is that not supported?

E.x.:  https://www.2ndwatch.com/blog/use-waiters-boto3-write/

**Comment by tim-finnigan** [comment]
Hi @hb2638 you could write your own waiters but we don't document support for custom waiters in the [boto3 Waiters documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html#waiters). We recommend using the existing waiters that are documented by service. But there are open feature requests related to customizing waiter functionality such as [here](https://github.com/boto/boto3/issues/712) in the boto3 repository and [here](https://github.com/aws/aws-cli/issues/1295) in the AWS CLI repository (which also uses botocore).
