### ISSUE TITLE
STS - SSL handshake take exactly one minutre before resolving. 

### ISSUE THREAD

**Issue by OmarBish** [boto/botocore#2821]
### Describe the bug

the attached photo [1]  shows a full profile of a sample `sts.AssumeRoleWithWebIdentity` request. 
the `do_handshake()` method is taking exactly one minute before succeeding after the first retry. 

this behavior happens intermittently and without a clear pattern in production env only (0.6 % of our total requests). 

----
[1]: request Profile
<img width="1453" alt="Screen Shot 2022-11-24 at 3 46 24 PM" src="https://user-images.githubusercontent.com/24843195/203801295-5a7446ae-d893-440f-b876-b3e752986d0d.png">

[2]: sts.AssumeRoleWithWebIdentity time 
<img width="394" alt="Screen Shot 2022-11-24 at 4 03 58 PM" src="https://user-images.githubusercontent.com/24843195/203806541-411f72de-a98c-4cb4-b9a5-c16062f88982.png">

### Expected Behavior

finish the sts request in an acceptable timeframe. 

### Current Behavior

the `do_handshake()` method is taking exactly one minute before succeeding after the first retry in `sts.AssumeRoleWithWebIdentity`.  

even after reducing the connect_timeout value to a lower value, it still finishes in 1 min. 

### Reproduction Steps

I wasn't able to reproduce it locally since it happens infrequently and on a system with a lot of traffic. 

   

### Possible Solution

Timeout and retry if the SSL handshake takes longer than X seconds

### SDK version used

botocore==1.27.96

### Environment details (OS name and version, etc.)

python: Python 3.7.10,OS: AmazonLinux2,boto3==1.24.91

**Comment by tim-finnigan** [comment]
Hi @OmarBish thanks for reaching out. Can you share your debug logs (with any sensitive info redacted) by adding `botocore.set_stream_logger('')` to your script? That may help give more insight into what's going on. Also if you could share any more details about your AMI, botocore configuration, or steps to reproduce this that might help as well. 

If this only occurs rarely as you're saying then it may just be a network issue which we wouldn't be able to reproduce or resolve.
