### ISSUE TITLE
Import fails with `-Werror` python option

### ISSUE THREAD

**Issue by headtr1ck** [boto/botocore#2822]
### Describe the bug

When importing `botocore.session` with the python option `-Werror` the import fails.

### Expected Behavior

Import works

### Current Behavior

The import raises:
> E   DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680

### Reproduction Steps

`python -Werror -c "import botocore.session"`

### Possible Solution

In line: https://github.com/boto/botocore/blob/dfda41c08e3ed5354dce9f958b6db06e6cce99ed/botocore/httpsession.py#L35
add `DeprecationWarning` to the excepted Errors.

### Additional Information/Context

See https://github.com/pydata/xarray/issues/7322 which run into this problem.

### SDK version used

1.27.59

### Environment details (OS name and version, etc.)

Win10/linux

**Comment by headtr1ck** [comment]
Thanks for pointing out that issue. Unfortunately in my case the solution of this PR does not work since no warning is issued when using `-Werror` but an error is raised.

So adding the DeprecationWarning to the expect block is the only thing that would help.

**Comment by tim-finnigan** [comment]
Do you see that error on the latest version of boto3/botocore?
