### ISSUE TITLE
SNS client.publish not working on v.1.26.24

### ISSUE THREAD

**Issue by chrisholmes1128** [boto/botocore#2829]
### Describe the bug

When attempting to run sns_client.publish(PhoneNumber="+***********", Message="Some Message") the error below is returned:

"botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the Publish operation: The request has a 'X-Amzn-Trace-Id' HTTP header which is reserved for AWS X-Ray trace header and has an invalid value 'amplify-mock-x-amzn-trace-id'"

I updated to v.1.26.25 and the error was no longer there, however the text message was not sending to the phone number.

I was able to get the text message to send and be received by changing my boto3 version back to v.1.20.52

### Expected Behavior

The message would successfully send and be received on my phone number.

### Current Behavior

Error on v.1.26.24:

"botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the Publish operation: The request has a 'X-Amzn-Trace-Id' HTTP header which is reserved for AWS X-Ray trace header and has an invalid value 'amplify-mock-x-amzn-trace-id'"

Error no longer shows when updating to v.1.26.25 however message is never received.

### Reproduction Steps

1. Run the following code:

sns_client = boto3.client('sns', region_name=f'{AWS_REGION}')
message="SNS test message"
sns_client.publish(
            PhoneNumber='+***********',  # E.164 format
            Message=message, 
            MessageAttributes={
                'AWS.MM.SMS.OriginationNumber': {
                    "DataType": 'String',
                    "StringValue": 'ORIGINATION_NUMBER'
                },
            },
        )

### Possible Solution

Change back to boto3 v.1.20.52

### SDK version used

aws-cli/1.27.18 Python/3.10.7 botocore/1.27.96

### Environment details (OS name and version, etc.)

MacOS 12.6 ARM

**Comment by tim-finnigan** [comment]
Hi @chrisholmes1128 thanks for reaching out. Have you tried using the latest versions of the boto3 or AWS CLI? The latest boto3 version is 1.26.25 per the [CHANGELOG](https://github.com/boto/boto3/blob/develop/CHANGELOG.rst) and the latest AWS CLI versions are [1.27.25](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst) for v1 and [2.9.5](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst) for v2.

It looks like that header error was also reported [here in the re:Post forums](https://repost.aws/questions/QUQmUkg7V-S-GikuUSWZoovQ/getting-error-when-using-local-amplify-mock-api-the-request-has-a-x-amzn-trace-id-http-header-which-is-reserved-for-aws-x-ray-trace-header), where someone responded:
>Looks like the issue stems from Amplify setting the 'X-Amzn-Trace-Id' to 'amplify-mock-x-amzn-trace-id', which may be an improper format when you send to SQS. Could you try removing the 'X-Amzn-Trace-Id' in the request for these tests if you aren't interested in tracing during testing?

If you're still seeing an issue could you share your debug logs (with any sensitive info redacted)? To do this using the AWS CLI you would just add `--debug` to your command. And for boto3 you'd need to add `boto3.set_stream_logger('')` to your script.
