### ISSUE TITLE
CloudWatch Synthetics Without Waiters

### ISSUE THREAD

**Issue by niCSan** [boto/botocore#2832]
### Describe the issue

Based on the documentation CloudWatch Synthetics [should have waiters](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/synthetics.html#Synthetics.Client.get_waiter), but it doesn't have any when using the `waiter_names` method:

```python
synthetics = boto3.client('synthetics')
print(synthetics.waiter_names) # Output = []
```

I don't know if it's expected or if the documentation is wrong, however in the meantime if someone face this issue I created a custom waiter for `GetCanaryRuns` API, hopefully is useful for anyone:

```python
synthetics = boto3.client('synthetics')
waiter_name = 'GetLastCanaryStatus'

{
    'version': 2,
    'waiters': {
        'GetLastCanaryStatus': {
            'delay': 10,
            'operation': 'GetCanaryRuns',
            'maxAttempts': 10,
            'acceptors': [
                {
                    'expected': 'RUNNING',
                    'matcher': 'path',
                    'state': 'retry',
                    'argument': "CanaryRuns[0].Status.State"
                },
                {
                    'expected': 'PASSED',
                    'matcher': 'path',
                    'state': 'success',
                    'argument': "CanaryRuns[0].Status.State"
                },
                {
                    'expected': 'FAILED',
                    'matcher': 'path',
                    'state': 'failure',
                    'argument': 'CanaryRuns[0].Status.State'
                }
            ]
        }
    }
}

waiter_model = WaiterModel(waiter_config)
custom_waiter = create_waiter_with_client(waiter_name, waiter_model, synthetics)
custom_waiter.wait(Name="MyCanary")
```

### Links

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/synthetics.html#Synthetics.Client.get_waiter

**Comment by tim-finnigan** [comment]
Hi @niCSan thanks for reaching out. The `get_waiter` command is available for every service by default, but it won't return any waiters if there aren't any to return. There would be a waiters `.json` file in [this directory](https://github.com/boto/botocore/blob/develop/botocore/data/synthetics/2017-10-11/ ) if waiters existed for this service and a corresponding waiters section in the [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/synthetics.html) (for example see [CloudWatch waiters](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html#waiters)).

Thanks for sharing that custom waiter definition. Are there any other waiters you were hoping to use with the Synthetics service? Waiter model definitions are owned and implemented by service teams and shared across SDKs. We recommend submitting feature requests for new waiters through [AWS Support](https://aws.amazon.com/contact-us/) but we can also redirect those requests internally.

**Comment by niCSan** [comment]
Thanks @tim-finnigan I will create the feature request with the AWS Support.

**Comment by tim-finnigan** [comment]
Thanks for following up - if you have any other questions regarding this please let us know.
