### ISSUE TITLE
Incorrect RAM endpoints for FIPS in us-gov regions

### ISSUE THREAD

**Issue by seanorama** [boto/botocore#2833]
### Describe the bug

The FIPS endpoints for RAM in us-gov regions is invalid in: https://github.com/boto/botocore/blob/master/botocore/data/ram/2018-01-04/endpoint-rule-set-1.json

It points to `ram-fips.us-gov-west-1.amazonaws.com` which does not exist.

According to https://aws.amazon.com/compliance/fips/, the default endpoint of `ram.us-gov-west-1.amazonaws.com` already has FIPS, so `ram-fips` does not exist.

### Expected Behavior

When enabling FIPS with `AWS_USE_FIPS_ENDPOINT=true` or `use_fips_endpoint=True`, the SDK uses the correct endpoint.

### Current Behavior

```
AWS_REGION=us-gov-west-1 AWS_USE_FIPS_ENDPOINT=true aws ram list-resources --resource-owner 111111111111

Could not connect to the endpoint URL: "https://ram-fips.us-gov-west-1.amazonaws.com/listresources"
```

### Reproduction Steps

1. Have an account/profile in a us-gov region.
2. Then execute:
```
AWS_REGION=us-gov-west-1 AWS_USE_FIPS_ENDPOINT=true aws ram list-resources --resource-owner 111111111111
```

### Possible Solution

Options are:

1. Update botocore logic in https://github.com/boto/botocore/blob/master/botocore/data/ram/2018-01-04/endpoint-rule-set-1.json to know that the us-gov regions use `ram.` not `ram-fips.`.
2. **Ideally, this would be fixed upstream at the AWS RAM service**, by them providing the `ram-fips` name in addition to `ram`. That would eliminate complex human managed logic and lookups. If the naming is consistent, then everything can work by convention.
	1. But until then, the SDK must adapt to what is provided.

### SDK version used

1.29.27

### Environment details (OS name and version, etc.)

Seen on MacOS and Linux of various versions

**Comment by jonemo** [comment]
This was fixed in botocore version 1.29.46 which was released on January 9, 2022. Apologies for not updating this issue earlier. There is no corresponding PR because the fix is in [the endpoint ruleset data file](https://github.com/boto/botocore/blob/develop/botocore/data/ram/2018-01-04/endpoint-rule-set-1.json) which botocore receives from an upstream source and that is shared with other AWS SDKs.
