### ISSUE TITLE
Split credentials-providing/config into separate package

### ISSUE THREAD

**Issue by thejcannon** [boto/botocore#2842]
### Describe the feature

Split the config/credential loading into a seperate package.

### Use Case

I have an application-case for loading credentials for s3, but not actually using botocore's S3 support (instead using the creds to presign a HTTP url). The latest `botocore` whl (`1.29.39`) is ~72.5MB extracted, so pulling in all of `botocore` for this is certainly not ideal

### Proposed Solution

Similar to Rusts' [aws-config](https://docs.rs/aws-config/latest/aws_config/) which is scoped to config-specific code (which also has the added benefit of the compiler ignoring unused code :sweat_smile: ), a dedicated package for config/credential loading.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by thejcannon** [comment]
On further inspection it looks like about `70MB` out of that `72.5MB` is just the `data/` directory. :exploding_head: 

I'm sure there's options here. One could be to split each service into an individual package. `botocore-a-la-carte` would contain core code with an extra per service (e.g. `botocore-a-la-carte[s3, cloudfront]`) and to maintain backwards-compatibility `botocore` would simply be `botocore-a-la-carte[all]`.

**Comment by tim-finnigan** [comment]
Hi @thejcannon thanks for reaching out. This appears to overlap with https://github.com/boto/botocore/issues/2365. Some ideas were proposed there for addressing the expanding size of schemas. The team plans to work on this issue but there are no other updates for now. For consolidation purposes I think we should continue using https://github.com/boto/botocore/issues/2365 to track this.

**Comment by thejcannon** [comment]
:wave: Thanks for the speedy response!

I think more honestly I'd call it a duplicate of https://github.com/boto/botocore/issues/1543 since I don't need any services just to access credentials.

**Comment by thejcannon** [comment]
(I'll close it either way, let the bot take the day off)
