### ISSUE TITLE
S3 service definition does not declare timestamp formats

### ISSUE THREAD

**Issue by endgame** [boto/botocore#2846]
### Describe the bug

I maintain Amazonka, an unofficial AWS SDK for Haskell. Its service bindings are generated by parsing botocore service definitions. While investigating https://github.com/brendanhay/amazonka/issues/879, we discovered that S3's `service-2.json` does not declare a `"timestampFormat"` on its timestamp shapes, but seems to require RFC822-format dates on many of its inputs. Example:

https://github.com/boto/botocore/blob/73d72c93034061a99ac687a8dfe7ee0a0ec1bd3f/botocore/data/s3/2006-03-01/service-2.json#L5454

We have added our own overrides in https://github.com/brendanhay/amazonka/pull/881 but I'm reporting it here in case it's useful to feed it back up to the service teams.

### Expected Behavior

We expected to read type information that said to generate RFC822-format timestamps.

### Current Behavior

We read type information that said to generate ISO8601-format timestamps, based on internal heuristics about the service.

### Reproduction Steps

On https://github.com/brendanhay/amazonka/pull/881, open a `nix-shell`, run `scripts/generate s3` and notice in the `git diff` that the date formats have changed.

### Possible Solution

Declare `"timestampFormat": "rfc822"` on any shapes in S3's `service-2.json`, where AWS specifically requires that format.

### SDK version used

Amazonka 2.0 from branch `main`.

### Environment details (OS name and version, etc.)

NixOS GNU/Linux

**Comment by tim-finnigan** [comment]
Thanks @endgame for reporting this — I have passed along the issue and context as you described to the S3 team for further investigation. Since those service models are implemented upstream by service teams like S3, they are the ones who would need to address issues like this. 

I will share any updates with you going forward and feel free to check back in here as well. But because this isn't something the boto3/botocore team can address directly, I'm going to close this issue.

**Comment by mtdowling** [comment]
Shapes bound to headers for the rest-xml protocol have an implicit timestamp format of rfc822. You can probably infer a mapping between these JSON files and what Smithy defines to understand the protocol (Smithy is the IDL AWS maintains publicly that deprecates what you see in botocore). You could also implement protocol tests to ensure the generator is correct.

* https://smithy.io/2.0/aws/protocols/aws-restxml-protocol.html
* https://smithy.io/2.0/spec/http-bindings.html#httpheader-serialization-rules
* https://github.com/smithy-lang/smithy/tree/main/smithy-aws-protocol-tests/model/restXml
