### ISSUE TITLE
Support BatchGetAssetPropertyValueHistory in Paginators for AWS IoT Sitewise

### ISSUE THREAD

**Issue by joysl** [boto/botocore#2850]
### Describe the feature

Support the call to AWS IoT Sitewise API BatchGetAssetPropertyValueHistory in Paginators https://github.com/boto/botocore/blob/develop/botocore/data/iotsitewise/2019-12-02/paginators-1.json

### Use Case

BatchGetAssetPropertyValueHistory returns a lot of data points for a machine data within a time window. The results beyond 4k is a common scenario.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.29.51

### Environment details (OS name and version, etc.)

Linux OS

**Comment by tim-finnigan** [comment]
Hi @joysl thanks for reaching out. Paginator models are owned by service API teams and shared across AWS SDKs, so I created a new issue for this request here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/451. I reached out to the IoT SiteWise team for feedback and will let you know when I hear back. Please refer to that issue for updates going forward.

**Comment by joysl** [comment]
> Hi @joysl thanks for reaching out. Paginator models are owned by service API teams and shared across AWS SDKs, so I created a new issue for this request here in our cross-SDK repository: [aws/aws-sdk#451](https://github.com/aws/aws-sdk/issues/451). I reached out to the IoT SiteWise team for feedback and will let you know when I hear back. Please refer to that issue for updates going forward.

thank you
