### ISSUE TITLE
Avoid ._credentials access with RefreshableCredentials

### ISSUE THREAD

**Issue by rbailey-godaddy** [boto/botocore#2852]
### Describe the feature

It should not be necessary to use unprotected access to the private `_credentials` member of `botocore.session.Session` objects in order to use refreshable credentials.

Provide a mechanism for setting this member properly, either by extending the `.set_credentials()` method or adding a new method.

### Use Case

This unfortunate code pattern for using RefreshableCredentials is splattered across the web:

```
from botocore.credentials import RefreshableCredentials
from botocore.session import get_session

my_creds = RefreshableCredentials(...)
my_session = get_session()
my_session._credentials = my_creds
```

### Proposed Solution

Extend `botocore.session.Session.set_credentials()` to accept a generic credentials object as an alternative to explicit access key information:

```
def set_credentials(self, access_key=None, secret_key=None, token=None, credentials=None):
        """
        ...
        :type credentials: valid Credentials or ReusableCredentials object
        :param credentials: An optional credentials object; if specified, other arguments are ignored

        Either access_key and secret_key, or credentials, must be provided
        """
        self._credentials = credentials or botocore.credentials.Credentials(
            access_key, secret_key, token
        )
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

botocore 1.29.41

### Environment details (OS name and version, etc.)

Linux, python3.9/3.10/3.11

**Comment by rbailey-godaddy** [comment]
I belatedly noticed that #1742 is the same problem, with a slightly different proposed implementation. I'm leaving this issue open because I didn't see that PR tied back to an issue, and perhaps this will provide the background/justification mentioned in the earlier discussion.

**Comment by rbailey-godaddy** [comment]
@tim-finnigan (and other readers): there is nothing which, as a user, fills me with despair like a reference to a 7-year-old issue which devolves into religious war within a few screens.

However, although I have not tested it myself yet, I would like to raise the visibility of this [gist ](https://gist.github.com/jappievw/2c54fd3150fd6e80cc05a7b4cdea60f6) published by @jappievw (from 2018!) which appears satisfy my use case. This is even more obtusely magical than the approach I initially studied, but it appears to be a classier (pun intended) implementation which avoids public access to private members, so I'm happy (provided it works!).

I believe my issue (a thinly veiled plug for a specific implementation approach) doesn't necessarily add much value to readers who generally understand the context of either of these two issues, so I am content to have this closed as a duplicate if it reduces cruft.

Thanks again for the pointer, without which I wouldn't have located a solution.

**Comment by tim-finnigan** [comment]
Thanks @rbailey-godaddy for following up and providing visibility to that gist. I understand your frustration regarding older issues such as those. We are trying to reduce the backlog and get the capacity to revisit those issues. I will go ahead and close this as a duplicate but will forward your feedback to the PM team.
