### ISSUE TITLE
Invalid STS API version CreatePolicy

### ISSUE THREAD

**Issue by chris93111** [boto/botocore#2869]
### Describe the bug

Hi 

I try to create a iam policy in Minio

But we have this error botocore.exceptions.ClientError: An error occurred (MissingParameter) when calling the CreatePolicy operation: Invalid STS API version 2010-05-08, expecting 2011-06-15

```
iamClient = boto3.client('iam', region_name='xxx', endpoint_url="https://minio", aws_access_key_id="xxxx", aws_secret_access_key="xxxx")

policy = {
   "Version": "2012-10-17",
   "Statement": [
      {
            "Sid": "GetObj",
            "Effect": "Allow",
            "Action": ["s3:GetObject"],
            "Resource": f"arn:aws:s3:::mybucket/*"
      },
      {
            "Sid": "PutDelObj",
            "Effect": "Allow",
            "Action": ["s3:PutObject", "s3:DeleteObject"],
            "Resource": f"arn:aws:s3:::anotherbucket/uploads/*"
      }
   ]
}

response = iamClient.create_policy(
    PolicyName='chris',
    Path='minio',
    PolicyDocument=json.dumps(policy, separators=(',',':')),
    Description='test'
)
```

boto3==1.24.89
botocore==1.27.89

### Expected Behavior

create policy

### Current Behavior

error with STS api version

### Reproduction Steps

```
iamClient = boto3.client('iam', region_name='xxx', endpoint_url="https://minio", aws_access_key_id="xxxx", aws_secret_access_key="xxxx")

policy = {
   "Version": "2012-10-17",
   "Statement": [
      {
            "Sid": "GetObj",
            "Effect": "Allow",
            "Action": ["s3:GetObject"],
            "Resource": f"arn:aws:s3:::mybucket/*"
      },
      {
            "Sid": "PutDelObj",
            "Effect": "Allow",
            "Action": ["s3:PutObject", "s3:DeleteObject"],
            "Resource": f"arn:aws:s3:::anotherbucket/uploads/*"
      }
   ]
}

response = iamClient.create_policy(
    PolicyName='chris',
    Path='minio',
    PolicyDocument=json.dumps(policy, separators=(',',':')),
    Description='test'
)
```

### SDK version used

1.27.89

### Environment details (OS name and version, etc.)

rhel8

**Comment by aBurmeseDev** [comment]
Hi @chris93111 - thanks for reaching out.

From looking at the error `Invalid STS API version 2010-05-08, expecting 2011-06-15`, it seems more related to Minio rather than AWS SDK and I'm not sure how much help we could provide regarding Minio as we don't support third-party services. 

However, I came across [this issue](https://github.com/minio/minio/issues/16151) from Minio that might help you.

Hope it helps,
John
