### ISSUE TITLE
Paginators missing for Timestream

### ISSUE THREAD

**Issue by mdavis-xyz** [boto/botocore#2875]
### Describe the bug

The Timestream API uses pagination in list_tables and list_databases. However [Timestream's pagination definition file](https://github.com/boto/botocore/blob/develop/botocore/data/timestream-write/2018-11-01/paginators-1.json) is empty. It's just:

```
{
  "pagination": {}
}
```

There are [paginators for the Timestream query service](https://github.com/boto/botocore/blob/develop/botocore/data/timestream-query/2018-11-01/paginators-1.json), but not for the Timestream write service.

### Expected Behavior

I expect to see paginators for [list_databases](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#TimestreamWrite.Client.list_databases) and [list_tables](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#TimestreamWrite.Client.list_tables). Those are client calls which involve pagination.

Failing that, if there are no paginators, then I expect there to be not section on paginators in the documentation. (Or the documentation should state that there are no paginators.)

### Current Behavior

The timestream write page for boto3 has [a section on paginators](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#paginators).

> [Paginators](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#id17)
> The available paginators are:

That's it. That's the whole section. There are no paginators listed.

### Reproduction Steps

Look at [the documentation for boto3's timestream write paginators](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html#paginators). Notice how it's empty. (Sorry for repeating myself and sounding harsh. This form won't let me submit the ticket unless I squeeze the issue into multiple mandatory fields.)

### Possible Solution

Please ask the upstream service team to add paginator definitions for list_table and list_database.

### SDK version used

develop branch

### Environment details (OS name and version, etc.)

N/A

**Comment by jonathan343** [comment]
Hey, @mdavis-xyz, thanks for bringing this up!
Regarding the empty documentation section for Paginators, this will be fixed in #2866. We'll only be displaying Paginator sections if it's relevant for a service.

**Comment by aBurmeseDev** [comment]
Hi @mdavis-xyz - thanks for reaching out. I was able to confirm that there are currently no modeled paginators for `timestream-write` and you can run [can_paginate](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write/client/can_paginate.html) method to confirm that as well. 

We have now removed the empty paginator section from the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/timestream-write.html) by the PR mentioned in the comment above. Again thanks for bringing it to our attention.

I'm going to close this now and if you have any other questions, feel free to reach out again!
Best,
John

**Comment by mdavis-xyz** [comment]
Are you able to also pass a feature request (bug report?) on to the Timestream service team, to ask that they add these two paginators to their service definition file?
