### ISSUE TITLE
test_token_chosen_from_provider fails when system timezone has a positive UTC offset

### ISSUE THREAD

**Issue by bridgetb** [boto/botocore#2884]
### Describe the bug

`tests/functional/test_credentials.py::SSOSessionTest::test_token_chosen_from_provider` fails with `RuntimeError: Credentials were refreshed, but the refreshed credentials are still expired.` when running on a machine that has the system timezone set to a timezone ahead of UTC e.g. NZDT.

### Expected Behavior

`test_token_chosen_from_provider` should pass. Token should be generated with an expiry of one hour later than the current time. E.g. for NZDT if the current time is 2023-03-10 09:00 the expiry time should be set to a local time of 2023-03-10 10:00 or UTC 2023-03-09 21:00.

### Current Behavior

`test_token_chosen_from_provider` fails in non-UTC timezones. Token is generated with an expiry of the current time + one hour - 2 times the difference between local timezone and UTC. E.g. if the current time is NZDT 2023-03-10 09:00 the expiry time is set to NZDT 2023-03-09 21:00 or UTC 2023-03-09 08:00.

### Reproduction Steps

1. Set system timezone to NZDT (or anything with a positive UTC offset).
2. Run the test `tests/functional/test_credentials.py::SSOSessionTest::test_token_chosen_from_provider`.

### Possible Solution

For more details on a possible fix, please see description in https://github.com/boto/botocore/pull/2882

### SDK version used

1.29.88

### Environment details (OS name and version, etc.)

Fedora 37, Python 3.11.2, Pytest 7.1.3

**Comment by nateprewitt** [comment]
Resolved in #2882
