### ISSUE TITLE
aws route53 ARC cluster tagging exception

### ISSUE THREAD

**Issue by jerryhxu** [boto/botocore#2886]
### Describe the bug

I am trying to tag the aws route53 ARC cluster resource and got the exception when the tag value has space between characters. If space is removed, the tagging action is successful. 

### Expected Behavior

The tagging action should be successful even when tag string has space between characters.

### Current Behavior

  
  ```
File "/Users/jerryxu/Library/Caches/pypoetry/virtualenvs/c7n-jLif1GDB-py3.10/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jerryxu/Library/Caches/pypoetry/virtualenvs/c7n-jLif1GDB-py3.10/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (BadRequestException) when calling the TagResource operation: Invalid request body
```

### Reproduction Steps

Here is the sample code. Notice when the tag is applied, please make sure that there is space between characters in the string. 

```
import boto3

client = boto3.client('route53-recovery-control-config', region_name = 'us-west-2')

response = client.tag_resource(
    ResourceArn='arn:aws:route53-recovery-control::644160558196:cluster/26703a3e-b187-4f9b-8ae6-f23fb2808623',
    Tags={
        'str1': 'hello abcd xyz'
    }
)
```

### SDK version used

boto3 1.26.89 with python 3.10.10

### Environment details (OS name and version, etc.)

mac os 11.6.1

**Comment by tim-finnigan** [comment]
Thanks @jerryhxu for reporting this issue, I could reproduce the error you referenced. The boto3 [tag_resource](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53-recovery-control-config/client/tag_resource.html) command is using the underlying [TagResource](https://docs.aws.amazon.com/recovery-cluster/latest/api/tags-resourcearn.html#tags-resourcearnpost) API. Service teams such as Route53 own the design and implementation of their APIs as those are used across SDKs, so I created a cross-SDK issue here for tracking this going forward: https://github.com/aws/aws-sdk/issues/496. I'll also reach out to that service team and share any updates in that issue. Thanks!
