### ISSUE TITLE
Fail to execute refresh_cache to an storage gateway file share

### ISSUE THREAD

**Issue by rodrigoa-most** [boto/botocore#2893]
### Describe the bug

Fail to execute refresh_cache to an storage gateway file share. 

I'm getting this error to any file share arn.

### Expected Behavior

It should return a response containing:

```
{
    'FileShareARN': 'string',
    'NotificationId': 'string'
}
```

### Current Behavior

```
Traceback (most recent call last):
  File "./refreshcache.py", line 7, in <module>
    response = client.refresh_cache(
  File "/home/XXXX/.local/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/XXXX/.local/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidGatewayRequestException: An error occurred (InvalidGatewayRequestException) when calling the RefreshCache operation: Cannot access XXXXXXXXXXX
```

### Reproduction Steps

```py
import boto3

client = boto3.client('storagegateway')

response = client.refresh_cache(
    FileShareARN='XXXXXX',
    FolderList=[
        '/',
    ],
    Recursive=True
)
```

### Additional Information/Context

I've got the same error running `aws storagegateway refresh-cache --file-share-arn XXXXXX`.

The debug log shows:

```
2023-03-22 15:20:09,226 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"__type":"InvalidGatewayRequestException","error":{"errorCode":"InvalidParameters"},"message":"Cannot access XXXXX"}'
```

The automatic refresh cache is disabled and there was no previous calling to this operation.

### SDK version used

1.26.96

### Environment details (OS name and version, etc.)

Ubuntu 20.04| Python 3.8.10

**Comment by tim-finnigan** [comment]
Hi @rodrigoa-most thanks for reaching out. That error you're receiving is coming from the service, so this issue has to do with the [RefreshCache API](https://docs.aws.amazon.com/storagegateway/latest/APIReference/API_RefreshCache.html) rather than boto3 directly. As noted in that documentation: 
>If you invoke the RefreshCache API when two requests are already being processed, any new request will cause an `InvalidGatewayRequestException` error because too many requests were sent to the server.

Also as mentioned there, you should wait at least 60 seconds between consecutive RefreshCache API requests. Can you confirm that you don't receive this error after waiting at least 60 seconds between consecutive requests?

**Comment by rodrigoa-most** [comment]
Tim,

There's no issue. 

I got the region variable mixed up. I used AWS_REGION instead of AWS_DEFAULT_REGION. :facepalm: 

Thank you and sorry for the trouble.
