### ISSUE TITLE
Unable to use Stubber for S3 generate_resigned_url

### ISSUE THREAD

**Issue by jenstroeger** [boto/botocore#2899]
### Describe the bug

This works:
```python
>>> import boto3
>>> client = boto3.client("s3")
>>> client.meta.method_to_api_mapping['put_object']
'PutObject'
>>> client.meta.service_model.operation_model('PutObject')
OperationModel(name=PutObject)
```
whereas this does not:
```python
>>> client.meta.method_to_api_mapping['generate_presigned_url']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'generate_presigned_url'
>>> client.meta.method_to_api_mapping.get('generate_presigned_url')
>>> # Returns None.
```
As a consequence, using
```python
with Stubber(client) as stubber:
    stubber.add_response("generate_presigned_url", response, expected_params)
```
fails, because this call in `_add_response()`

https://github.com/boto/botocore/blob/2baa022100f8fdb4d65fe3b902ac40b415bbeebe/botocore/stub.py#L249-L250

makes `operation_name = None` and in turn

https://github.com/boto/botocore/blob/2baa022100f8fdb4d65fe3b902ac40b415bbeebe/botocore/stub.py#L406-L407

raises an error:
```python
  File "/.../.venv/lib/python3.10/site-packages/botocore/stub.py", line 410, in _validate_operation_response
    operation_model = service_model.operation_model(operation_name)
  File "/.../.venv/lib/python3.10/site-packages/botocore/utils.py", line 1421, in _cache_guard
    result = func(self, *args, **kwargs)
  File "/.../.venv/lib/python3.10/site-packages/botocore/model.py", line 364, in operation_model
    raise OperationNotFoundError(operation_name)
botocore.model.OperationNotFoundError: None
```

### Expected Behavior

Stubber adding the expected response to its queue.

### Current Behavior

See above.

### Reproduction Steps

See above.

### Possible Solution

I _suspect_ that the list of service methods in [data/](https://github.com/boto/botocore/tree/develop/botocore/data) may not contain all actual service methods.

### SDK version used

1.26.104

### Environment details (OS name and version, etc.)

macOS Ventura 13.2.1 (22D68), Python 3.10.10

**Comment by RyanFitzSimmonsAK** [comment]
Hi @jenstroeger, thanks for reaching out.  The reason this is happening is because generating a presigned url is not actually an API call, but instead done locally.  If you enable debug logs and generate a presigned url, you can see there isn't actually a response since a request isn't being made.  You can also check the [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations_Amazon_Simple_Storage_Service.html) to see that generate_presigned_url is not listed.  Since this is the case, you shouldn't need to use a stubber for this method.  Hope that helps, and please let me know if you have any follow-up questions.

**Comment by jenstroeger** [comment]
@RyanFitzSimmonsAK oh so for testing I can just call that Boto3 function then, good to know 👍🏼 

Let me try that out first, and then close this issue.

**Comment by RyanFitzSimmonsAK** [comment]
Looking at the [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html), I believe that is correct, since a request isn't being made.

**Comment by RyanFitzSimmonsAK** [comment]
Hi @jenstroeger; is this issue still a problem for you?

**Comment by jenstroeger** [comment]
@RyanFitzSimmonsAK I think it’s ok. If we have problems I’ll reopen, but for now I think we’re good. Thank you for your support 👍🏼
