### ISSUE TITLE
How do I get the HTTP URL using Botocore?

### ISSUE THREAD

**Issue by faridelnasire** [boto/botocore#291]
I've always used the Boto library to use Amazon's S3 service, but because of a Python 3.4 project I had to use Botocore instead. I've figured out how to do most things, but I can't seem to find how to do one (pretty essential) thing; generating urls. In Boto I would simply set a Key and fire the generate_url method. How do I do this in Botocore? I know how to download and save files, but I would much rather just get a link because of server performance and what-not.

**Comment by vlcinsky** [comment]
@faridelnasire I had similar question and got promising answer at boto/boto3#110.

It is partially (only relative expiration time) implemented in branch clients-only and is on the [botocore roadmap](https://github.com/boto/botocore) as just the next step to complete.

**Comment by kyleknap** [comment]
The feature is currently available in botocore. Here is the related documentation:
http://botocore.readthedocs.org/en/latest/reference/services/s3.html#S3.Client.generate_presigned_url

Here is an example of how you would use the method as well: https://github.com/boto/botocore/blob/develop/tests/integration/test_s3.py#L441

Closing issue. Please update the issue if you have any more questions or comments.
