### ISSUE TITLE
Unable to import boto3 because of botocore dependancies on urllib3s removed DEFAULT_CIPHERS

### ISSUE THREAD

**Issue by phil-bell** [boto/botocore#2921]
### Describe the bug

We're unable to import boto3 because botocore imports DEFAULT_CIPHERS in `botocore/httpsession.py` which has been removed from urllib3 a bit back https://github.com/urllib3/urllib3/pull/2705

### Expected Behavior

Importing `boto3` doesnt result in an error.

### Current Behavior

Importing `boto3` results in the following error:

```
import boto3
  File "/usr/local/lib/python3.11/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/lib/python3.11/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/local/lib/python3.11/site-packages/botocore/docs/client.py", line 17, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/lib/python3.11/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/lib/python3.11/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/lib/python3.11/site-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.11/site-packages/botocore/httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py)
```

### Reproduction Steps

Do the following:
```python
import boto3
```

### Possible Solution

`urllib3` now just checks if its been given some ciphers and if not doesn't add them to the context:
https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/ssl_.py#L289

Could possibly do the same or add you're own defaults.

### SDK version used

1.26.121

### Environment details (OS name and version, etc.)

Docker python:3.11

**Comment by nateprewitt** [comment]
Hi @phil-bell,

Thanks for opening this. We're aware of the changes in urllib3. Botocore and Requests are the primary consumers for urllib3, and we haven't moved the support pins to include urllib3 2.0 yet ([ref](https://github.com/boto/botocore/blob/develop/setup.py#L28)). We'll be providing some time for the new major version to be tested before opting users into it by default.

I've posted #2922 to help unblock preliminary testing, but I would advise sticking to the current pins until they're moved for stability.

**Comment by mariokudolani** [comment]
Hello,
I had same issue but now I'm getting another one which might be relevant to urlib3 2.0.
`
{
  "errorMessage": "set_ciphers() argument must be str, not None",
  "errorType": "TypeError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
    "  File \"/var/task/app.py\", line 21, in <module>\n    s3 = boto3.client(\"s3\")\n",
    "  File \"/opt/python/boto3/__init__.py\", line 92, in client\n    return _get_default_session().client(*args, **kwargs)\n",
    "  File \"/opt/python/boto3/session.py\", line 299, in client\n    return self._session.create_client(\n",
    "  File \"/opt/python/botocore/session.py\", line 951, in create_client\n    credentials = self.get_credentials()\n",
    "  File \"/opt/python/botocore/session.py\", line 507, in get_credentials\n    self._credentials = self._components.get_component(\n",
    "  File \"/opt/python/botocore/session.py\", line 1108, in get_component\n    self._components[name] = factory()\n",
    "  File \"/opt/python/botocore/session.py\", line 186, in _create_credential_resolver\n    return botocore.credentials.create_credential_resolver(\n",
    "  File \"/opt/python/botocore/credentials.py\", line 92, in create_credential_resolver\n    container_provider = ContainerProvider()\n",
    "  File \"/opt/python/botocore/credentials.py\", line 1894, in __init__\n    fetcher = ContainerMetadataFetcher()\n",
    "  File \"/opt/python/botocore/utils.py\", line 2846, in __init__\n    session = botocore.httpsession.URLLib3Session(\n",
    "  File \"/opt/python/botocore/httpsession.py\", line 320, in __init__\n    self._manager = PoolManager(**self._get_pool_manager_kwargs())\n",
    "  File \"/opt/python/botocore/httpsession.py\", line 338, in _get_pool_manager_kwargs\n    'ssl_context': self._get_ssl_context(),\n",
    "  File \"/opt/python/botocore/httpsession.py\", line 347, in _get_ssl_context\n    return create_urllib3_context()\n",
    "  File \"/opt/python/botocore/httpsession.py\", line 116, in create_urllib3_context\n    context.set_ciphers(ciphers or DEFAULT_CIPHERS)\n"
  ]
}
`
