### ISSUE TITLE
Botocore issue with docs, when importing boto3

### ISSUE THREAD

**Issue by Alonreznik** [boto/botocore#2957]
### Describe the bug

When importing boto3 Session, we're facing lately that the latest botocore next message:

```
File "/usr/local/lib/python3.8/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 25, in <module>
    from .resources.factory import ResourceFactory
  File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 17, in <module>
    from ..docs import docstring
  File "/usr/local/lib/python3.8/site-packages/boto3/docs/__init__.py", line 15, in <module>
    from botocore.docs import DEPRECATED_SERVICE_NAMES
ImportError: cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs' (/usr/local/lib/python3.8/site-packages/botocore/docs/__init__.py)
``` 

It seems there's no `botocore` specific version in the requirements, which makes any `boto3` (even some old versions) to update automatically to a non-compatible `botocore` latest version.

### Expected Behavior

```sh
pip install boto3==1.26.120
```
for example should update the botocore version compatible with this specific version.

### Current Behavior

botocore is updated regardless to the boto3 version specified.

### Reproduction Steps

run
```sh
pip install --upgrade boto3==1.26.120
```

and see the botocore is updated to `botocore==1.29.139` which is not compatible with the version.

### SDK version used

boto3==1.26.120

### Environment details (OS name and version, etc.)

amazon linux 2, docker

**Comment by tim-finnigan** [comment]
Hi @Alonreznik thanks for reaching out. If you reinstall boto3 then it should install compatible versions of boto3 and botocore.

There is a related issue here involving third-party software pinning to incompatible versions: https://github.com/boto/boto3/issues/3648. (The `DEPRECATED_SERVICE_NAMES` change was introduced in this PR: https://github.com/boto/boto3/pull/3640.)

Can you confirm the botocore version in your environment by adding this to your script?
```python3
import botocore
print(botocore.__version__)
```
