### ISSUE TITLE
boto3 stubber should allow SQS resource to be mocked

### ISSUE THREAD

**Issue by neilferreira** [boto/botocore#2978]
### Describe the feature

The boto3 Stubber can be used to add responses to boto3 client calls, which can then be used to mock API calls within pytest.

Using the boto3 Stubber to mock `boto3.resource` instead of `boto3.client` is not a well-documented or perhaps supported feature. 

This code:
```
sqs = boto3.resource("sqs")
sqs_stubber = Stubber(sqs.meta.client)
sqs_stubber.add_response(
    method="get_queue_by_name",
    service_response={},
    expected_params={},
)
sqs_stubber.activate()
```

Raises:
```
self = <botocore.stub.Stubber object at 0x12ffce4f0>, method = 'get_queue_by_name', service_response = {}, expected_params = {}

    def _add_response(self, method, service_response, expected_params):
        if not hasattr(self.client, method):
>           raise ValueError(
                "Client %s does not have method: %s"
                % (self.client.meta.service_model.service_name, method)
            )
E           ValueError: Client sqs does not have method: get_queue_by_name
```

If there is any way to mock `boto3.resource("sqs").get_queue_by_name()` that would be great.

### Use Case

I would like to use pytest to verify the inputs and outputs of some boto3 SDK calls within my codebase.

### Proposed Solution

Some people have mentioned a workaround on https://github.com/boto/botocore/issues/1125 - but a proper and documented solution would be great.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.29.163

### Environment details (OS name and version, etc.)

Any

**Comment by tim-finnigan** [comment]
Hi @neilferreira thanks for the feature request. As mentioned in https://github.com/boto/botocore/issues/1125 the Stubber will only work for client methods (but you can access the client methods from a resource as [documented here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html) and demonstrated in your code snippet.)

There is no `get_queue_by_name` client method, could you use the [get_queue_url](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/get_queue_url.html) method instead?

(I should also note that there is a freeze on feature requests involving the resources interface as [noted here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html).)

**Comment by neilferreira** [comment]
@tim-finnigan Thankyou for the explanation.  Refactoring my code to use `get_queue_url` is a perfectly fine solution given the freeze on the resource interface.
