### ISSUE TITLE
Support for Runtine: python3.11

### ISSUE THREAD

**Issue by Rogalek** [boto/botocore#2980]
### Describe the feature

Will you add support for Runtine: python3.11?

https://github.com/boto/botocore/blob/99d6a50ea6c2bf6e78e9dbe8dcb1e23e391f3fc1/botocore/data/lambda/2015-03-31/service-2.json#L5199C1-L5234C1

### Use Case

I would like to deploy my new lambdas using python3.11

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.30.1

### Environment details (OS name and version, etc.)

ubuntu 22.04

**Comment by tim-finnigan** [comment]
Thanks for the feature request — this would need to be supported by Lambda first. They are tracking this feature request here: https://github.com/aws/aws-lambda-base-images/issues/62. Once they support Python 3.11 they will update the service API model file you linked to add that as a runtime enum value. Please refer to that issue for updates going forward.
