### ISSUE TITLE
Bump urllib3 requirement to v2

### ISSUE THREAD

**Issue by sodul** [boto/botocore#2982]
### Describe the feature

botocore requires urllib3<1.27 preventing the installation of urllib3 v2. 

### Use Case

We want to work with boto and urllib3 v2.

### Proposed Solution

Unless there is a runtime dependency on the deprecated methods in urllib3 v2 that requirement should either be updated or removed.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

boto3==1.28.3, botocore==1.31.3

### Environment details (OS name and version, etc.)

macOS 13.4.1 (c)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @sodul, thanks for reaching out.  This request has been made several times in the past, and the team has made a reply in [another issue](https://github.com/boto/botocore/issues/2926#issuecomment-1528863806).  

> 
> Hi @epicserve, thanks for reaching out. The pin is currently intentional while we wait for the major version bump to stabilize. We intend to move the pin shortly after Requests does to ensure we're not negatively impacting users.
> 
> We'll keep this issue updated and feel free to follow along in https://github.com/psf/requests/issues/6432 as well if you like.

Any updates about this pin will be in the tracking issue that I linked.  Hope that helps!
