### ISSUE TITLE
IAM service policyDocumentType shape does not represent actual response

### ISSUE THREAD

**Issue by vemel** [boto/botocore#2992]
### Describe the bug

`policyDocumentType` shape definition is incorrent. According to it, it should be a string. Actual response from botocore is a dict: `{"Version": "str", "Statement": [{...}, ]}`.

It affects auto-generated `boto3` docs as well: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam/client/get_policy_version.html#

### Expected Behavior

- `boto3` documentation should describe `IAM.Client.get_policy_version` response correctly

### Current Behavior

Current shape definition:

```json
    "policyDocumentType":{
      "type":"string",
      "max":131072,
      "min":1,
      "pattern":"[\\u0009\\u000A\\u000D\\u0020-\\u00FF]+"
    }
```

### Reproduction Steps

https://github.com/youtype/mypy_boto3_builder/issues/212

### Possible Solution

The shape definition should be something like:

```json
    "policyDocumentType":{
      "type":"structure",
      "required":["Version", "Statement"],
      "members":{
        "Version":{
          "shape":"policyDocumentTypeVersion", # string
        },
        "Statement":{
          "shape":"policyDocumentTypeVersion", # list[dict[str, Any]]
        }
      },
    }
```

### SDK version used

1.31.16

### Environment details (OS name and version, etc.)

Ubuntu Linux

**Comment by vemel** [comment]
Just in case, this is how it looks in Python types:

```python
PolicyDocumentStatementTypeDef = TypedDict(
    "PolicyDocumentStatementTypeDef",
    {
        "Effect": str,
        "Resource": Union[str, List[str]],
        "Sid": str,
        "Action": Union[str, List[str]],
    },
)

PolicyDocumentTypeDef = TypedDict(
    "PolicyDocumentTypeDef",
    {
        "Version": str,
        "Statement": List[PolicyDocumentStatementTypeDef],
    },
)
```

**Comment by tim-finnigan** [comment]
Hi @vemel thanks for reaching out. This has come up before in a few other issues:
* https://github.com/boto/boto3/issues/229
* https://github.com/boto/boto3/issues/978

It appears to affect all PolicyDocument types. I think we should continue tracking this in the open issues above.

**Comment by nateprewitt** [comment]
To add some more context, this isn't specific to PolicyDocuments. Botocore will attempt to decode strings members in responses into a Python object with `json.loads` if possible. This is to provide a more native Python representation of structured data to allow for indexing/iteration.

You'll see similar behaviors for timestamps as well which are converted to datetime objects on receipt.
