### ISSUE TITLE
Add public method to retrieve instance id (and other instance metadata)

### ISSUE THREAD

**Issue by hayd** [boto/botocore#2993]
### Describe the feature

You can access the instance-id but it requires using private `IMDSFetcher` methods:

```py
f = IMDSFetcher()
token = f._fetch_metadata_token()
f._get_request("latest/meta-data/instance-id", None, token=token).text
```

there's an unfortunately (?) named `InstanceMetadataFetcher`:

```py
class InstanceMetadataFetcher(IMDSFetcher):
    _URL_PATH = 'latest/meta-data/iam/security-credentials/'
   ...
```
that sounds like it could be used for arbitrary metadata but it's not.

### Use Case

For some ec2/asg methods I need to access my instance id first.

Previously I could make a single request to `http://169.254.169.254/latest/meta-data/instance-id` (with some retries/error handling).... whilst a little annoying to be outside of boto3/botocore it was ok.

Now, with IMDSv2, it's quite a bit noisier/requires significantly more boilerplate error handling to use urllib.request or requests (as you can see from the size of `IMDSFetcher` methods!)

### Proposed Solution

Add a public method to `IMDSFetcher` to fetch specific path e.g.

```py
    def retrieve(self, url_path, retry_func=None):
        token = self._fetch_metadata_token()
        return self._get_request(url_path, retry_func, token=token).text

# use as
IMDSFetcher().retrieve('latest/meta-data/instance-id')
```

alternatively subclass `IMDSFetcher` and define a similar method...

Perhaps it makes sense to call this as `retrieve_metadata("instance_id")` ?

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

boto3

### Environment details (OS name and version, etc.)

amazon linux 2023

**Comment by tim-finnigan** [comment]
Hi @hayd thanks for reaching out. This feature request is currently being tracked here in the Boto3 repository: https://github.com/boto/boto3/issues/313. Please feel free to 👍 that issue or add a comment there to share your use case.

However the team does not currently have any plans to expand the functionality of IMDSFetcher as it is not really intended for use and therefore not documented.
