### ISSUE TITLE
RFE: Pease proviide support for `urllib3` 2.0.x

### ISSUE THREAD

**Issue by kloczek** [boto/botocore#3012]
### Describe the feature

https://github.com/boto/botocore/blob/71a80e4dd9428351bbdcd0c1a06fbcc70bb091b4/setup.cfg#L5-L8

### Use Case

Some modules already supports or even requires `urllib3` 2.0.x and it is hard to build consistent packaged distribution of modules with `urllib3` 1.x.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

N/A

### Environment details (OS name and version, etc.)

Linux x86/64

**Comment by RyanFitzSimmonsAK** [comment]
Hi @kloczek, thanks for reaching out.  This request has been made several times in the past, and the team has offered a workaround in https://github.com/boto/botocore/issues/2926#issuecomment-1673963526 while the pin is still on the range it's at now.

> You can currently install urllib3 2.0.x with boto3/botocore/awscli and it will work as we've unblocked Gentoo and nixpkgs to do. The primary reason that the pin is still in place for general python installations is because urllib3 2.0 has compatibility issues with Amazon Linux 2 and some versions of AWS Lambda. These are detailed in the urllib3 migration guide [here](https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#ssl-module-is-compiled-with-openssl-1-0-2-k-fips).
> 
> Because of the way pip works by always choosing to install the latest version of packages, moving the pin for urllib3 will unexpectedly break everyone not pinning urllib3 or using OpenSSL 1.1.1+. That's something we take very seriously with AWS products and try to ensure never happens. We're still working on a plan to smoothly migrate this customer base, but don't have any immediate timeline.
> 
> For the time being, users are free to install urllib3 2.x after they've installed boto3/botocore/awscli, and should be able to use each package. Something like this would work in automated environments returning a successful response code. We realize it's not ideal, but is the most tractable solution we have currently that maintains stability:

Any updates to changing the `urblib3` pin will be in that thread.  Hope that helps!
