### ISSUE TITLE
botocore InstanceMetadataProvider refreshes creds too frequently 

### ISSUE THREAD

**Issue by shutingwang-db** [boto/botocore#3019]
### Describe the bug

InstanceMetadataProvider refreshes creds from IMDS way too frequently. It doesn't seem to honor the advisory and mandatory refresh timeout.

### Expected Behavior

Creds are refreshed voluntarily 15mins before expiry time and mandatorily 10mins before expiry time. Speaking of that, can we increase the 15mins to 20mins so that we gave 10mins buffer for IMDS downtime?

### Current Behavior

Based on my reading on the botocore/credentials.py, the expected behavior for leveraging instance profile for credentials is that 1. Trigger a non-blocking, voluntary, aka, fail without raise or invalidate existing creds, refresh if there is less than 15mins but more than 10mins left before expiry time 2. Trigger a mandatory refresh if there's less than 10mins before expiry time. However, when I use boto3 to access S3, which should use botocore behind the scene, I find that refresh is triggered much often than necessary, basically not honoring the logic I see in the code. For instance, my creds expires at 2023-09-21 16:47:26 and IMDS would receive request to fetch credentials when I try to access S3 at 2023/09/21 16:08:14 which doesn't seem to be correct.

### Reproduction Steps

client = boto3.client('s3')
response = client.get_object(Bucket=bucket_name, Key=key_name)
result = response['Body'].read().decode("utf-8")

And monitor the IMDS requests. (The reason I know when IMDS receives request is because we intercept the IMDS request and process it in a mock-up service.)

I do create new client for each request. Not sure if that's related.

### SDK version used

1.28.3

### Environment details (OS name and version, etc.)

Ubuntu 20.04.5 LTS

**Comment by shutingwang-db** [comment]
Recent observation:

Creds expire at 2023-09-21T19:22:26Z

But receive IMDS request at 2023/09/21 18:49:25, 2023/09/21 18:49:39 and 2023/09/21 18:50:09.

**Comment by shutingwang-db** [comment]
Probably not an issue since I was running multiple processes inside of the same container which seems to fetch from IMDS separately. But if possible, it would be great if anyone can confirm the Expected Behavior I put above is how credential cache works today. Thank you so much!

**Comment by indrora** [comment]
I'm not sure the exact rationale behind this choice. I suspect being proaxvmdß

I can also see how this would be a problem from a logging and monitoring standpoint.

**Comment by nateprewitt** [comment]
> I do create new client for each request. Not sure if that's related.

Hi @shutingwang-db, I think this is the cause of what you're seeing. The credentials are cached per client when resolved from IMDS. When you create a new client for every invocation, you're throwing away the cache and having to build a new one. We recommend persisting clients between requests for performance.

The version of IMDS provided on EC2 provides credentials that should be valid for 6 hours, so refreshes should be done very infrequently. It also has safeguards built into the AWS-hosted infrastructure to handle IMDS stability which can be utilized by the SDK in the event of IMDS being unreachable.

In regards to the timings, these have been established in the SDK for quite some time and are now expected by third-party tools as well. We aren't able to change these values in a backwards compatible way.

Hopefully that sheds some more light on what you're seeing. Please let us know if you have further questions.
