### ISSUE TITLE
Ensure AWS_PROFILE is passed to the credential_process

### ISSUE THREAD

**Issue by mss** [boto/botocore#3043]
### Describe the feature

It would be helpful if the environment variable `AWS_PROFILE` was always passed to the process called as `credential_process` even if the profile was chosen via the command line switch `--profile` (in case of aws-cli).

### Use Case

I have to use an local fork of the [aws-adfs](https://github.com/venth/aws-adfs) `credential_process` helper to authenticate against the company's ADFS.

The fork maintains the config per profile in a separate config file `~/.aws/adfs-config`. The config for each profile is slightly different. So I can't configure a single `credential_process` for all my profiles but have to pass a `--profile xyz` switch to the helper as well. This makes configuring the tool unnecessary complex.

### Proposed Solution

The tool already picks up the profile from the `AWS_PROFILE` environment variable. That one is passed through if set for the aws-cli process only. It would be simpler if the current profile name was always passed to the subprocess.

It looks like all one would have to do is to add something like
```
  env=os.environ | { 'AWS_PROFILE': self._profile_name }
```
to the `popen` call in `ProcessProvider._retrieve_credentials_using`.

While that sounds trivial I didn't test that assumption and might be missing something obvious. Before I invest the time I wanted to ask if such a change would be accepted.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

Edge cases where this could break existing processes:
* Somebody combines an `AWS_PROFILE` environment variable with a different value for `--profile`.
* According to the `subprocess.Popen` documentation does Linux support binary environments via `os.environb` (TIL!). Supporting that would make the outlined solution more complicated so I would skip that.

### SDK version used

aws-cli/2.13.27 Python/3.10.12 Linux/6.2.0-35-generic source/x86_64.neon.22 prompt/off

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Hi @mss thanks for reaching out. I don't think that this change could be considered. Anything involving credentials/configuration must be heavily scrutinized in order to maintain backwards compatibility. [Here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#cli-configure-quickstart-precedence) is the current AWS CLI documentation on configuration and credentials precedence for reference. Supporting unofficial authentication use cases through third-party applications is unlikely to get prioritized.

Have you explored alternative approaches? I found a couple AWS links on AD FS that may be helpful:
* https://repost.aws/knowledge-center/adfs-grant-ad-access-api-cli
* https://aws.amazon.com/blogs/architecture/field-notes-integrating-active-directory-federation-service-with-aws-single-sign-on/

**Comment by mss** [comment]
@tim-finnigan thanks for the quick response. I understand that reasoning though I think the potential impact here is minimal. 

I checked the links you posted and am not sure if there isn't maybe a misunderstanding of the impact involved here: 
1. The `aws-adfs` I linked is used in combination with option 7 from the first page you linked ("Custom Process").
2. The script linked in the blog post linked from the second article is a hack of which the `aws-adfs` script is a more evolved variant (and the internal corporate script is even more sophisticated). I actually think that second article should point to the `aws-adfs` script instead of that blog post.
3. The third article doesn't seem to be relevant since it describes how to set up the ADFS-AWS-SSO integration which is already done by corporate IT.

What I am proposing is that an environment variable `AWS_PROFILE` (with the value from the `--profile` command line switch) is always passed to the [Custom Process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) invoked. There are edge cases where this might break existing workflows but those are very odd ones.

The patch would look something like this:
```patch
diff --git a/botocore/credentials.py b/botocore/credentials.py
index 6c2d72013..012d8eeae 100644
--- a/botocore/credentials.py
+++ b/botocore/credentials.py
@@ -994,7 +994,8 @@ class ProcessProvider(CredentialProvider):
         # command and all arguments as a list.
         process_list = compat_shell_split(credential_process)
         p = self._popen(
-            process_list, stdout=subprocess.PIPE, stderr=subprocess.PIPE
+            process_list, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
+            env=os.environ | { 'AWS_PROFILE': self._profile_name },
         )
         stdout, stderr = p.communicate()
         if p.returncode != 0:
```

Hmmm... if I changed that to to `{ 'AWS_PROFILE': self._profile_name } | os.environ` I think even the mentioned edge case would not apply.

Do you think there is any chance of getting this added? This is mainly an onboarding issue for us since people have to ensure that they set up their environment correctly and not miss the one place where they have to replace their username in each profile `~/.aws/config`.

If you don't see a reasonable chance I will close this feature request and look for another way to solve the issue. It should be solvable in the internal fork of the `aws-adfs` tool, I just thought this would be helpful for other people as well.

**Comment by tim-finnigan** [comment]
Thanks for following up and expanding on this. I still think this is unlikely to be considered, mainly because of the potential to break existing workflows. Maybe this feature request warrants more discussion and input from the team/community, but I do think you're better off trying to address this in the internal fork of the `aws-adfs` tool.

**Comment by mss** [comment]
No worries, that's why I asked first before creating a PR. In the end it is just a minor inconvenience which can be scripted away.

**Comment by mss** [comment]
Re-closing, I used the wrong resolution.
