### ISSUE TITLE
sqs.create_queue fails for ".fifo" suffix in queue name

### ISSUE THREAD

**Issue by kamikaze** [boto/botocore#3058]
### Describe the bug

SQS

```python
response = await sqs.create_queue(QueueName='messages.fifo')
```

results in:

```
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateQueue operation: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length
```

while in docs there is:
```
PARAMETERS:
QueueName (string) –

[REQUIRED]

The name of the new queue. The following limits apply to this name:

A queue name can have up to 80 characters.

Valid values: alphanumeric characters, hyphens ( -), and underscores ( _).

A FIFO queue name must end with the **.fifo suffix**.
```

### Expected Behavior

```
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateQueue operation: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length
```

### Current Behavior

Queue created

### Reproduction Steps

```python
response = await sqs.create_queue(QueueName=queue_name)
```

### SDK version used

botocore==1.31.17

### Environment details (OS name and version, etc.)

Linux

**Comment by RyanFitzSimmonsAK** [comment]
Hi @kamikaze, thanks for reaching out.  You're getting this error because you're trying to create a standard queue with a `.fifo` suffix.  To create a FIFO queue, you must specify the FifoQueue to be true in the attributes.  Here's an example : 

```
import boto3

sqs = boto3.client("sqs")

response = sqs.create_queue(
    QueueName='myTestQueue.fifo',
    Attributes={
        'FifoQueue': 'true'
    }
)
```

Hope that helps!

**Comment by kamikaze** [comment]
> Hi @kamikaze, thanks for reaching out.  You're getting this error because you're trying to create a standard queue with a `.fifo` suffix.  To create a FIFO queue, you must specify the FifoQueue to be true in the attributes.  Here's an example : 
> 
> ```
> import boto3
> 
> sqs = boto3.client("sqs")
> 
> response = sqs.create_queue(
>     QueueName='myTestQueue.fifo',
>     Attributes={
>         'FifoQueue': 'true'
>     }
> )
> ```
> 
> Hope that helps!

thanks. but what is the point to name it with a suffix then? two conditions instead of one

**Comment by RyanFitzSimmonsAK** [comment]
It's likely so that users have an easier way to determine the type of a queue, without needing to use `GetQueueAttributes`.
