### ISSUE TITLE
Posting to s3 bucket with bytes content (py3) leads to a signature problem

### ISSUE THREAD

**Issue by gwachob** [boto/botocore#306]
I am trying to post a binary blob to S3 (putObject), using py3.3 (botocore 0.50)

I have the binary data in a bytes object. I assumed, erroneously, that I could pass in the bytes and botocore would happily call the operation if I passed the bytes in as the "data" (not a file since I don't have that).

It turns out that because of line 420 and following, of botocore/vendored/requests/models.py, if the content type is not a str or file-like object, it seems to add a new content-type header (see   `content_type = 'application/x-www-form-urlencoded'`).. I think this behavior is curious, but I haven't dug into why the requests package is doing that (it may make total sense in the context of the requests package).

The real problem is that the signature being calculated by botocore does *not* include this header, so S3 complains with the `SignatureDoesNotMatch` error. (BTW, thanks for the excellent debug info, I was able to trace this down pretty quickly!)

My workaround is to create a BytesIO from the bytes and seek(0) and pass that to the operation.call body parameter. Requests doesn't add the header and the signature applied by botocore matches the actual request being sent.

I'm leaving this issue report a) to create a breadcrumb for future folks who might run across this problem and b) perhaps to raise this as an issue to fix by making bytes a valid body type or causing an error explicitly if bytes aren't to be allowed as a type for the body parameter.

Thanks!

**Comment by danielgtaylor** [comment]
This was fixed with the recent [Requests dependency update](https://github.com/boto/botocore/releases/tag/0.87.0).
