### ISSUE TITLE
Allow using urllib3 2.1.x with Python 3.10+

### ISSUE THREAD

**Issue by iherasymenko** [boto/botocore#3065]
### Describe the feature

This [commit](https://github.com/boto/botocore/commit/785d22457779cdb4054b77f4bd8fbca3feaf45a2) relaxed the version constraint and now it is possible to use `botocore` with `urllib3` versions 2.0.x; however, this does not allow using `botocore` with urllib3 `2.1.x`. 

### Use Case

I want to keep all of my dependencies up-to-date.

### Proposed Solution

Change the constraint from `urllib3>=1.25.4,<2.1; python_version>="3.10"` to `urllib3>=1.25.4,<3; python_version>="3.10"`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.29.1

### Environment details (OS name and version, etc.)

N/A

**Comment by RyanFitzSimmonsAK** [comment]
Hi @iherasymenko, thanks for reaching out.  According to the [main tracking thread](https://github.com/boto/botocore/issues/2926) for the `urllib3` pin, `urllib3 2.1.x` contains several breaking changes.  

https://github.com/boto/botocore/issues/2926#issuecomment-1753332063

> We're currently pinned at urllib3<2.1 since it will contain a handful of breaking changes.

I'm going to close this issue as a duplicate in favor of the main tracking thread, which you can refer to for any updates regarding the `urllib3` pin.
