### ISSUE TITLE
SSO OIDC client should not attempt to contact AWS metadata

### ISSUE THREAD

**Issue by jorhett** [boto/botocore#3076]
### Describe the bug

When initializing the OIDC client, it attempts to contact the AWS Metadata service, causing the client to hang.

### Expected Behavior

It should not attempt to contact the AWS Metadata service. Arguably, the entire stack of credential lookup should be avoided as none of those are relevant to OIDC https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

### Current Behavior

Initializing an OIDC client causes the python script to stop running while it waits for irrelevant queries to AWS Metadata service to be performed.

### Reproduction Steps

Code:

```python
import boto3
import logging
logging.basicConfig(level = 'DEBUG')

client = boto3.client('sso-oidc')
```

Output:

```
$ python3 repro.py
DEBUG:botocore.hooks:Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
DEBUG:botocore.hooks:Changing event name from before-call.apigateway to before-call.api-gateway
DEBUG:botocore.hooks:Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
DEBUG:botocore.hooks:Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
DEBUG:botocore.hooks:Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
DEBUG:botocore.hooks:Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
DEBUG:botocore.hooks:Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
DEBUG:botocore.utils:IMDS ENDPOINT: http://169.254.169.254/
DEBUG:botocore.credentials:Looking for credentials via: env
DEBUG:botocore.credentials:Looking for credentials via: assume-role
DEBUG:botocore.credentials:Looking for credentials via: assume-role-with-web-identity
DEBUG:botocore.credentials:Looking for credentials via: sso
DEBUG:botocore.credentials:Looking for credentials via: shared-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: custom-process
DEBUG:botocore.credentials:Looking for credentials via: config-file
DEBUG:botocore.credentials:Looking for credentials via: ec2-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: boto-config
DEBUG:botocore.credentials:Looking for credentials via: container-role
DEBUG:botocore.credentials:Looking for credentials via: iam-role
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254:80
DEBUG:botocore.utils:Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
```

### Possible Solution

Two valid solutions:

1. Don't search for AWS credentials. They aren't relevant to OIDC
2. Add an option to avoid this search

The suggestion previously provided boto/botocore#2275 [issuecomment-769476542](https://github.com/boto/botocore/issues/2275#issuecomment-769476542) 
> You can pass dummy credentials while creating client so that it won't look for any credentials.

...seems a bit superfluous. Why should a user cloud up their code with unused parameters so as to disable a completely irrelevant lookup?

### Additional Information/Context

this is replicable on every OS, so the OS version below does not matter.

### SDK version used

1.29.0

### Environment details (OS name and version, etc.)

Darwin RG42VR4F6V 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

**Comment by tim-finnigan** [comment]
Hi @jorhett thanks for reaching out. You can set the [AWS_EC2_METADATA_DISABLED](https://docs.aws.amazon.com/sdkref/latest/guide/feature-imds-credentials.html) environment variable to `true` in order to prevent the IMDS call. Also [this comment](https://github.com/boto/botocore/issues/2275#issuecomment-764888393) in the issue you linked still applies:
>Irrespective of anything when we create a client with boto3, botocore will look for valid sets of credential. So it will look in every possible places in [this order](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) and then it will try to fetch from instance metadata if the credentials has not been found in other places.

There is an open issue in the CLI repository (https://github.com/aws/aws-cli/issues/6130) about improving the error message here to help catch cases such as when a proxy configuration prevents the IMDS connection.

**Comment by jorhett** [comment]
> There is an open issue in the CLI repository ([aws/aws-cli#6130](https://github.com/aws/aws-cli/issues/6130)) about improving the error message here to help catch cases such as when a proxy configuration prevents the IMDS connection.

I think you miss the point. Making useless/unnecessary network calls, the results of which won't and cannot be used is pointless. Making someone wait for these unnecessary network calls to time out before showing them an "improved" message is truly missing the point.

This is not about proxies, this is about ec2 metadata being irrelevant in this context. Even if the call succeeds, it won't be used by this code.

**Comment by tim-finnigan** [comment]
Thanks for following up. Per the [credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) documentation:
>Boto3 will look in several locations when searching for credentials. The mechanism in which Boto3 looks for credentials is to search through a list of possible locations and stop as soon as it finds credentials.

The standardized credential flow documented there applies whenever initializing a client for [sso-oidc](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-oidc.html) or any other service. As previously mentioned, setting `AWS_EC2_METADATA_DISABLED` to `true` will stop the attempt to use Amazon EC2 Instance Metadata Service (IMDS) to obtain credentials. Please expand on your use case and proposed changes if you're expecting different behavior here.
