### ISSUE TITLE
client.py : _resolve_endpoint_ruleset returns 3 values instead of 2

### ISSUE THREAD

**Issue by conormb** [boto/botocore#3080]
### Describe the bug

_resolve_endpoint_ruleset used to return 2 values.  Now it returns 3.  No warning or explanation given.  Coming from 
https://github.com/boto/botocore/commit/826b78c54dd87b9da368e9ab6017d8c4823b28c1

### Expected Behavior

Return the same number of values as before

### Current Behavior

Downstream dependency, specifically PynamoDB, is expecting 2 values.  Since 3 are given an exception is thrown:

ValueError: too many values to unpack (expected 2)

### Reproduction Steps

- pip install pynamodb
- Map to a DynamoDB table
- Table.get(key) -> exception as described

### Possible Solution

Revert to a 2-value return

### Additional Information/Context

I realize this is an issue with how dependencies to boto3/botocore handle the return, but this can't be an isolated thing.  My workaround for now is pinning my version of boto3 to a prior version.

### SDK version used

Current / boto 1.33.1

### Environment details (OS name and version, etc.)

Python 3.9

**Comment by nateprewitt** [comment]
Hi @conormb, thanks for reaching out. `_resolve_endpoint_resolver` is a private interface which is subject to abrupt breaking changes between releases. We aren't able to provide a support contract on all of our private internals without halting development on the SDK unfortunately.

Looking at the [code in `PynamoDB`](https://github.com/pynamodb/PynamoDB/blob/c1d6222de280caf2dee603d2b7ac7558d52ebe96/pynamodb/connection/base.py#L383), it's calling private functions on the boto3 client to patch into our endpoints resolution behavior. This will likely need to be updated in `PynamoDB` to make it compatible with ongoing releases of Botocore. For the time being, the best resolution step would be to pin `botocore<1.33.0` with `PynamoDB` until they're able to provide a patch.

**Comment by conormb** [comment]
Thanks for the prompt response.  I'll pin to 1.33.0 and work with the PynamoDB contributors.
