### ISSUE TITLE
Lambda python 3.11 does not start with current boto 1.33.2

### ISSUE THREAD

**Issue by megaproaktiv** [boto/botocore#3082]
### Describe the bug

Python Lambda with 
boto3==1.33.2
botocore==1.33.2
Does not start

### Expected Behavior

Starts without problem

### Current Behavior

[2023-11-29T11:28:51+01:00] (2023/11/29/[$LATEST]9664a7f7e9e248f886b4d98e973b9c5a) INIT_START Runtime Version: python:3.11.v18	Runtime Version ARN: arn:aws:lambda:eu-central-1::runtime:6ebff6b58cf714d30879a40cc31554cd1bbc242da7bf75a000bc0c3052c6ebbc
[2023-11-29T11:28:52+01:00] (2023/11/29/[$LATEST]9664a7f7e9e248f886b4d98e973b9c5a) START RequestId: fb119c11-0401-456b-a9df-3b692ec3e9de Version: $LATEST
[2023-11-29T11:28:52+01:00] (2023/11/29/[$LATEST]9664a7f7e9e248f886b4d98e973b9c5a) [ERROR] Runtime.ImportModuleError: Unable to import module 'app': cannot import name 'is_s3express_bucket' from 'botocore.utils' (/var/lang/lib/python3.11/site-packages/botocore/utils.py)

### Reproduction Steps

Create a lambda with requirements txt. It does not have to have any functions

### Possible Solution

Publish current boto, the function 

def is_s3express_bucket(bucket):
    if bucket is None:
        return False
    return bucket.endswith('--x-s3')
    
    existis.

### Additional Information/Context

This could be a problem with new re-invent feature

### SDK version used

1.33.2

### Environment details (OS name and version, etc.)

Lambda Python 3.11

**Comment by FernandoAndrade83** [comment]
Same on Python 3.9

**Comment by Saarett** [comment]
Same with Python 3.8

```
{
  "errorMessage": "Unable to import module 'my_module': cannot import name 'is_s3express_bucket' from 'botocore.utils' (/var/runtime/botocore/utils.py)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}
```

We have to pin the boto3 version because otherwise it could crush our production services

**Comment by FernandoAndrade83** [comment]
[WORKARROUND]
I needed to force the downgrade of boto3 and botocore in the Lambda, using `pip install boto3==XXXXX botocore==XXXXX --upgrade` inside the code. XXXXX was the last version that worked.

That's working for me now

**Comment by nateprewitt** [comment]
Hi everyone, thanks for reaching out. We're currently taking a look at this but it appears something is going wrong with how these packages are being updated on Lambda in your cases.

`is_s3express_bucket` was released yesterday with boto3 1.33.2 which requires botocore 1.33.2. You can see the function defined [here](https://github.com/boto/botocore/blob/1.33.2/botocore/utils.py#L3563-L3566) in the release. If Lambda is unable to find this, it implies it's using an older version of Botocore despite other modules (boto3 and/or s3transfer) being updated.

Can anyone provide the exact versions of these three packages they're importing into their function?

* boto3
* botocore
* s3transfer

For immediate mitigation while we investigate, you'll need `boto3<1.33.2`, `botocore<1.33.2`, `s3transfer<0.8.1`. Note that you cannot update any of these independently of each other.

**Comment by MostafaHosseinian** [comment]
I just re-launch my script and still the same import error raised. Following packages were used.
boto3-1.33.0
botocore-1.33.0
s3transfer-0.8.1
sagemaker-2.183.0

**Comment by nateprewitt** [comment]
For @MostafaHosseinian, the culprit is almost certainly `s3transfer`. You'll need to downgrade that to `0.8.0` unless you have the latest versions of boto3/botocore. It's [only compatible 1.33.2+](https://github.com/boto/s3transfer/blob/develop/setup.py#L12).

Those dependencies look correct @FernandoAndrade83 and run fine off Lambda. I'm moving to testing on Lambda now.

**Comment by Saarett** [comment]
In case it helps - We have the same versions as @FernandoAndrade83 has, and it works for us off Lambda as well

**Comment by nateprewitt** [comment]
I've packaged a lambda deployment zip that looks like:

```bash
$ tree -L 1
.
├── lambda_function.py
├── boto3
├── boto3-1.33.2.dist-info
├── botocore  
├── botocore-1.33.2.dist-info 
├── s3transfer
└── s3transfer-0.8.1.dist-info
```
This was generated from downloading the wheels off PyPI with `python -m pip download boto3`, unzipping them into the directory with my lambda function, and zipping them all into a `.zip` archive for Lambda.

The function I'm using is just to sanity check versions being used:
```python
import json
import boto3
import botocore
import s3transfer

def lambda_handler(event, context):
    response = f"Boto3: {boto3.__version__}, Botocore: {botocore.__version__}, S3Transfer: {s3transfer.__version__}"
    return {
        'statusCode': 200,
        'body': response
    }
```

Uploading this to Lambda on all available Python versions is producing the same response:

```json
{
  "statusCode": 200,
  "body": "Boto3: 1.33.2, Botocore: 1.33.2, S3Transfer: 0.8.1"
}
```

So, I think there's something common with how users in this thread are packaging their deployments that's leading to version mismatches. If there's anything I've used above you think may not be relevant to your case, please let me know.

@Saarett @FernandoAndrade83, can you provide any more info on how you created your lambda packages and how you confirmed the versions you listed are in the zip/being picked up by Lambda?

**Comment by Saarett** [comment]
@nateprewitt So, I didn't run the lambda as you did (which is a very good idea!).
We're creating a layer that contains all the relevant packages. After downloading and unpacking the zip, I found the list of all packaged packages. Neither `boto3` nor `botocore` were there, but `s3transfer` was present under the name `s3transfer-0.8.1.dist-info`. When I looked at the `METADATA` file, I found under the `Requires-Dist` section `botocore (<2.0a.0,>=1.33.2)`.

Feels like your way is a bit easier though 😄

**Comment by tim-finnigan** [comment]
The default [Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) for Python 3.11 are `boto3-1.27.1 botocore-1.30.1`.  I also tested using a Lambda layer including boto3/botocore 1.33.2 with the [code](https://github.com/boto/botocore/issues/3082#issuecomment-1832300927) referenced above and it ran successfully. 

Steps for creating the layer (paraphrased from [this article](https://repost.aws/knowledge-center/lambda-python-runtime-errors)):

* `mkdir -p boto3-layer/python`
* `pip3 install boto3 -t boto3-layer/python`
* `cd boto3-layer`
* `zip -r /tmp/boto3-layer.zip .  `
* `aws lambda publish-layer-version --layer-name boto3-layer --zip-file fileb:///tmp/boto3-layer.zip --compatible-runtimes python 3.11`

And then attach the layer:

![image](https://github.com/boto/botocore/assets/87778557/40ecbc08-f3cd-47e4-a48b-3c4e91641d00)
   
Using the code [referenced above](https://github.com/boto/botocore/issues/3082#issuecomment-1832300927) results in:

![image](https://github.com/boto/botocore/assets/87778557/59f6141d-5355-4023-96b4-e35a2fef1b0f)

**Comment by nateprewitt** [comment]
Thanks for confirming, @Saarett! It appears we now have 2 of the three cases confirmed to be s3transfer being newer than boto3/botocore. You'll either want to downgrade s3transfer back to `0.8.0` or ensure you pull `boto3`/`botocore` 1.33.2 into your layer.

I think we can state the general guidance is if you've upgraded to `s3transfer==0.8.1` you MUST also update to `boto3>=1.33.2` and `botocore>=1.33.2` in your layer or zip.

**Comment by Saarett** [comment]
@nateprewitt But according to the `METADATA` file of the `s3transfer` package, it appears that I am using `botocore>=1.33.2`, aren't I? Otherwise, the package resolution wouldn't work,  please correct me if I'm wrong.

I do understand Lambda runtimes for Python 3.11 use lower version of `botocore` and `boto3`, so I'm not sure what I'm missing.

**Comment by nateprewitt** [comment]
@Saarett you're correct that s3transfer _requires_ Botocore>=1.33.2. But if you're not including that within your layer, it won't work. It's likely you have newer versions of boto3/botocore installed on your local system that are satisfying the requirements for s3transfer when creating the layer.

If those boto3/botocore copies don't end up in the final zip though, your function will fallback to the old copies supplied by Lambda, causing a failure.

> After downloading and unpacking the zip, I found the list of all packaged packages. Neither boto3 nor botocore were there, but s3transfer was present under the name s3transfer-0.8.1.dist-info.

Please let me know if I'm misunderstanding this statement. I'm reading it to be your final layer has s3transfer==0.8.1, but not boto3 or botocore.

**Comment by donsokolone** [comment]
I'm experiencing the same issue using default boto3/botocore provided in 3.9 runtime:
```
INIT_START Runtime Version: python:3.9.v36	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:386a1053a16b9122f1622b361a8a78f39595e5a53df0c82932eacae85b33cd62
[ERROR] Runtime.ImportModuleError: Unable to import module 'runner_s3.app': cannot import name 'is_s3express_bucket' from 'botocore.utils' (/var/runtime/botocore/utils.py)
Traceback (most recent call last):
```

**Comment by Saarett** [comment]
@nateprewitt Correct. It does make sense. In that case, sounds like I have 2 possible solutions:
1. Add the relevant boto3 and botocore versions to the layer, and they will override the Lambda runtime versions
2. Pin the local boto3 and botocore versions to be equal to those which are being used in the Lambda runtime (currently boto3-1.26.90, botocore-1.29.90)

Is that correct?

**Comment by MostafaHosseinian** [comment]
> @nateprewitt Correct. It does make sense. In that case, sounds like I have 2 possible solutions:
> 
> 1. Add the relevant boto3 and botocore versions to the layer, and they will override the Lambda runtime versions
> 2. Pin the local boto3 and botocore versions to be equal to those which are being used in the Lambda runtime (currently boto3-1.26.90, botocore-1.29.90)
> 
> Is that correct?


The second option you noted in my side is as follows, and it worked.

- **Lambda**: boto3~=1.20.50  -  botocore~=1.29.109
- **local**: boto3==1.29.5  -  botocore==1.32.5

**Comment by nateprewitt** [comment]
@Saarett that's correct. `s3transfer` should only be used by `boto3` and `awscli`. If you're updating either of those, you should always have a matching version of `botocore` in those layers, otherwise it's going to be susceptible to these kinds of failures.

The two options you listed are sufficient:

1. Pin to a known working set of dependencies for `boto3`, `botocore`, and `s3transfer`.
2. If you choose to upgrade, all three must be included in the layer/zip.

**Comment by Saarett** [comment]
@nateprewitt Thank you for the assistance, it makes sense. We'll ensure that we pin the dependencies and also remove `s3transfer` from the layer.
As a small suggestion, it would be helpful to state in the documentation that we (the users) should also remove `s3transfer` from the layer. This information could have prevented our issue. Now I'm asking myself if there are similar dependencies I'm not aware of in other frameworks we use (i.e NodeJS) 🙂

**Comment by nateprewitt** [comment]
> As a small suggestion, it would be helpful to state in the documentation that we (the users) should also remove s3transfer from the layer.

Ideally this shouldn't be necessary. Do you know what other dependency was updating s3transfer in your layer? If it's not packaged with the awscli or boto3, I'm surprised it ended up on the layer to begin with.

**Comment by ayudovin** [comment]
@MostafaHosseinian, have you found any solution that helps you?

**Comment by Saarett** [comment]
@nateprewitt Even if I have no dependencies using s3transfer, and I'm the only one to include boto3, botocore3 in my Pipfile, when I zip them into a layer excluding boto3 and botocore, all their dependencies, including dateutil, six, urllib3, jmespath, and s3transfer itself, are still getting zipped. I didn't realize I also needed to remove s3transfer.

**Comment by MostafaHosseinian** [comment]
> @MostafaHosseinian, have you found any solution that helps you?

I kept the lambda as it was:
boto3~=1.20.50
botocore~=1.29.109
requests~=2.28.2
Also, pin the local boto3 and botocore versions to be the same as the last successful job (currently boto3-1.29.5, botocore-1.32.5)
My job run successfully, then

**Comment by jasongi** [comment]
I ran into the issue and this was the cause.

Lots of examples out there will instruct you to run something like

```
RUN rm -rdf \
    /asset/boto3* \
    /asset/botocore* \
#... etc
```

As a part of your lambda build docker file after your pip install - as lambda runtime includes these packages and then they won't count towards your size limit for your lambda package.
However (at least in my case - [looking at this dockerfile](https://github.com/developmentseed/titiler/blob/main/deployment/aws/lambda/Dockerfile#L15)) s3transfer wasn't in the list of packages to remove. So if you updated the boto3/botocore dependencies and then build using a dockerfile like this that removes boto3 you'll get the lambda runtime boto3 but the latest s3transfer, which are incompatible. The solution is that if you're relying on the lambda runtime boto3 package then delete s3transfer too.


```
RUN rm -rdf \
    /asset/boto3* \
    /asset/botocore* \
    /asset/s3transfer* \
#... etc
```
Now you'll get all three from the lambda runtime - and they should all be compatible.

In an ideal world, we would be able to reference a boto3 package that always matches what is provided by lambda in our poetry/pip files, so that running things locally behaves the same as it does on lambda.

**Comment by kousi26** [comment]
Is this resolved ? I tried to update to the latest versions but still I get the error : 
After downloading and unpacking the zip, the below are the versions:
boto3 - 1.33.2
botocore - 1.33.2
s3transfer - 0.8.2

**Comment by krismanaya** [comment]
Is this ticket resolved? I was able to roll back and ship with Lambda by adding the following to my `requirements.txt` file.
`python3.10`
 
`boto3<1.33.2
botocore<1.33.2
s3transfer<0.8.1 `

**Comment by nateprewitt** [comment]
The ticket is still open for visibility but there isn't an issue with boto3/botocore to be resolved. The case this occurs is when s3transfer is updated without updating boto3/botocore violating the requirements specified by each package. The current cases where this may happen is if you're removing boto3/botocore for space savings but not removing s3transfer.

You can see the [repro above](https://github.com/boto/botocore/issues/3082#issuecomment-1832300927) demonstrating everything works as intended when all files are updated. If you need to remove boto3/botocore from your deployment to save space, you'll also need to ensure s3transfer is omitted. [One example](https://github.com/boto/botocore/issues/3082#issuecomment-1859187054) of how you might do this was provided @jasongi above, but this will vary depending on how your lambda is packaged.

**Comment by krismanaya** [comment]
@nateprewitt This is perfect. Thanks so much Nate for the quick response!

**Comment by allison-mm255** [comment]
sorry if someone already said this.
I started getting this error after installing awsebcli.
Steps to fix:
1. pip3 uninstall awsebcli
2. pip3 uninstall awscli
3. pip3 uninstall botocore s3transfer
4. pip3 install awscli

**Comment by vhosakot** [comment]
saw same error on mac when using `aws eks update-kubeconfig ...` cli, and below steps fixed it for me on mac:

```
$ aws eks update-kubeconfig --name <AWS EKS cluster name> --region <AWS region>
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/clidriver.py", line 78, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/handlers.py", line 78, in <module>
    from awscli.customizations.s3.s3 import s3_plugin_initialize
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/customizations/s3/s3.py", line 15, in <module>
    from awscli.customizations.s3.subcommands import ListCommand, WebsiteCommand, \
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/customizations/s3/subcommands.py", line 18, in <module>
    from botocore.utils import is_s3express_bucket, ensure_boolean
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/botocore/utils.py)

# saw above error with below versions
$ pip3 list | grep 'aws\|boto\|s3'                               
awscli                     1.32.80
boto3                      1.28.38
botocore                   1.31.85
s3transfer                 0.6.2
```

below steps fixed it for me:

```
pip3 uninstall -y awscli boto3 botocore s3transfer
pip3 install awscli

# below command worked for me
aws eks update-kubeconfig --name <AWS EKS cluster name> --region <AWS region>
```
