### ISSUE TITLE
SageMaker client's FIPS endpoint incorrect in us-gov-west-1

### ISSUE THREAD

**Issue by ben-kaiser** [boto/botocore#3097]
### Describe the bug

The Boto3 SageMaker client's endpoint does not match the expected endpoint when setting `AWS_USE_FIPS_ENDPOINT=true` and `AWS_DEFAULT_REGION=us-gov-west-1`

### Expected Behavior

I expect the endpoint url to match the [documented FIPS endpoint](https://aws.amazon.com/compliance/fips/)

### Current Behavior

the endpoint url did not match the documentation:
`https://api-fips.sagemaker.us-gov-west-1.amazonaws.com`

### Reproduction Steps

python@3.9
boto3@1.33.1
botocore@1.33.1

```python
import boto3, os
os.environ["AWS_USE_FIPS_ENDPOINT"]="true"
os.environ["AWS_DEFAULT_REGION"]="us-gov-west-1"
c = boto3.client("sagemaker")
print(c.meta._endpoint_url)
```
outputs the following:
```
https://api-fips.sagemaker.us-gov-west-1.amazonaws.com
```

### Possible Solution

I have found an instance of the incorrect url https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L21706

### SDK version used

1.33.1

### Environment details (OS name and version, etc.)

python@3.9.16

**Comment by RyanFitzSimmonsAK** [comment]
Hi @ben-kaiser, thanks for reaching out.  I was able to reproduce this issue.  I've reached out to the SageMaker service about this behavior.  In the meantime, as this is a service team issue, I've created a tracking issue in our cross-SDK repository (https://github.com/aws/aws-sdk/issues/680).  Please refer to this issue for any updates.  Thanks!
