### ISSUE TITLE
get_available_regions does not return ec2 for the new region ca-west-1

### ISSUE THREAD

**Issue by naveenarra** [boto/botocore#3101]
### Describe the feature

EC2 is available for ca-west-1. However boto3 get_available_regions does not include ca-west-1. I noticed this is missing in the file https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L5776.

### Use Case

We need to run commands to get EC2 instances in ca-west-1.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.34.23

### Environment details (OS name and version, etc.)

Linux

**Comment by RyanFitzSimmonsAK** [comment]
Hi @naveenarra, thanks for reaching out.  I was able to get a response that includes `ca-west-1` as an available region.  Could you verify that you have this region enabled, as it is an opt-in region?  You can get more information about opt-in regions [here](https://docs.aws.amazon.com/controltower/latest/userguide/opt-in-region-considerations.html).

**Comment by RyanFitzSimmonsAK** [comment]
Hi @naveenarra, thanks for your patience.  My prior comment was incorrect, my mistake.  `get_available_regions` is known to be inaccurate, and I would recommend that you use the [SSM Parameter Store API ](https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/) for your use case.  For full context, [here](https://github.com/aws/aws-sdk/issues/206#issuecomment-1471354853) is a comment on a similar issue that explains it pretty thoroughly.

> Upon discussing this further with a colleague we wanted to clarify that the Python SDK team is currently investigating paths forward for this method, and deprecation is one possible outcome. Here is why:
> 
> As mentioned above, the source of information returned by get_available_regions is the endpoints.json file. This file is embedded in botocore and until version 1.28.0 was used for endpoint resolution in botocore.
> 
> The get_available_regions method was introduced many years ago as a secondary use of endpoints.json data, long before other sources of service availability were available. This has always been a sub-optimal solution because the information in endpoints.json is inherently frozen at release time. And even at release time the data in endpoints.json may lag behind reality due to how it is generated internally. The boto3 documentation addresses this (the function is not documented in the botocore documentation).
> 
> Since get_available_regions was introduced, [the SSM Parameter Store API was introduced](https://aws.amazon.com/blogs/aws/new-query-for-aws-regions-endpoints-and-more-using-aws-systems-manager-parameter-store/) to solve the same user need better in 2019. Endpoint resolution in SDKs migrated to a different data source starting with botocore 1.28.0. As a result, endpoints.json will become an even less complete and up-to-date data source.
> 
> If completeness and recency of information is important for your use, switching to the SSM API is, and has been, the recommended approach.

Hope that helps, and please let me know if you have any other questions.
