### ISSUE TITLE
Support urllib3 2.1.0 and 2.2.0 to be installed

### ISSUE THREAD

**Issue by matejsp** [boto/botocore#3112]
### Describe the feature

There is a new version of urllib3 (v2.2.0, v2.1.9) that can't be installed in projects that use botocore because, in the setup.py file, it has the version restriction:

urllib3>=1.25.4,<2.1; python_version>="3.10"

### Use Case

urllib3 getting http/2 support (basic for now).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.34.34

### Environment details (OS name and version, etc.)

MacOSX Sonoma

**Comment by RyanFitzSimmonsAK** [comment]
Hi @iherasymenko, thanks for reaching out. According to the [main tracking thread](https://github.com/boto/botocore/issues/2926) for the urllib3 pin, urllib3 2.1.x+ contains several breaking changes.  

https://github.com/boto/botocore/issues/2926#issuecomment-1753332063

    We're currently pinned at urllib3<2.1 since it will contain a handful of breaking changes.

I'm going to close this issue as a duplicate in favor of the main tracking thread, which you can refer to for any updates regarding the urllib3 pin.
