### ISSUE TITLE
100-continue handled incorrectly

### ISSUE THREAD

**Issue by dbrumley** [boto/botocore#3124]
### Describe the bug

 From RFC: https://tools.ietf.org/html/rfc7231#section-5.1.1
Requirement for clients:
- A client MUST NOT generate a 100-continue expectation in a request that does not include a message body.

The current code always returns true, even with an empty message body.

### Expected Behavior

Change to self._expect_header_set = headers.get('Content-Length') != '0'

### Current Behavior

botocore will incorrectly generate a 100-continuation.

### Reproduction Steps

Had this bug with minio. I don't have a repro local, but did cite the RFC.

### Possible Solution

I'll submit a PR. It's a simple change.

### SDK version used

develop

### Environment details (OS name and version, etc.)

macos, python 3.9

**Comment by SamRemis** [comment]
Thank you for bringing this to our attention

We have had this issue reported a number of times; one of the boto maintainers gave an in depth explanation of the complexity of the issue [here](https://github.com/boto/boto3/issues/3757#issuecomment-1603242542).  We currently have [an open PR](https://github.com/boto/botocore/pull/3123) for an experimental opt in header to solve this issue.
