### ISSUE TITLE
[EC2] `PlatformValues` enum is incorrect in botocore shapes

### ISSUE THREAD

**Issue by vemel** [boto/botocore#3128]
### Describe the bug

In botocore shape `PlatformValues` enum has value `Windows`, while the actual return value is `windows`.

### Expected Behavior

`PlatformValues` enum has [`windows`] value.

### Current Behavior

`PlatformValues` enum has [`Windows`] value.

### Reproduction Steps

Run any related method, e.g. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_fleet.html#

and check the response.

### Possible Solution

Replace `Windows` with `windows` in `PlatformValues`

### SDK version used

1.34.50

### Environment details (OS name and version, etc.)

OS-independent

**Comment by RyanFitzSimmonsAK** [comment]
Hi @vemel, thanks for reaching out and for your patience.  I was able to reproduce this issue using `CreateFleet`.  You are correct that there is a mismatch between what is documented (`CreateFleetInstance` structure and botocore enum both are uppercase) and what is returned.  I've reached out to the service team to clarify what the intended behavior is here.  In the meantime, as this is a service team issue, I've created a tracking issue (https://github.com/aws/aws-sdk/issues/797) in our cross-SDK repository that you can refer to for future updates.  Thanks!
