### ISSUE TITLE
Fix wrong documentation in ec2 import-key-pair around base64 encoding

### ISSUE THREAD

**Issue by victorhooi** [boto/botocore#3130]
### Describe the issue

This is related to the below two issues against aws-cli:
* https://github.com/aws/aws-cli/issues/41
* https://github.com/aws/aws-cli/issues/4969

There seems to be a documentation bug in botocore - I filed a very small PR to fix it:
* https://github.com/boto/botocore/pull/3129

However, I just re-read the CONTRIBUTING.md - it seems the preference is to file issues to fix these upstream (which I assume is AWS internal).

The PR should be self-explanatory - but specifically, can we update the documentation to remove the sentence:
> For command line tools, base64 encoding is performed for you.
(Which is no longer accurate with AWS CLI V2).

And replace with a reference to using the fileb:// URI please?

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/import-key-pair.html

**Comment by Redeys** [comment]
Describe the issue
This is related to the below two issues against aws-cli:

Fix ec2 import-key-pair aws/aws-cli#41
ec2 import-key-pair issue aws/aws-cli#4969
There seems to be a documentation bug in botocore - I filed a very small PR to fix it:

Fix documentation for ec2 import-key-pair for how to properly base64-encode keyfiles #3129
However, I just re-read the CONTRIBUTING.md - it seems the preference is to file issues to fix these upstream (which I assume is AWS internal).

The PR should be self-explanatory - but specifically, can we update the documentation to remove

**Comment by tim-finnigan** [comment]
Thanks for reaching out and for your patience. As you mentioned, changes to the service documentation would need to be implemented upstream. To send suggestions for APIs like [ImportKeyPair](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportKeyPair.html), you can use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=EC2%20API&topic_url=https://docs.aws.amazon.com/en_us/AWSEC2/latest/APIReference/API_ImportKeyPair.html) at the bottom of the API documentation page.

But it looks like handling base64 commands is already mentioned here in the AWS CLI documentation for the EC2 `import-key-pair` command: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/import-key-pair.html

![image](https://github.com/boto/botocore/assets/87778557/ca4279af-3bfb-499d-961d-9567bb3fa3e0)

And in the example on that page which uses `fileb://`:

![image](https://github.com/boto/botocore/assets/87778557/979b7403-6b71-4611-adad-128be4b026f6)

If you'd like to submit feedback specific to the CLI command reference, please use the [Give us feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AWS%20Command%20Line%20Interface&hidden_guide_name=Reference&topic_url=https%3A%2F%2Fdocs.aws.amazon.com%2Fcli%2Flatest%2Freference/ec2/import-key-pair.html) on the sidebar.
