### ISSUE TITLE
Allow urllib3 2.2.1 to be installed

### ISSUE THREAD

**Issue by epicserve** [boto/botocore#3137]
### Describe the feature

There is a new version of urllib3 (v2.2.1) that can't be installed in projects that use botocore because, in the setup.py file, it has the version restriction `urllib3>=1.25.4,<2.1`.

### Use Case

So other projects that want to upgrade to urllib3 2.2.1 can without being blocked by the botocore library.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

all

**Comment by nateprewitt** [comment]
Hi @epicserve, 

This is currently being tracked in https://github.com/boto/boto3/issues/4025 which I believe was linked in your last issue. We're working on the update and will provide status there when it's available.

**Comment by epicserve** [comment]
@nateprewitt,

Sorry about the extra noise. I'm not sure how I missed it. I did look before creating the issue.

**Comment by nateprewitt** [comment]
No worries!
