### ISSUE TITLE
sqs create_queue does not return `QueueUrl` since v1.34.90

### ISSUE THREAD

**Issue by zodiac403** [boto/botocore#3169]
### Describe the bug

Sample code to reproduce the issue:]

```py
sqs = boto3.client("sqs")
queue = sqs.create_queue(QueueName="name.fifo", Attributes={"FifoQueue": "true"})
queue_url = queue["QueueUrl"]
```

According to boto docs, `create_queue()` should return a dict like {  'QueueUrl': 'string' }
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/create_queue.html

With version `botocore==1.34.89` this is still the behavior I can observe

### Expected Behavior

Resolve URL with `queue_url = queue["QueueUrl"]`

### Current Behavior

`queue_url = queue["QueueUrl"]` results in a `KeyError` as the the result of `create_queue()` does not have an entry `"QueueUrl"`.

### Reproduction Steps

Code sample above

### SDK version used

Observed the issue in `1.34.90`, could not reproduce the issue in `1.34.89`

### Environment details (OS name and version, etc.)

MacOs Sonoma 14.4

**Comment by zodiac403** [comment]
Hi @tim-finnigan ,

thanks for the very quick response. I will check that out on my side.

**Comment by zodiac403** [comment]
Hi @tim-finnigan ,

indeed, there was moto pinned to an old version in this project. Appreciate your support here!

**Comment by vbhjckfd** [comment]
I have same error, although no moto package installed.
1.34.89 works good, 90+ returns no QueueUrl in response
I had to pin botocore==1.34.89 😢

**Comment by vkundas** [comment]
The same goes for me. Moto and similar are not used, but 1.34.90+ fails with this error.
Also had to pin the version :(

**Comment by laredoo** [comment]
> Hi [@zodiac403](https://github.com/zodiac403) thanks for reaching out. There was a recent change in [1.34.90](https://github.com/boto/botocore/blob/e0998da2f531f5985c02aa4a9fdaaabffe0075c9/CHANGELOG.rst?plain=1#L16) related to SQS:
> 
> > * api-change:`sqs`: This release enables customers to call SQS using AWS JSON-1.0 protocol
> 
> However, the response syntax should be the same. I just tested your snippet in both 1.34.89 and 1.34.90 and confirmed that `QueueUrl` was returned as expected. Are you by chance using moto or some other third-party package? If so please try updating to see if that resolves the issue.
> 
> It looks like in moto version [4.2.10](https://github.com/getmoto/moto/blob/master/CHANGELOG.md#4210) is where support for the SQS change was added.

Exactly, the same happened here. We've been using third-party moto package, and after upgrading boto3/botocore to version 1.37.32 we were getting the same errors. Upgrading moto3 to version [4.2.10](https://github.com/getmoto/moto/blob/master/CHANGELOG.md#4210) worked just fine. Thanks for the suggestion
