### ISSUE TITLE
Waiter documentation about error behavior is incorrect

### ISSUE THREAD

**Issue by Shtutnik** [boto/botocore#3193]
### Describe the issue

Hi,

(Also opened [this](https://github.com/boto/boto3/issues/4107) issue that was merged)

From what I see in the different waiter pages, it states that An error is **returned** (see code [here](https://github.com/boto/botocore/blob/53028006b6817b98adf7643718313d1a375779e4/botocore/docs/waiter.py#L166)) ... although when checking the python code (for example [here](https://github.com/boto/botocore/blob/331c5fecc8f87d1c923460371a785cf62e86b5f8/botocore/waiter.py#L357)) it seems that actually an error is raised, not returned.

Could you please emphasize this so that developers know what behavior to expect from the wait function?

I listed some examples below, but I think this is a generic thing that applies to all waiter pages.

### Links

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs/waiter/ServicesStable.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/waiter/ImageExists.html

**Comment by tim-finnigan** [comment]
Thanks for following up here, created https://github.com/boto/botocore/pull/3196 which should address this.
