### ISSUE TITLE
Did you recently rewrite history?

### ISSUE THREAD

**Issue by antoine-sac** [boto/botocore#3241]
### Describe the bug

Hello,

It looks like you may have recently rewritten the commit history and incidentally broken `meta-aws` because all referenced commits no longer exist on the master branch. 

We cannot set up reproducible builds if commits disappear and years of commits have been rewritten :/ 

For example, this was the commit for botocore v1.34.157 three weeks ago: https://github.com/boto/botocore/commit/894686f5fc8d1440715877ec361695fb71fc900c

It is no longer attached to any branch so cannot be found.

Related to : https://github.com/aws4embeddedlinux/meta-aws/issues/9442

### Expected Behavior

The commits prior to a few weeks ago should still exist in the commit history of a branch.

### Current Behavior

Commits have disappeared from the history and broken years of reproducible builds via `meta-aws`.

For example:
0a2e478bfc813cd7a0f4aa5a58388fc5bf8d77ab
894686f5fc8d1440715877ec361695fb71fc900c
19ce2f58608601c6dce3311045fec0461d7e484d
da3918aafc5493478fe2bec86fccb348aef7fdb9

### Reproduction Steps

NA

### SDK version used

NA

### Environment details (OS name and version, etc.)

NA

**Comment by antoine-sac** [comment]
There have been multiple force-push commits to master in the past 2 weeks according the repository activity https://github.com/boto/botocore/activity.

With any luck, either @nateprewitt or @hssyoo still have the previous master branch and could rebase and force-push it back to its normal state?

I also imagine anyone with the repo checked out prior to the history rewrite will have the previous commits?

<img width="338" alt="image" src="https://github.com/user-attachments/assets/e2a17616-5d03-41cf-82ce-a1fcaa50e74e">

<img width="546" alt="image" src="https://github.com/user-attachments/assets/48f2e5c3-6e9b-45ea-b109-64ff2417b5f5">

**Comment by jonathan343** [comment]
Hey @antoine-sac,
Thank you for reporting this issue. We’re in the process of restoring the original history in the `master` branch. We're currently taking steps to make sure we get recover this properly and prevent further issues. We'll post an update once we have more information.

**Comment by antoine-sac** [comment]
The good news is that all the version tags are still attached to the correct commits, so people using boto/botocore@vx.y.z are not impacted. Although those commits are not attached to the master branch.

An issue only arises for yocto builds because we are forced to also provide the branch of the commit, so we can't use a floating commit.

<img width="788" alt="image" src="https://github.com/user-attachments/assets/2bed0b9e-5750-44d4-8001-2131db8948cb">

**Comment by antoine-sac** [comment]
As a temporary fix, would you be able to create a branch for the "old" master, like `temp/fixed_master`?

This would allow us to keep using the old commits (matching the version tags) simply by switching branch.

**Comment by jonathan343** [comment]
Hey @antoine-sac,
I just pushed up a `temp-master-fix` branch. Can you let us know if this resolves your problem or if you run into any other issues?

**Comment by zach-welch-aquabyte** [comment]
The `temp-master-fix` fixed my Yocto build that uses `meta-aws` (after some manual intervention). It is a good short-term workaround that unblocked my development, so thanks for that. Looking forward to seeing the original branch restored and reading the postmortum.

**Comment by jonathan343** [comment]
We've pushed an update to the `master` which restores the lost commits and should resolve this issue.
@antoine-sac can you switch off the `temp-master-fix` and verify the new update to `master` resolves your issue?

**Comment by zach-welch-aquabyte** [comment]
I can verify that my build now works again using the unmodified `scarthgap` branch of `meta-aws`.

**Comment by jonathan343** [comment]
Thanks for the patience and assistance with resolving this issue!
We’ve made updates to our release infrastructure that will prevent us getting in a state where manual pushes to `master` are required. We encourage anyone using the `temp-master-fix` branch to migrate off of it ASAP and don’t guarantee its existence forever.
