### ISSUE TITLE
AnnotationConsolidationLambdaArn is not required

### ISSUE THREAD

**Issue by BeRT2me** [boto/botocore#3278]
### Describe the issue

> This parameter is required for all labeling jobs.

This is no longer true since `AnnotationConsolidationConfig` is no longer a required parameter.

This specific phrase should be removed.

### Links

https://github.com/boto/botocore/blob/131f207c848663997e95f6490617d3642b37c662/botocore/data/sagemaker/2017-07-24/service-2.json#L4640

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Looking at the Amazon SageMaker docs for the [AnnotationConsolidationConfig API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_AnnotationConsolidationConfig.html), it says for `Required: Yes` for `AnnotationConsolidationLambdaArn` towards the bottom of the page. So I'd think we'd have to confirm with the SageMaker team what updates would be required here. Are you running [create_labeling_job](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_labeling_job.html#) or another SageMaker command? If you can share a snippet or any more details on your use case please let us know.

**Comment by BeRT2me** [comment]
`AnnotationConsolidationLambdaArn` is required _only if_ `AnnotationConsolidationConfig` is provided. 

`AnnotationConsolidationConfig` itself is not required [API_HumanTaskConfig](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_HumanTaskConfig.html#sagemaker-Type-HumanTaskConfig-AnnotationConsolidationConfig)

Therefore, it is incorrect to say that `AnnotationConsolidationLambdaArn` is required for all labeling jobs. It is now only required for labeling jobs that request Annotation Consolidation.

**Comment by tim-finnigan** [comment]
Thanks for following up and clarifying that. I'll reach out to the SageMaker documentation team about updating the wording, and any updates to the API documentation should be reflected downstream in SDK documentation.

**Comment by tim-finnigan** [comment]
We got confirmation from the SageMaker team that that was removed from the documentation. I confirmed that "This parameter is required for all labeling jobs." was removed from the [service model](https://github.com/boto/botocore/blob/develop/botocore/data/sagemaker/2017-07-24/service-2.json). Thanks again for reporting this issue.
