### ISSUE TITLE
Need support for Servicecatalog waiters createprovisionedproduct and updateprovisionedproduct

### ISSUE THREAD

**Issue by ARUNJIJO** [boto/botocore#3281]
### Describe the feature

Waiters are missing for Servicecatalog in Boto3

### Use Case

Instead of polling the status repeatedly from boto3 to get the status in our application, we would like to use waiters so that we can avoid polling from our end and can have a blocking request.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

boto3 1.35.42

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by tim-finnigan** [comment]
Thanks for the feature request. Waiters are implemented and maintained upstream by service teams, as they are shared across AWS SDKs like boto3. So I'll go ahead and forward this request to the Service Catalog team internally for consideration. 

Are there any particular Waiters that would be most beneficial for your use case? Here are the ServiceCatalog commands for reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/servicecatalog.html.
