### ISSUE TITLE
GetBucketPolicy broken by PR #3276

### ISSUE THREAD

**Issue by odormond** [boto/botocore#3286]
### Describe the bug

Trying to get a bucket policy consistently fails with fake error 500 Internal Server Error.

The issue comes from PR #3276 forcibly trying to parse the body as an XML document and failing as it's a JSON document and then considering it `_looks_like_special_case_error` due to this line: https://github.com/boto/botocore/blob/bab77d87db47c28dfa4329c9b849c5febf3998cc/botocore/handlers.py#L180

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

The bucket policy document is returned successfully.

### Current Behavior

An error is ClientError is raised.

### Reproduction Steps

With adequate permissions, and a bucket with some policy configured, run:
```
aws --debug s3api get-bucket-policy --bucket test-bucket-with-policy
```

### Possible Solution

Don't feed a response body whose header says `Content-Type: application/json` to an XML parser.

### SDK version used

1.35.45

### Environment details (OS name and version, etc.)

Ubuntu 22.04.5 LTS

**Comment by tim-finnigan** [comment]
Thanks for reporting, the team in looking into this issue and will post updates here.

**Comment by tim-finnigan** [comment]
Linking PR including fix: https://github.com/boto/botocore/pull/3288, which should be released soon.

**Comment by mukitmomin** [comment]
@tim-finnigan just confirming, is this fix to be released in `v1.35.46` or the following release? I'm seeing the same error with `botocore=v1.35.46` right now.

**Comment by nateprewitt** [comment]
@mukitmomin the fix for `GetBucketPolicy` should be available in our next release. You can track releases in our [tags](https://github.com/boto/botocore/tags) or via [PyPI](https://pypi.org/project/boto3/#history). We'll also post here once it's available.

**Comment by tim-finnigan** [comment]
@mukitmomin - release 1.35.47 is now out, please [update](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/migrationpy3.html#to-update-the-aws-sdk-for-python) your version of boto3/botocore in order to have access to this fix.
