### ISSUE TITLE
Invalid Link in "DeleteCapacityProvider" Documentation

### ISSUE THREAD

**Issue by YukiMichishita** [boto/botocore#3299]
### Describe the issue

There is an invalid link in the overview section of the "DeleteCapacityProvider" documentation. The link mistakenly refers to a non-existent API, PutCapacityProviderProviders, instead of the correct API, PutClusterCapacityProviders.

### Links

https://github.com/boto/botocore/blob/develop/botocore/data/ecs/2014-11-13/service-2.json#L138

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue. This is a problem with the upstream API documentation: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeleteCapacityProvider.html. The broken links are present there in addition to the SDK documentation. I'll go ahead and reach out to the ECS team about fixing this. For future reference, you can also use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=ECS&topic_url=https://docs.aws.amazon.com/en_us/AmazonECS/latest/APIReference/API_DeleteCapacityProvider.html) links at the bottom of API documentation pages to report issues directly to the appropriate team, and any fixes should get automatically reflected in the SDK documentation.

**Comment by tim-finnigan** [comment]
Closing as the documentation has been fixed — thanks again for reporting this issue.
