### ISSUE TITLE
range() integer end argument expected, got str

### ISSUE THREAD

**Issue by hltbra** [boto/botocore#395]
I found this using aws-cli, and investigating I found out this is a bug in botocore:
* https://github.com/boto/botocore/blob/d4094511f7c5f084133578bb4d5a30befa7ccbe8/botocore/credentials.py#L47
* https://github.com/boto/botocore/blob/42b49b103662048fed22fc9debfbde78e11d5686/botocore/utils.py#L140

This is an easy fix, just apply `int()` to the values that must be integers - `metadata_service_num_attempts` is only one of them.

I just reproduced in my laptop:
```
$ aws ec2 describe-instances

range() integer end argument expected, got str.

$ cat ~/.aws/config
[default]
metadata_service_num_attempts = 10

$ pip freeze | egrep '(aws|boto)'
awscli==1.6.5
botocore==0.76.0
```

**Comment by anthcourtney** [comment]
+1
