### ISSUE TITLE
Changing session profile doesn't change credentials

### ISSUE THREAD

**Issue by garnaat** [boto/botocore#435]
A simple test:

    In [1]: import botocore.session
    In [2]: session = botocore.session.get_session()
    In [4]: session.profile = 'cdn'
    In [5]: session.get_credentials().access_key
    Out[5]: 'AKIATHISISNOTMYACCESSKEY'
    In [7]: session.profile = 'personal'
    In [8]: session.get_credentials().access_key
    Out[8]: 'AKIATHISISNOTMYACCESSKEY'

Basically, the credentials never change regardless of what the profile is set to.  This seems wrong to me.  I can work on a patch but I just wanted to confirm that the correct behavior should be to change the credentials when the profile is changed.  If not, we should probably remove the property setter on the profile attribute.

**Comment by russellballestrini** [comment]
I ran into this same bug.  I'm going to supply my work around so it could help people passerby's in the interim:

*~/.aws/config:*
```
[profile project1]
account_id = 111111111111
aws_access_key_id=THISISNOTMYACCESSKEY1
aws_secret_access_key=THISISNOTMYSECRETKEY1
# Optional, to define default region for this profile.
region=us-west-1

[profile project2]
account_id = 222222222222
aws_access_key_id=THISISNOTMYACCESSKEY2
aws_secret_access_key=THISISNOTMYSECRETKEY2
# Optional, to define default region for this profile.
region=us-west-2
```

Now instead of using a single object, we create multiple objects, one for each profile we intend to use.

```
>>> import botocore.session
>>> session1 = botocore.session.get_session()
>>> session2 = botocore.session.get_session()
>>> session1.profile = 'project1'
>>> session2.profile = 'project2'
>>> session1.get_credentials().access_key
'THISISNOTMYACCESSKEY1'
>>> session2.get_credentials().access_key
'THISISNOTMYACCESSKEY2'
```

Also figured out how to get at the `account_id` integer:

```
>>> session1.get_scoped_config()['account_id']
'111111111111'
```

**Comment by mtdowling** [comment]
A recent update to botocore made it so that `profile` is now read only and must be passed in when constructing a session.

```python
session = botocore.session.Session(profile='my-session')
```

For reference, see https://github.com/boto/botocore/pull/580

Because of this change, I think this issue can now be closed.
