### ISSUE TITLE
s3 delete_bucket fails when bucket is in a region (e.g. eu-west-1)

### ISSUE THREAD

**Issue by Jc2k** [boto/botocore#436]
If I create a bucket in the AWS console in Europe then I cannot use ``delete_bucket``. ``get_bucket_lifecycle`` also fails. Not all calls fail - for example ``get_bucket_location`` is ok. I can also see the bucket in ``list_bucket``.

If I delete the bucket in the AWS console and recreate it in US Standard and repeat the experiment then now it works.

I then switch back to using Europe and it fails again.

The access keys i'm using at the moment are based on the Full Administrator template in the IAM console.

Looking at the debug output from urllib3 I can see it making a request to BUCKETNAME.s3.amazonaws.com, getting a 307 to BUCKETNAME.s3-eu-west-1.amazonaws.com. I then see a connection to that location. It ends with a 403.

With US standard, there is no need for the redirect so it is successful immediately - returning a 204.

In both cases I can see the fix_s3_host handler triggering and updating the URI. This happens before any signing, if that matters.

**Comment by jamesls** [comment]
Could you share some sample code that demonstrates the issue?

**Comment by Jc2k** [comment]
I was testing this in pdb and found that the calls that hit ``BUCKETNAME.s3-eu-west-1.aws.amazon.com`` (after hitting ``BUCKETNAME.s3.aws.amazon.com`` first) would fail. But ``ListBuckets``, ``CreateBucket`` and ``GetBucketLocation`` were all fine. Like wise, by moving to the US Standard zone (avoiding BUCKETNAME.s3-eu-west-1.aws.amazon.com) everything worked, without any ACL/IAM changes.

It was really freaky, and annoyingly it stopped happening before I could explain it. So unless it crops up again I guess this ticket can be closed.

In case it crops up for anyone else: when it was happening the following would have broken.

    import logging
    import botocore.session

    def test_bucket(client, bucket_name, location):
        print client.create_bucket(
            Bucket=bucket_name,
            CreateBucketConfiguration={
                "LocationConstraint": location,
            }
        )

        client.get_waiter("bucket_exists").wait(
            Bucket=bucket_name
        )

        print client.get_bucket_lifecycle(
            Bucket=bucket_name,
        )

        print client.delete_bucket(
            Bucket=bucket_name
        )

    if __name__ == "__main__":
        logging.basicConfig(level=logging.DEBUG)

        session = botocore.session.get_session()
        client = session.create_client("s3", "eu-west-1")

        test_bucket(client, "test123", "eu-west-1")
