### ISSUE TITLE
asyncio

### ISSUE THREAD

**Issue by jab** [boto/botocore#452]
Are there any plans to support asyncio/trollius? Assume not but figured it was worth checking. The aiohttp API is friendly and somewhat similar to requests' (compare http://aiohttp.readthedocs.org/en/v0.14.4/client.html with http://docs.python-requests.org/en/latest/user/quickstart/#make-a-request)

Thanks for the great work on boto.

**Comment by jamesls** [comment]
This is something I am interesting in adding.  We don't have any specific dates, but this is in our backlog of features.  I don't have anything more concrete at this time.  If you have any more info you'd like to share about asyncio support we'd love to hear more.

**Comment by jab** [comment]
Great to hear this is something you're interested in adding. Did you close this because you didn't hear any feedback yet, or because you keep your backlog of to-be-implemented features somewhere else? (I [looked](https://botocore.readthedocs.org/en/latest/search.html?q=roadmap) [around](https://github.com/boto/botocore/wiki/Roadmap) for a Roadmap but didn't see one.)

**Comment by jamesls** [comment]
Sorry, I thought this was just a question about our thoughts on asyncio support.  I don't mind having an open issue that tracks this feature request.   I've gone ahead and created an issue where we can track the status on asyncio support here: https://github.com/boto/botocore/issues/458

Thanks again for reaching out.

**Comment by jab** [comment]
Thanks @jamesls, I'll follow the new issue.
