### ISSUE TITLE
Signature is absent in headers for 

### ISSUE THREAD

**Issue by Andrey-mp** [boto/botocore#454]
I have a set of tests. I wrote it for checking EC2 layer of OpenStack.
I run it against Amazon first and check that all tests are passed.

But botocore with version 0.86 has a strange behavior against Amazon.
First 5-8 tests are passed but all next tests are failed with message
'The request must contain the parameter AWSAccessKeyId (MissingParameter)'.
I checked and found that failed requests didn't have 'Authorization' header.

version 0.85 works well.

**Comment by jamesls** [comment]
Are you still seeing this issue on the latest commit on the `develop` branch?

**Comment by Andrey-mp** [comment]
yes. behavior is the same

**Comment by jamesls** [comment]
Interesting.  We recently upgraded the version of requests we use, and we had to put a specific override in their to ensure the Auth header isn't being removed.  Can you share sample code that demonstrates this issue?

**Comment by Andrey-mp** [comment]
All our tests are here - https://github.com/stackforge/ec2-api/tree/master/ec2api/tests/functional

botocoreclient.py - encapsulates access to botocore library by method name.
base.py - is a base class for all tests
api folder contains tests

tests run against OpenStack can be found here - http://logs.openstack.org/75/154075/11/check/check-functional-neutron-dsvm-ec2api/6d76d59/console.html

run against Amazon is the same except error message.

**Comment by Andrey-mp** [comment]
This is my fail. In second run code worked with cached operation and new service/endpoint.
Fix for my code is here - https://review.openstack.org/#/c/156625/
