### ISSUE TITLE
More retrying for CreateNetworkAclEntry?

### ISSUE THREAD

**Issue by Jc2k** [boto/botocore#482]
It's quite easy to hit RequestLimitExceeded for CreateNetworkAclEntry operations. Can we increase the number of retries please?

**Comment by kyleknap** [comment]
We can look into it. Is it possible if you could give us an example (a set of steps to follow would be great) of how to hit this exception? We do exponential backoff on retries, but we could also look into increasing the sleep time between retries.

**Comment by Jc2k** [comment]
I create 5 or 6 subnets each with a set of network act's. I configure the acl's to all traffic between the subnets. Obviously its stateless not stateful so each rule turns into an inbound and outbound rule in both groups. For the load balancer network acl i limit it to IP's retrieved from the json file that Amazon provides with all the CloudFront IP's in it. This adds up to quite a lot of calls to CreateNetworkAclEntry and it fails 1 in 2 times.

**Comment by rayluo** [comment]
Documenting a recent conversation here. We decide that rather than increase the retry limits globally, a more flexible way is to expose an api for caller to customize the retry limit.

**Comment by 2rs2ts** [comment]
Is there a way to customize the retry limit yet?
