### ISSUE TITLE
pyopenssl + strict handling of bytes

### ISSUE THREAD

**Issue by Jc2k** [boto/botocore#494]
On trusty + python 2.7. Using a virtualenv. If you have pyopenssl+ndg-httpsclient+pyasn1 installed then botocore cannot call change_resource_record_sets. With:

    from botocore.session import get_session
    session = get_session()
    client = session.create_client("route53", "eu-west-1")
    client.change_resource_record_sets(
        HostedZoneId="1111",
        ChangeBatch={
            "Changes": [{"Action": "UPSERT", "ResourceRecordSet": {"Name": "www", "Type": "A"}}],
        },
    )

These are invalid parameters, but valid enough that the parameters are serialized and passed to requests. It looks like they serialize as UTF-8 because then i get:

    Traceback (most recent call last):
      File "example.py", line 10, in <module>
    "Changes": [{"Action": "UPSERT", "ResourceRecordSet": {"Name": "www", "Type": "A"}}],
      File "botocore/client.py", line 315, in _api_call
    operation_model, request_dict)
      File "botocore/endpoint.py", line 110, in make_request
    return self._send_request(request_dict, operation_model)
      File "botocore/endpoint.py", line 156, in _send_request
    success_response, exception):
      File "botocore/endpoint.py", line 207, in _needs_retry
    caught_exception=caught_exception)
      File "botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
      File "botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
      File "botocore/retryhandler.py", line 180, in __call__
    if self._checker(attempts, response, caught_exception):
      File "botocore/retryhandler.py", line 247, in __call__
    caught_exception)
      File "botocore/retryhandler.py", line 262, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
      File "botocore/retryhandler.py", line 310, in __call__
    caught_exception)
      File "botocore/retryhandler.py", line 219, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
      File "botocore/retryhandler.py", line 352, in _check_caught_exception
        raise caught_exception
    TypeError: data must be a byte string

This is actually coming from here: ``OpenSSL/SSL.py(947)send()``.

**Comment by kyleknap** [comment]
We would have to look into it. For the time being, if you really need to make these calls you can try to turning off ssl when you create the client:
```
client = session.create_client("route53", "eu-west-1", use_ssl=False)
```

Let me know if that helps or if you run into any more information that could help.

**Comment by Jc2k** [comment]
I have just removed pyopenssl for the moment, and took a local copy of the cloudfront ip json file.

This patch fixes it, if it's any help:

    diff --git a/botocore/serialize.py b/botocore/serialize.py
    index 961e1b0..644d3c4 100644
    --- a/botocore/serialize.py
    +++ b/botocore/serialize.py
    @@ -516,7 +516,7 @@ class RestXMLSerializer(BaseRestSerializer):
             self._serialize(shape, params, pseudo_root, root_name)
             real_root = list(pseudo_root)[0]
             # TODO: double check on the utf-8 encoding bit.
    -        return ElementTree.tostring(real_root).decode('utf-8')
    +       return ElementTree.tostring(real_root).encode('utf-8')

         def _serialize(self, shape, params, xmlnode, name):
             method = getattr(self, '_serialize_type_%s' % shape.type_name,

As far as I can tell the body of a requests post needs to be bytes, not unicode. `decode` will unfortunately return unicode.

**Comment by danielgtaylor** [comment]
@Jc2k does the above patch fix it when PyOpenSSL is still installed, or does it also require the removal of that package?

**Comment by Jc2k** [comment]
If i take my test case from my first message and get a virtualenv into a state where it is broken (i.e. installing pyopenssl and friends) then applying that patch fixes it.

**Comment by Jc2k** [comment]
The latest release of pyopenssl also fixes this - even so i don't know if its technically more correct to ensure rest-xml bodies are bytes?

**Comment by jamesls** [comment]
Glad to hear you got it working.  I'll go ahead and close this issue.  Please let us know if you have any further questions.
