### ISSUE TITLE
Add DeleteSnapshot member to EC2 DeregisterImageRequest

### ISSUE THREAD

**Issue by acaire** [boto/botocore#508]
Hi, is it possible to please add the ability to delete the root snapshot when [deregistering](https://github.com/boto/botocore/blob/develop/botocore/data/aws/ec2/2014-09-01.normal.json#L3802-3815) an AMI?  Looks like this has been in Boto since https://github.com/boto/boto/commit/09d90d04c72b9f5ceed39fdf44321af181774a57

I'd love to be able to run the following in aws-cli:

```
$ aws ec2 deregister-image --image-id ami-12345678 --delete-snapshot

Unknown options: --delete-snapshot
```

**Comment by jamesls** [comment]
Marking as a feature request.

**Comment by JordonPhillips** [comment]
We try to maintain a 1-1 parity with the service API, and so I don't think we would want to implement something like this as a customization. I would recommend asking EC2 team for this feature on [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=30). If they pick it up, every SDK will benefit from this.
