### ISSUE TITLE
aws ec2 describe-spot-price-history always raises PaginationError without --max-items param

### ISSUE THREAD

**Issue by U-lis** [boto/botocore#533]
Hello. First of all, thanks for all your efforts.

I'm using this library through [aws-cli](https://github.com/aws/aws-cli) on **OS X 10.10.3**, **python 3.4.2** with **awscli 1.7.25** and **botocore 0.106.0**.

I tried aws ec2 describe-spot-price-history api to get spot price history but for any regions/AZs, my command raises PaginationError without *--max-items* param.

Here is my command(I typed **us-east-1a** in AZ, **m3.medium** in type):
```
>>> aws ec2 describe-spot-price-history --start-time 2015-05-08T00:00:00 --end-time 2015-05-08T01:00:00 --availability-zone [any AZ] --instance-types [any type(s) the AZ supports]
```

and this is error message:
```
>>> botocore.exceptions.PaginationError: Error during pagination: The same next token was received twice: ['']
```

When I add `--max-items 1` param, then results are successfully returned with NextToken. 

I found that message is created at paginate.py.

I think amazon returns empty string('') to NextToken when there are no more results to return.

According to [amazon document](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-price-history.html), Next token will be `null` when there are no more results to return but I can't sure that `null` means `None`. That `null` can be empty string? I don't know...

I edited some codes in paginate.py; insert following codes after break at L#111:
```
elif next_token == ['']:
                yield response
                break
```

after that, I could get right results with same command without *--max-items* param.

I'm not sure about more usage of same function(class) so I can't say my work is right, but NextToken with empty string should be handled. In current version, previous_next_token only can handle None.

Please review this issue. Thanks.

**Comment by kyleknap** [comment]
Yeah this issue was ran into last week. It was fixed by this PR: https://github.com/boto/botocore/pull/531. This is in the latest version of botocore and the cli. Try upgrading to v1.7.26 of the CLI and 0.107.0 of botocore.

Let me know how that works for you.

**Comment by U-lis** [comment]
After updating to awscli==1.7.26 and botocore==0.107.0, all my commands worked like charm!

Any command without --max-items param returned as I expected without redundant NextToken(this problem also solved).

Again, thanks for all your works!
