### ISSUE TITLE
Data path not handled correctly on Windows

### ISSUE THREAD

**Issue by garnaat** [boto/botocore#54]
The data search path is constructed using the `__file__` attribute of the base.py module but it doesn't take into account the drive letter on Windows installations.  So, installing on C: and then running while on D: will cause an error:

```
botocore.exceptions.DataNotFoundError: Unable to load data for: cli
```

**Comment by MatthewRalston** [comment]
Hi @garnaat we're having a similar issue in `aws-cli` [#101](https://github.com/aws/aws-cli/issues/101) and [#3258](https://github.com/aws/aws-cli/issues/3258). Would you mind telling me what file this refers to? I can't find a cli.py or cli.json file in either repo, so I'm having trouble describing the issue.
