### ISSUE TITLE
Add proper class names for clients

### ISSUE THREAD

**Issue by jamesls** [boto/botocore#565]
We use the service names when creating class names for clients, which have class names that don't match up with the standard CamelCase conventions used for python classes.

Additionally, this causes issues with documentation, as sphinx won't think this is a proper python class.

An example class name:

```
In [1]: s.create_client('cognito-identity')
Out[1]: <botocore.client.cognito-identity at 0x10718ba50>

In [2]: s3 = _

In [3]: client = s.create_client('cognito-identity')

In [4]: client.__class__.__name__
Out[4]: 'cognito-identity'
```

Ideally, the `client.__class__.__name__` should be `CognitoIdentity`.

**Comment by kyleknap** [comment]
The related PR is now merged. Closing.
