### ISSUE TITLE
botocore 1.0.0 reports being in beta

### ISSUE THREAD

**Issue by vlcinsky** [boto/botocore#586]
On [PyPi botocore packege page](https://pypi.python.org/pypi/botocore) I see version 1.0.0 but the classifiers do report `Development Status :: 4 - Beta`

[Botocore Readthedocs](http://botocore.readthedocs.org/en/latest/tutorial/index.html) it claims:

> Botocore is currently under a developer preview, and its API is subject to change prior to a GA (1.0) release. Until botocore reaches a 1.0 release, backwards compatibility is not guaranteed.

I guess, `botocore` now got out of beta and shall be considered having stable API. If that is true, it would be nice to change the classifier on PyPi to report real development status.

**Comment by jamesls** [comment]
Thanks for reporting.  We'll get that updated.  Looks like we missed removing the dev preview disclaimer from the tutorial doc.

**Comment by jamesls** [comment]
Fixed in #587
