### ISSUE TITLE
Add support for keyring in config file

### ISSUE THREAD

**Issue by garnaat** [boto/botocore#59]
It might be nice to allow the use of keyring (https://pypi.python.org/pypi/keyring) for securely storing credentials, similar to what we did with boto.

**Comment by mtdowling** [comment]
This sounds like a cool idea -- I think that keyring integration with botocore would be great. I agree with what @jamesls said in a [related PR](https://github.com/boto/botocore/pull/72#issuecomment-36897378) though: we want to keep botocore small and allow users to extend it as needed. Now that it's possible to create custom [credential providers](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L251), I could definitely see keyring integration with botocore as a third-party library.
