### ISSUE TITLE
Add AWS_CREDENTIALS_FILE for alternate credentials file location

### ISSUE THREAD

**Issue by freimer** [boto/botocore#599]
The credentials file is hard-coded for ~/.aws/credentials with no environment variable to specify an alternate location.  For many organizations, keeping credentials on an unencrypted volume is not allowed.  Simple one-line change to be in a forthcoming pull request to add this capability.

**Comment by jamesls** [comment]
Linking pull request: https://github.com/boto/botocore/pull/600

**Comment by jamesls** [comment]
Closing out issue.  This was fixed in #623
