### ISSUE TITLE
Mismatch between map keys, documentation, and enum values

### ISSUE THREAD

**Issue by brendanhay** [boto/botocore#602]
This issue arises in a number of service definitions, I'll use SQS as the motivating example.

In the documentation for the [Message](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Message.html) data type, the valid keys in an [`AttributeMap`](https://github.com/boto/botocore/blob/4fb1c05892234de2d6e2bac500e93b2d00df14d9/botocore/data/sqs/2012-11-05/service-2.json#L562) shape form the following set:

* `Policy`
* `VisibilityTimeout`
* `MaximumMessageSize`
* `MessageRetentionPeriod`
* `ApproximateNumberOfMessages`
* `ApproximateNumberOfMessagesNotVisible`
* `CreatedTimestamp`
* `LastModifiedTimestamp`
* `QueueArn`
* `ApproximateNumberOfMessagesDelayed`
* `DelaySeconds`
* `ReceiveMessageWaitTimeSeconds`
* `RedrivePolicy`

These keys are reflected in the SQS [service definition](https://github.com/boto/botocore/blob/4fb1c05892234de2d6e2bac500e93b2d00df14d9/botocore/data/sqs/2012-11-05/service-2.json#L1167-L1180) for the `QueueAttributeName` enumeration.

If you look at the sample response for the [ReceiveMessage](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) operation, it utilises keys that are not in the above set.

Question:

* Is the `ReceiveMessage` operation documentation wrong in the sample response
* Is the `Message` type documentation and service definition wrong WRT the use of `QueueAttributeName` for attribute keys?

**Comment by mtdowling** [comment]
Thanks for reporting. I see that there is a discrepancy here between the docs itself and between the docs and the model. We'll investigate the see why several items are missing from the enum list or perhaps if these attributes are somehow modeled incorrectly.

**Comment by JordonPhillips** [comment]
Sorry for the long delay on this, but the fix has been committed upstream and will work its way into one of the next releases.

**Comment by brendanhay** [comment]
:+1:
