### ISSUE TITLE
S3 Expires attribute fails when passed a datetime

### ISSUE THREAD

**Issue by oiez** [boto/botocore#603]
First, the documentation: Expires (datetime) -- The date and time at which the object is no longer cacheable.

If you set Expires=datetime.datetime.now() (or any datetime object) it fails with an AttributeError.

For example:

import boto3
import datetime

YOUR_BUCKET_HERE = ""
TEST_FILENAME = ""
s3 = boto3.resource('s3')
expire_time = datetime.datetime.now() + datetime.timedelta(minutes=5)
s3.Object(YOUR_BUCKET_HERE, TEST_FILENAME).put(Body=open(TEST_FILENAME, 'rb'), Expires=expire_time)

Fails with an AttributeError, specifically from lib/python3.4/site-packages/botocore/utils.py", line 318, in parse_timestamp (should have a check to see if the value is already a datetime object and return if it is instead of trying to parse it again).

Giving it an int/float timestamp works, but it still doesn't set an actual expire time on S3. I am not sure if this is related to the original bug.

**Comment by jamesls** [comment]
Thanks for reporting.

**Comment by stevenbrichards** [comment]
I can't reproduce this anymore with the latest boto3

**Comment by JordonPhillips** [comment]
Also cannot reproduce, tested on 2.6.9, 2.7.10, 3.3.6, and 3.4.3

**Comment by JordonPhillips** [comment]
Also cannot reproduce in python 2.6, 2.7, 3.3, and 3.4 using latest boto3 and botocore
