### ISSUE TITLE
API Gateway not supported

### ISSUE THREAD

**Issue by graham** [boto/botocore#607]
I can't seem to figure out how to add http://docs.aws.amazon.com/apigateway/api-reference/ to botocore. Do the service-2.json files need to be created manually?

(if so, i'm happy to do it, I'm just trying to figure out how to add an APIGateway client)

Is it as simple as adding a 'apigateway' directory to 'data' and then creating the appropriate service-2.json?

**Comment by graham** [comment]
Realized I should probably tag: @mtdowling

After a couple hours of learning how the service-2.json files work I was able to create: https://gist.github.com/graham/f8491b05d1bdd28b5ca8

But I worry I'm still doing things wrong. If this is a manual process, I'll just manually create the service.json file. If I'm going the wrong way, just let me know. (learned a ton about boto!)

**Comment by mtdowling** [comment]
Amazon API Gateway is not currently supported in botocore because it utilizes HAL (a format that is not yet supported). As for the models, we use an AWS internal tool to generate the service-2.json models, so there's typically no need to try to create one manually. We'll update this issue when we have more information.

**Comment by graham** [comment]
Cool, thank you!

**Comment by brendanhay** [comment]
Is it possible to obtain the HAL formatted API Gateway definition/model separately from botocore?

**Comment by joshuadfranklin** [comment]
Currently, API Gateway only has this Java [aws-apigateway-importer](https://github.com/awslabs/aws-apigateway-importer).

I captured the current API Gateway HAL JSON file by running the importer with [full http wire logging](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-logging.html):
https://gist.github.com/joshuadfranklin/b0be14cc47e2c930b28c

For the HAL to be useful you'd need to also implement AWS Signature Version 4 (aws4):
http://docs.aws.amazon.com/apigateway/api-reference/signing-requests/

**Comment by JordonPhillips** [comment]
API Gateway is supported as of today's release (1.3.1)
