### ISSUE TITLE
Connection pool is full, discarding connection

### ISSUE THREAD

**Issue by code-tree** [boto/botocore#619]
I'm getting a massive amount of these exceptions while trying to retrieve S3 logs, as I'm retrieving each object in separate threads.

`WARNING:botocore.vendored.requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: bucket.s3.amazonaws.com`

Should I be closing connections after using them? Or is this in boto's hands?

thanks

**Comment by jamesls** [comment]
Should not have to manually close any connections, botocore should be handling this for you.  If you have sample code the demonstrates the issue I'd be happy to investigate further.

**Comment by code-tree** [comment]
Hi James, thanks for helping

I'm trying to retrieve (and then delete) all logs present in an S3 bucket, in the fastest possible way. I'm retrieving them all in separate threads, so that it doesn't wait for one request to complete before starting another. I wrote the code in a bit of a rush, and just now noticed that all threads are using the same client object, which might be the reason for the above exceptions.

I'm not aware of how botocore internals work. Does a client object reuse connections? / Avoid repeat TLS setup?

What is the most efficient way to fetch multiple objects?

thanks,
Jon

```
def fetch_logs(bucket):
    s3 = boto3.client('s3')

    # Retrieve list of object keys for logs
    objects = s3.list_objects(Bucket=bucket, Prefix='logs/')
    if 'Contents' not in objects:
        return
    objects = [obj['Key'] for obj in objects['Contents']]
    
    # Start processing objects
    threads = []
    for key in objects:
        threads.append(Thread(target=_fetch_log, args=[s3, bucket, key]))
        threads[-1].start()
    
    # Wait till all objects processed
    for thread in threads:
        thread.join()


def _fetch_log(s3, bucket, key):
    body = s3.get_object(Bucket=bucket, Key=key)['Body'].read().decode('utf-8')
    process...
    s3.delete_object(Bucket=bucket, Key=key)
```

**Comment by JordonPhillips** [comment]
I'm having trouble reproducing this issue. Using the code as you have it, I don't run into it. I modified it to run on more than 1000 objects at a time and ran into a `RuntimeError` rather than a connection pool. I'm gonna try with bigger objects to see if that does anything, but in the meantime could tell me approximately the size and number of objects you're looking at?

Also, just to note, `list_objects` returns a max of 1000 objects at a time.

**Comment by JordonPhillips** [comment]
This issue is being closed due to inactivity

**Comment by codemang** [comment]
I'm having the same issue when writing to DynamoDB using 20 connections/threads. Any suggestions on debugging/fixing it?

**Comment by code-tree** [comment]
Not sure, sorry, haven't had the time to investigate further. Though it doesn't seem to break anything for my app. I wonder if it is affecting network efficiency though.

**Comment by codemang** [comment]
Yes the network calls complete eventually but I'm experiencing delays of up to 10 minutes for a program that should take ~1 minute.

**Comment by odinplus** [comment]
Got this on my experiments with Celery + eventlet + DynamoDB.
Celery worker:

**Comment by synhershko** [comment]
@JordonPhillips this happens for me as well with boto3, I can share the code that's causing it while trying to download several hundred of files from S3 - or is this a known issue now?

**Comment by synhershko** [comment]
Please also see related discussion: https://github.com/boto/boto3/issues/268#issuecomment-199759246

**Comment by christophlingg** [comment]
This one can happen if the number of threads that create a http connection is higher than the default connection pool size of botocore. which is 10.

https://github.com/boto/botocore/issues/766

**Comment by farshidz** [comment]
Is the connection pool shared between sessions? I'm creating a session per thread (because resources and clients are not thread safe, see http://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading). But I'm still getting this message

**Comment by srikiraju** [comment]
Wondering the same thing, as @farshidz is this connection pool a process singleton?

**Comment by oscargws** [comment]
I'm having the same issue when trying to send bulk emails out with SES

**Comment by JustinTArthur** [comment]
Same with Lambda.

**Comment by oscargws** [comment]
Not sure what your use case is @JustinTArthur, but I was able to fix this problem in my situation. I was attempting to send requests to SES with a Lambda and after about 1000ish emails sent on different threads I'd get the connection pool error. For some reason, new threads kept being made and weren't being discarded. 

What fixed it was changing how I instantiated my ThreadPoolExecutor from this: 
`with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:`

to this: 
`with concurrent.futures.ThreadPoolExecutor(4) as executor:`

And also making sure that I wasn't going over my maximum send rate for AWS.

**Comment by matse004** [comment]
> Same with Lambda.

Same with SQS

**Comment by JustinTArthur** [comment]
This warning is fine. If you dig into the urllib3 connection pool code, it's basically the pool of persistent connections and not the maximum number of concurrent connections you can have. The connections in the pool are re-used if they haven't been closed by the endpoint.

If you'd like to boost the size of this pool, it can be done per-endpoint using the low level botocore config. boto3 example:
```python
client_config = botocore.config.Config(
    max_pool_connections=25,
)
boto3.client('lambda', region_name=region, config=client_config)
```

Botocore Config Documentation:
https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

**Comment by myselfdesai** [comment]
Solution here .. use new feature max_pool_connections 
`s3_client = boto3.client('s3', config=botocore.client.Config(max_pool_connections=50))`

**Comment by JuanAntonio03** [comment]
I am having the same issue with a package that use boto3 for reading parquets when they are in S3.
Why doesn't the `max pool connections` parameter appear in the docs so I can set it from a config file or environment variable?

**Comment by ricardofunke** [comment]
The max_pool_connection config doesn't work for me, I keep seeying the message:
"[WARNING]	{...} Connection pool is full, discarding connection: archive.org. Connection pool size: 10"

My config:
`import boto3
from botocore.config import Config

client_config = Config(
    max_pool_connections=20,
)
dynamodb = boto3.resource('dynamodb',
                          region_name='us-west-2',
                          config=client_config)`

**Comment by bkyryliuk** [comment]
> The max_pool_connection config doesn't work for me, I keep seeying the message:
> 
> > [WARNING]	{...} Connection pool is full, discarding connection: {...}. Connection pool size: 10
> 
> My config:
> 
> ```
> import boto3
> from botocore.config import Config
> 
> client_config = Config(
>     max_pool_connections=20,
> )
> dynamodb = boto3.resource('dynamodb',
>                           region_name='us-west-2',
>                           config=client_config)
> ```

+1 - I am experiencing the same issue

**Comment by malanEvans** [comment]
> The max_pool_connection config doesn't work for me, I keep seeying the message:
> 
> > [WARNING]	{...} Connection pool is full, discarding connection: {...}. Connection pool size: 10
> 
> My config:
> 
> ```
> import boto3
> from botocore.config import Config
> 
> client_config = Config(
>     max_pool_connections=20,
> )
> dynamodb = boto3.resource('dynamodb',
>                           region_name='us-west-2',
>                           config=client_config)
> ```

I have the same issue

**Comment by crojasqnextroll** [comment]
> > The max_pool_connection config doesn't work for me, I keep seeying the message:
> > > [WARNING]	{...} Connection pool is full, discarding connection: {...}. Connection pool size: 10
> > 
> > 
> > My config:
> > ```
> > import boto3
> > from botocore.config import Config
> > 
> > client_config = Config(
> >     max_pool_connections=20,
> > )
> > dynamodb = boto3.resource('dynamodb',
> >                           region_name='us-west-2',
> >                           config=client_config)
> > ```
> 
> I have the same issue

You might need to use boto3.client instead.

**Comment by enote-kane** [comment]
@crojasqnextroll is correct.

For the record, here are the official docs:
1. Create a configuration object (param `max_pool_connections`): https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html
2. Get a resource (suply configuration object in param `config`): https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.resource
