### ISSUE TITLE
LaunchConfigurationName erroneously marked as required for AutoScalingGroup and Instance shapes

### ISSUE THREAD

**Issue by brendanhay** [boto/botocore#629]
For `AutoScalingGroup`, the set of [required fields](https://github.com/boto/botocore/blob/0269685f34eaa7a2d982ba7cefea7b8ac7551a60/botocore/data/autoscaling/2011-01-01/service-2.json#L1583) includes `LaunchConfigurationName`, likewise for `Instance`s [required fields](https://github.com/boto/botocore/blob/0269685f34eaa7a2d982ba7cefea7b8ac7551a60/botocore/data/autoscaling/2011-01-01/service-2.json#L2606).

Both of these types are only referred to by the `DescribeAutoScalingGroups` operation which can return results without a `LaunchConfigurationName` due to termination state and configuration deletion.

The scenario is as follows:

- Create a `LaunchConfiguration`
- Create an `AutoScalingGroup` with the above launch configuration and a number of instances
- Delete the `AutoScalingGroup` ( goes into a terminate state while instances are shut down )
- Delete the `LaunchConfiguration` ( this is only possible when not attached to an active ASG ) 
- Call `DescribeAutoScalingGroups` 
 
The `AutoScalingGroup` in the terminating state is returned, but as the `LaunchConfiguration` has been deleted it is not included in the response for both the group and any `Instance`s belonging to that group.

Should `LaunchConfigurationName` not exist in the `"required": [...]` set for both `AutoScalingGroup` and `Instance`?

**Comment by rayluo** [comment]
Thanks. We will check this and get back to you later.

**Comment by JordonPhillips** [comment]
This has been fixed upstream and should be available in the next release (after 1.8.13, the change was made too late to make it in this one).

**Comment by brendanhay** [comment]
:+1:
