### ISSUE TITLE
Downgrading rsa package

### ISSUE THREAD

**Issue by orome** [boto/botocore#644]
The botocore install or update (`pip install -U botocore`) is downgrading rsa (to 3.1.4).

**Comment by mtdowling** [comment]
Can you provide the output? We don't have a dependency on rss, so this seems strange.

**Comment by orome** [comment]
Sorry: rs**a** (the title is correct but the comment got autocorrected)

**Comment by mtdowling** [comment]
Are you using the CLI? Botocore does not have a dependency on rsa, but the CLI does: https://github.com/aws/aws-cli/blob/develop/requirements.txt#L12. We could look at updating to the latest version or rsa, but that might require a bit of time to vet it.

**Comment by orome** [comment]
Yes, both `awscli` and `awsebcli`.

**Comment by orome** [comment]
[Opened on awscli.](https://github.com/aws/aws-cli/issues/1498)

**Comment by jamesls** [comment]
Closing in preference to aws/aws-cli#1498
