### ISSUE TITLE
conflicting requirements on jmespath between botocore and boto3

### ISSUE THREAD

**Issue by jvehent** [boto/botocore#660]
While installing boto3 via pip on a fresh centos7 box today, I noticed the following incompatible requirements:

```bash
$ sudo pip install -U botocore
Collecting jmespath==0.7.1 (from botocore)
  Using cached jmespath-0.7.1-py2.py3-none-any.whl

$ sudo pip install -U boto3
Collecting jmespath<1.0.0,>=0.6.2 (from boto3)
  Using cached jmespath-0.8.0-py2.py3-none-any.whl
```
Installing boto3 alone will install jmespath-0.8.0 which is incompatible with botocore. But botocore and boto3 seem to work fine with jmespath-0.7.1.

**Comment by kyleknap** [comment]
Thanks for reporting. This was reported in https://github.com/boto/botocore/issues/656. We fixed this yesterday with these PRs https://github.com/boto/botocore/pull/658 and https://github.com/boto/boto3/pull/272. Will be available in the next release of botocore and boto3. Closing issue.
