### ISSUE TITLE
Recent commit breaks --profile functionality in 1.2.5.

### ISSUE THREAD

**Issue by paulysullivan** [boto/botocore#663]
Commit 3c09b00e6593bb565edfa4d214b8362d6dd9cebb breaks the --profile overriding ENV functionality which was recently introduced in revision 1.2.5.

Once line 70 of botocore/credentials.py is adjusted to `if session.profile is None:`, everything continues to function as expected.

I'd submit a PR, but I'm unsure how this breaks your test cases.

Thanks.

**Comment by jamesls** [comment]
Taking a look...
