### ISSUE TITLE
botocore 1.8.10 breaks lambda add-permission

### ISSUE THREAD

**Issue by lewisd32** [boto/botocore#678]
Running:
`aws lambda add-permission --function-name <arn> --region us-east-1 --statement-id Test --action "lambda:InvokeFunction" --principal s3.amazonaws.com --source-arn arn:aws:s3:::<bucketname> --source-account <accountId>`

With awscli 1.8.11 and botocore 1.2.9 works, but with awscli 1.8.12 and botocore 1.2.10 it gives the following error:
`A client error (AccessDeniedException) occurred when calling the AddPermission operation: Unable to determine service/operation name to be authorized`

EDIT: correcting botocore versions.

**Comment by rayluo** [comment]
I believe you mean "... botocore 1.2.9 ... botocore 1.2.10 ...". This issue looks very similar to another we are investigating. Just a quick question, do you happen to have your another lambda setup on region us-west-2? If yes, I guess that one may work.

**Comment by lewisd32** [comment]
You're correct about the versions.  I updated them in the issue here.  Thanks.
We only currently have these lambdas in us-east-1, due to the various restrictions about lambdas being in the same region as S3 buckets.

**Comment by rayluo** [comment]
Hi @lewisd32 would you mind to have a quick test again?  The [similar issue](https://github.com/boto/boto3/issues/294) I mentioned earlier has already been fixed. Let's see whether it makes a difference for your case.

**Comment by jamesls** [comment]
Looks like this has been fixed.  Let us know if you're still seeing issues and we can reopen this issue.

**Comment by lewisd32** [comment]
It appears to work now, after I upgraded again to awscli 1.8.12 and botocore 1.2.10. I see from the similar issue you mentioned that it was service side, not in the client libraries.  Thanks for the help!
