### ISSUE TITLE
Credentials files are only read once and are never reread

### ISSUE THREAD

**Issue by DenverJ** [boto/botocore#704]
We require short term credentials to be used for all API calls. As an easy way to deal with this, we have been writing credentials to a credentials file continually every X minutes and relying on the default search order for finding credentials. That way, we don't have to write any specific authentication code inside the app.

This worked with boto because every time credentials were required, boto went and read from the credentials file. However with boto3/botocore the credentials are only read when the session is created. When the credentials expire boto3/botocore continues to try to use them and we see a RequestExpired error.

Can we make the Credentials object a proxy object to read from file each time they are needed for file credentials?

P.S. I think the same issue exists for environment variables as well although they are less likely to be used in this manner.

**Comment by JordonPhillips** [comment]
Reading the credentials file every time a call is made would incur unreasonable (and likely unexpected by the average user) I/O cost. Overwriting the config file was the only way to do things in legacy boto, but there are APIs for that now. You would need to create your own [CredentialProvider](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L232) and insert it in the provider chain. Your provider would then return [RefreshableCredentials](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L127) that handles the logic of updating when necessary. This would avoid the need to overwrite the credentials file by allowing you to insert the refresh logic in your code. Once you have your credential provider, you would add it to the credential resolver like so:

```python
from botocore.session import Session

# Create a botocore session with your custom credential provider
custom_credential_provider = CustomCredentialProvider()
botocore_session = Session()
credential_resolver = botocore_session.get_component('credential_provider')
credential_resolver.insert_before('config', custom_credential_provider)

# Create a new boto3 session with your botocore session
dev = boto3.session.Session(botocore_session=botocore_session)

# Configure the default session with your botocore session
boto3.setup_default_session(botocore_session=botocore_session)
```

Now your credential provider has been inserted into that session's provider chain before it searches the config file.

You could also inherit from the botocore session and overwrite the `get_credentials` to never cache the credentials, but that's inadvisable.

Let me know if you have any other questions.

**Comment by DenverJ** [comment]
Yep, I have done exactly that and abstracted it away. It works great and for our home-grown apps it's not a problem. But as mentioned, the goal for this is to be able to use open source projects etc that expect to find credentials in the usual places. With the new shared credentials location it also allows us to use one way to provide credentials for apps written in languages other than python. 

Reading from the credentials file every time was the simplest solution but below are some other suggestions that still employ caching.
* Write expiration time to credentials file and use that to auto-refresh
* Refresh credentials every 60 seconds.
* Refresh credentials as part of request retry

I'm happy to raise a PR if we can find an approach that would be acceptable.

**Comment by JordonPhillips** [comment]
The shared credentials file is just not meant to change in run-time. Among the credential provider chain, the only provider that is intended to change is the EC2 instance metadata provider. This is standard amongst all the SDKs that we support.

May I ask what your use case is?

**Comment by DenverJ** [comment]
One example use case for us is running Security Monkey (https://github.com/Netflix/security_monkey). It expects to use an instance role for credentials but our organisation doesn't currently allow using roles due to the maintenance overheard of creating/maintaining/securing for hundreds of users/applications. So we were using credentials file instead. 

The problem is made worse due to the way that the default session is cached... Security Monkey uses APScheduler to run 'watchers' every 15 minutes. So new threads are spinning up and calling boto3.resource('ec2') but they are getting the already cached session with the expired credentials. In this case if the credentials were reread (or the session wasn't cached) when the boto3 resource or client was instantiated everything would work.

**Comment by maresb** [comment]
While it appears that periodically updating the credentials file is not considered a best practice, it is [exactly what the AWS Cloud9 service does](https://docs.aws.amazon.com/cloud9/latest/user-guide/how-cloud9-with-iam.html#auth-and-access-control-temporary-managed-credentials). (The credentials update every 5 minutes and expire after 15 minutes.) This makes it seemingly impossible to perform long-running operations with boto on S3 without writing my own credential manager.

**Comment by maresb** [comment]
By the way, I went ahead and [wrote my own credential manager](https://gist.github.com/maresb/69a3f4e1f4b1765388994a91309af99c).

Example usage:
```python
import boto3
from managed_temporary_credentials_provider import ManagedTempCredentialsProvider

mtcp = ManagedTempCredentialsProvider()

mtcp.register_default()
s3 = boto3.resource("s3")  # Now the credentials will automatically refresh.

s3 = mtcp.boto3_session.resource("s3")  # Effectively the same as before, but more explicit.
```

Many thanks to @JordonPhillips for all the hints above.

**Comment by kdaily** [comment]
Hi all, I can understand how it could be useful to reload parts of the credential/config files if it is scoped to authentication related things (access key, secret key, token). If other parts of the configuration could be reloaded, it would surely cause many hard to debug errors. As noted above (and demonstrated by @maresb) writing your own credential provider is a viable solution. 

However, implementing this is not something that will be addressed solely in the Python SDK - it needs AWS SDK-wide adoption to have a consistent experience. I am going to close this issue here and re-open one at [`aws/aws-sdk`](https://github.com/aws/aws-sdk/) to raise visibility across the AWS SDKs, link it to the other relevant issues, and raise it with the SDK team for further discussion.

Thanks again!

**Comment by kdaily** [comment]
I opened an issue to track this for AWS SDKs here: https://github.com/aws/aws-sdk/issues/107
