### ISSUE TITLE
Missing support for RDS API's DescribeDBSnapshotAttributes and ModifyDBSnapshotAttribute

### ISSUE THREAD

**Issue by aronrosenberg** [boto/botocore#716]
The API's described at http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBSnapshotAttribute.html and http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBSnapshotAttributes.html are missing from the RDS implementation.

**Comment by rayluo** [comment]
Duplicated to boto/boto3#357 (although in fact the implementation will be shipped in botocore here)

**Comment by rayluo** [comment]
It is now released in latest botocore 1.3.7
