### ISSUE TITLE
missing lots of paginators

### ISSUE THREAD

**Issue by kapilt** [boto/botocore#733]
ec2 describe images, kms list grants, etc. the golang sdk has all of these.

**Comment by kapilt** [comment]
is there a canonical location for these json api files or a defined update policy for these? at the moment they seem to be haphazard strewn around in botocore, boto3, and other language sdks.

**Comment by JordonPhillips** [comment]
Thanks for letting us know, it looks like we missed the KMS paginators. We'll make sure to pull them in in our next release. In the case of describe images, that particular operation does not actually expose a pagination interface. Some SDKs (javascript and php for example) will expose a pagination-like interface for some of these operations even though there is no pagination going on. The python SDK does not do that.

**Comment by JordonPhillips** [comment]
The KMS paginators will be out in today's release, so I'm going to go ahead and close out this issue. I'll also check to see if there are any others we're missing.
