### ISSUE TITLE
improve docs for CloudWatchLogs client's filter_log_events parameters

### ISSUE THREAD

**Issue by jstewmon** [boto/botocore#739]
I know that the client docs are generated from upstream sources, but the [boto docs](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html) for `startTime` and `endTime` say that the expected value is a unix timestamp (implies seconds). But the API docs say:
> A point in time expressed as the number of milliseconds since Jan 1, 1970 00:00:00 UTC

If the SDK is supposed to accept seconds, then I guess this would be a bug, but I presume the SDK is supposed to accept milliseconds, in which case the docs should match the API docs.

**Comment by rayluo** [comment]
So the [API docs](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html) and the [botocore docs](http://botocore.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events) (which is generated from the former) both mention the time will be a number of milliseconds. Is it not the case?

And which "boto docs" were you referring to? You happened to give a wrong url in your question. :-)  Let us know if we can help.

**Comment by jstewmon** [comment]
Sorry about that - I meant to link to the botocore docs and quote the api docs.

At the time of filing, the boto3 and botocore docs had:
> startTime (integer) -- A unix timestamp indicating the start time of the range for the request. If provided, events with a timestamp prior to this time will not be returned.

> endTime (integer) -- A unix timestamp indicating the end time of the range for the request. If provided, events with a timestamp later than this time will not be returned.

I spent a few hours troubleshooting my boto3 requests which were using unix timestamps before checking the API docs.

Can you say anything more about the lifecycle of the docs? Is there a regular lag between the API docs and boto docs? Are boto docs only republished when new versions of botocore/boto3 are released?

**Comment by rayluo** [comment]
> At the time of filing, the boto3 and botocore docs had:

Can you provide the exact url for the doc you were quoting? I checked [botocore docs](http://botocore.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events) and [boto3 docs](http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events) but can not find the content you quoted. What I saw is the doc properly mentions "milliseconds".

**Comment by jstewmon** [comment]
There's a snapshot in the WayBack Machine:
https://web.archive.org/web/20150911072105/http://boto3.readthedocs.org/en/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events

**Comment by JordonPhillips** [comment]
There is sometimes a lag between service docs updating and our docs updating, usually it isn't too long. Our docs update shortly after every commit, with service updates usually only occurring during releases. I'm sorry that this lag has caused you pain.

Since the docs seem to be in order now, I'm going to close out this issue.
