### ISSUE TITLE
Should StreamingBody proxy underlying stream attributes?

### ISSUE THREAD

**Issue by dwieeb** [boto/botocore#749]
When wrapping a raw stream, which is exactly what `botocore.response.StreamingBody` does, it would be nice to have more access to the raw stream. 

My specific use case is calling `stream.seek(0)`. 

Basically, I don't think `StreamingBody` fulfills the ABC of `io.IOBase` in the standard library (https://docs.python.org/3.4/library/io.html#io.IOBase) and it should fully implement it. The easiest way to do that is to proxy attributes down to the raw stream, like how werkzeug does it for its `FileStorage` class (http://werkzeug.pocoo.org/docs/0.11/datastructures/#werkzeug.datastructures.FileStorage).

**Comment by JordonPhillips** [comment]
You can't call `seek` on a socket, once it's read it's gone. I'm not familiar with Werkzueg, but do they perhaps buffer the stream for you? That seems to me to be the only way to be able to seek back to the beginning.

As for the rest of `io.IOBase`, I don't see much value in subclassing it when we would just throw `OSError` for every method besides `read` and `close`.

**Comment by dwieeb** [comment]
Yes, sorry. Werkzeug has the file in entirety and can therefore seek.

**Comment by dwieeb** [comment]
Just wanted to thank the developers. boto 3 is such a vast improvement on an already fantastic library. 

Cheers :beers:
