### ISSUE TITLE
Updates required for Lambda create_function(), Runtime parameter

### ISSUE THREAD

**Issue by charleswhchan** [boto/botocore#754]
In the example for [create_function()](http://boto3.readthedocs.org/en/latest/reference/services/lambda.html#Lambda.Client.create_function):

```
response = client.create_function(
    ...
    Runtime='nodejs'|'java8'|'python2.7',
```

But in the Runtime description:
> Runtime (string) --
> [REQUIRED]
> 
> The runtime environment for the Lambda function you are uploading. Currently, Lambda supports "java" and "nodejs" as the runtime.

- Python is missing
- Conflicting information for "java" or "java8"

**Comment by JordonPhillips** [comment]
Thanks for reporting! It looks like the changes have been made upstream, and so should be out the next time lambda does a release. I'll see if I can get them to push out the docs earlier, but for now I'm going to close out this issue since the fix is in the release pipeline.

**Comment by charleswhchan** [comment]
Thanks @JordonPhillips!
