### ISSUE TITLE
Problems with Python 3.5

### ISSUE THREAD

**Issue by Fale** [boto/botocore#755]
Trying to execute the tests in Fedora Rawhide I receive the following result: http://koji.fedoraproject.org/koji/taskinfo?taskID=12518858
(you can find in the build.log the tests failing, while in the root.log all the packages that have been installed).
Could it be some problems with Python 3.5?

**Comment by JordonPhillips** [comment]
We [test](https://travis-ci.org/boto/botocore) against 3.5, so I don't think that's the issue. I think it's a problem with your build script. It doesn't have, for instance, `mock` installed.

**Comment by Fale** [comment]
I'm not sure about this, since the whole build has been built inside mock, as you can see in the [root](https://kojipkgs.fedoraproject.org//work/tasks/8858/12518858/root.log) log

**Comment by Fale** [comment]
I've tried a new build forcing the installation of all the packages listed in the require.txt and this is the [result](http://koji.fedoraproject.org/koji/taskinfo?taskID=12519685)

**Comment by JordonPhillips** [comment]
Looks like it might have something to do with the default test runner, though I'm not sure why. If you switch the test runner to nose I think your problems might go away, though I'm curious why this is happening.

```sh
$ pyenv virtualenv 3.5.0 testEnv # Create Python 3.5 virtual environment
$ workon testEnv # Switch to the newly created environment
(testEnv) $ git clone https://github.com/boto/botocore.git bctest
(testEnv) $ cd bctest
(testenv) $ pip install -e .
(testenv) $ nosetests tests/unit

Ran 1624 tests in 4.832s
OK

(testEnv) $ python setup.py test -m tests/

running test
running egg_info
writing top-level names to botocore.egg-info/top_level.txt
writing requirements to botocore.egg-info/requires.txt
writing botocore.egg-info/PKG-INFO
writing dependency_links to botocore.egg-info/dependency_links.txt
reading manifest file 'botocore.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/build'
writing manifest file 'botocore.egg-info/SOURCES.txt'
running build_ext
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/Users/phjordon/.pyenv/versions/3.5.0/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/phjordon/workspace/test/bctest/tests/__init__.py", line 16, in <module>
    import mock
ImportError: No module named 'mock'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by JordonPhillips** [comment]
I'm going to go ahead and close this with the recommendation that you use nose to run the tests, which is the method we officially support.
