### ISSUE TITLE
Paginator breaks with NextMarker for "aws s3 ls" (non-recursive)

### ISSUE THREAD

**Issue by boivie** [boto/botocore#762]
Hi,
There is an issue with the `aws s3 ls` command when key names contains non-alphanumeric
characters. The issue only occurs when the number of results exceeds the page size value. 
Here's an example:
```
aws s3 ls s3://some-bucket/test/yearmonth=201601/
2016-01-19 12:10:42          0 file1
2016-01-19 12:10:46          0 file2
2016-01-19 12:10:49          0 file3
```
If we set the --page-size value to be less than the number of files then the following error occurs:
```
aws s3 --page-size=2 ls s3://some-bucket/test/yearmonth=201601/
2016-01-19 12:10:42          0 file1
2016-01-19 12:10:46          0 file2
2016-01-19 12:10:42          0 file1
2016-01-19 12:10:46          0 file2
Error during pagination: The same next token was received twice: ['test/yearmonth%3D201601/file2']
```
Note, listing files with the --recursive flag works fine.
```
aws s3 ls --page-size 2 --recursive s3://some-bucket/test/yearmonth=201601/
2016-01-19 12:10:42          0 test/yearmonth=201601/file1
2016-01-19 12:10:46          0 test/yearmonth=201601/file2
2016-01-19 12:10:49          0 test/yearmonth=201601/file3
```

The problem seems to be that the results for "aws s3 ls" (without recursive) gives the marker in "NextMarker" for the first response, and it's returned urlencoded (`=` becomes `%3D`) by the s3 service. The paginator will then specify that value (still urlencoded) as "Marker" for the following request. The S3 service expects it to be decoded (unquoted) (`%3D` becomes `=`).

One way to solve this - which may not be correct at all, is to modify `data/s3/2006-03-01/service-2.json`:
```
diff --git a/data/s3/2006-03-01/service-2.json b/data/s3/2006-03-01/service-2.json
index c3227f9..22972c5 100644
--- a/data/s3/2006-03-01/service-2.json
+++ b/data/s3/2006-03-01/service-2.json
@@ -3100,6 +3100,7 @@
         "Marker":{"shape":"Marker"},
         "NextMarker":{
           "shape":"NextMarker",
+          "location":"querystring",
           "documentation":"When response is truncated (the IsTruncated element value in the response is true), you can use the key name in this field as marker in the subsequent request to get next set of objects. Amazon S3 lists objects in alphabetical order Note: This element is returned only if you have delimiter request parameter specified. If response does not include the NextMaker and it is truncated, you can use the value of the last Key in the response as the marker in the subsequent request to get the next set of object keys."
         },
         "Contents":{"shape":"ObjectList"},
```

With the added line, "aws s3 ls" works as expected.

Please advice - is this the correct solution?

**Comment by mtdowling** [comment]
Interesting. I was able to reproduce this. I'll take a look and see I can determine what's going on.

**Comment by mtdowling** [comment]
I've identified the issue and have submitted a pull request to botocore to address it: https://github.com/boto/botocore/pull/765. I'll update this issue when that has been merged.

**Comment by mtdowling** [comment]
Thanks again for reporting. This has been fixed in https://github.com/boto/botocore/issues/765 and will be present in the next release of the AWS CLI.
