### ISSUE TITLE
CloudFormation client - Tags parameter failing validation

### ISSUE THREAD

**Issue by justinwatkinson** [boto/botocore#768]
Looking at the boto3 documentation, it appears that tagging of CloudFormation stacks should be possible through the create_stack or update_stack client functions. 

When I attempt to create a stack via boto3, it's throwing the following botocore error.

botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Tags", must be one of: StackName, TemplateBody, TemplateURL, UsePreviousTemplate, StackPolicyDuringUpdateBody, StackPolicyDuringUpdateURL, Parameters, Capabilities, ResourceTypes, StackPolicyBody, StackPolicyURL, NotificationARNs

The syntax all looks correct and I'm using the majority of the other properties without issue.  Confirmed in the stable/final and confirmed that boto3 version is 1.2.3 (matches doc) and botocore is 1.3.22.  Currently running this from a Windows host, in case that matters.

Let me know if you need any additional information.

**Comment by mtdowling** [comment]
I was able to specify tags using the following (you'd need to provide a working TemplateBody):

```python
cf.create_stack(StackName='foo', Tags=[{"Key": "a", "Value": "b"}, {"Key": "c", "Value": "d"}], TemplateBody='{}')
```

This is also show in the documentation: http://botocore.readthedocs.org/en/latest/reference/services/cloudformation.html#CloudFormation.Client.create_stack

Does using this type of format work for you?

**Comment by justinwatkinson** [comment]
I just tried it again and it looks like this issue is actually limited to the update_stack operation.  I took the exact "Tags" argument you provided and created a stack no problem.  I copied the same values to the update_stack operation in the same script and that's when I'm reproducing the error.

**Comment by mtdowling** [comment]
Ah I see. CloudFormation only supports `Tags` on `create_stack`. Updating the tags of a stack using `update_stack` is not currently part of their API. See: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html

**Comment by jszwedko** [comment]
@mtdowling I'm not sure if the API was updated recently, but updating the tags as part of `UpdateStack` is supported (you can see it on the link you posted).

**Comment by jszwedko** [comment]
Never mind, I see it was already updated: https://github.com/boto/botocore/blob/07422f03901f4bb30aaa8ec1e18f24628262c63b/botocore/data/cloudformation/2010-05-15/service-2.json#L377-L380
