### ISSUE TITLE
Strange behavior from the CloudFormation list_stack_resources paginator

### ISSUE THREAD

**Issue by copumpkin** [boto/botocore#771]
I'm on botocore 1.3.20.

Let's say I have a stack with two IAM role resources in it, called `mystack`. Now:

```python
# client is a pre-existing cloudformation client

paginator = client.get_paginator('list_stack_resources')
for resource in paginator.paginate(StackName='mystack'):
    print resource
```

This gives me

```python
{ 'ResponseMetadata': { ... },
  u'StackResourceSummaries': [
     { u'ResourceType': 'AWS::IAM::Role', 
       u'PhysicalResourceId': 'blah-woof-1J5RE8ALSU88Q',
       u'LastUpdatedTimestamp': datetime.datetime(2016, 1, 26, 19, 46, 39, 862000, tzinfo=tzutc()),
       u'ResourceStatus': 'UPDATE_COMPLETE',
       u'LogicalResourceId': 'woof'},
     { u'ResourceType': 'AWS::IAM::Role',
       u'PhysicalResourceId': 'blah-meow-V0LLYH4CX82S',
       u'LastUpdatedTimestamp': datetime.datetime(2016, 1, 26, 19, 23, 32, 985000, tzinfo=tzutc()),
       u'ResourceStatus': 'CREATE_COMPLETE',
       u'LogicalResourceId': 'meow'}
   ]}
```

Note that I'm getting a single dict back from the paginator iterator, and that dict itself contains two resources that the paginator seems unaware of. My understanding is that the paginator is supposed to handle this for me, right?

**Comment by JordonPhillips** [comment]
@copumpkin No, the paginator gives you *pages* of results. Try setting the `PageSize` to 1, it should give you two pages of results.

**Comment by copumpkin** [comment]
Ohh, I had misunderstood how it was supposed to work. I see now that I was wrong. So if I just want a flat iterator of all items, is there a canonical way to get that? If I look at the paginator JSON, it seems to know which attribute to be looking for inside the returned dict, so it seems like botocore might know how to flatten it for me.

**Comment by copumpkin** [comment]
Either way, it's not a real issue, but still curious.

**Comment by JordonPhillips** [comment]
@copumpkin You can get iterators via resource collections, though that isn't available for every service.

**Comment by JordonPhillips** [comment]
CloudFormation does have a resource model, so it would look like this:

```python
import boto3

cf = boto3.resource('cloudformation')
stack = cf.Stack('name')

for resource in stack.resource_summaries.all():
    print(resource.logical_id)
```

**Comment by copumpkin** [comment]
Oh that's nice but I'm reluctant to bring in the boto3 dependency for that, when I'm using just botocore everywhere else. Good to know in future though, thanks!
