### ISSUE TITLE
Add ability to alias arguments

### ISSUE THREAD

**Issue by kyleknap** [boto/botocore#772]
We need the ability to rename and alias arguments, like we do in the CLI. Here are some examples of where this would be nice or is actually needed:
https://github.com/boto/boto3/issues/463
https://github.com/boto/boto3/issues/456

Furthermore, it would be cool if these aliases can be become aliases for parameters in the CLI.

**Comment by jamesls** [comment]
Another request for this, this time from a CLI customer.

How would we actually do this?  Just have the shape object from the model be marked with some new deprecated flag?  That way the doc gen has something to determine if it should be documented or not?

**Comment by kyleknap** [comment]
That is what I am thinking. I am not sure if we could do something clever and manipulate the runtime model such that we add the new member for ``filters`` that is a copy of the ``filter`` and add a flag that means the ``filter`` member is deprecated so docs handle that appropriately as well.

**Comment by jamesls** [comment]
What would `.members` return from the struct shape?  Should it include both `filter` and `filters` in the return dict?

Thinking through that, this would require all downstream consumers to change their code to filter out deprecated members, i.e the AWS CLI, AWS Shell, etc.

**Comment by kyleknap** [comment]
I am just throwing out ideas. Have not thought about it too much. I think ``.members`` would still be a structure shape. The undocumented part would just be somehow added as a member trait. And the members structure would include both members.

Ideally, I would want to just rename the ``filter`` member in the model at runtime and add a handler to make ``Filter`` an alias for ``Filters`` but CLI cannot do that because it generates its arguments from the model and I do not think we can easily alias this in the CLI other than taking advantage of the argparse "feature" of auto-completing if you type an argument that does not exist and is a subset one that does exist, it will fill it out for you. But that is a bit hacky...

**Comment by jamesls** [comment]
Another idea (also thinking out loud):

Have `.members` return a dict that includes *only* non-deprecated members.  This represents the "ideal" case that customers, tools should use going forward.  For example, the AWS Shell wouldn't autocomplete both `--filter` and `--filters` and would work without any changes.

Add a new property `.all_members` or some other better name that included all members, including aliased, deprecated members.

Update our internal code (param validator, request serializer) to use the new `.all_members`.

That way most downstream tooling wouldn't have to change, though the CLI would probably need to use `.all_members` so it could tell argparse about the deprecated feature.

**Comment by kyleknap** [comment]
Yeah I think that should work. I know documentation would work right off the bat in botocore/boto3. The CLI would probably have to be able to determine if there are ``members`` missing from ``all_members`` in order to undocument them, but that's not hard.

Whatever we decide on I feel like an ideal solution would require the least amount of handlers across all of our projects.

**Comment by quiver** [comment]
My colleague ran into boto/boto3#456 this week.
+1 for this feature.

**Comment by kyleknap** [comment]
Including this issue in as well: https://github.com/boto/boto3/issues/404
