### ISSUE TITLE
Add an EC2 waiter for VPC peering connections

### ISSUE THREAD

**Issue by copumpkin** [boto/botocore#781]
Sometimes when you initiate a peering connection, it takes a few moments to appear (especially across accounts), so you want to wait before calling accept on the other side. It seems like it would be fairly easy to add a waiter for`DescribeVpcPeeringConnections`, right?

**Comment by kyleknap** [comment]
It looks like it should not be difficult to implement especially since all of the states are enumerated here: https://github.com/boto/botocore/blob/develop/botocore/data/ec2/2015-10-01/service-2.json#L16074. It just may take a bit of time to test it out to make sure all of the state logic is correct. Feel free to give a crack at an implementation if you need them relatively soon. Otherwise, we will look into adding them eventually.

**Comment by copumpkin** [comment]
Thanks! By "state logic", do you mean the fact that "active" and "pending-acceptance" are two states one might want to wait for, and that they might pass through "initiating-request" or "provisioning" before getting there (the others are probably all failures)?

**Comment by kyleknap** [comment]
Yeah pretty much just figuring out what states are the final failure states, what are the final success states, and what are the transition states. So for example, I could see the ``failed`` or ``rejected`` state as being defined as failure states in the waiter and ``active`` as the success state in the waiter if the purpose of the waiter is to wait for the peering connection to be active.

**Comment by copumpkin** [comment]
Cool. It looks like [this page](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-peering.html) has a good diagram and explanation of the various states. If I get some time, I'll try to throw together a PR, or leave this up here in case someone else comes across it and is feeling generous :smile: 

![Peering lifecycle](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/images/peering-lifecycle-diagram.png)

**Comment by kyleknap** [comment]
Awesome. Thanks!

**Comment by copumpkin** [comment]
It looks like there's now a waiter for [VPC peering connections existing](http://botocore.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Waiter.VpcPeeringConnectionExists), but not for it to be in the accepted state.

**Comment by copumpkin** [comment]
As far as I understand, that waiter will wait for the peering connection to exist, but mere existence isn’t very useful for networking, where you want the connection to have been accepted by the other side as well as simply existing. Does that make sense?
