### ISSUE TITLE
Add automatic url encoding to more S3 operations

### ISSUE THREAD

**Issue by mtdowling** [boto/botocore#782]
We recently adding the ability to set automatic "url" to ListObjects, but we also need to add it for ListObjectVersions and ListMultipartUploads
- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETVersion.html
- http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListMPUpload.html

**Comment by mtdowling** [comment]
This is similar to https://github.com/boto/boto/pull/2948

**Comment by kyleknap** [comment]
Going over older issues. This is now half-implemented. We added this logic to the [ListObjectsVersions](https://github.com/boto/botocore/blob/783b96d3cf72ab9cb1cec2e6d534c010c77a49bd/botocore/handlers.py#L946-L951) but have yet to do it for `ListMultipartUploads`.
