### ISSUE TITLE
Handling of x-amz-date in HmacV1Auth

### ISSUE THREAD

**Issue by lopuhin** [boto/botocore#786]
According to the spec http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html, section "Time Stamp Requirement", and "Example delete" below, it should be possible to override ``date`` header with ``x-amz-date``, and in this case ``x-amz-date`` should not be included into the string to sign. ``boto`` does handle this correctly, but ``botocore`` includes both date value and ``x-amz-date`` header into string to sign:
```
DELETE


Tue, 27 Mar 2007 21:20:26 +0000
x-amz-date:Tue, 27 Mar 2007 21:20:26 +0000
/johnsmith/photos/puppy.jpg
```

Is it intended? This is not something affecting me, just noticed it while porting tests from ``boto`` to ``botocore``.

**Comment by JordonPhillips** [comment]
The section of documentation you linked pertains specifically to generating pre-signed S3 posts, not general signing. In the pre-signed case, the date *header* is not signed, but `x-amz-date` is included as part of the policy, which is signed.

That said, it shouldn't be including both `x-amz-date` and `Date`. Could you provide a code snippet to replicate that output?

**Comment by lopuhin** [comment]
Thanks for the clarification!
This is what I meant - both dates are included here:

```
$ python test_s3_sign.py 
DEBUG:botocore.auth:Calculating signature using hmacv1 auth.
DEBUG:botocore.auth:HTTP request method: GET
DEBUG:botocore.auth:StringToSign:
GET


Tue, 16 Feb 2016 06:05:20 GMT
x-amz-date:Tue, 27 Mar 2007 21:20:26 +0000
/bucket/path
```

And here is the code:
```
import logging
logging.basicConfig(level=logging.DEBUG)

import botocore.auth
import botocore.credentials
import botocore.awsrequest

# keys from AWS examples
AWS_ACCESS_KEY_ID = '0PN5J17HBGZHT7JJ3X82'
AWS_SECRET_ACCESS_KEY = 'uV3F3YluFJax1cknvbcGwgjvx4QpvB+leU8dUj2o'

SignerCls = botocore.auth.AUTH_TYPE_MAPS['s3']
signer = SignerCls(botocore.credentials.Credentials(
    AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY))

awsrequest = botocore.awsrequest.AWSRequest(
    method='GET',
    url='http://s3.amazonaws.com/bucket/path',
    headers={'x-amz-date': 'Tue, 27 Mar 2007 21:20:26 +0000'})
signer.add_auth(awsrequest)
```

**Comment by JordonPhillips** [comment]
Ah, I see. `x-amz-date` exists for clients where the `Date` header cannot be set. We *are* able to set the `Date` header, so we don't attempt to use `x-amz-date`. We could account for it in the signer, but since the `auth`, `signer`, and `awsrequest` packages are not intended to be used outside of botocore, it would probably not be user modifiable. We only support function calls from within the client interface.

**Comment by lopuhin** [comment]
I see, thanks!
Btw, what interface would you recommend to use for external libraries what are making requests to S3 themselves (for example, in scrapy we currently use twisted), and are using botocore just to calculate the correct signature?
