### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by nchammas** [boto/botocore#788]
Is there a change log that calls out the significant changes in each release?

All I see are the files under [development](https://github.com/boto/botocore/tree/develop/docs/source/development), but they haven't been updated in a while.

**Comment by JordonPhillips** [comment]
There is not, at least not on botocore. The changelog for the CLI covers botocore as well (they used to be much more tightly coupled), but I think in the future we really should have one here.

**Comment by nchammas** [comment]
:+1:

It would be good for those of us who like to review the change log when we upgrade our dependencies.

**Comment by JordonPhillips** [comment]
As of yesterday's release, I've added a changelog. We may at some point back-fill from the CLI changelog, but for now you should be able to see what's new.

**Comment by nchammas** [comment]
Thank you.
