### ISSUE TITLE
Update documentation link in services-2.json for CloudFormation

### ISSUE THREAD

**Issue by brint** [boto/botocore#800]
Per this contribution guideline:

> We may choose not to accept pull requests that change the JSON service descriptions, such as botocore/data/aws/s3/2006-03-01/service-2.json. We generate these files upstream based on our internal knowledge of the AWS services. If there is something incorrect with or missing from a service description, it may be more appropriate to submit an issue so we can get the issue fixed upstream. This constraint only applies to the */service-2.json files.

The link http://docs.aws.amazon.com/documentation/ was introduced in commit f35e49d203889f90fead6f5ad5c0e653b54f4634. This link doesn't point to the right place for CloudFormation docs.

Here's the exact line:
https://github.com/boto/botocore/commit/f35e49d203889f90fead6f5ad5c0e653b54f4634#diff-c9eb8f09352c1c8a08ff7298a8462a03R1486

**Comment by JordonPhillips** [comment]
Thanks for letting us know! I've raised an issue with the service team.
