### ISSUE TITLE
Random ('Connection aborted.', BadStatusLine("''",)) Errors

### ISSUE THREAD

**Issue by alexphelps** [boto/botocore#816]
I'm getting random  ('Connection aborted.', BadStatusLine("''",)) from BotoCore that I really dont understand and dont know how to reproduce. I get about 5 of these errors per day with an app hosted on AWS that has really low traffic. My setup is ELB --> EC2 (Nginx/uWsgi/Django) --> RDS and DynamoDB.

I'm using [PynamoDB](https://github.com/jlafon/PynamoDB) to interface with DynamoDB which uses Botocore.

Anyone have any ideas what could cause this?

```
Traceback:
File "/home/www/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)
File "/home/www/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py" in wrapper
  499.                 return wrapped(*args, **kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py" in wrapper
  872.             return wrapped(*args, **kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)
File "./trackers/views.py" in get
  1085.             if not TrackerSessions.exists():
File "/home/www/venv/local/lib/python2.7/site-packages/pynamodb/models.py" in exists
  640.             cls._get_connection().describe_table()
File "/home/www/venv/local/lib/python2.7/site-packages/pynamodb/connection/table.py" in describe_table
  181.         return self.connection.describe_table(self.table_name)
File "/home/www/venv/local/lib/python2.7/site-packages/pynamodb/connection/base.py" in describe_table
  463.         tbl = self.get_meta_table(table_name, refresh=True)
File "/home/www/venv/local/lib/python2.7/site-packages/pynamodb/connection/base.py" in get_meta_table
  309.                 data = self.dispatch(DESCRIBE_TABLE, operation_kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/pynamodb/connection/base.py" in dispatch
  217.         data = self._make_api_call(operation_name, operation_kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/pynamodb/connection/base.py" in _make_api_call
  238.         response = self.requests_session.send(prepared_request)
File "/home/www/venv/local/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py" in send
  573.         r = adapter.send(request, **kwargs)
File "/home/www/venv/local/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py" in send
  415.             raise ConnectionError(err, request=request)
Exception Type: ConnectionError at /trackers/api/94240981abf74bdf85dfd99f8b3dc3eb/callback/
Exception Value: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by kyleknap** [comment]
What version of botocore are you using with PynamoDB? We have seen this issue in the past, but have not got reports of it recently so it may be fixed in the latest version of botocore.

**Comment by alexphelps** [comment]
Here is a full pip freeze list. Looks like boto==2.39.0, botocore==1.3.29, and pynamodb==1.4.4

```
Babel==2.2.0
Delorean==0.6.0
Django==1.9.1
Pillow==2.9.0
YURL==0.13
argparse==1.2.1
boto==2.39.0
botocore==1.3.29
cffi==1.5.2
click==6.3
coverage==4.0.3
cryptography==1.2.2
cssselect==0.9.1
cssutils==1.0.1
decorator==4.0.9
dj-stripe==0.8.0
django-appconf==1.0.1
django-braces==1.8.1
django-debug-toolbar==1.4
django-imagekit==3.3
django-model-utils==2.4
django-phonenumber-filter==1.0.0
django-storages==1.4
docopt==0.4.0
docutils==0.12
enum34==1.1.2
geocoder==1.8.2
geoip2==2.2.0
httplib2==0.9.2
humanize==0.5.1
idna==2.0
ipaddr==2.1.11
ipaddress==1.0.16
jmespath==0.9.0
jsonfield==1.0.3
lxml==3.5.0
mailchimp==2.0.9
maxminddb==1.2.0
ndg-httpsclient==0.3.1
newrelic==2.60.0.46
phonenumbers==7.2.5
pilkit==1.1.13
premailer==2.9.7
psycopg2==2.6.1
pyOpenSSL==0.15.1
pyasn1==0.1.9
pycparser==2.14
pynamodb==1.4.4
python-dateutil==2.4.2
pytz==2015.7
ratelim==0.1.6
requests==2.7.0
six==1.10.0
sqlparse==0.1.18
stripe==1.29.1
timezones==1.9.6
twilio==5.3.0
tzlocal==1.2
wheel==0.29.0
wsgiref==0.1.2
```

**Comment by kyleknap** [comment]
Thanks! We will look into this then and see if we can figure anything out.

**Comment by Lifto** [comment]
I have this too, pretty regularly. I have an Elastic Beanstalk worker that gets this when accessing a certain table. It is intermittent. PynamoDB 1.4.4, boto 2.39.0, botocore 1.4.7

**Comment by Jc2k** [comment]
I used to get this (see #470) - we seem to pretty reliably have connection issues if we have `PyOpenSSL`/`ndg-httpsclient`/`pyasn1` installed. @Lifto can you confirm if you have them installed in your app?

**Comment by Lifto** [comment]
@Jc2k I don't have that installed. Here's my virtualenv.
aniso8601==1.1.0
awscli==1.10.32
awsebcli==3.7.6
Babel==2.3.4
blessed==1.9.5
boto==2.39.0
botocore==1.4.22
cement==2.8.2
colorama==0.3.3
contextlib2==0.5.1
datadog==0.11.0
decorator==4.0.9
Delorean==0.6.0
docker-py==1.7.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.12
Flask==0.10.1
Flask-RESTful==0.3.5
flask-restplus==0.9.0
functools32==3.2.3.post2
futures==3.0.5
humanize==0.5.1
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.0
jsonschema==2.5.1
MarkupSafe==0.23
onctuous==0.5.84
ordereddict==1.1
pathspec==0.3.4
Pillow==2.9.0
psycopg2==2.6.1
pyasn1==0.1.9
pynamodb==1.4.4
python-dateutil==2.5.3
pytz==2016.4
PyYAML==3.11
raven==5.11.1
requests==2.9.1
rsa==3.3
s3transfer==0.0.1
semantic-version==2.5.0
simplejson==3.8.2
six==1.10.0
statsd==3.2.1
texttable==0.8.4
time-uuid==0.1.1
tzlocal==1.2.2
voluptuous==0.8.9
wcwidth==0.1.6
websocket-client==0.37.0
Werkzeug==0.11.5

**Comment by JordonPhillips** [comment]
We've made a few changes to address these sorts of issues, particularly with regards to pyopenssl. Is anybody still seeing this issue on the latest versions?
