### ISSUE TITLE
Applying sigv4 to requests to URLs wtih a path containing '.' or '..' can fail

### ISSUE THREAD

**Issue by migtor** [boto/botocore#838]
This happens if `.` or `..` are at the beginning of a path segment: they get stripped out, but that's correct only if the whole path segment is `.` or `..`.

For example, generating a signature for a request to `https://service.amazonaws.com/path/.somepath/` would be rejected by the services, because when the path is normalised, it gets converted to `/path/somepath/`.

See pull request: #827

**Comment by jamesls** [comment]
Closing, PR #827 was merged which fixes this issue.
