### ISSUE TITLE
Amazon Inspector API change

### ISSUE THREAD

**Issue by joewing** [boto/botocore#843]
The Amazon Inspector API has been updated and it appears that botocore (as of 1.4.4) still provides the old API, which no longer works.  Are there plans to update this?  The documentation is here:
http://docs.aws.amazon.com/inspector/latest/APIReference/Welcome.html

**Comment by JordonPhillips** [comment]
Thanks for letting us know, I'll let the service team know the old api version isn't being routed correctly and get the updates pushed out ASAP.

**Comment by mjschultz** [comment]
This is affecting us too, any tips on how to get the boto API calls to match the new version of the Amazon API?

**Comment by Raybuster** [comment]
I found this forum post on how to adjust the CLI to the new API: https://forums.aws.amazon.com/thread.jspa?threadID=227591

I think there may be a way to update boto using the model file linked from that post

**Comment by rayluo** [comment]
@Raybuster The workaround mentioned from your forum link is very likely also effective for botocore. Did you try that?

**Comment by JordonPhillips** [comment]
We have updated the Inspector api to the latest version, sorry for the delay.
