### ISSUE TITLE
Intermittent WSAECONNABORTED when uploading file to s3

### ISSUE THREAD

**Issue by pandours** [boto/botocore#844]
Hi,

When uploading large files (using **multipart** upload) to s3 under **windows 7** using boto3, I am intermittently getting **WSAECONNABORTED** errors. 

The exception that is raised is **OpenSSL.SSL.SysCallError** (with the message: 10053, 'WSAECONNABORTED).

My understanding is that botocore does not retry uploading the failing part when this exception is raised because this exception is not part of the _retryable_exceptions collection, member of MaxAttemptsDecorator, filed up from the EXCEPTION_MAP collection (**retryhandler.py**) and is thus only caught by boto3 in transfer.py when it is already too late. At that time, **S3UploadFailedError** is raised. At this point, the only options are to catch the exception and start the upload over or not use the high level API offered by boto3.

I am posting here because it appears that handling this in the boto3 layer would be too late.

Please find below a snippet of code to reproduce the issue that allows me to consistently reproduce the issue (the file I upload is around 150MB):

```
import boto3

# Please initialize the following variables with the proper values.
region_name = ''
aws_access_key_id = ''
aws_secret_access_key = ''
local_file_pathname = ''
bucket_name = ''
s3_key = ''

client = boto3.client(
    service_name='s3',
    region_name=region_name,
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key
)

config = boto3.s3.transfer.TransferConfig(
    multipart_threshold=8 * 1024 * 1024,
    max_concurrency=20
)

transfer = boto3.s3.transfer.S3Transfer(client, config)
for i in range(1, 25):
    transfer.upload_file(
        local_file_pathname,
        bucket_name,
        s3_key)

```

Note: Centos7 boxes on the same network do not exhibit the problem.

Thank you for your time,

Best regards,
Alexis

**Comment by JordonPhillips** [comment]
What version of boto3 are you using?

**Comment by pandours** [comment]
Hi,

I just reproduced it with:
 boto3-1.3.0 and botocore-1.4.6

Thanks,
Alexis

**Comment by jamesls** [comment]
I believe this issue is resolved.  I'm going to go ahead and close this issue out.  The traceback's you were getting were coming from the optional pyopenssl extensions, which we now disable in botocore.  As a result, you shouldn't be seeing those errors anymore.

Let me know if you're still seeing issues and we'll reopen and take another look.
