### ISSUE TITLE
Documentation that contains hyperlinks with different URLs but the same description text all render as the same URL

### ISSUE THREAD

**Issue by gene1wood** [boto/botocore#863]
Despite the fact that the service definitions (for example the [SES service definition](https://github.com/boto/botocore/blob/develop/botocore/data/ses/2010-12-01/service-2.json)) contain documentation strings with links where the link name is the same and the URLs are different, those documentation strings render through Sphinx all with the same URL.

Here's an example

In the [SES service definition](https://github.com/boto/botocore/blob/develop/botocore/data/ses/2010-12-01/service-2.json), the [documentation string for the `CloneReceiptRuleSet` method](https://github.com/boto/botocore/blob/0d5aa67fa8e2b38312aa3b87f0783a47c2a4d274/botocore/data/ses/2010-12-01/service-2.json#L30) contains this content

```
"<p>Creates a receipt rule set by cloning an existing one. All receipt rules and configurations are copied to the new receipt rule set and are completely independent of the source rule set.</p> <p>For information about setting up rule sets, see the <a href=\"http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-receipt-rule-set.html\">Amazon SES Developer Guide</a>.</p> <p>This action is throttled at one request per second.</p>"
```

Where the link for `Amazon SES Developer Guide` points to the url http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-receipt-rule-set.html

However, when you go and look at the [Sphinx rendered documentation](http://boto3.readthedocs.org/en/latest/reference/services/ses.html#SES.Client.clone_receipt_rule_set) for the `CloneReceiptRuleSet` method, the resulting link doesn't point to http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-receipt-rule-set.html but instead to http://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim-dns-records.html

All links on the page that have a link name of `Amazon SES Developer Guide` point to http://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim-dns-records.html despite the fact that throughout the documentation strings in the service definition, the `Amazon SES Developer Guide` links point to many different URLs.

**Comment by jamesls** [comment]
Thanks for letting us know.  Looks like a bug in our doc generation process.  We're assuming that the link keys are unique.  In the raw rst we have:

```
    For information about setting up receipt rule sets, see the `Amazon SES Developer Guide`_ .
```

and then elsewhere in the document:

```
.. _Amazon SES Developer Guide: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim-dns-records.html
```

We keep a map of `link title -> href`, which doesn't work when the same link text is used for multiple links.

We'll get this updated.
