### ISSUE TITLE
Exponential backoff timeout?

### ISSUE THREAD

**Issue by sidewinder12s** [boto/botocore#864]
I am using boto3/botocore in AWS Lambda to perform some management tasks against the AWS API. I was noticing that some of my lambda functions would timeout when I started hammering the API and was getting throttled. It appeared that Boto3 was using it's exponential backoff logic as intended. What I am trying to figure out is if there is any kind of timeout logic to the exponential backoff logic. It appears that there is a maxRetries option available, but other than that is Boto3/botocore's default behavior to keep retrying the API with exponential backoff until AWS returns a 503/RequestLimitExceeded error or succeeds?

I am trying to figure out a good balance for my Lambda timeout time between letting Boto retry and not having my lambda run for 5 minutes.

**Comment by jamesls** [comment]
>  other than that is Boto3/botocore's default behavior to keep retrying the API with exponential backoff until AWS returns a 503/RequestLimitExceeded error or succeeds?

The default behavior is to retry until we the request succeeds or until max_retries is set (https://github.com/boto/botocore/blob/develop/botocore/data/_retry.json#L61-L67).

I don't have any guidance in general about finding a good balance between lambda timeout times and boto3 retries.  I suspect finding a good balance would be highly dependent on the specific task you're trying to accomplish.

Let us know if we can answer any other questions.

**Comment by sidewinder12s** [comment]
Thanks, that was primarily what I was looking to find out. Can't really think of a use case where I would want a "timeout" option from Boto, but with Lambda available where runtime matters someone might have a use case for it.
