### ISSUE TITLE
Incorrect detection signature version for S3 request

### ISSUE THREAD

**Issue by Andrey-mp** [boto/botocore#865]
botocore version: 1.4.8

request:
aws s3 --endpoint-url http://192.168.137.21:8080 --profile user mb s3://ttt --region RegionOne

answer:
make_bucket failed: s3://ttt/ A client error (InvalidRequest) occurred when calling the CreateBucket operation: Missing required header for this request: x-amz-content-sha256

In my opinion it happens becasue used signature version is not 's3v4'.
(I have another test wher I set signature version explicitly for this URL and this call works)

**Comment by jamesls** [comment]
Can you give us more information about 191.168.137.21:8080?  Is that a proxy or an S3 compatible alternative?  By default, botocore does not use signature version 4 for S3 unless the region *only* supports signature version 4 (such as eu-central-1).  This check is based on the metadata for a region (for example: https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L685-L690).  If your using a region that's not specified in that file you'll either need to explicitly set the signature version as you're doing or override the `endpoints.json` file.

**Comment by Andrey-mp** [comment]
192.168.137.21:8080 is a S3 compatible server based on OpenStack solution.
I found that if I pass region parameter to awscli then it uses v4 signature. and it uses v2 without region param.
In my client code I can pass config with signature version (s3v4) to Session.create_client method for right choosing but I don't know how to do it with awscli...

**Comment by JordonPhillips** [comment]
@Andrey-mp To use signature version 4 in the CLI you'll need to set `signature_version` to `s3v4` in your configuration file: http://docs.aws.amazon.com/cli/latest/topic/s3-faq.html
