### ISSUE TITLE
fix_s3_hosts always assumes you're using central aws instead of a local S3.

### ISSUE THREAD

**Issue by IainSteers** [boto/botocore#875]
I've noticed when attempting to generate presigned urls that the logic behind fix_s3_hosts and the virtual styling always assumes you're using AWS S3. [fix_s3_host](https://github.com/boto/botocore/blob/6065566237de957507fc63ae4d3a034c87552adf/botocore/utils.py#L649)

However, we have a local s3 api on top of ceph, as such it throws away our local s3 endpoint and substitutes s3.amazonaws.com, although the presigned urls work when you switch out the virtual path for our local s3, it's a pain.

This is because the default_endpoint_url passed to [switch_to_virtual_host_style](https://github.com/boto/botocore/blob/6065566237de957507fc63ae4d3a034c87552adf/botocore/utils.py#L656) is always set to 's3.amazonaws.com'

The request object is available in the fix_s3_host function so it should be a fairly simple fix.

**Comment by kyleknap** [comment]
This is something we would like to change. We just need to make sure we account for all of the potential edge cases in removing this.
