### ISSUE TITLE
AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by satyrius** [boto/botocore#893]
I've faced I strange thing while using `awscli`: having a user with keys and configured permissions, but getting an error while

```bash
aws ec2 describe-instances --region eu-central-1 --debug
```

```xml
<Response>
  <Errors>
    <Error>
      <Code>AuthFailure</Code>
      <Message>AWS was not able to validate the provided access credentials</Message>
    </Error>
  </Errors>
  <RequestID>3b660143-6e90-4739-a501-2ace577bcb0a</RequestID>
</Response>
```

I is not working when credentials are in ~/.aws/credentials not in environment. My keys was

```
[REDACTED]
```

It has a percent sign at the end, and I think it is a problem. I created another key (without special chars) and everything start working.

P.S. I found this bug using `awscli`, but I think it is `boto` issue.
```
CLI version: aws-cli/1.10.19 Python/2.7.10 Darwin/15.4.0 botocore/1.4.10
```

**Comment by JordonPhillips** [comment]
I think I may know what the issue is. Did you copy credentials downloaded from the console using `cat` to print them onto the terminal? That CSV doesn't have an empty line at the end of the file, so `cat` will print a `%` to show that.

**Comment by satyrius** [comment]
I cant remember how it was copied. You could close the issue if it's clear in boto. Thanks!
