### ISSUE TITLE
boto3 not using Connection: Keep-Alive

### ISSUE THREAD

**Issue by benh57** [boto/botocore#902]
We use boto3 against a local Ceph S3 sever and i noticed it's not sending Connection: Keep-Alive

We are uploading like so:

- Is there an option in boto to do this? Either via injecting a custom header, or method?

```          
 session = boto3.session.Session(aws_access_key_id=parsed_args.s3_auth_key, aws_secret_access_key=parsed_args.s3_auth_secret)
             client = session.client('s3',
                                     endpoint_url='http://{}:{}'.format(parsed_args.s3server, 80),
                                     config=botocore.client.Config(s3={'addressing_style': 'path'}))
             transfer = boto3.s3.transfer.S3Transfer(client, config=boto3.s3.transfer.TransferConfig(max_concurrency=8))
         except Exception as e:
             logging.exception('Failed to connect to the S3 server %s [%s]: %s', parsed_args.s3server, parsed_args.s3bucket, e)
             return None
         try:
             progress = ProgressPercentage(parsed_args.filename, self)
             transfer.upload_file(parsed_args.filename, bucket=parsed_args.s3bucket, key=package_name, extra_args={'ACL': 'public-read'}, callback=progress)
             progress.complete_message()
```

**Comment by jamesls** [comment]
The most straightforward way to inject a custom header would be to use the event system in botocore.  Something like:
```
def inject_header(params, **kwargs):
    params['headers']['Custom-Header'] = 'Some-Value'


session.events.register('before-call.s3', inject_header)
```

The above is saying that before every s3 call, the `inject_header` function will be called and passed the request dictionary (which contains a `headers` key you can add to).

Let us know if you run into any issues.

**Comment by benh57** [comment]
Thanks! We'll try that out.

**Comment by benh57** [comment]
Seems to work great, but i'm not sure why you wouldn't want to have this on by default.

**Comment by kevin1024** [comment]
Also curious about this, using connection keepalive is a big performance boost when uploading a lot of files.

**Comment by peterbe** [comment]
@jamesls Can you re-open this issue? It seems you answered the immediate concern with a "hack" but the real issue is, why is not on by default or an option to the `Session` object.

**Comment by karthikvadla** [comment]
@jamesls @benh57 No luck for me. Still keeps on creating new HTTPS connections
I did as below.

  session = boto3.session.Session()
  session.events.register('before-call.s3', inject_header)
  conn = session.resource('s3')
  #assume i'm getting bucket.
 bucket.upload_file(filename, key_name)

def inject_header(params, **kwargs):
    params['headers']['Connection'] = 'Keep-Alive'

Still i cannot re-use the same connection. It keeps on creating pool on new connections. 
Can you please tell me am i passing the headers correctly?

Thanks 
Karthik

**Comment by boarik** [comment]
Any update on this one?
