### ISSUE TITLE
better to add the route53 request limits in _retry.json

### ISSUE THREAD

**Issue by henrysher** [boto/botocore#91]
better to add route53 request limits here:
https://github.com/boto/botocore/blob/develop/botocore/data/aws/_retry.json

Details can be found in the issue #1618  in boto:
https://github.com/boto/boto/issues/1618

**Comment by mtdowling** [comment]
Is this still an issue in botocore? Can you send a PR?

**Comment by rayluo** [comment]
The "accepted" and "closing soon if no response" labels just don't mix.  Closing for now.  Feel free to reopen if needed.

**Comment by jamesls** [comment]
Sorry, just to clarify the remaining work here:

From the route53 docs:

> All requests – Five requests per second per AWS account. If you submit more than five requests per second, Amazon Route 53 returns an HTTP 400 error (Bad request). The response header also includes a Code element with a value of Throttling and a Message element with a value of Rate exceeded.

Therefore the pending work remaining is to add the status 400 Code=Throttling rule to our _retry.json.  Once this is done we can close this issue out.
