### ISSUE TITLE
Add paginators for 4 IAM actions 

### ISSUE THREAD

**Issue by gene1wood** [boto/botocore#919]
It looks like the following IAM actions manifest pagination
* `GetAccountAuthorizationDetails`
* `ListSshPublicKeys`
* `SimulatePrinciplePolicy`
* `SimulateCustomPolicy`

but don't have paginators in botocore

Would it be possible to add them to the [IAM paginators](https://github.com/boto/botocore/blob/develop/botocore/data/iam/2010-05-08/paginators-1.json)?

**Comment by jamesls** [comment]
Yep, we can get that updated.
