### ISSUE TITLE
generate_presigned_url - SignatureDoesNotMatch

### ISSUE THREAD

**Issue by rstalbow** [boto/botocore#923]
Hi

I'm upgrading from Boto 2 to Boto 3. As part of this I need to generate presigned URL's for content in my S3 bucket. I am experiencing issues doing this, it works fine with Boto 2 however with Boto 2 I get:
code - SignatureDoesNotMatch
message - The request signature we calculated does not match the signature you provided. Check your key and signing method.

This is the code I use to generate the URL:

```
def connect_to_s3_bucket(self):
        s3_conn = boto3.client(
            's3',
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY
        )
        return s3_conn
```
```

def s3_bucket_content(self):
        s3_conn = self.connect_to_s3_bucket()
        s3_bucket = s3_conn.list_objects(Bucket='{my bucket name}')['Contents']
        return s3_bucket
```

```
content = self.s3_bucket_content()
for file_key in content:
                    s3_conn = self.connect_to_s3_bucket()
                    file_url = s3_conn.generate_presigned_url(
                        'put_object',
                        Params={'Bucket': '{my bucket name}', 'Key': file_key['Key']},
                        ExpiresIn=5000
                    )
```

Please help or I wont be able to switch to Boto 3

**Comment by JordonPhillips** [comment]
At what point are you getting this error? How are you calling the generated url?

**Comment by rstalbow** [comment]
I was debugging, getting the value of the file_url variable. Then copying it into my browser, this is where is see the SignatureDoesNotMatch error. I dont get this with boto2

**Comment by JordonPhillips** [comment]
Your browser will perform a GET, not a PUT, on urls you enter. Therefore, you'll only be able to use it to test out GET requests. An easy alternative is the python `requests` library.

```python
import boto3
import requests

s3 = boto3.client('s3')
url = s3.generate_presigned_url(
    'put_object', 
    Params={'Bucket': 'mybucket', 'Key': 'mykey'}, 
    ExpiresIn=5000)

# test the url
requests.put(url, data='foo')
```

**Comment by rstalbow** [comment]
This isn't going to work for me. The end goal in my case is to pass the URL to another service which will download the file. Using this package the service isn't able to download the file (i guess its doing a GET on the url)

I don't encounter any off these issues using Boto 2

**Comment by JordonPhillips** [comment]
If you want to download the file,  you will need to use `get_object`, not `put_object`

**Comment by rstalbow** [comment]
will try that, sounds right

**Comment by zelima** [comment]
@JordonPhillips Hi, considering the code above I'm getting same `SignatureDoesNotMatch` error using boto3, but In my case, I'm using `get_object`. Any suggestions?
```
url = s3_client.generate_presigned_url(
            ClientMethod='get_object',
            Params={
                'Bucket': bucket_name,
                'Key': my_key
            },
            ExpiresIn=3600*6)
```

**Comment by assem-ch** [comment]
> If you want to download the file, you will need to use get_object, not put_object
this fixed it for me, thank you @JordonPhillips
