### ISSUE TITLE
DOCS: APIGateway create_deployment variables validation

### ISSUE THREAD

**Issue by FrancescoRizzi** [boto/botocore#925]
Hello.

Looking at [ReadTheDocs > Available Services > APIGateway > Client > create_deployment](https://botocore.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.create_deployment), it reads as follows for the variables Request Parameter:

> [...] Variable names can have alphanumeric characters, and the values must match [A-Za-z0-9-._~:/?#=,]+ .

Unless I am misreading, the variable names should be ONLY alphanumeric characters (eg: A-Za-z0-9).
However, I used the API to succesfully deploy to a stage with the following variable name: **stage_storageprefix**.

So, I think the document might be wrong, or maybe the regex it includes applies to both variable names and values (instead of just the values as it seems to suggest).

I think the botocore docs in this regard are piped from the AWS API Reference. The relevant snippet _might_ be [this one](https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/#variables)... but maybe you have a way to submit request for docs clarifications or changes to the mothership?

Clearly this is not a blocking issue for me, more of a curiosity I followed-up on because, after writing code to validate the alphanumeric range, I was able to add that stage variable via the AWS Web Console, and wanted to figure out where the inconsistency came from.
Thanks in advance

**Comment by JordonPhillips** [comment]
I'm not sure where the confusion is coming from, it does say that it must match `[A-Za-z0-9-._~:/?#=,]+ .` If the wording specified only alphanumeric, I agree it would be a contradiction.

**Comment by FrancescoRizzi** [comment]
probably I'm reading it wrong, but to me it says 2 separate things:

> Variable names can have alphanumeric characters,

and

> the values must match [A-Za-z0-9-._~:/?#=,]+ .

If the same regex is meant to apply to both, I'd think

> Variable names and values must match [A-Za-z0-9-._~:/?#=,]+

no?

**Comment by JordonPhillips** [comment]
Ah, I see what you're saying now. It's a difference of *names* vs *values*. With that in mind, I agree it seems to be incorrect (or at least poorly worded). I let the service team know. Thanks for pointing out the ambiguity!

**Comment by JordonPhillips** [comment]
The docs have since been fixed, thanks again!
