### ISSUE TITLE
Provide caller with information on raised exception after retry

### ISSUE THREAD

**Issue by jantman** [boto/botocore#926]
As far as I can tell, when [retryhandler.MaxAttemptsDecorator](https://github.com/boto/botocore/blob/develop/botocore/retryhandler.py#L234) reaches its maximum number of attempts, the retryable exception is returned to the caller. I just spent about 3 hours tracing through boto3 and botocore and writing test code to reproduce a RequestLimitExceeded error, only to find that botocore was properly retrying and the only thing I can think of is that the request limit was really exceeded (even after 5 exponential backoff retries).

It would be very useful in cases like this if the retry handler either (a) wrapped the actual exception in a (e.g.) MaxRetriesExceeded exception, to make it clear that the request was retried and perhaps include the number of retries and maybe the sleep duration, or (b) at least fire an event with this information.

While I do *really* appreciate that the retry logic is so transparent, this also makes it a bit opaque for debugging, as there's really no way I can find to confirm (especially programmatically in the caller) that the request was, in fact, retried and all retries failed.

Thanks,
Jason Antman

(this came up when investigating [this issue](https://github.com/jantman/awslimitchecker/issues/187).)

**Comment by jamesls** [comment]
Thanks for the feedback.  The only thing we'll need to keep in mind is we'll need to do this in a way that's backwards compatible.  Otherwise, I think being able to communicate this information somehow would be useful.

**Comment by JordonPhillips** [comment]
@jamesls I was just thinking about this, could we just add it to the `ResponseMetadata`?

**Comment by jamesls** [comment]
@JordonPhillips I think that would work.

**Comment by jantman** [comment]
@jamesls @JordonPhillips I've got a simple implementation of this as https://github.com/boto/botocore/pull/965 - coverage stayed the same, though it appears that most of ``Endpoint`` isn't covered. I don't really have any experience with unittest, so I didn't attempt to rectify that.

The implementation may be a bit naive, so I'm certainly open to changing/reworking it as needed.
