### ISSUE TITLE
Redshift EnhancedVpcRouting response data

### ISSUE THREAD

**Issue by infame-io** [boto/botocore#942]
Currently there is no way to check whether enhanced VPC routing is enabled in a redshift cluster when using describe_cluster. It would be nice to include EnhancedVpcRouting on the response

**Comment by JordonPhillips** [comment]
This feature doesn't seem to appear in the service's api reference, indicating that it is a beta feature. With that in mind, I'm going to close out this issue. When the feature is released, SDK support will also be released. Please address any update requests to the service team in the meantime.

**Comment by zsimjee** [comment]
https://docs.aws.amazon.com/redshift/latest/mgmt/enhanced-vpc-routing.html

**Comment by BigDataDaddy** [comment]
Was this issue in Boto fixed so that enhanced networking is reported in the API?  We're about switch to enhanced networking and a lot of Python code will break on us if we can't reliably determine if a Redshift cluster has the feature enabled or not.
