### ISSUE TITLE
Question about source of API json specification?

### ISSUE THREAD

**Issue by Posnet** [boto/botocore#944]
All the AWS sdks seem to have some variation of this JSON spec. (See examples below).
Is this spec canonically located somewhere either on an AWS website on in the AWS console itself, or is it provided internally from AWS and cannot be publically accessed.

https://github.com/boto/botocore/tree/develop/botocore/data
https://github.com/aws/aws-sdk-ruby/tree/master/aws-sdk-core/apis
https://github.com/aws/aws-sdk-go/tree/master/models/apis

**Comment by JordonPhillips** [comment]
We generate these files upstream based on our internal knowledge of the AWS services. There is no public source for these models other than what can be found in our SDK repos. While the service naming may vary slightly, the actual files should be identical between repos.
