### ISSUE TITLE
Where is the scripts/gen-changelog script?

### ISSUE THREAD

**Issue by darjus** [boto/botocore#945]
Trying to setup similar feel in botoflow by using the new-change script but noticed that gen-changelog script is missing. Is it being used, or changes are done manually on the CHANGELOG.rst?

Thanks,
Darjus

**Comment by JordonPhillips** [comment]
We took that out because customers didn't need it, but we'll see about publishing it separately.

**Comment by JordonPhillips** [comment]
In the meantime, [here](https://github.com/aws/aws-cli/pull/1909) is the PR that originally introduced all the changelog stuff.

**Comment by darjus** [comment]
Awesome, thanks!
