### ISSUE TITLE
S3 SignatureDoesNotMatch with Unicode params

### ISSUE THREAD

**Issue by jamesls** [boto/botocore#956]
Originally from #948 

> Here's a script that demonstrates the error. With the fix, Chrome downloads a file named "Test®.txt". Without it, S3 gives a signature error. (Using the more ambitious Unicode string from the first commented out line dl_name gets past the signature phase with this fix, but does still yield a different error.)

Repro script:

```
# coding=utf-8

import boto3


S3_PARAMS = {
    'region_name': " … ",
    'aws_access_key_id': " … ",
    'aws_secret_access_key': " … "
}
S3_BUCKET = " … "
S3_KEY = " … "

#dl_name = u"Uñicød∑ 👍🏾"
dl_name = u"Test®.txt"

s3 = boto3.client('s3', **S3_PARAMS)
url = s3.generate_presigned_url('get_object', Params={
    'Bucket': S3_BUCKET,
    'Key': S3_KEY,
    'ResponseContentDisposition': "attachment; filename=\"%s\"" % dl_name.replace('"', '\\"')
})

print url
```

**Comment by jamesls** [comment]
Marking as enhancement / needs-discussion.  We'll need to see what we want to support client side here.

**Comment by JordonPhillips** [comment]
I believe this was an issue with sigv4 that has since been resolved. If this still seems to be an issue to anybody feel free to open a new GitHub issue.
