### ISSUE TITLE
Waiters for Elastic Beanstalk

### ISSUE THREAD

**Issue by elee** [boto/botocore#973]
Feature request: adding waiters for Elastic Beanstalk environment creation would be nice, right now I am doing a bit of custom polling in its stead.

``` shell
$  python -c 'import boto3;print "{}\n".format(boto3.__version__), boto3.client("elasticbeanstalk").waiter_names'
1.3.1
[]
$
```

**Comment by JordonPhillips** [comment]
This definitely sounds like a useful thing to have. Thanks for the feature request!

**Comment by srri** [comment]
I'd like to work on this if no one else is currently

**Comment by JordonPhillips** [comment]
Go right ahead!

**Comment by philippelabat** [comment]
I would also appreciate this feature very much, i was surprised to see none.

**Comment by mosheeshel** [comment]
any progress on this?

**Comment by digitalfiz** [comment]
This would be super useful right now. Almost been a year... :(

**Comment by darrikonn** [comment]
No status on this?
Would be super nice to be able to listen for elastic beanstalk state changes, e.g. to add a deployment progress bar in a custom cli.

**Comment by swetashre** [comment]
Currently these waiters are available for elastic beanstalk:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elasticbeanstalk.html#waiters

**Comment by ccope** [comment]
This was added in boto3 v1.14.23 in July, in case anyone was curious.

**Comment by elee** [comment]
It's been real y'all.

Since opening this issue I've:

- moved jobs twice
- moved cities once
- had another child
- finished Infinite Jest
