### ISSUE TITLE
DirectConnect waiters

### ISSUE THREAD

**Issue by copumpkin** [boto/botocore#994]
There's a whole set of states around [virtual interfaces](http://docs.aws.amazon.com/directconnect/latest/APIReference/API_VirtualInterface.html) and it's not clear how transitions work between them. To make things worse, the directconnect API is remarkably painful to test and play with (regardless of botocore) because it's pretty hard and expensive to get a connection to run any API calls against. In my case, I don't have direct access to one but I still need the waiters.

I'm not sure how to submit a change for this when I can't run tests against it. Do folks at Amazon have the ability to test DC? It seems like it could be a fairly straightforward addition if one had access to a DC connection.

**Comment by jamesls** [comment]
I don't have a direct connect I can test with either.  Feature wise, I think this would be good to have.  Marking as a feature request.

**Comment by copumpkin** [comment]
Yeah, they seem hard to get 😄 hoping someone has one lying around to bang this out quickly, but unfortunately by their nature these DC links tend to be considered critical infrastructure and most people don't get to tinker with them.
