### ISSUE TITLE
Add support for streaming (transfer-encoding: chunked) v4 uploads

### ISSUE THREAD

**Issue by timuralp** [boto/botocore#995]
Currently, botocore (and boto3) when using v4 signatures will upload an object to S3 with a SHA256 of the entire content in the signature. This is a problem for streaming uploads, as the entire stream must be buffered first, the SHA256 computed, and then submitted as a PUT to S3.

AWS S3 describes a method for v4 signer streaming uploads: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html. The premise is to set `transfer-encoding: chunked` and upload each chunk of a set size (except for the last one) where only a chunk's content is signed (as opposed to the entire stream). The one limitation is that the content length must be known ahead of time and set as the `x-amz-decoded-content-length`. Still, supporting such uploads would be greatly beneficial when retrieving a stream of known length from one location and putting it into S3 without having to buffer on disk or memory and seeking through it to compute the signature.

When submitting such requests, the content hash is initially set to `STREAMING-AWS4-HMAC-SHA256-PAYLOAD` and each individual chunk is submitted with its hash.

**Comment by jamesls** [comment]
I'd like to consolidate issues.  Given you have an issue opened on boto3 about this, let's track discussion about this feature over in https://github.com/boto/boto3/issues/751.

**Comment by timuralp** [comment]
Sounds good. I only did that because I noticed botocore didn't get many replies (I still have a PR and an issue open from May 5th: #911 and #913).
