### ISSUE TITLE
Context conditional retry checker

### ISSUE THREAD

**Issue by andreimircescu** [boto/botocore#998]
We have some issues when we create a new object and if you start describing it immediately it may fail with an exception. 

As an concrete example, sometimes we receive a NoSuchBucket exception if we describe the bucket immediately after we create it. if we retry , then the operation will move forward.  In other cases other than newly created bucket, there should be no need for a retry.

I think this is upper layer logic(application) and it will be nice to have the possibility to control the flow of a specific retry . 

this is somehow related to #882 .

is it possible to do it?

**Comment by jamesls** [comment]
The best way to deal with this is to use waiters.  In your specific case, the best option here is the `bucket_exists` waiter, which will poll until the bucket exists: http://botocore.readthedocs.io/en/latest/reference/services/s3.html#S3.Waiter.BucketExists

Let me know if that doesn't work for you and I'll reopen and take another look.
